// @generated DO NOT EDIT — regenerated by build.rs from fpss_event_schema.toml
// Typed #[napi(object)] structs for every `FpssData` and `FpssControl`
// variant + a flat `FpssEvent` wrapper and the `buffered_event_to_typed`
// dispatcher. Consumers discriminate on `event.kind` and pull the matching
// optional payload field; control variants surface their typed payloads on
// `event.loginSuccess` / `event.disconnected` / etc. so TypeScript users
// dispatch via the same `switch (event.kind)` they already use for ticks.
//
// `BigInt` is pulled in via `tick_classes.rs`'s `use` line — both
// files `include!` into the same TS-SDK module scope (see
// `sdks/typescript/src/lib.rs`), so importing it here would collide.

/// FPSS contract identifier. Surfaced on every decoded FPSS data
/// event as `event.quote.contract` / `event.trade.contract` / etc.
/// `secType` is the symbolic uppercase name (`"STOCK"` / `"OPTION"` /
/// `"INDEX"` / `"RATE"`); `right` is `"C"` / `"P"` / `null`;
/// `strike` is the option strike in dollars — the same unit historical
/// rows carry under the same name, so streaming contracts join against
/// historical data directly. `expiration` is a `YYYYMMDD` integer.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Contract {
    pub symbol: String,
    pub sec_type: String,
    pub expiration: Option<i32>,
    pub right: Option<String>,
    pub strike: Option<f64>,
}

/// FPSS OHLCVC bar. Mirrors `FpssData::Ohlcvc`.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Ohlcvc {
    pub contract: Contract,
    pub ms_of_day: i32,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: BigInt,
    pub count: BigInt,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS OpenInterest tick. Mirrors `FpssData::OpenInterest`.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct OpenInterest {
    pub contract: Contract,
    pub ms_of_day: i32,
    pub open_interest: i32,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS Quote tick. Mirrors `FpssData::Quote`.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Quote {
    pub contract: Contract,
    pub ms_of_day: i32,
    pub bid_size: i32,
    pub bid_exchange: i32,
    pub bid: f64,
    pub bid_condition: i32,
    pub ask_size: i32,
    pub ask_exchange: i32,
    pub ask: f64,
    pub ask_condition: i32,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS Trade tick. Mirrors `FpssData::Trade`.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Trade {
    pub contract: Contract,
    pub ms_of_day: i32,
    pub sequence: i32,
    pub ext_condition1: i32,
    pub ext_condition2: i32,
    pub ext_condition3: i32,
    pub ext_condition4: i32,
    pub condition: i32,
    pub size: i32,
    pub exchange: i32,
    pub price: f64,
    pub condition_flags: i32,
    pub price_flags: i32,
    pub volume_type: i32,
    pub records_back: i32,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS server connection ack (wire code 4, `StreamMsgType::Connected`). Mirrors `FpssControl::Connected`. Carries no payload.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Connected {}

/// FPSS server assigned a contract id. Mirrors `FpssControl::ContractAssigned`. The `contract` payload carries the full resolved `Contract` (root, sec_type, expiration / strike / right for options).
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct ContractAssigned {
    pub id: i32,
    pub contract: Contract,
}

/// FPSS server disconnected the client (wire code 12). Mirrors `FpssControl::Disconnected`. `reason` is the `RemoveReason` discriminant cast to `i32`; compare against `tdbe::types::enums::RemoveReason as i32` for symbolic interpretation.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Disconnected {
    pub reason: i32,
    /// Resolved `RemoveReason` variant name (e.g. `"TooManyRequests"`,
    /// `"InvalidCredentials"`, `"Unspecified"` for unknown codes).
    /// Derived from the wire-level `reason` integer.
    pub reason_name: String,
}

/// FPSS login succeeded. Mirrors `FpssControl::LoginSuccess`. `permissions` is the server's opaque `Bundle` string — diagnostic metadata only; for feature gating use the Nexus REST subscription tiers (see `FpssControl::LoginSuccess` doc on the core crate).
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct LoginSuccess {
    pub permissions: String,
}

/// FPSS market-close signal (wire code 32). Mirrors `FpssControl::MarketClose`. Carries no payload.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct MarketClose {}

/// FPSS market-open signal (wire code 30). Mirrors `FpssControl::MarketOpen`. Carries no payload.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct MarketOpen {}

/// FPSS protocol-level parse error. Mirrors `FpssControl::Error`. Named `ParseError` on every binding so it never collides with the language's own error types (Python's exception classes, the JS global `Error`).
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct ParseError {
    pub message: String,
}

/// FPSS server heartbeat (wire code 10, `StreamMsgType::Ping`). Mirrors `FpssControl::Ping`. The server emits PING frames (observed 1-byte payload `[0]`) the client heartbeat logic does not have to answer; payload preserved for diagnostics.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Ping {
    pub payload: Vec<u8>,
}

/// FPSS auto-reconnect succeeded — connection is live again. Mirrors `FpssControl::Reconnected`. Carries no payload.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Reconnected {}

/// FPSS server-side reconnect ack (wire code 13). Mirrors `FpssControl::ReconnectedServer`. Distinct from `Reconnected`, which the client emits from its auto-reconnect state machine once the new TLS session is authenticated.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct ReconnectedServer {}

/// FPSS auto-reconnect is about to attempt reconnection. Mirrors `FpssControl::Reconnecting`. Emitted before sleeping for `delay_ms` milliseconds. `attempt` is 1-based and saturates at `i32::MAX` if the reconnect loop exceeds 2^31 attempts.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Reconnecting {
    pub reason: i32,
    pub attempt: i32,
    pub delay_ms: BigInt,
    /// Resolved `RemoveReason` variant name (e.g. `"TooManyRequests"`,
    /// `"InvalidCredentials"`, `"Unspecified"` for unknown codes).
    /// Derived from the wire-level `reason` integer.
    pub reason_name: String,
}

/// FPSS auto-reconnect stopped without a user-initiated shutdown — terminal for the session. Mirrors `FpssControl::ReconnectsExhausted`. Emitted when the reconnect budget (attempt count or wall-clock envelope) is exhausted, a permanent disconnect reason short-circuits recovery, a manual policy declines to reconnect, or a custom policy returns no delay. `reason` is the `RemoveReason` discriminant of the final drop cast to `i32`; `attempts` is the number of consecutive reconnect attempts consumed before giving up (0 when no reconnect was attempted).
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct ReconnectsExhausted {
    pub reason: i32,
    pub attempts: i32,
    /// Resolved `RemoveReason` variant name (e.g. `"TooManyRequests"`,
    /// `"InvalidCredentials"`, `"Unspecified"` for unknown codes).
    /// Derived from the wire-level `reason` integer.
    pub reason_name: String,
}

/// FPSS subscription response (wire code 40). Mirrors `FpssControl::ReqResponse`. `result` is the `StreamResponseType` discriminant cast to `i32` (0=Subscribed, 1=Error, 2=MaxStreamsReached, 3=InvalidPerms).
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct ReqResponse {
    pub req_id: i32,
    pub result: i32,
}

/// FPSS server stream restart (wire code 31, `StreamMsgType::Restart`). Mirrors `FpssControl::Restart`. The server restarts the stream without dropping the TCP connection; delta decode state should be cleared on receipt.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct Restart {}

/// FPSS server-error message (wire code 11). Mirrors `FpssControl::ServerError`.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct ServerError {
    pub message: String,
}

/// FPSS control variant the SDK does not yet recognise. Surfaced when the core crate adds a new `FpssControl::*` arm — keep dispatch logic forward-compatible by handling this variant. Carries no payload.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct UnknownControl {}

/// FPSS server sent a frame with an unrecognised wire code. Mirrors `FpssControl::UnknownFrame`. Raw bytes preserved for diagnostics / upstream bug reports.
#[must_use]
#[napi(object)]
#[derive(Clone)]
pub struct UnknownFrame {
    pub code: u32,
    pub payload: Vec<u8>,
}

/// A single FPSS event surfaced to JS/TS.
///
/// `kind` is the discriminator — switch on it and read the matching
/// payload field. The shape is stable and every payload is typed, so
/// consumers never fall back to untyped `any`.
#[must_use]
#[napi(object, object_from_js = false)]
#[derive(Clone)]
pub struct FpssEvent {
    /// Discriminator matching one of the typed payload fields below.
    /// Narrowed to a literal union in TS so `switch (event.kind)`
    /// correctly narrows the optional payload fields.
    #[napi(ts_type = "'connected' | 'contract_assigned' | 'disconnected' | 'login_success' | 'market_close' | 'market_open' | 'ohlcvc' | 'open_interest' | 'parse_error' | 'ping' | 'quote' | 'reconnected' | 'reconnected_server' | 'reconnecting' | 'reconnects_exhausted' | 'req_response' | 'restart' | 'server_error' | 'trade' | 'unknown_control' | 'unknown_frame'")]
    pub kind: &'static str,
    pub ohlcvc: Option<Ohlcvc>,
    pub open_interest: Option<OpenInterest>,
    pub quote: Option<Quote>,
    pub trade: Option<Trade>,
    pub connected: Option<Connected>,
    pub contract_assigned: Option<ContractAssigned>,
    pub disconnected: Option<Disconnected>,
    pub login_success: Option<LoginSuccess>,
    pub market_close: Option<MarketClose>,
    pub market_open: Option<MarketOpen>,
    pub parse_error: Option<ParseError>,
    pub ping: Option<Ping>,
    pub reconnected: Option<Reconnected>,
    pub reconnected_server: Option<ReconnectedServer>,
    pub reconnecting: Option<Reconnecting>,
    pub reconnects_exhausted: Option<ReconnectsExhausted>,
    pub req_response: Option<ReqResponse>,
    pub restart: Option<Restart>,
    pub server_error: Option<ServerError>,
    pub unknown_control: Option<UnknownControl>,
    pub unknown_frame: Option<UnknownFrame>,
}

pub(crate) fn buffered_event_to_typed(event: BufferedEvent) -> FpssEvent {
    let mut out = FpssEvent {
        kind: "unknown_control",
        ohlcvc: None,
        open_interest: None,
        quote: None,
        trade: None,
        connected: None,
        contract_assigned: None,
        disconnected: None,
        login_success: None,
        market_close: None,
        market_open: None,
        parse_error: None,
        ping: None,
        reconnected: None,
        reconnected_server: None,
        reconnecting: None,
        reconnects_exhausted: None,
        req_response: None,
        restart: None,
        server_error: None,
        unknown_control: None,
        unknown_frame: None,
    };
    match event {
        BufferedEvent::Ohlcvc {
            contract,
            ms_of_day,
            open,
            high,
            low,
            close,
            volume,
            count,
            date,
            received_at_ns,
        } => {
            out.kind = "ohlcvc";
            out.ohlcvc = Some(Ohlcvc {
                contract: Contract {
                    symbol: contract.symbol.to_string(),
                    sec_type: contract.sec_type.as_str().to_string(),
                    expiration: contract.expiration,
                    right: contract.right().map(|r| r.as_char().to_string()),
                    strike: contract.strike_dollars(),
                },
                ms_of_day,
                open,
                high,
                low,
                close,
                volume: BigInt::from(volume),
                count: BigInt::from(count),
                date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::OpenInterest {
            contract,
            ms_of_day,
            open_interest,
            date,
            received_at_ns,
        } => {
            out.kind = "open_interest";
            out.open_interest = Some(OpenInterest {
                contract: Contract {
                    symbol: contract.symbol.to_string(),
                    sec_type: contract.sec_type.as_str().to_string(),
                    expiration: contract.expiration,
                    right: contract.right().map(|r| r.as_char().to_string()),
                    strike: contract.strike_dollars(),
                },
                ms_of_day,
                open_interest,
                date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::Quote {
            contract,
            ms_of_day,
            bid_size,
            bid_exchange,
            bid,
            bid_condition,
            ask_size,
            ask_exchange,
            ask,
            ask_condition,
            date,
            received_at_ns,
        } => {
            out.kind = "quote";
            out.quote = Some(Quote {
                contract: Contract {
                    symbol: contract.symbol.to_string(),
                    sec_type: contract.sec_type.as_str().to_string(),
                    expiration: contract.expiration,
                    right: contract.right().map(|r| r.as_char().to_string()),
                    strike: contract.strike_dollars(),
                },
                ms_of_day,
                bid_size,
                bid_exchange,
                bid,
                bid_condition,
                ask_size,
                ask_exchange,
                ask,
                ask_condition,
                date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::Trade {
            contract,
            ms_of_day,
            sequence,
            ext_condition1,
            ext_condition2,
            ext_condition3,
            ext_condition4,
            condition,
            size,
            exchange,
            price,
            condition_flags,
            price_flags,
            volume_type,
            records_back,
            date,
            received_at_ns,
        } => {
            out.kind = "trade";
            out.trade = Some(Trade {
                contract: Contract {
                    symbol: contract.symbol.to_string(),
                    sec_type: contract.sec_type.as_str().to_string(),
                    expiration: contract.expiration,
                    right: contract.right().map(|r| r.as_char().to_string()),
                    strike: contract.strike_dollars(),
                },
                ms_of_day,
                sequence,
                ext_condition1,
                ext_condition2,
                ext_condition3,
                ext_condition4,
                condition,
                size,
                exchange,
                price,
                condition_flags,
                price_flags,
                volume_type,
                records_back,
                date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::Connected => {
            out.kind = "connected";
            out.connected = Some(Connected {});
        }
        BufferedEvent::ContractAssigned {
            id,
            contract,
        } => {
            out.kind = "contract_assigned";
            out.contract_assigned = Some(ContractAssigned {
                id,
                contract: Contract {
                    symbol: contract.symbol.to_string(),
                    sec_type: contract.sec_type.as_str().to_string(),
                    expiration: contract.expiration,
                    right: contract.right().map(|r| r.as_char().to_string()),
                    strike: contract.strike_dollars(),
                },
            });
        }
        BufferedEvent::Disconnected {
            reason,
        } => {
            out.kind = "disconnected";
            out.disconnected = Some(Disconnected {
                reason,
                reason_name: tdbe::types::enums::RemoveReason::from_code(reason as i16).as_str().to_string(),
            });
        }
        BufferedEvent::LoginSuccess {
            permissions,
        } => {
            out.kind = "login_success";
            out.login_success = Some(LoginSuccess {
                permissions,
            });
        }
        BufferedEvent::MarketClose => {
            out.kind = "market_close";
            out.market_close = Some(MarketClose {});
        }
        BufferedEvent::MarketOpen => {
            out.kind = "market_open";
            out.market_open = Some(MarketOpen {});
        }
        BufferedEvent::ParseError {
            message,
        } => {
            out.kind = "parse_error";
            out.parse_error = Some(ParseError {
                message,
            });
        }
        BufferedEvent::Ping {
            payload,
        } => {
            out.kind = "ping";
            out.ping = Some(Ping {
                payload,
            });
        }
        BufferedEvent::Reconnected => {
            out.kind = "reconnected";
            out.reconnected = Some(Reconnected {});
        }
        BufferedEvent::ReconnectedServer => {
            out.kind = "reconnected_server";
            out.reconnected_server = Some(ReconnectedServer {});
        }
        BufferedEvent::Reconnecting {
            reason,
            attempt,
            delay_ms,
        } => {
            out.kind = "reconnecting";
            out.reconnecting = Some(Reconnecting {
                reason,
                attempt,
                delay_ms: BigInt::from(delay_ms),
                reason_name: tdbe::types::enums::RemoveReason::from_code(reason as i16).as_str().to_string(),
            });
        }
        BufferedEvent::ReconnectsExhausted {
            reason,
            attempts,
        } => {
            out.kind = "reconnects_exhausted";
            out.reconnects_exhausted = Some(ReconnectsExhausted {
                reason,
                attempts,
                reason_name: tdbe::types::enums::RemoveReason::from_code(reason as i16).as_str().to_string(),
            });
        }
        BufferedEvent::ReqResponse {
            req_id,
            result,
        } => {
            out.kind = "req_response";
            out.req_response = Some(ReqResponse {
                req_id,
                result,
            });
        }
        BufferedEvent::Restart => {
            out.kind = "restart";
            out.restart = Some(Restart {});
        }
        BufferedEvent::ServerError {
            message,
        } => {
            out.kind = "server_error";
            out.server_error = Some(ServerError {
                message,
            });
        }
        BufferedEvent::UnknownControl => {
            out.kind = "unknown_control";
            out.unknown_control = Some(UnknownControl {});
        }
        BufferedEvent::UnknownFrame {
            code,
            payload,
        } => {
            out.kind = "unknown_frame";
            out.unknown_frame = Some(UnknownFrame {
                code: code as u32,
                payload,
            });
        }
    }
    out
}
