//! Static config accessor emitter.
//!
//! Renders the uniform `thetadatadx_config_{set,get}_*` family from
//! `config_surface.toml`: the FFI Rust entry points
//! (`ffi/src/config_accessors.rs`) and the matching C++ inline `Config`
//! methods (`sdks/cpp/include/config_accessors.hpp.inc`). Divergent
//! accessors (string, enum, Option-widened, policy-aware, validated)
//! stay hand-written in `ffi/src/auth.rs` and `thetadatadx.hpp`.

use std::fmt::Write as _;

use serde::Deserialize;

/// One generated accessor. `set` produces a unit-returning setter via
/// `require_config_mut!`; `get` produces an `i32`-returning getter with
/// the dual null-check.
#[derive(Debug, Deserialize)]
struct Accessor {
    symbol: String,
    kind: String,
    param: String,
    abi_type: String,
    path: String,
    /// `ms` / `secs` Duration wrap (setter) or `.as_secs()` read (getter).
    #[serde(default)]
    duration_unit: Option<String>,
    /// Per-site `// SAFETY:` block for the getter write, when it differs
    /// from the canonical one-liner. Carries its own indentation.
    #[serde(default)]
    out_safety: Option<String>,
    doc: String,
    cpp_doc: String,
}

#[derive(Debug, Deserialize)]
struct ConfigSurface {
    accessor: Vec<Accessor>,
}

fn load() -> Result<Vec<Accessor>, Box<dyn std::error::Error>> {
    let spec_str = std::fs::read_to_string("config_surface.toml")?;
    let spec: ConfigSurface = toml::from_str(&spec_str)?;
    Ok(spec.accessor)
}

const CFG_SAFETY: &str = "        // SAFETY: config is a non-null `*const ThetaDataDxConfig` returned by `thetadatadx_config_*` and not yet freed; `&*` produces a shared reference valid for the call duration.";
const OUT_SAFETY: &str = "        // SAFETY: out pointer checked non-null above; the FFI contract pins the storage for the call duration and forbids concurrent calls on the same handle.";

/// Append `text` as `///` Rust doc lines, emitting a bare `///` for a
/// blank line so the round-trip is byte-exact (no trailing space).
fn rust_doc(buf: &mut String, text: &str) {
    for line in text.trim_matches('\n').split('\n') {
        if line.is_empty() {
            buf.push_str("///\n");
        } else {
            writeln!(buf, "/// {line}").unwrap();
        }
    }
}

/// Append `text` as indented `///` C++ doc lines under `indent`.
fn cpp_doc(buf: &mut String, indent: &str, text: &str) {
    for line in text.trim_matches('\n').split('\n') {
        if line.is_empty() {
            writeln!(buf, "{indent}///").unwrap();
        } else {
            writeln!(buf, "{indent}/// {line}").unwrap();
        }
    }
}

/// The FFI Rust file: one `#[no_mangle]` entry point per accessor.
pub(super) fn render_ffi_config_accessors() -> Result<String, Box<dyn std::error::Error>> {
    let accessors = load()?;
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from config_surface.toml\n\n",
    );
    for a in &accessors {
        rust_doc(&mut out, &a.doc);
        out.push_str("#[no_mangle]\n");
        if a.kind == "set" {
            let rhs = match a.duration_unit.as_deref() {
                Some("ms") => format!("std::time::Duration::from_millis({})", a.param),
                Some("secs") => format!("std::time::Duration::from_secs({})", a.param),
                _ => a.param.clone(),
            };
            write!(
                out,
                "pub unsafe extern \"C\" fn {sym}(\n    config: *mut ThetaDataDxConfig,\n    {p}: {ty},\n) {{\n    ffi_boundary!((), {{\n        let config = require_config_mut!(config);\n        config.inner.{path} = {rhs};\n    }})\n}}\n\n",
                sym = a.symbol, p = a.param, ty = a.abi_type, path = a.path,
            )?;
        } else {
            let suffix = if a.duration_unit.as_deref() == Some("secs") {
                ".as_secs()"
            } else {
                ""
            };
            let out_safety = a
                .out_safety
                .as_deref()
                .map(|s| s.trim_end_matches('\n'))
                .unwrap_or(OUT_SAFETY);
            write!(
                out,
                "pub unsafe extern \"C\" fn {sym}(\n    config: *const ThetaDataDxConfig,\n    {p}: *mut {ty},\n) -> i32 {{\n    ffi_boundary!(-1, {{\n        if config.is_null() || {p}.is_null() {{\n            set_error(\"config or out-parameter pointer is null\");\n            return -1;\n        }}\n{cfg}\n        let config = unsafe {{ &*config }};\n{outs}\n        unsafe {{\n            *{p} = config.inner.{path}{suffix};\n        }}\n        0\n    }})\n}}\n\n",
                sym = a.symbol, p = a.param, ty = a.abi_type, path = a.path,
                cfg = CFG_SAFETY, outs = out_safety, suffix = suffix,
            )?;
        }
    }
    Ok(out)
}

/// Map an FFI integer type to the C++ spelling used on the `Config`
/// method surface.
fn cpp_type(abi: &str) -> &'static str {
    match abi {
        "u32" => "std::uint32_t",
        "u64" => "std::uint64_t",
        "u16" => "std::uint16_t",
        "usize" => "std::size_t",
        "bool" => "bool",
        other => panic!("config_surface: unmapped abi_type '{other}'"),
    }
}

/// The C++ include: one inline `Config` method per accessor, spliced
/// into the class body in `thetadatadx.hpp`.
pub(super) fn render_cpp_config_accessors() -> Result<String, Box<dyn std::error::Error>> {
    let accessors = load()?;
    let mut out = String::new();
    out.push_str(
        "/* @generated DO NOT EDIT — regenerated by build.rs from config_surface.toml */\n",
    );
    for a in &accessors {
        let method = a.symbol.strip_prefix("thetadatadx_config_").unwrap();
        let ty = cpp_type(&a.abi_type);
        out.push('\n');
        cpp_doc(&mut out, "    ", &a.cpp_doc);
        if a.kind == "set" {
            write!(
                out,
                "    void {method}({ty} {p}) {{\n        {sym}(handle_.get(), {p});\n    }}\n",
                method = method,
                ty = ty,
                p = a.param,
                sym = a.symbol,
            )?;
        } else {
            write!(
                out,
                "    {ty} {method}() const {{\n        {ty} out{{}};\n        {sym}(handle_.get(), &out);\n        return out;\n    }}\n",
                ty = ty, method = method, sym = a.symbol,
            )?;
        }
    }
    Ok(out)
}
