//! Emit `tools/cli/src/raw_headers_generated.rs` — per-tick raw header
//! constants for the CLI's generic row formatter.

use std::fmt::Write as _;

use super::schema::{Schema, TickTypeDef};
use super::sorted_type_names;

pub(super) fn render_cli_raw_headers(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        let const_name = cli_raw_header_const_name(type_name);
        let headers = cli_raw_headers(type_name, def);
        writeln!(out, "pub(crate) const {const_name}: &[&str] = &[").unwrap();
        for header in headers {
            writeln!(out, "    {header:?},").unwrap();
        }
        out.push_str("];\n\n");
    }
    out
}

/// Derive the per-tick raw-header constant name from the schema type
/// name. `EodTick` -> `EOD_TICK_RAW_HEADERS`, `GreeksFirstOrderTick` ->
/// `GREEKS_FIRST_ORDER_TICK_RAW_HEADERS`. Adding a tick type to
/// `tick_schema.toml` flows through here automatically -- no helper edit.
fn cli_raw_header_const_name(type_name: &str) -> String {
    let mut out = String::new();
    for (i, c) in type_name.chars().enumerate() {
        if c.is_ascii_uppercase() && i != 0 {
            out.push('_');
        }
        out.push(c.to_ascii_uppercase());
    }
    out.push_str("_RAW_HEADERS");
    out
}

fn cli_raw_headers(type_name: &str, def: &TickTypeDef) -> Vec<String> {
    let mut headers: Vec<String> = def
        .columns
        .iter()
        .map(|column| column.name.clone())
        .collect();
    if type_name == "QuoteTick" {
        headers.push("midpoint".to_string());
    }
    if def.contract_id {
        headers.extend(
            ["expiration", "strike", "right"]
                .into_iter()
                .map(std::string::ToString::to_string),
        );
    }
    headers
}
