//! Emit `decode_generated.rs` (row-oriented tick parser functions).
//!
//! Struct definitions now live in the `tdbe` crate (`crates/tdbe/src/types/tick.rs`);
//! only parser functions are generated here. Parsers return
//! `Result<Vec<Tick>, DecodeError>`; each cell access threads `?` so a type
//! mismatch in one row fails the whole table, matching Java terminal
//! semantics (see `PojoMessageUtils.convert`).

use std::fmt::Write as _;
use std::path::Path;

use super::schema::{load_schema, TickTypeDef};

pub(super) fn generate() -> Result<(), Box<dyn std::error::Error>> {
    let schema = load_schema()?;
    let schema_path = "tick_schema.toml";

    let out_dir = std::env::var("OUT_DIR")?;

    // Collect type names and sort for deterministic output.
    let mut type_names: Vec<&String> = schema.types.keys().collect();
    type_names.sort();

    // ── Generate decode_generated.rs (parser functions) ──────────────────────
    let mut parsers = String::new();
    parsers
        .push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n\n");
    // Note: tick types are imported by decode.rs via `use tdbe::types::tick::*;`
    // No additional imports needed in the generated code.

    for type_name in &type_names {
        let def = &schema.types[*type_name];
        generate_parser(&mut parsers, type_name, def);
    }

    let parsers_dest = Path::new(&out_dir).join("decode_generated.rs");
    std::fs::write(&parsers_dest, &parsers)?;

    // Rerun if schema changes
    println!("cargo:rerun-if-changed={schema_path}");

    Ok(())
}

/// Generate a single parser function.
///
/// Price columns are decoded to `f64` during extraction using the wire
/// `price_type` (internally fetched, never exposed on the public struct).
/// The emitted parser returns `Result<Vec<T>, DecodeError>` and threads `?`
/// on every cell access so a type mismatch in one row fails the whole table.
// Reason: code generator -- the match dispatch over column types cannot be meaningfully split.
#[allow(clippy::too_many_lines)]
fn generate_parser(out: &mut String, type_name: &str, def: &TickTypeDef) {
    let fn_name = &def.parser;

    writeln!(
        out,
        "pub fn {fn_name}(table: &crate::proto::DataTable) -> Result<Vec<{type_name}>, DecodeError> {{"
    )
    .unwrap();

    // If eod_style, emit the local EOD helpers inline.
    if def.eod_style {
        out.push_str(
            "    // EOD numeric/time fields may arrive as Price, Number, or Timestamp cells.\n",
        );
        out.push_str("    fn eod_num(row: &crate::proto::DataValueList, idx: usize) -> Result<i32, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as i32),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(p.value),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(crate::decode::timestamp_to_ms_of_day(ts.epoch_ms)),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD numeric field widened to i64 (for volume/count) — same cell types as eod_num, i64 target.\n");
        out.push_str("    fn eod_num64(row: &crate::proto::DataValueList, idx: usize) -> Result<i64, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(i64::from(p.value)),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(i64::from(crate::decode::timestamp_to_ms_of_day(ts.epoch_ms))),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD date fields may arrive as Price, Number, or Timestamp cells.\n");
        out.push_str("    fn eod_date(row: &crate::proto::DataValueList, idx: usize) -> Result<i32, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as i32),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(p.value),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(crate::decode::timestamp_to_date(ts.epoch_ms)),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD price field: decode to f64 from Price or Number cell.\n");
        out.push_str("    fn eod_price(row: &crate::proto::DataValueList, idx: usize) -> Result<f64, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str("            Some(crate::proto::data_value::DataType::Price(p)) => Ok(tdbe::types::price::Price::new(p.value, p.r#type).to_f64()),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as f64),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0.0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Price|Number\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Price|Number\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");
    }

    out.push_str("    let h: Vec<&str> = table.headers.iter().map(|s| s.as_str()).collect();\n");

    // For eod_style, use the shared find_header() from decode.rs.
    if def.eod_style {
        out.push_str("    let find = |name: &str| find_header(&h, name);\n\n");
    }

    // Determine which columns need helpers.
    let needs_opt_number = def
        .columns
        .iter()
        .any(|c| c.r#type == "i32" && !def.required.contains(&c.name) && c.field != "date");
    let needs_opt_float = def
        .columns
        .iter()
        .any(|c| c.r#type == "f64" && !def.required.contains(&c.name));
    let needs_opt_i64 = def
        .columns
        .iter()
        .any(|c| c.r#type == "i64" && !def.required.contains(&c.name));

    // Emit opt_number / opt_float / opt_i64 helpers (non-eod only). Each
    // returns `Result<T, DecodeError>`: absent column or NullValue → default,
    // type mismatch → error propagated.
    if !def.eod_style {
        if needs_opt_number {
            out.push_str("    fn opt_number(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<i32, DecodeError> {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_number(row, i)?.unwrap_or(0)),\n");
            out.push_str("            None => Ok(0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_float {
            // `f64` columns (greeks, IV, interest rates) legitimately arrive
            // as Price or Number on the v3 MDDS server; dispatch on the wire
            // type the same way Java's `dataValue2Object` does (PRICE →
            // BigDecimal, NUMBER → Long). See `row_price_f64` for the
            // accept-list.
            out.push_str("    fn opt_float(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<f64, DecodeError> {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_price_f64(row, i)?.unwrap_or(0.0)),\n");
            out.push_str("            None => Ok(0.0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_i64 {
            out.push_str(
                "    fn opt_i64(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<i64, DecodeError> {\n",
            );
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_number_i64(row, i)?.unwrap_or(0)),\n");
            out.push_str("            None => Ok(0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
    }

    // Required header guards (non-eod only).
    if !def.eod_style {
        for req in &def.required {
            let var = format!("{req}_idx");
            writeln!(out,
                "    let Some({var}) = find_header(&h, \"{req}\") else {{\n        return Ok(vec![]);\n    }};"
            ).unwrap();
        }
        if !def.required.is_empty() {
            out.push('\n');
        }
    }

    // Declare index variables for all columns.
    for col in &def.columns {
        let var = format!("{}_idx", col.name);
        if def.eod_style {
            writeln!(out, "    let {var} = find(\"{}\");", col.name).unwrap();
        } else if def.required.contains(&col.name) {
            // Already declared above as required.
        } else {
            writeln!(out, "    let {var} = find_header(&h, \"{}\");", col.name).unwrap();
        }
    }

    // Contract identification columns (wildcard queries inject expiration/strike/right).
    if def.contract_id {
        out.push_str("    let _cid_exp_idx = h.iter().position(|c| *c == \"expiration\");\n");
        out.push_str("    let _cid_strike_idx = h.iter().position(|c| *c == \"strike\");\n");
        out.push_str("    let _cid_right_idx = h.iter().position(|c| *c == \"right\");\n");
        out.push_str("    let _cid_strike_is_typed = _cid_strike_idx.is_some() && h.contains(&\"strike\");\n");
    }

    // Check if this is QuoteTick (needs midpoint computation).
    let is_quote_tick = type_name == "QuoteTick";

    out.push('\n');

    // Emit the row mapping. Each row produces a `Result<Tick, DecodeError>`;
    // `.collect::<Result<Vec<_>, _>>()` short-circuits on the first error.
    out.push_str("    table\n");
    out.push_str("        .data_table\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|row| {\n");

    // Struct literal.
    if is_quote_tick {
        writeln!(out, "            let _tick = {type_name} {{").unwrap();
    } else {
        writeln!(out, "            Ok({type_name} {{").unwrap();
    }

    for col in &def.columns {
        let var = format!("{}_idx", col.name);
        let is_required = def.required.contains(&col.name);

        match col.r#type.as_str() {
            "i32" => {
                if def.eod_style {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => eod_num(row, i)?, None => 0 }},",
                        col.field
                    )
                    .unwrap();
                } else if is_required {
                    if col.field == "date" {
                        writeln!(
                            out,
                            "                {}: row_date(row, {var})?.unwrap_or(0),",
                            col.field
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            out,
                            "                {}: row_number(row, {var})?.unwrap_or(0),",
                            col.field
                        )
                        .unwrap();
                    }
                } else if col.field == "date" {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => row_date(row, i)?.unwrap_or(0), None => 0 }},",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: opt_number(row, {var})?,",
                        col.field
                    )
                    .unwrap();
                }
            }
            "i64" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_number_i64(row, {var})?.unwrap_or(0),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(out, "                {}: opt_i64(row, {var})?,", col.field).unwrap();
                }
            }
            "f64" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_price_f64(row, {var})?.unwrap_or(0.0),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: opt_float(row, {var})?,",
                        col.field
                    )
                    .unwrap();
                }
            }
            "String" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_text(row, {var})?.unwrap_or_default(),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => row_text(row, i)?.unwrap_or_default(), None => String::new() }},",
                        col.field
                    )
                    .unwrap();
                }
            }
            "price" => {
                // Decode price to f64 at parse time.
                let field = &col.field;
                if is_required {
                    writeln!(
                        out,
                        "                {field}: row_price_f64(row, {var})?.unwrap_or(0.0),"
                    )
                    .unwrap();
                } else {
                    writeln!(out, "                {field}: match {var} {{").unwrap();
                    out.push_str(
                        "                    Some(i) => row_price_f64(row, i)?.unwrap_or(0.0),\n",
                    );
                    out.push_str("                    None => 0.0,\n");
                    out.push_str("                },\n");
                }
            }
            "eod_num" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_num(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_num64" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_num64(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_date" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_date(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_price" => {
                // EOD price field: decode to f64 from Price or Number cell.
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_price(row, i)?, None => 0.0 }},",
                    col.field
                )
                .unwrap();
            }
            other => panic!("unknown column type '{other}' in parser for {type_name}"),
        }
    }

    // Contract identification fields (injected when contract_id = true). The
    // `expiration` column legitimately arrives as Number (YYYYMMDD) or Text
    // (ISO "2026-04-13") depending on upstream version — dispatch on the
    // cell's own type rather than coalescing silently.
    if def.contract_id {
        out.push_str("                expiration: match _cid_exp_idx {\n");
        out.push_str("                    Some(i) => {\n");
        out.push_str("                        let dv = row.values.get(i).ok_or(DecodeError::MissingCell { column: i })?;\n");
        out.push_str("                        match dv.data_type.as_ref() {\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Number(n)) => *n as i32,\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Text(s)) => parse_iso_date(s),\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::NullValue(_)) => 0,\n");
        out.push_str(
            "                            None => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str("                                observed: \"Unset\",\n");
        out.push_str("                            }),\n");
        out.push_str(
            "                            other => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str(
            "                                observed: crate::decode::observed_name(other),\n",
        );
        out.push_str("                            }),\n");
        out.push_str("                        }\n");
        out.push_str("                    }\n");
        out.push_str("                    None => 0,\n");
        out.push_str("                },\n");
        // strike: decode to f64
        out.push_str("                strike: match _cid_strike_idx {\n");
        out.push_str(
            "                    Some(i) if _cid_strike_is_typed => row_price_f64(row, i)?.unwrap_or(0.0),\n",
        );
        out.push_str("                    Some(i) => row_number(row, i)?.unwrap_or(0) as f64,\n");
        out.push_str("                    None => 0.0,\n");
        out.push_str("                },\n");
        // right: ASCII code (Number) or text (Text) — strict dispatch.
        out.push_str("                right: match _cid_right_idx {\n");
        out.push_str("                    Some(i) => {\n");
        out.push_str("                        let dv = row.values.get(i).ok_or(DecodeError::MissingCell { column: i })?;\n");
        out.push_str("                        match dv.data_type.as_ref() {\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Number(n)) => *n as i32,\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Text(s)) => match s.as_str() {\n");
        out.push_str("                                \"CALL\" | \"C\" => 67,\n");
        out.push_str("                                \"PUT\" | \"P\" => 80,\n");
        out.push_str("                                _ => 0,\n");
        out.push_str("                            },\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::NullValue(_)) => 0,\n");
        out.push_str(
            "                            None => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str("                                observed: \"Unset\",\n");
        out.push_str("                            }),\n");
        out.push_str(
            "                            other => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str(
            "                                observed: crate::decode::observed_name(other),\n",
        );
        out.push_str("                            }),\n");
        out.push_str("                        }\n");
        out.push_str("                    }\n");
        out.push_str("                    None => 0,\n");
        out.push_str("                },\n");
    }

    if is_quote_tick {
        // QuoteTick gets midpoint computed from bid + ask.
        out.push_str("                midpoint: 0.0, // placeholder, set below\n");
        out.push_str("            };\n");
        out.push_str("            let mut _tick = _tick;\n");
        out.push_str("            _tick.midpoint = (_tick.bid + _tick.ask) / 2.0;\n");
        out.push_str("            Ok(_tick)\n");
    } else {
        out.push_str("            })\n");
    }

    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n\n");
}
