//! Emit `sdks/python/src/tick_classes.rs` — typed `#[pyclass]` structs,
//! `<Tick>List` wrapper pyclasses, and list converters.
//!
//! Matches the typed-struct approach used by Rust core, TypeScript, Go,
//! and C++ FFI. Primary return shape for all historical endpoint methods:
//! every generated endpoint returns `Py<<TickName>List>`, a typed list
//! wrapper whose terminal methods chain straight into Arrow / pandas /
//! polars / plain `list` without any free-function round-trip.

use std::fmt::Write as _;

use super::schema::{Schema, TickTypeDef};
use super::{pyclass_name, sorted_type_names};

pub(super) fn render_python_tick_classes(
    schema: &Schema,
    snapshot_return_types: &std::collections::HashSet<String>,
) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str(
        "// Typed pyclass structs per tick type + `<Tick>List` wrappers + list converters.\n",
    );
    out.push_str("// Matches the typed-struct approach used by Rust core, TypeScript, Go,\n");
    out.push_str("// and C++ FFI. Primary return shape for historical endpoint methods.\n");
    out.push_str("//\n");
    out.push_str("// Every historical endpoint returns `Py<<TickName>List>`; terminal\n");
    out.push_str("// methods (`to_list`, `to_arrow`, `to_pandas`, `to_polars`) live on\n");
    out.push_str("// the wrapper so chained calls like\n");
    out.push_str("//     tdx.stock_history_eod(...).to_polars()\n");
    out.push_str("// avoid a free-function round-trip.\n\n");

    // Imports kept here because `tick_classes.rs` is `include!`-ed into
    // `lib.rs` BEFORE `tick_arrow.rs`; the `use` statements in the
    // sibling file don't yet apply at this splice point. Duplicates are
    // a no-op in Rust at module scope.
    out.push_str("use arrow::array::{ArrayRef, StringArray};\n");
    out.push_str("use arrow::datatypes::{DataType, Field, Schema};\n");
    out.push_str("use arrow::record_batch::RecordBatch;\n\n");

    let type_names = sorted_type_names(schema);

    // Structs + pymethods for the leaf tick pyclasses.
    for type_name in &type_names {
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_class_struct(type_name, def));
        out.push('\n');
    }

    // `<Tick>List` + `<Tick>ListIter` pyclasses. Emitted per tick type so
    // every historical endpoint that returns `EodTicks` (etc.) lands on a
    // concrete typed wrapper.
    for type_name in &type_names {
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_list_struct(type_name, def));
        out.push('\n');
    }

    // Converter helpers: take an owned `Vec<tick::T>` and produce
    // `Py<<TickName>List>`. The decoder-owned Vec is moved straight into
    // the wrapper, so no extra allocation / no double-buffering RSS spike.
    for type_name in &type_names {
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_class_list_fn(type_name, def));
        out.push('\n');
    }

    // Snapshot-endpoint fast-path converter: take an owned `Vec<tick::T>`
    // and produce a plain `Py<PyList>` of typed pyclass instances. Skips
    // the `<TickName>List` wrapper allocation — snapshots return <=10
    // small rows and callers never chain `.to_polars()` on a 1-row
    // calendar-day result, so the wrapper cost is pure overhead on the
    // latency-sensitive path. Only the snapshot / calendar generator
    // branch in `endpoints/render/python.rs` emits calls to these.
    //
    // Emission is gated on `snapshot_return_types` (derived from
    // `endpoint_surface.toml` by `endpoints::snapshot_return_types`) so
    // tick types that are not returned by any snapshot endpoint — e.g.
    // `EodTick`, `TradeQuoteTick`, `InterestRateTick`, `OptionContract`
    // at the time of writing — do not land as dead-code functions in the
    // generated file. Adding a snapshot endpoint of a new tick type to
    // the TOML automatically opts its converter into emission on the
    // next generator run.
    for type_name in &type_names {
        // `python_list_fn_name` yields the `*_to_pyclass_list` name;
        // the matching collection return-type is the prefix (e.g.
        // `OhlcTick` -> `OhlcTicks`). Map using `tick_collection_name`
        // below so the filter key matches `endpoint_surface.toml::returns`
        // verbatim.
        let collection_name = tick_collection_name(type_name);
        if !snapshot_return_types.contains(collection_name) {
            continue;
        }
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_class_vec_to_pylist_fn(type_name, def));
        out.push('\n');
    }

    // `StringList` wrapper + converter for every endpoint whose public
    // return shape is `Vec<String>` (symbols / dates / expirations /
    // strikes). Emitted unconditionally — not schema-driven, but kept
    // in the same generator output so one `include!("tick_classes.rs")`
    // seam covers every list-returning endpoint.
    out.push_str(&render_python_string_list());

    // Registration helper.
    out.push_str(
        "pub(crate) fn register_tick_classes(m: &Bound<'_, PyModule>) -> PyResult<()> {\n",
    );
    for type_name in &type_names {
        writeln!(out, "    m.add_class::<{}>()?;", pyclass_name(type_name)).unwrap();
        writeln!(
            out,
            "    m.add_class::<{}List>()?;",
            pyclass_name(type_name)
        )
        .unwrap();
        writeln!(
            out,
            "    m.add_class::<{}ListIter>()?;",
            pyclass_name(type_name)
        )
        .unwrap();
    }
    out.push_str("    m.add_class::<StringList>()?;\n");
    out.push_str("    m.add_class::<StringListIter>()?;\n");
    out.push_str("    Ok(())\n}\n\n");

    // Note: the `columns_for_qualname` dispatcher that used to live
    // here has been subsumed by `arrow_schema_for_qualname` in
    // `tick_arrow.rs` -- the Arrow schema carries the column names
    // AND types in one typed surface, so the bare name list became
    // redundant.
    out
}

/// Render the `StringList` + `StringListIter` pyclasses. Wraps
/// `Vec<String>` returned by list endpoints (`stock_list_symbols`,
/// `option_list_expirations`, `stock_list_dates`, ...) with the same
/// Python list protocol + chainable terminals as the tick list wrappers.
/// The `column_name` captured at construction drives the DataFrame
/// column name when `.to_arrow()` / `.to_pandas()` / `.to_polars()` is
/// called, so `stock_list_symbols().to_polars()` lands with a column
/// called `symbol` (not `_0` or similar).
fn render_python_string_list() -> String {
    let mut out = String::new();
    out.push_str("// ─────────────── String list wrapper ───────────────\n");
    out.push_str("//\n");
    out.push_str("// Emitted unconditionally (not schema-driven). Shared by every\n");
    out.push_str("// endpoint whose public return is `Vec<String>`.\n\n");

    // StringList pyclass.
    out.push_str("/// Typed list of strings returned by list endpoints\n");
    out.push_str("/// (`stock_list_symbols`, `option_list_expirations`, ...).\n");
    out.push_str("/// Wraps `Vec<String>` and exposes the Python list protocol plus\n");
    out.push_str("/// the chainable terminals (`to_list`, `to_arrow`, `to_pandas`,\n");
    out.push_str("/// `to_polars`). The `column_name` captured at construction drives\n");
    out.push_str("/// the DataFrame column name produced by the Arrow terminals, so\n");
    out.push_str("/// `stock_list_symbols().to_polars()` lands with a typed `symbol`\n");
    out.push_str("/// column rather than a numeric positional index.\n");
    out.push_str("#[must_use]\n");
    out.push_str("#[pyclass(module = \"thetadatadx\", frozen, skip_from_py_object)]\n");
    out.push_str("pub(crate) struct StringList {\n");
    out.push_str("    inner: Vec<String>,\n");
    out.push_str("    column_name: String,\n");
    out.push_str("}\n\n");

    out.push_str("impl StringList {\n");
    out.push_str("    pub(crate) fn new(inner: Vec<String>, column_name: &str) -> Self {\n");
    out.push_str("        Self {\n");
    out.push_str("            inner,\n");
    out.push_str("            column_name: column_name.to_string(),\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("#[pymethods]\n");
    out.push_str("impl StringList {\n");
    out.push_str("    fn __len__(&self) -> usize {\n");
    out.push_str("        self.inner.len()\n");
    out.push_str("    }\n\n");
    out.push_str("    fn __bool__(&self) -> bool {\n");
    out.push_str("        !self.inner.is_empty()\n");
    out.push_str("    }\n\n");
    out.push_str("    fn __repr__(&self) -> String {\n");
    out.push_str(
        "        format!(\"StringList({} rows, column={:?})\", self.inner.len(), self.column_name)\n",
    );
    out.push_str("    }\n\n");
    out.push_str("    fn __getitem__(&self, idx: isize) -> PyResult<String> {\n");
    out.push_str("        let len = self.inner.len() as isize;\n");
    out.push_str("        let resolved = if idx < 0 { idx + len } else { idx };\n");
    out.push_str("        if resolved < 0 || resolved >= len {\n");
    out.push_str("            return Err(pyo3::exceptions::PyIndexError::new_err(format!(\n");
    out.push_str(
        "                \"StringList index {} out of range (len={})\", idx, self.inner.len()\n",
    );
    out.push_str("            )));\n");
    out.push_str("        }\n");
    out.push_str("        Ok(self.inner[resolved as usize].clone())\n");
    out.push_str("    }\n\n");
    out.push_str(
        "    fn __iter__(slf: PyRef<'_, Self>, py: Python<'_>) -> PyResult<Py<StringListIter>> {\n",
    );
    out.push_str("        Py::new(py, StringListIter { inner: slf.inner.clone(), cursor: 0 })\n");
    out.push_str("    }\n\n");
    out.push_str("    /// Return the wrapped values as a plain Python `list[str]`.\n");
    out.push_str("    fn to_list(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    out.push_str("        let list = pyo3::types::PyList::empty(py);\n");
    out.push_str("        for s in &self.inner {\n");
    out.push_str("            list.append(s.as_str())?;\n");
    out.push_str("        }\n");
    out.push_str("        Ok(list.into_any().unbind())\n");
    out.push_str("    }\n\n");
    out.push_str(
        "    /// Return a `pyarrow.Table` with a single `column_name`-named string column.\n",
    );
    out.push_str("    fn to_arrow(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    out.push_str("        string_list_slice_to_arrow_table(py, &self.inner, &self.column_name)\n");
    out.push_str("    }\n\n");
    out.push_str("    /// Return a `pandas.DataFrame` with a single `column_name` column.\n");
    out.push_str("    fn to_pandas(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    out.push_str(
        "        let table = string_list_slice_to_arrow_table(py, &self.inner, &self.column_name)?;\n",
    );
    out.push_str("        pyarrow_table_to_pandas(py, table)\n");
    out.push_str("    }\n\n");
    out.push_str("    /// Return a `polars.DataFrame` with a single `column_name` column.\n");
    out.push_str("    fn to_polars(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    out.push_str(
        "        let table = string_list_slice_to_arrow_table(py, &self.inner, &self.column_name)?;\n",
    );
    out.push_str("        pyarrow_table_to_polars(py, table)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // StringListIter pyclass.
    out.push_str("/// Companion iterator for [`StringList`]. Yields owned `String`s\n");
    out.push_str("/// until the wrapped `Vec` is exhausted. One allocation per call to\n");
    out.push_str("/// `__next__` (clone of the inner entry); the underlying Vec is\n");
    out.push_str("/// cloned once at construction so mutating it mid-iteration is\n");
    out.push_str("/// a non-issue.\n");
    out.push_str("#[pyclass(module = \"thetadatadx\", skip_from_py_object)]\n");
    out.push_str("pub(crate) struct StringListIter {\n");
    out.push_str("    inner: Vec<String>,\n");
    out.push_str("    cursor: usize,\n");
    out.push_str("}\n\n");

    out.push_str("#[pymethods]\n");
    out.push_str("impl StringListIter {\n");
    out.push_str("    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {\n");
    out.push_str("        slf\n");
    out.push_str("    }\n\n");
    out.push_str("    fn __next__(&mut self) -> Option<String> {\n");
    out.push_str("        if self.cursor >= self.inner.len() {\n");
    out.push_str("            return None;\n");
    out.push_str("        }\n");
    out.push_str("        let s = self.inner[self.cursor].clone();\n");
    out.push_str("        self.cursor += 1;\n");
    out.push_str("        Some(s)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // Constructor helper for endpoint generators.
    out.push_str("pub(crate) fn strings_to_string_list(\n");
    out.push_str("    py: Python<'_>,\n");
    out.push_str("    values: Vec<String>,\n");
    out.push_str("    column_name: &str,\n");
    out.push_str(") -> PyResult<Py<StringList>> {\n");
    out.push_str("    Py::new(py, StringList::new(values, column_name))\n");
    out.push_str("}\n\n");

    // Slice -> Arrow table helper. Lives here so `StringList.to_arrow`
    // stays zero-copy at the pyarrow boundary (the single column is
    // materialized as an Arrow `StringArray`, then the RecordBatch goes
    // through the same `record_batch_to_pyarrow_table` the tick types use).
    out.push_str("fn string_list_slice_to_arrow_table(\n");
    out.push_str("    py: Python<'_>,\n");
    out.push_str("    values: &[String],\n");
    out.push_str("    column_name: &str,\n");
    out.push_str(") -> PyResult<Py<PyAny>> {\n");
    out.push_str("    let schema = Arc::new(Schema::new(vec![Field::new(\n");
    out.push_str("        column_name,\n");
    out.push_str("        DataType::Utf8,\n");
    out.push_str("        false,\n");
    out.push_str("    )]));\n");
    out.push_str(
        "    let column: ArrayRef = Arc::new(StringArray::from_iter_values(values.iter().map(String::as_str)));\n",
    );
    out.push_str("    let batch = RecordBatch::try_new(schema, vec![column])\n");
    out.push_str(
        "        .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(e.to_string()))?;\n",
    );
    out.push_str("    record_batch_to_pyarrow_table(py, batch)\n");
    out.push_str("}\n\n");

    out
}

fn python_list_fn_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "eod_ticks_to_pyclass_list",
        "OhlcTick" => "ohlc_ticks_to_pyclass_list",
        "TradeTick" => "trade_ticks_to_pyclass_list",
        "QuoteTick" => "quote_ticks_to_pyclass_list",
        "TradeQuoteTick" => "trade_quote_ticks_to_pyclass_list",
        "OpenInterestTick" => "open_interest_ticks_to_pyclass_list",
        "MarketValueTick" => "market_value_ticks_to_pyclass_list",
        "GreeksTick" => "greeks_ticks_to_pyclass_list",
        "IvTick" => "iv_ticks_to_pyclass_list",
        "PriceTick" => "price_ticks_to_pyclass_list",
        "CalendarDay" => "calendar_days_to_pyclass_list",
        "InterestRateTick" => "interest_rate_ticks_to_pyclass_list",
        "OptionContract" => "option_contracts_to_pyclass_list",
        other => panic!("unsupported Python list fn: {other}"),
    }
}

/// Slice-based Arrow converter name in `tick_arrow::slice_arrow`. The
/// `<Tick>List.to_arrow` terminal calls this converter directly so the
/// decoder-owned `Vec<tick::T>` feeds the Arrow column builders without
/// any pyclass-list round-trip.
fn slice_arrow_converter(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "slice_arrow::eod_tick_slice_to_arrow_table",
        "OhlcTick" => "slice_arrow::ohlc_tick_slice_to_arrow_table",
        "TradeTick" => "slice_arrow::trade_tick_slice_to_arrow_table",
        "QuoteTick" => "slice_arrow::quote_tick_slice_to_arrow_table",
        "TradeQuoteTick" => "slice_arrow::trade_quote_tick_slice_to_arrow_table",
        "OpenInterestTick" => "slice_arrow::open_interest_tick_slice_to_arrow_table",
        "MarketValueTick" => "slice_arrow::market_value_tick_slice_to_arrow_table",
        "GreeksTick" => "slice_arrow::greeks_tick_slice_to_arrow_table",
        "IvTick" => "slice_arrow::iv_tick_slice_to_arrow_table",
        "PriceTick" => "slice_arrow::price_tick_slice_to_arrow_table",
        "CalendarDay" => "slice_arrow::calendar_day_slice_to_arrow_table",
        "InterestRateTick" => "slice_arrow::interest_rate_tick_slice_to_arrow_table",
        "OptionContract" => "slice_arrow::option_contract_slice_to_arrow_table",
        other => panic!("unsupported slice-arrow converter: {other}"),
    }
}

/// Strip " -- N fields[...]." from the first doc line so the rendered
/// comment reflects the actual field set once `contract_id` and
/// `QuoteTick` midpoint get appended to `def.columns`. Words stay stable
/// even when a schema edit adds/removes a column, so we drop the numeric
/// count instead of recomputing it per surface.
pub(super) fn strip_field_count_from_doc(doc: &str) -> String {
    let first_line = doc.lines().next().unwrap_or("");
    if let Some(pos) = first_line.find(" -- ") {
        let after_dash = &first_line[pos + 4..];
        if after_dash.starts_with(|c: char| c.is_ascii_digit()) {
            let rest = after_dash
                .find(". ")
                .map(|i| &after_dash[i + 2..])
                .unwrap_or("");
            if rest.is_empty() {
                return format!("{}.", &first_line[..pos]);
            }
            return format!("{}. {rest}", &first_line[..pos]);
        }
    }
    first_line.to_string()
}

/// Pick the first few fields for `__repr__` rendering. Caps at
/// `max_fields` to keep output one-line readable in REPL / debugger
/// transcripts. Contract-id fields are appended after the schema
/// columns on the emitted struct, so we mirror that order here — the
/// first few real columns come first (e.g. `ms_of_day`, `open`,
/// `high`, `low`), never the trailing `expiration`/`strike`/`right`
/// triple which is identical across a result set and carries no
/// per-row diagnostic signal.
fn repr_fields_for_tick<'a>(
    type_name: &str,
    def: &'a TickTypeDef,
    max_fields: usize,
) -> Vec<ReprField<'a>> {
    let mut fields: Vec<ReprField<'a>> = Vec::new();
    for column in &def.columns {
        if fields.len() >= max_fields {
            break;
        }
        // `OptionContract.right` is surfaced as a String (see
        // `render_python_tick_class_struct`), so prefer `{:?}` so the
        // quotes are visible — consistent with other String fields
        // like `QuoteTick` never exposing `right` directly.
        let is_string = (type_name == "OptionContract" && column.field == "right")
            || matches!(column.r#type.as_str(), "String");
        fields.push(ReprField {
            name: &column.field,
            is_string,
        });
    }
    fields
}

struct ReprField<'a> {
    name: &'a str,
    is_string: bool,
}

fn render_python_tick_class_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";
    let doc_text = if def.doc.is_empty() {
        format!("Typed {type_name} record.")
    } else {
        let stripped = strip_field_count_from_doc(&def.doc);
        // Preserve any trailing doc lines (e.g. `OptionContract`'s "Cannot
        // be `Copy` ..." note) by splicing the stripped first line back
        // onto the rest of the original doc. Lines after the first rarely
        // carry field-count language.
        let mut combined = stripped;
        for line in def.doc.lines().skip(1) {
            combined.push('\n');
            combined.push_str(line);
        }
        combined
    };
    for line in doc_text.lines() {
        writeln!(out, "/// {line}").unwrap();
    }
    // `#[must_use]` — these ticks come from expensive network calls; dropping
    // the result silently is a bug. `skip_from_py_object` opts out of the
    // auto-derived `FromPyObject` impl (deprecated for `Clone` pyclasses in
    // pyo3 0.28+); these classes are returned FROM Rust to Python but never
    // consumed AS arguments INTO Rust, so `FromPyObject` is dead weight.
    out.push_str("#[must_use]\n");
    out.push_str("#[pyclass(module = \"thetadatadx\", frozen, skip_from_py_object)]\n");
    out.push_str("#[derive(Clone)]\n");
    writeln!(out, "pub(crate) struct {class} {{").unwrap();
    for column in &def.columns {
        // Special case: `OptionContract.right` is stored on the wire as
        // `i32` (ASCII 67/80), but every other tick surfaces `right` as
        // a Python `"C" | "P" | ""` string (via the contract_id injection
        // below). Emit it as String here too so the two paths match and
        // consumer code doesn't get an integer on one endpoint and a
        // string on the others.
        let rust_type = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            pyclass_field_type(column.r#type.as_str(), type_name)
        };
        writeln!(out, "    #[pyo3(get)] pub {}: {},", column.field, rust_type).unwrap();
    }
    if is_quote_tick {
        out.push_str("    #[pyo3(get)] pub midpoint: f64,\n");
    }
    if def.contract_id {
        out.push_str("    #[pyo3(get)] pub expiration: i32,\n");
        out.push_str("    #[pyo3(get)] pub strike: f64,\n");
        out.push_str("    #[pyo3(get)] pub right: String,\n");
    }
    out.push_str("}\n");

    // `__repr__` shows the first six schema fields with their live
    // values so REPLs and debuggers (pdb, IDE watch windows, pytest
    // short-repr) surface per-instance data instead of a useless
    // `"<EodTick(...)>"`. Six is a readable cap; `contract_id` columns
    // (`expiration`/`strike`/`right`) are identical across a result
    // set and carry no per-row signal, so we skip them.
    //
    // `#[new]` constructor accepts every field as a kwarg defaulting
    // to zero / empty-string. Tick classes are primarily returned
    // from the network endpoints so users rarely need to build them
    // manually; the one exception is test fixtures -- the Arrow
    // DataFrame adapter test suite constructs known lists in Python
    // and round-trips them through the `<Tick>List` terminals to
    // verify value preservation. Without this ctor there is no way
    // to drive that test.
    writeln!(out, "#[pymethods]").unwrap();
    writeln!(out, "impl {class} {{").unwrap();
    out.push_str(&render_python_tick_class_new(type_name, def));
    let repr_fields = repr_fields_for_tick(type_name, def, 6);
    if repr_fields.is_empty() {
        // Unlikely (every tick has columns), but keep the fallback so
        // a future schema type without columns still compiles.
        writeln!(
            out,
            "    fn __repr__(&self) -> String {{ \"{class}()\".to_string() }}"
        )
        .unwrap();
    } else {
        let mut fmt_string = String::new();
        for (idx, field) in repr_fields.iter().enumerate() {
            if idx > 0 {
                fmt_string.push_str(", ");
            }
            fmt_string.push_str(field.name);
            fmt_string.push('=');
            // `{:?}` quotes strings (`right="C"`), `{}` for numerics —
            // matches the shape an engineer expects in a debugger line.
            fmt_string.push_str(if field.is_string { "{:?}" } else { "{}" });
        }
        let args = repr_fields
            .iter()
            .map(|f| format!("self.{}", f.name))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "    fn __repr__(&self) -> String {{").unwrap();
        writeln!(out, "        format!(\"{class}({fmt_string})\", {args})").unwrap();
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    out
}

fn pyclass_field_type(column_type: &str, type_name: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" | "eod_num64" => "i64",
        "f64" | "price" | "eod_price" => "f64",
        "String" => "String",
        other => panic!("unsupported column type '{other}' in pyclass for {type_name}"),
    }
}

/// Emit a `#[new]` kwarg constructor so Python test fixtures can
/// build tick instances. Every field accepts a default (0 / 0.0 /
/// empty-string) so callers can pass just the fields they care
/// about: `EodTick(ms_of_day=1, volume=1_000)`.
fn render_python_tick_class_new(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    struct CtorField<'a> {
        name: &'a str,
        rust_type: &'a str,
        default: &'static str,
    }
    let mut fields: Vec<CtorField> = Vec::new();
    for column in &def.columns {
        // Same OptionContract.right special case as the struct emitter.
        let rust_type = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            pyclass_field_type(column.r#type.as_str(), type_name)
        };
        let default = match rust_type {
            "i32" => "0i32",
            "i64" => "0i64",
            "f64" => "0.0f64",
            "String" => "String::new()",
            other => panic!("unhandled pyclass ctor default for {other}"),
        };
        fields.push(CtorField {
            name: column.field.as_str(),
            rust_type,
            default,
        });
    }
    if type_name == "QuoteTick" {
        fields.push(CtorField {
            name: "midpoint",
            rust_type: "f64",
            default: "0.0f64",
        });
    }
    if def.contract_id {
        fields.push(CtorField {
            name: "expiration",
            rust_type: "i32",
            default: "0i32",
        });
        fields.push(CtorField {
            name: "strike",
            rust_type: "f64",
            default: "0.0f64",
        });
        fields.push(CtorField {
            name: "right",
            rust_type: "String",
            default: "String::new()",
        });
    }

    // `#[pyo3(signature = (*, a=..., b=...))]` forces keyword-only args so
    // the argument order in tests doesn't hard-code the schema field order.
    out.push_str("    #[new]\n");
    out.push_str("    #[pyo3(signature = (*,");
    for (idx, f) in fields.iter().enumerate() {
        if idx > 0 {
            out.push(',');
        }
        // pyo3 accepts literal Rust expressions for kwarg defaults.
        out.push_str(&format!(" {} = {}", f.name, f.default));
    }
    out.push_str("))]\n");
    // `too_many_arguments` is suppressed at the crate build command
    // (`cargo clippy ... -A clippy::too_many_arguments` in the
    // validation checklist) rather than per-function -- the project
    // policy forbids per-item `#[allow(...)]` additions.
    out.push_str("    fn new(");
    for (idx, f) in fields.iter().enumerate() {
        if idx > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{}: {}", f.name, f.rust_type));
    }
    out.push_str(") -> Self {\n");
    writeln!(out, "        Self {{").unwrap();
    for f in &fields {
        writeln!(out, "            {n},", n = f.name).unwrap();
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out
}

/// Emit a Rust block that reads the fields of a `<TickName>` pyclass
/// (accessed via `source_expr`) and constructs the matching
/// `tick::<TickName>` struct. Used by the `#[new]` constructor on
/// `<TickName>List` — users pass a list of pyclass instances, the
/// generator-emitted loop pushes `tick::T` values into the inner Vec.
///
/// Inverse of `pyclass_from_tick_expr`. Handles the `right: String` ->
/// `right: i32` ASCII projection (pyclass exposes `"C" | "P" | ""`, the
/// Rust tick holds 67 / 80 / 0).
fn pyclass_to_tick_expr(
    out: &mut String,
    type_name: &str,
    def: &TickTypeDef,
    source_expr: &str,
    indent: &str,
) {
    writeln!(out, "{indent}tick::{type_name} {{").unwrap();
    for column in &def.columns {
        if type_name == "OptionContract" && column.field == "right" {
            // `OptionContract.right` is stored as `i32` on the tick
            // struct; pyclass surfaces it as "C" / "P" / "". Reverse
            // the projection here.
            writeln!(
                out,
                "{indent}    right: match {source_expr}.right.as_str() {{ \"C\" => 67, \"P\" => 80, _ => 0 }},",
            )
            .unwrap();
            continue;
        }
        let rust_type = pyclass_field_type(column.r#type.as_str(), type_name);
        if rust_type == "String" {
            writeln!(
                out,
                "{indent}    {}: {source_expr}.{}.clone(),",
                column.field, column.field
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "{indent}    {}: {source_expr}.{},",
                column.field, column.field
            )
            .unwrap();
        }
    }
    if type_name == "QuoteTick" {
        writeln!(out, "{indent}    midpoint: {source_expr}.midpoint,").unwrap();
    }
    if def.contract_id {
        writeln!(out, "{indent}    expiration: {source_expr}.expiration,").unwrap();
        writeln!(out, "{indent}    strike: {source_expr}.strike,").unwrap();
        // Same "C"/"P"/"" -> 67/80/0 projection as the OptionContract case above.
        writeln!(
            out,
            "{indent}    right: match {source_expr}.right.as_str() {{ \"C\" => 67, \"P\" => 80, _ => 0 }},",
        )
        .unwrap();
    }
    writeln!(out, "{indent}}}").unwrap();
}

/// Emit a Rust expression that clones a `tick::<TickName>` into the
/// matching `<TickName>` pyclass instance. Shared by `__getitem__`,
/// `__next__`, and the `to_list` terminal on `<TickName>List`.
///
/// `source_expr` is the Rust expression that evaluates to a
/// `&tick::<TickName>` (borrowed) — callers can pass `&self.inner[idx]`,
/// `&tick_ref`, or similar. The emitted code clones String fields and
/// copies primitive fields.
fn pyclass_from_tick_expr(
    out: &mut String,
    type_name: &str,
    def: &TickTypeDef,
    source_expr: &str,
    indent: &str,
) {
    let class = pyclass_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";
    writeln!(out, "{indent}{class} {{").unwrap();
    for column in &def.columns {
        if type_name == "OptionContract" && column.field == "right" {
            writeln!(
                out,
                "{indent}    right: (if {source_expr}.is_call() {{ \"C\" }} else if {source_expr}.is_put() {{ \"P\" }} else {{ \"\" }}).to_string(),",
            )
            .unwrap();
            continue;
        }
        let rust_type = pyclass_field_type(column.r#type.as_str(), type_name);
        if rust_type == "String" {
            writeln!(
                out,
                "{indent}    {}: {source_expr}.{}.clone(),",
                column.field, column.field
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "{indent}    {}: {source_expr}.{},",
                column.field, column.field
            )
            .unwrap();
        }
    }
    if is_quote_tick {
        writeln!(out, "{indent}    midpoint: {source_expr}.midpoint,").unwrap();
    }
    if def.contract_id {
        writeln!(out, "{indent}    expiration: {source_expr}.expiration,").unwrap();
        writeln!(out, "{indent}    strike: {source_expr}.strike,").unwrap();
        writeln!(
            out,
            "{indent}    right: (if {source_expr}.is_call() {{ \"C\" }} else if {source_expr}.is_put() {{ \"P\" }} else {{ \"\" }}).to_string(),",
        )
        .unwrap();
    }
    writeln!(out, "{indent}}}").unwrap();
}

/// Render the `<Tick>List` + `<Tick>ListIter` pyclasses for a given
/// tick type. The List wraps `Vec<tick::T>` and exposes the Python
/// list protocol (`__len__`, `__getitem__`, `__iter__`, `__bool__`,
/// `__repr__`) plus the chained terminals (`to_list`, `to_arrow`,
/// `to_pandas`, `to_polars`).
fn render_python_tick_list_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let list_class = format!("{class}List");
    let iter_class = format!("{class}ListIter");
    let slice_arrow = slice_arrow_converter(type_name);

    // Rust-side source type. The wrapper holds the decoder-owned
    // Vec<tick::T>; no intermediate pyclass-list materialisation.
    let source_ty = format!("tick::{type_name}");

    // ───────── <Tick>List ─────────

    writeln!(
        out,
        "/// Typed list of `{class}` returned by every historical endpoint"
    )
    .unwrap();
    writeln!(
        out,
        "/// whose response is `{class}`. Wraps the decoder-owned `Vec<{type_name}>`"
    )
    .unwrap();
    out.push_str("/// and exposes the Python list protocol (`len(ticks)`, `ticks[i]`,\n");
    out.push_str("/// `for t in ticks: ...`, `bool(ticks)`) plus the chained terminals\n");
    out.push_str("/// `.to_list()`, `.to_arrow()`, `.to_pandas()`, `.to_polars()`.\n");
    out.push_str("#[must_use]\n");
    out.push_str("#[pyclass(module = \"thetadatadx\", frozen, skip_from_py_object)]\n");
    writeln!(out, "pub(crate) struct {list_class} {{").unwrap();
    writeln!(out, "    inner: Vec<{source_ty}>,").unwrap();
    out.push_str("}\n\n");

    writeln!(out, "impl {list_class} {{").unwrap();
    writeln!(
        out,
        "    pub(crate) fn new(inner: Vec<{source_ty}>) -> Self {{"
    )
    .unwrap();
    out.push_str("        Self { inner }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    writeln!(out, "#[pymethods]").unwrap();
    writeln!(out, "impl {list_class} {{").unwrap();
    // `#[new]` ctor — accepts an iterable of `<Tick>` pyclass instances
    // and builds the wrapper. Primary caller is the test suite: users in
    // production get `<Tick>List` handed back from endpoints, but the
    // round-trip tests (`<Tick>List.__len__`, `__getitem__`, `to_list`,
    // `to_arrow`) need a way to stand up a list from Python-constructed
    // `<Tick>` instances. Accepting `Vec<PyRef<<Tick>>>` sidesteps the
    // `FromPyObject` opt-out on the tick pyclasses — pyo3 can always
    // borrow a `PyRef<T>` when T is `#[pyclass]`, regardless of the
    // `skip_from_py_object` setting.
    out.push_str("    #[new]\n");
    out.push_str("    #[pyo3(signature = (ticks = Vec::new()))]\n");
    writeln!(
        out,
        "    fn py_new(ticks: Vec<pyo3::PyRef<'_, {class}>>) -> Self {{"
    )
    .unwrap();
    out.push_str("        let mut inner = Vec::with_capacity(ticks.len());\n");
    out.push_str("        for t in &ticks {\n");
    out.push_str("            inner.push(");
    pyclass_to_tick_expr(&mut out, type_name, def, "t", "            ");
    out.push_str("            );\n");
    out.push_str("        }\n");
    out.push_str("        Self { inner }\n");
    out.push_str("    }\n\n");

    // __len__
    out.push_str("    fn __len__(&self) -> usize {\n");
    out.push_str("        self.inner.len()\n");
    out.push_str("    }\n\n");

    // __bool__
    out.push_str("    fn __bool__(&self) -> bool {\n");
    out.push_str("        !self.inner.is_empty()\n");
    out.push_str("    }\n\n");

    // __repr__
    writeln!(out, "    fn __repr__(&self) -> String {{").unwrap();
    writeln!(
        out,
        "        format!(\"{list_class}({{}} rows)\", self.inner.len())"
    )
    .unwrap();
    out.push_str("    }\n\n");

    // __getitem__ — supports negative indexing, raises IndexError on OOB.
    writeln!(
        out,
        "    fn __getitem__(&self, idx: isize) -> PyResult<{class}> {{"
    )
    .unwrap();
    out.push_str("        let len = self.inner.len() as isize;\n");
    out.push_str("        let resolved = if idx < 0 { idx + len } else { idx };\n");
    out.push_str("        if resolved < 0 || resolved >= len {\n");
    out.push_str("            return Err(pyo3::exceptions::PyIndexError::new_err(format!(\n");
    writeln!(
        out,
        "                \"{list_class} index {{}} out of range (len={{}})\", idx, self.inner.len()"
    )
    .unwrap();
    out.push_str("            )));\n");
    out.push_str("        }\n");
    out.push_str("        let t = &self.inner[resolved as usize];\n");
    out.push_str("        Ok(");
    pyclass_from_tick_expr(&mut out, type_name, def, "t", "            ");
    // Trim the trailing newline pyclass_from_tick_expr emits inside the expression.
    out.push_str("        )\n");
    out.push_str("    }\n\n");

    // __iter__
    writeln!(
        out,
        "    fn __iter__(slf: PyRef<'_, Self>, py: Python<'_>) -> PyResult<Py<{iter_class}>> {{"
    )
    .unwrap();
    writeln!(
        out,
        "        Py::new(py, {iter_class} {{ inner: slf.inner.clone(), cursor: 0 }})"
    )
    .unwrap();
    out.push_str("    }\n\n");

    // to_list — plain PyList of pyclass instances.
    out.push_str("    /// Return a plain Python `list` of typed tick pyclass instances.\n");
    out.push_str("    /// Explicit escape hatch for callers that want a mutable list or\n");
    out.push_str("    /// need to pass the data into an API that only accepts `list`.\n");
    out.push_str("    fn to_list(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    out.push_str("        let list = pyo3::types::PyList::empty(py);\n");
    out.push_str("        for t in &self.inner {\n");
    out.push_str("            let obj = ");
    pyclass_from_tick_expr(&mut out, type_name, def, "t", "                ");
    out.push_str("            ;\n");
    out.push_str("            list.append(Py::new(py, obj)?)?;\n");
    out.push_str("        }\n");
    out.push_str("        Ok(list.into_any().unbind())\n");
    out.push_str("    }\n\n");

    // to_arrow — slice-based fast path, zero-copy into pyarrow.Table.
    out.push_str("    /// Return a `pyarrow.Table` backed by the decoder-owned slice.\n");
    out.push_str("    /// Zero-copy at the pyarrow boundary courtesy of the Arrow C\n");
    out.push_str("    /// Data Interface; downstream pandas / polars / DuckDB alias the\n");
    out.push_str("    /// same Rust buffers in place.\n");
    out.push_str("    fn to_arrow(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    writeln!(out, "        {slice_arrow}(py, &self.inner)").unwrap();
    out.push_str("    }\n\n");

    // to_pandas — delegates to to_arrow.
    out.push_str("    /// Return a `pandas.DataFrame` via `pyarrow.Table.to_pandas()`.\n");
    out.push_str("    /// Requires pandas + pyarrow: `pip install thetadatadx[pandas]`.\n");
    out.push_str("    fn to_pandas(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    writeln!(out, "        let table = {slice_arrow}(py, &self.inner)?;").unwrap();
    out.push_str("        pyarrow_table_to_pandas(py, table)\n");
    out.push_str("    }\n\n");

    // to_polars — delegates to to_arrow.
    out.push_str("    /// Return a `polars.DataFrame` via `polars.from_arrow`.\n");
    out.push_str("    /// Requires polars + pyarrow: `pip install thetadatadx[polars]`.\n");
    out.push_str("    fn to_polars(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {\n");
    writeln!(out, "        let table = {slice_arrow}(py, &self.inner)?;").unwrap();
    out.push_str("        pyarrow_table_to_polars(py, table)\n");
    out.push_str("    }\n");

    out.push_str("}\n\n");

    // ───────── <Tick>ListIter ─────────

    writeln!(
        out,
        "/// Companion iterator for [`{list_class}`]. Yields `{class}` pyclass"
    )
    .unwrap();
    out.push_str("/// instances until the wrapped `Vec` is exhausted, then raises\n");
    out.push_str("/// `StopIteration`. One allocation at construction (Vec clone); each\n");
    out.push_str("/// `__next__` only copies one tick out of the inner buffer.\n");
    out.push_str("#[pyclass(module = \"thetadatadx\", skip_from_py_object)]\n");
    writeln!(out, "pub(crate) struct {iter_class} {{").unwrap();
    writeln!(out, "    inner: Vec<{source_ty}>,").unwrap();
    out.push_str("    cursor: usize,\n");
    out.push_str("}\n\n");

    writeln!(out, "#[pymethods]").unwrap();
    writeln!(out, "impl {iter_class} {{").unwrap();
    out.push_str("    fn __iter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {\n");
    out.push_str("        slf\n");
    out.push_str("    }\n\n");
    writeln!(out, "    fn __next__(&mut self) -> Option<{class}> {{").unwrap();
    out.push_str("        if self.cursor >= self.inner.len() {\n");
    out.push_str("            return None;\n");
    out.push_str("        }\n");
    out.push_str("        let t = &self.inner[self.cursor];\n");
    out.push_str("        self.cursor += 1;\n");
    out.push_str("        Some(");
    pyclass_from_tick_expr(&mut out, type_name, def, "t", "            ");
    out.push_str("        )\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Emit the `*_to_pyclass_list` converter. Takes an owned
/// `Vec<tick::T>` and wraps it into a `Py<<TickName>List>`; the Vec is
/// moved straight in, no extra allocation.
fn render_python_tick_class_list_fn(type_name: &str, _def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let list_class = format!("{class}List");
    let fn_name = python_list_fn_name(type_name);

    writeln!(
        out,
        "pub(crate) fn {fn_name}(py: Python<'_>, ticks: Vec<tick::{type_name}>) -> PyResult<Py<{list_class}>> {{"
    )
    .unwrap();
    writeln!(out, "    Py::new(py, {list_class}::new(ticks))").unwrap();
    out.push_str("}\n");
    out
}

/// Map a `tick_schema.toml` tick-type name (e.g. `OhlcTick`) to the
/// collection name used in `endpoint_surface.toml::returns`
/// (`OhlcTicks`). Bridges the two TOML files at the generator layer so
/// the snapshot-return-type filter driving `_vec_to_pylist` emission can
/// match `returns` verbatim.
fn tick_collection_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "EodTicks",
        "OhlcTick" => "OhlcTicks",
        "TradeTick" => "TradeTicks",
        "QuoteTick" => "QuoteTicks",
        "TradeQuoteTick" => "TradeQuoteTicks",
        "OpenInterestTick" => "OpenInterestTicks",
        "MarketValueTick" => "MarketValueTicks",
        "GreeksTick" => "GreeksTicks",
        "IvTick" => "IvTicks",
        "PriceTick" => "PriceTicks",
        "CalendarDay" => "CalendarDays",
        "InterestRateTick" => "InterestRateTicks",
        "OptionContract" => "OptionContracts",
        other => panic!("unsupported tick-type collection name: {other}"),
    }
}

/// Snapshot-kind converter name. See [`python_vec_to_pylist_fn_name`]
/// caller in `endpoints/render/python.rs`.
fn python_vec_to_pylist_fn_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "eod_ticks_vec_to_pylist",
        "OhlcTick" => "ohlc_ticks_vec_to_pylist",
        "TradeTick" => "trade_ticks_vec_to_pylist",
        "QuoteTick" => "quote_ticks_vec_to_pylist",
        "TradeQuoteTick" => "trade_quote_ticks_vec_to_pylist",
        "OpenInterestTick" => "open_interest_ticks_vec_to_pylist",
        "MarketValueTick" => "market_value_ticks_vec_to_pylist",
        "GreeksTick" => "greeks_ticks_vec_to_pylist",
        "IvTick" => "iv_ticks_vec_to_pylist",
        "PriceTick" => "price_ticks_vec_to_pylist",
        "CalendarDay" => "calendar_days_vec_to_pylist",
        "InterestRateTick" => "interest_rate_ticks_vec_to_pylist",
        "OptionContract" => "option_contracts_vec_to_pylist",
        other => panic!("unsupported Python vec-to-pylist fn: {other}"),
    }
}

/// Emit the `<tick>_vec_to_pylist` converter — the snapshot fast-path
/// helper. Takes an owned `Vec<tick::T>` and materialises a plain
/// `Py<PyList>` of typed pyclass instances, skipping the `<TickName>List`
/// wrapper allocation. Body mirrors the `to_list` terminal on the wrapper
/// (SSOT: both call `pyclass_from_tick_expr` to build each pyclass row)
/// so snapshot-path and `.to_list()` output a byte-identical pylist.
fn render_python_tick_class_vec_to_pylist_fn(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let fn_name = python_vec_to_pylist_fn_name(type_name);

    writeln!(
        out,
        "/// Snapshot-endpoint fast-path converter. Materialises a plain"
    )
    .unwrap();
    writeln!(
        out,
        "/// `PyList` of `{class}` pyclass instances without allocating a"
    )
    .unwrap();
    writeln!(
        out,
        "/// `{class}List` wrapper. Used by snapshot / calendar endpoints"
    )
    .unwrap();
    writeln!(
        out,
        "/// where callers never chain `.to_polars()` on the result."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) fn {fn_name}(py: Python<'_>, ticks: Vec<tick::{type_name}>) -> PyResult<Py<pyo3::types::PyList>> {{"
    )
    .unwrap();
    out.push_str("    let list = pyo3::types::PyList::empty(py);\n");
    out.push_str("    for t in &ticks {\n");
    out.push_str("        let obj = ");
    pyclass_from_tick_expr(&mut out, type_name, def, "t", "            ");
    out.push_str("        ;\n");
    out.push_str("        list.append(Py::new(py, obj)?)?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(list.unbind())\n");
    out.push_str("}\n");
    out
}
