//! Emit `crates/thetadatadx/src/frames_generated.rs` — per-tick-type
//! `TicksPolarsExt` / `TicksArrowExt` impls.
//!
//! Two extension traits live in the hand-written `crates/thetadatadx/src/frames.rs`:
//!
//! * `TicksPolarsExt::to_polars(&self) -> PolarsResult<DataFrame>`
//! * `TicksArrowExt::to_arrow(&self) -> ArrowResult<RecordBatch>`
//!
//! This generator reads `tick_schema.toml` and emits one `impl TicksPolarsExt
//! for [tick::T]` and one `impl TicksArrowExt for [tick::T]` per tick type.
//! Both impls are feature-gated (`#[cfg(feature = "polars")]` / `#[cfg(feature
//! = "arrow")]`) so the SDK's default dep graph is unchanged — polars and
//! arrow stay opt-in.
//!
//! # SSOT with the Python slice_arrow path
//!
//! The column-shape decisions (column name, Arrow data type, widening
//! rules for `eod_num` / `eod_num64`, the `OptionContract.right` i32 →
//! string projection, the contract-id tail `expiration` / `strike` /
//! `right` trio, the `QuoteTick.midpoint` virtual column) are identical
//! to the Python slice_arrow emitter in `python_arrow.rs`. Both
//! generators read from the same `tick_schema.toml` and apply the same
//! field-type → Arrow-constructor mapping via `arrow_array_ctor` /
//! `arrow_data_type_expr` below (mirrored from `python_arrow.rs`).
//! Keeping both generators on the same schema SSOT is the reason the
//! Python `.to_polars()` and the Rust `.to_polars()` on equivalent
//! slices produce byte-identical DataFrame schemas.

use std::fmt::Write as _;

use super::schema::{Schema, TickTypeDef};
use super::sorted_type_names;

pub(super) fn render_rust_frames(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("//\n");
    out.push_str("// Per-tick-type `TicksPolarsExt` / `TicksArrowExt` impls. The traits\n");
    out.push_str("// themselves live in `crates/thetadatadx/src/frames.rs`; this file is\n");
    out.push_str("// `include!`-ed from that module so the feature-gated `#[cfg]` walls\n");
    out.push_str("// and the trait definitions share a single compilation unit.\n\n");

    out.push_str("#[cfg(feature = \"arrow\")]\n");
    out.push_str(
        "use arrow_array::{ArrayRef, Float64Array, Int32Array, Int64Array, StringArray};\n",
    );
    out.push_str("#[cfg(feature = \"arrow\")]\n");
    out.push_str("use arrow_array::RecordBatch;\n");
    out.push_str("#[cfg(feature = \"arrow\")]\n");
    out.push_str("use arrow_schema::{DataType, Field, Schema as ArrowSchema};\n");
    out.push_str("#[cfg(feature = \"arrow\")]\n");
    out.push_str("use std::sync::Arc;\n\n");

    out.push_str("#[cfg(feature = \"polars\")]\n");
    out.push_str(
        "use polars::prelude::{DataFrame, NamedFrom, PlSmallStr, PolarsResult, Series};\n\n",
    );

    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_arrow_impl(type_name, def));
        out.push('\n');
        out.push_str(&render_polars_impl(type_name, def));
        out.push('\n');
    }

    out
}

// ── Arrow impl ──────────────────────────────────────────────────────────
//
// Mirror of `python_arrow::render_python_slice_reader`. Same column set,
// same dtype mapping, same `right: i32` → `"C"/"P"/""` string projection
// on contract-id ticks + `OptionContract`.

fn render_arrow_impl(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let is_quote_tick = type_name == "QuoteTick";
    let is_contract = def.contract_id;
    let is_option_contract = type_name == "OptionContract";

    out.push_str("#[cfg(feature = \"arrow\")]\n");
    out.push_str("#[cfg_attr(docsrs, doc(cfg(feature = \"arrow\")))]\n");
    writeln!(
        out,
        "impl crate::frames::TicksArrowExt for [tdbe::types::tick::{type_name}] {{"
    )
    .unwrap();
    out.push_str(
        "    fn to_arrow(&self) -> ::core::result::Result<RecordBatch, arrow_schema::ArrowError> {\n",
    );
    out.push_str("        let n = self.len();\n");

    // Column vectors.
    let mut column_decls: Vec<(String, String, bool)> = Vec::new();
    for column in &def.columns {
        let (rust_ty, effective_type) = if is_option_contract && column.field == "right" {
            ("String", "String")
        } else {
            let ty = tick_struct_field_type(column.r#type.as_str());
            (ty, column.r#type.as_str())
        };
        writeln!(
            out,
            "        let mut col_{field}: Vec<{rust_ty}> = Vec::with_capacity(n);",
            field = column.field
        )
        .unwrap();
        column_decls.push((
            column.field.clone(),
            effective_type.to_string(),
            rust_ty == "String",
        ));
    }
    if is_quote_tick {
        out.push_str("        let mut col_midpoint: Vec<f64> = Vec::with_capacity(n);\n");
    }
    if is_contract {
        out.push_str("        let mut col_expiration: Vec<i32> = Vec::with_capacity(n);\n");
        out.push_str("        let mut col_strike: Vec<f64> = Vec::with_capacity(n);\n");
        out.push_str("        let mut col_right: Vec<String> = Vec::with_capacity(n);\n");
    }

    // Fill loop.
    out.push_str("        for t in self {\n");
    for (field, _effective, is_string) in &column_decls {
        if is_option_contract && field == "right" {
            out.push_str(
                "            col_right.push(if t.is_call() { \"C\".to_string() } else if t.is_put() { \"P\".to_string() } else { String::new() });\n",
            );
            continue;
        }
        if *is_string {
            writeln!(out, "            col_{field}.push(t.{field}.clone());").unwrap();
        } else {
            writeln!(out, "            col_{field}.push(t.{field});").unwrap();
        }
    }
    if is_quote_tick {
        out.push_str("            col_midpoint.push(t.midpoint);\n");
    }
    if is_contract {
        out.push_str("            col_expiration.push(t.expiration);\n");
        out.push_str("            col_strike.push(t.strike);\n");
        out.push_str(
            "            col_right.push(if t.is_call() { \"C\".to_string() } else if t.is_put() { \"P\".to_string() } else { String::new() });\n",
        );
    }
    out.push_str("        }\n");

    // Schema.
    out.push_str("        let schema = Arc::new(ArrowSchema::new(vec![\n");
    for column in &def.columns {
        let dt = if is_option_contract && column.field == "right" {
            "DataType::Utf8"
        } else {
            arrow_data_type_expr(column.r#type.as_str())
        };
        writeln!(
            out,
            "            Field::new(\"{name}\", {dt}, false),",
            name = column.name
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("            Field::new(\"midpoint\", DataType::Float64, false),\n");
    }
    if is_contract {
        out.push_str("            Field::new(\"expiration\", DataType::Int32, false),\n");
        out.push_str("            Field::new(\"strike\", DataType::Float64, false),\n");
        out.push_str("            Field::new(\"right\", DataType::Utf8, false),\n");
    }
    out.push_str("        ]));\n");

    // Columns.
    out.push_str("        let columns: Vec<ArrayRef> = vec![\n");
    for (field, column_type, _is_string) in &column_decls {
        let ctor = arrow_array_ctor(column_type);
        writeln!(
            out,
            "            Arc::new({ctor}::from(col_{field})) as ArrayRef,"
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("            Arc::new(Float64Array::from(col_midpoint)) as ArrayRef,\n");
    }
    if is_contract {
        out.push_str("            Arc::new(Int32Array::from(col_expiration)) as ArrayRef,\n");
        out.push_str("            Arc::new(Float64Array::from(col_strike)) as ArrayRef,\n");
        out.push_str("            Arc::new(StringArray::from(col_right)) as ArrayRef,\n");
    }
    out.push_str("        ];\n");
    out.push_str("        RecordBatch::try_new(schema, columns)\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ── Polars impl ─────────────────────────────────────────────────────────
//
// Polars `Series` has `NamedFrom<&str, [i32]>` / `[i64]` / `[f64]` /
// `[String]` impls which accept owned `Vec<T>` slices via `&[T]`. Build
// each series, then assemble the DataFrame. Column order / schema
// matches the Arrow path 1:1.

fn render_polars_impl(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let is_quote_tick = type_name == "QuoteTick";
    let is_contract = def.contract_id;
    let is_option_contract = type_name == "OptionContract";

    out.push_str("#[cfg(feature = \"polars\")]\n");
    out.push_str("#[cfg_attr(docsrs, doc(cfg(feature = \"polars\")))]\n");
    writeln!(
        out,
        "impl crate::frames::TicksPolarsExt for [tdbe::types::tick::{type_name}] {{"
    )
    .unwrap();
    out.push_str("    fn to_polars(&self) -> PolarsResult<DataFrame> {\n");
    out.push_str("        let n = self.len();\n");

    // Column buffers.
    let mut column_decls: Vec<(String, String, bool)> = Vec::new();
    for column in &def.columns {
        let (rust_ty, effective_type) = if is_option_contract && column.field == "right" {
            ("String", "String")
        } else {
            let ty = tick_struct_field_type(column.r#type.as_str());
            (ty, column.r#type.as_str())
        };
        writeln!(
            out,
            "        let mut col_{field}: Vec<{rust_ty}> = Vec::with_capacity(n);",
            field = column.field
        )
        .unwrap();
        column_decls.push((
            column.field.clone(),
            effective_type.to_string(),
            rust_ty == "String",
        ));
    }
    if is_quote_tick {
        out.push_str("        let mut col_midpoint: Vec<f64> = Vec::with_capacity(n);\n");
    }
    if is_contract {
        out.push_str("        let mut col_expiration: Vec<i32> = Vec::with_capacity(n);\n");
        out.push_str("        let mut col_strike: Vec<f64> = Vec::with_capacity(n);\n");
        out.push_str("        let mut col_right: Vec<String> = Vec::with_capacity(n);\n");
    }

    out.push_str("        for t in self {\n");
    for (field, _effective, is_string) in &column_decls {
        if is_option_contract && field == "right" {
            out.push_str(
                "            col_right.push(if t.is_call() { \"C\".to_string() } else if t.is_put() { \"P\".to_string() } else { String::new() });\n",
            );
            continue;
        }
        if *is_string {
            writeln!(out, "            col_{field}.push(t.{field}.clone());").unwrap();
        } else {
            writeln!(out, "            col_{field}.push(t.{field});").unwrap();
        }
    }
    if is_quote_tick {
        out.push_str("            col_midpoint.push(t.midpoint);\n");
    }
    if is_contract {
        out.push_str("            col_expiration.push(t.expiration);\n");
        out.push_str("            col_strike.push(t.strike);\n");
        out.push_str(
            "            col_right.push(if t.is_call() { \"C\".to_string() } else if t.is_put() { \"P\".to_string() } else { String::new() });\n",
        );
    }
    out.push_str("        }\n");

    // polars 0.46+ requires `Series::new(PlSmallStr, ...)` and
    // `DataFrame::new(Vec<Column>)`; call `.into()` on each `Series` to
    // coerce it into a `Column` before handing the vector to `DataFrame::new`.
    out.push_str("        DataFrame::new(vec![\n");
    for column in &def.columns {
        writeln!(
            out,
            "            Series::new(PlSmallStr::from_static(\"{name}\"), col_{field}).into(),",
            name = column.name,
            field = column.field
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str(
            "            Series::new(PlSmallStr::from_static(\"midpoint\"), col_midpoint).into(),\n",
        );
    }
    if is_contract {
        out.push_str("            Series::new(PlSmallStr::from_static(\"expiration\"), col_expiration).into(),\n");
        out.push_str(
            "            Series::new(PlSmallStr::from_static(\"strike\"), col_strike).into(),\n",
        );
        out.push_str(
            "            Series::new(PlSmallStr::from_static(\"right\"), col_right).into(),\n",
        );
    }
    out.push_str("        ])\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ── Type-mapping helpers (mirror of python_arrow.rs) ────────────────────

fn tick_struct_field_type(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" | "eod_num64" => "i64",
        "f64" | "price" | "eod_price" => "f64",
        "String" => "String",
        other => panic!("unsupported tick-struct field type '{other}'"),
    }
}

fn arrow_data_type_expr(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "DataType::Int32",
        "i64" | "eod_num64" => "DataType::Int64",
        "f64" | "price" | "eod_price" => "DataType::Float64",
        "String" => "DataType::Utf8",
        other => panic!("unsupported Arrow data type for column type '{other}'"),
    }
}

fn arrow_array_ctor(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "Int32Array",
        "i64" | "eod_num64" => "Int64Array",
        "f64" | "price" | "eod_price" => "Float64Array",
        "String" => "StringArray",
        other => panic!("unsupported Arrow array ctor for column type '{other}'"),
    }
}
