#!/usr/bin/env python3
"""Bump every user-visible version pin in lockstep.

Usage:
    scripts/release/bump_version.py 9.9.9

Reads the canonical version from ``thetadatadx-rs/Cargo.toml`` (only
to print "from -> to" for context), then walks every file that pins a
version of the published artifact and rewrites it. Every npm
``package.json`` file (the TypeScript SDK launcher + its three platform
packages, and the MCP server launcher + its five platform packages), the
six member Cargo.toml files (thetadatadx-rs + ffi + tools/mcp + tools/server
+ thetadatadx-py + thetadatadx-ts), and the ``optionalDependencies`` pins
inside both ``package.json`` launchers. Cargo.lock files are refreshed via
``cargo update --workspace`` against every manifest that carries its own
lockfile.

After the bump, ``scripts/ci/check_version_sync.py`` runs to verify nothing
got missed. Exits non-zero if anything is out of sync.

This is the only supported way to bump the SDK version. Doing it by
hand reliably misses ``thetadatadx-ts/`` files (lesson from npm being
stuck at v9.9.6 across v9.9.7 / v9.9.8 / v9.9.9 releases).
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

WORKSPACE_CARGOS = [
    ROOT / "thetadatadx-rs" / "Cargo.toml",
    ROOT / "thetadatadx-ffi" / "Cargo.toml",
    ROOT / "tools" / "mcp" / "Cargo.toml",
    ROOT / "tools" / "server" / "Cargo.toml",
    ROOT / "thetadatadx-py" / "Cargo.toml",
    ROOT / "thetadatadx-ts" / "Cargo.toml",
]

SUB_LOCK_MANIFESTS = [
    ROOT / "tools" / "mcp" / "Cargo.toml",
    ROOT / "tools" / "server" / "Cargo.toml",
    ROOT / "thetadatadx-py" / "Cargo.toml",
    ROOT / "thetadatadx-ts" / "Cargo.toml",
]


def parse_semver(value: str) -> tuple[int, int, int]:
    # Accept an optional SemVer pre-release / build suffix (e.g.
    # `9.9.9-rc.1`) so a release candidate can be bumped with the same
    # tool. The numeric core is returned; the suffix rides through on the
    # version strings the bump writes. Cargo and npm take `-rc.1` as-is;
    # maturin normalises it to the PEP 440 form, and CMake (operator-set)
    # carries the numeric core.
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)(?:[-+][0-9A-Za-z.\-]+)?", value)
    if not match:
        sys.exit(f"not a semver MAJOR.MINOR.PATCH[-prerelease]: '{value}'")
    return int(match.group(1)), int(match.group(2)), int(match.group(3))


def current_canonical() -> str:
    text = (ROOT / "thetadatadx-rs" / "Cargo.toml").read_text()
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not match:
        sys.exit("could not parse current version from thetadatadx-rs/Cargo.toml")
    return match.group(1)


def bump_cargo(path: Path, current: str, target: str) -> None:
    text = path.read_text()
    pattern = re.compile(rf'^version\s*=\s*"{re.escape(current)}"', re.MULTILINE)
    new_text, count = pattern.subn(f'version = "{target}"', text, count=1)
    if count != 1:
        sys.exit(
            f"{path.relative_to(ROOT)}: expected one `version = \"{current}\"` line, "
            f"found {count}"
        )
    path.write_text(new_text)


def bump_root_package_json(path: Path, current: str, target: str) -> None:
    data = json.loads(path.read_text())
    if data.get("version") != current:
        sys.exit(
            f"{path.relative_to(ROOT)}: version is {data.get('version')!r}, "
            f"expected {current!r}"
        )
    data["version"] = target
    deps = data.get("optionalDependencies", {})
    for name, pinned in list(deps.items()):
        if pinned == current:
            deps[name] = target
        else:
            sys.exit(
                f"{path.relative_to(ROOT)} optionalDependencies['{name}'] is "
                f"{pinned!r}, expected {current!r}"
            )
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def bump_platform_package_json(path: Path, current: str, target: str) -> None:
    data = json.loads(path.read_text())
    if data.get("version") != current:
        sys.exit(
            f"{path.relative_to(ROOT)}: version is {data.get('version')!r}, "
            f"expected {current!r}"
        )
    data["version"] = target
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def bump_napi_index_js(path: Path, current: str, target: str) -> None:
    """Rewrite the version napi baked into `thetadatadx-ts/index.js`.

    The file is generated by the napi build from package.json and committed,
    and it ships to npm inside package.json's `files`. It pins the version at
    every native-binding load path, so a bump that leaves it behind publishes a
    package whose own loader rejects its own binary once
    NAPI_RS_ENFORCE_VERSION_CHECK is set. Every semantic version in the file is
    that one pin, which is why a textual replace produces exactly what
    regenerating would; `check_version_sync.py` verifies the result either way.
    """
    text = path.read_text()
    found = set(re.findall(r"\b\d+\.\d+\.\d+\b", text))
    if found != {current}:
        sys.exit(
            f"{path.relative_to(ROOT)}: pins {sorted(found)}, expected only "
            f"{current!r}; regenerate it with `npm run build` in thetadatadx-ts "
            "and bump again"
        )
    path.write_text(text.replace(current, target))


def bump_package_lock(path: Path, current: str, target: str, first_party_prefix: str) -> None:
    """Move this package's version, and its own platform packages, in a lockfile.

    Three kinds of entry carry it: the top-level `version`, `packages[""]`, and
    the `node_modules/<first-party>` entries for the per-platform binary
    packages this project publishes alongside the launcher. Third-party
    dependencies that happen to sit at the same version are left alone.

    The platform entries matter as much as the self-version: the launcher pins
    them through `optionalDependencies`, so a lockfile left behind makes
    `npm ci` install the previous release's binaries under the new launcher,
    which is the exact mismatch `index.js` throws on.
    """
    data = json.loads(path.read_text())
    root_pkg = data.get("packages", {}).get("", {})
    for where, holder in (("version", data), ('packages[""].version', root_pkg)):
        if holder.get("version") != current:
            sys.exit(
                f"{path.relative_to(ROOT)} {where} is {holder.get('version')!r}, "
                f"expected {current!r}"
            )
        holder["version"] = target

    moved = 0
    for name, entry in data.get("packages", {}).items():
        if not name.startswith("node_modules/"):
            continue
        if not name.rsplit("/", 1)[-1].startswith(first_party_prefix):
            continue
        if isinstance(entry, dict) and entry.get("version") == current:
            entry["version"] = target
            moved += 1
    if moved == 0:
        sys.exit(
            f"{path.relative_to(ROOT)}: found no `node_modules/{first_party_prefix}*` "
            f"entry at {current!r}; the platform packages are pinned through "
            "optionalDependencies and must move with the launcher"
        )

    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def bump_cmake(path: Path, current: str, target: str) -> None:
    """Move the `project(... VERSION x.y.z ...)` pin in the C++ CMakeLists."""
    text = path.read_text()
    needle = f"VERSION {current}"
    if text.count(needle) != 1:
        sys.exit(
            f"{path.relative_to(ROOT)}: expected exactly one {needle!r}, "
            f"found {text.count(needle)}"
        )
    path.write_text(text.replace(needle, f"VERSION {target}"))


def bump_openapi_yaml(path: Path, current: str, target: str) -> None:
    """Move `info.version` in the published OpenAPI document."""
    text = path.read_text()
    needle = f"version: {current}"
    if text.count(needle) != 1:
        sys.exit(
            f"{path.relative_to(ROOT)}: expected exactly one {needle!r}, "
            f"found {text.count(needle)}"
        )
    path.write_text(text.replace(needle, f"version: {target}"))


def bump_doc_pins(current: str, target: str) -> list[Path]:
    """Move every `thetadatadx-rs = "<version>"` pin in the docs.

    The file set and the pin pattern come from `check_version_sync.py` rather
    than being restated here, so the files the bump writes are exactly the
    files the gate reads. Restating them is how `index.js` and
    `package-lock.json` came to be written by one and checked by neither.
    """
    sys.path.insert(0, str(ROOT / "scripts" / "ci"))
    import check_version_sync as sync

    touched: list[Path] = []
    for doc in sync._discover_doc_pin_files():
        text = doc.read_text()
        replaced = sync.DOC_PIN_RE.sub(
            lambda m: m.group(0).replace(f'"{current}"', f'"{target}"'), text
        )
        if replaced != text:
            doc.write_text(replaced)
            touched.append(doc)
    return touched


def cargo_update(manifest: Path) -> None:
    subprocess.run(
        ["cargo", "update", "--manifest-path", str(manifest), "--workspace"],
        cwd=ROOT,
        check=True,
    )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        sys.exit("usage: scripts/release/bump_version.py <new-version>")
    target = argv[1]
    parse_semver(target)
    current = current_canonical()
    if current == target:
        sys.exit(f"current version is already {current}; nothing to bump")
    print(f"bumping {current} -> {target}")

    for cargo in WORKSPACE_CARGOS:
        bump_cargo(cargo, current, target)
        print(f"  bumped {cargo.relative_to(ROOT)}")

    bump_root_package_json(
        ROOT / "thetadatadx-ts" / "package.json", current, target
    )
    print("  bumped thetadatadx-ts/package.json (+ optionalDependencies)")

    for platform_pkg in (ROOT / "thetadatadx-ts" / "npm").glob("*/package.json"):
        bump_platform_package_json(platform_pkg, current, target)
        print(f"  bumped {platform_pkg.relative_to(ROOT)}")

    bump_napi_index_js(ROOT / "thetadatadx-ts" / "index.js", current, target)
    print("  bumped thetadatadx-ts/index.js (napi binding-version pins)")

    bump_package_lock(
        ROOT / "thetadatadx-ts" / "package-lock.json", current, target, "thetadatadx-ts"
    )
    print("  bumped thetadatadx-ts/package-lock.json")

    # The MCP server ships to npm too (`npx -y thetadatadx-mcp-server`): a launcher
    # package with per-platform binary packages as optionalDependencies,
    # mirroring the TypeScript SDK layout under `tools/mcp/npm/`.
    bump_root_package_json(
        ROOT / "tools" / "mcp" / "npm" / "thetadatadx-mcp-server" / "package.json",
        current,
        target,
    )
    print("  bumped tools/mcp/npm/thetadatadx-mcp-server/package.json (+ optionalDependencies)")

    for platform_pkg in (ROOT / "tools" / "mcp" / "npm").glob("*/package.json"):
        if platform_pkg.parent.name == "thetadatadx-mcp-server":
            continue  # the launcher package, bumped above
        bump_platform_package_json(platform_pkg, current, target)
        print(f"  bumped {platform_pkg.relative_to(ROOT)}")

    bump_cmake(ROOT / "thetadatadx-cpp" / "CMakeLists.txt", current, target)
    print("  bumped thetadatadx-cpp/CMakeLists.txt")

    bump_openapi_yaml(
        ROOT / "docs-site" / "docs" / "public" / "thetadatadx.yaml", current, target
    )
    print("  bumped docs-site/docs/public/thetadatadx.yaml")

    for doc in bump_doc_pins(current, target):
        print(f"  bumped {doc.relative_to(ROOT)} (doc pin)")

    print("refreshing Cargo.lock files ...")
    cargo_update(WORKSPACE_CARGOS[0])
    for manifest in SUB_LOCK_MANIFESTS:
        cargo_update(manifest)

    print("verifying with scripts/ci/check_version_sync.py ...")
    subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "ci" / "check_version_sync.py")],
        cwd=ROOT,
        check=True,
    )
    print(f"version bump to {target} complete; review `git diff` before committing")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
