// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml

#[pymethods]
impl ThetaDataDx {
    /// List all available stock ticker symbols.
    fn stock_list_symbols(
        &self,
        py: Python<'_>,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.stock_list_symbols().await
                })
                .map_err(to_py_err)
        })
    }

    /// List available dates for a stock by request type (EOD, TRADE, QUOTE, etc.).
    fn stock_list_dates(
        &self,
        py: Python<'_>,
        request_type: &str,
        symbol: &str,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.stock_list_dates(request_type, symbol).await
                })
                .map_err(to_py_err)
        })
    }

    /// Get the latest OHLC snapshot for one or more stocks.
    #[pyo3(signature = (symbols, *, venue=None, min_time=None))]
    fn stock_snapshot_ohlc(
        &self,
        py: Python<'_>,
        symbols: Vec<String>,
        venue: Option<&str>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_snapshot_ohlc(&refs);
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| ohlc_tick_to_dict(py, t)).collect())
    }

    /// Get the latest trade snapshot for one or more stocks.
    #[pyo3(signature = (symbols, *, venue=None, min_time=None))]
    fn stock_snapshot_trade(
        &self,
        py: Python<'_>,
        symbols: Vec<String>,
        venue: Option<&str>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_snapshot_trade(&refs);
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_tick_to_dict(py, t)).collect())
    }

    /// Get the latest NBBO quote snapshot for one or more stocks.
    #[pyo3(signature = (symbols, *, venue=None, min_time=None))]
    fn stock_snapshot_quote(
        &self,
        py: Python<'_>,
        symbols: Vec<String>,
        venue: Option<&str>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_snapshot_quote(&refs);
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| quote_tick_to_dict(py, t)).collect())
    }

    /// Get the latest market value snapshot for one or more stocks.
    #[pyo3(signature = (symbols, *, venue=None, min_time=None))]
    fn stock_snapshot_market_value(
        &self,
        py: Python<'_>,
        symbols: Vec<String>,
        venue: Option<&str>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_snapshot_market_value(&refs);
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| market_value_tick_to_dict(py, t)).collect())
    }

    /// Fetch end-of-day stock data for a date range. Returns OHLCV + bid/ask per trading day.
    fn stock_history_eod(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.stock_history_eod(symbol, start_date, end_date).await
                })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| eod_tick_to_dict(py, t)).collect())
    }

    /// Fetch intraday OHLC bars for a stock on a single date.
    #[pyo3(signature = (symbol, date, interval, *, start_time=None, end_time=None, venue=None, start_date=None, end_date=None))]
    fn stock_history_ohlc(
        &self,
        py: Python<'_>,
        symbol: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        venue: Option<&str>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_history_ohlc(symbol, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| ohlc_tick_to_dict(py, t)).collect())
    }

    /// Fetch all trades for a stock on a given date.
    #[pyo3(signature = (symbol, date, *, start_time=None, end_time=None, venue=None, start_date=None, end_date=None))]
    fn stock_history_trade(
        &self,
        py: Python<'_>,
        symbol: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        venue: Option<&str>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_history_trade(symbol, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_tick_to_dict(py, t)).collect())
    }

    /// Fetch NBBO quotes for a stock on a given date at a given interval.
    #[pyo3(signature = (symbol, date, interval, *, start_time=None, end_time=None, venue=None, start_date=None, end_date=None))]
    fn stock_history_quote(
        &self,
        py: Python<'_>,
        symbol: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        venue: Option<&str>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_history_quote(symbol, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| quote_tick_to_dict(py, t)).collect())
    }

    /// Fetch combined trade + quote ticks for a stock on a given date. Returns raw DataTable.
    #[pyo3(signature = (symbol, date, *, start_time=None, end_time=None, exclusive=None, venue=None, start_date=None, end_date=None))]
    fn stock_history_trade_quote(
        &self,
        py: Python<'_>,
        symbol: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        exclusive: Option<bool>,
        venue: Option<&str>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_history_trade_quote(symbol, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = exclusive {
                request = request.exclusive(value);
            }
            if let Some(value) = venue {
                request = request.venue(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_quote_tick_to_dict(py, t)).collect())
    }

    /// Fetch the trade at a specific time of day across a date range.
    #[pyo3(signature = (symbol, start_date, end_date, time_of_day, *, venue=None))]
    fn stock_at_time_trade(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
        time_of_day: &str,
        venue: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_at_time_trade(symbol, start_date, end_date, time_of_day);
            if let Some(value) = venue {
                request = request.venue(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_tick_to_dict(py, t)).collect())
    }

    /// Fetch the quote at a specific time of day across a date range.
    #[pyo3(signature = (symbol, start_date, end_date, time_of_day, *, venue=None))]
    fn stock_at_time_quote(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
        time_of_day: &str,
        venue: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_at_time_quote(symbol, start_date, end_date, time_of_day);
            if let Some(value) = venue {
                request = request.venue(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| quote_tick_to_dict(py, t)).collect())
    }

    /// List all available option underlying symbols.
    fn option_list_symbols(
        &self,
        py: Python<'_>,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.option_list_symbols().await
                })
                .map_err(to_py_err)
        })
    }

    /// List available dates for an option contract by request type.
    fn option_list_dates(
        &self,
        py: Python<'_>,
        request_type: &str,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.option_list_dates(request_type, symbol, expiration, strike, right).await
                })
                .map_err(to_py_err)
        })
    }

    /// List available expiration dates for an option underlying.
    fn option_list_expirations(
        &self,
        py: Python<'_>,
        symbol: &str,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.option_list_expirations(symbol).await
                })
                .map_err(to_py_err)
        })
    }

    /// List available strike prices for an option at a given expiration.
    fn option_list_strikes(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.option_list_strikes(symbol, expiration).await
                })
                .map_err(to_py_err)
        })
    }

    /// List all option contracts for a symbol on a given date.
    #[pyo3(signature = (request_type, symbol, date, *, max_dte=None))]
    fn option_list_contracts(
        &self,
        py: Python<'_>,
        request_type: &str,
        symbol: &str,
        date: &str,
        max_dte: Option<i32>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_list_contracts(request_type, symbol, date);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| option_contract_to_dict(py, t)).collect())
    }

    /// Get the latest OHLC snapshot for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, max_dte=None, strike_range=None, min_time=None))]
    fn option_snapshot_ohlc(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_ohlc(symbol, expiration, strike, right);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| ohlc_tick_to_dict(py, t)).collect())
    }

    /// Get the latest trade snapshot for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, strike_range=None, min_time=None))]
    fn option_snapshot_trade(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        strike_range: Option<i32>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_trade(symbol, expiration, strike, right);
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_tick_to_dict(py, t)).collect())
    }

    /// Get the latest NBBO quote snapshot for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, max_dte=None, strike_range=None, min_time=None))]
    fn option_snapshot_quote(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_quote(symbol, expiration, strike, right);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| quote_tick_to_dict(py, t)).collect())
    }

    /// Get the latest open interest snapshot for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, max_dte=None, strike_range=None, min_time=None))]
    fn option_snapshot_open_interest(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_open_interest(symbol, expiration, strike, right);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| open_interest_tick_to_dict(py, t)).collect())
    }

    /// Get the latest market value snapshot for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, max_dte=None, strike_range=None, min_time=None))]
    fn option_snapshot_market_value(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_market_value(symbol, expiration, strike, right);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| market_value_tick_to_dict(py, t)).collect())
    }

    /// Get implied volatility snapshot for an option contract (from ThetaData server).
    #[pyo3(signature = (symbol, expiration, strike, right, *, annual_dividend=None, rate_type=None, rate_value=None, stock_price=None, version=None, max_dte=None, strike_range=None, min_time=None, use_market_value=None))]
    fn option_snapshot_greeks_implied_volatility(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        stock_price: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
        use_market_value: Option<bool>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_greeks_implied_volatility(symbol, expiration, strike, right);
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = stock_price {
                request = request.stock_price(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            if let Some(value) = use_market_value {
                request = request.use_market_value(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| iv_tick_to_dict(py, t)).collect())
    }

    /// Get all Greeks snapshot for an option contract (from ThetaData server).
    #[pyo3(signature = (symbol, expiration, strike, right, *, annual_dividend=None, rate_type=None, rate_value=None, stock_price=None, version=None, max_dte=None, strike_range=None, min_time=None, use_market_value=None))]
    fn option_snapshot_greeks_all(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        stock_price: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
        use_market_value: Option<bool>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_greeks_all(symbol, expiration, strike, right);
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = stock_price {
                request = request.stock_price(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            if let Some(value) = use_market_value {
                request = request.use_market_value(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Get first-order Greeks snapshot (delta, theta, rho) for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, annual_dividend=None, rate_type=None, rate_value=None, stock_price=None, version=None, max_dte=None, strike_range=None, min_time=None, use_market_value=None))]
    fn option_snapshot_greeks_first_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        stock_price: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
        use_market_value: Option<bool>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_greeks_first_order(symbol, expiration, strike, right);
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = stock_price {
                request = request.stock_price(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            if let Some(value) = use_market_value {
                request = request.use_market_value(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Get second-order Greeks snapshot (gamma, vanna, charm) for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, annual_dividend=None, rate_type=None, rate_value=None, stock_price=None, version=None, max_dte=None, strike_range=None, min_time=None, use_market_value=None))]
    fn option_snapshot_greeks_second_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        stock_price: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
        use_market_value: Option<bool>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_greeks_second_order(symbol, expiration, strike, right);
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = stock_price {
                request = request.stock_price(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            if let Some(value) = use_market_value {
                request = request.use_market_value(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Get third-order Greeks snapshot (speed, color, ultima) for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, *, annual_dividend=None, rate_type=None, rate_value=None, stock_price=None, version=None, max_dte=None, strike_range=None, min_time=None, use_market_value=None))]
    fn option_snapshot_greeks_third_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        stock_price: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        min_time: Option<&str>,
        use_market_value: Option<bool>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_snapshot_greeks_third_order(symbol, expiration, strike, right);
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = stock_price {
                request = request.stock_price(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            if let Some(value) = use_market_value {
                request = request.use_market_value(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch end-of-day option data for a contract over a date range.
    #[pyo3(signature = (symbol, expiration, strike, right, start_date, end_date, *, max_dte=None, strike_range=None))]
    fn option_history_eod(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        start_date: &str,
        end_date: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_eod(symbol, expiration, strike, right, start_date, end_date);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| eod_tick_to_dict(py, t)).collect())
    }

    /// Fetch intraday OHLC bars for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, interval, *, start_time=None, end_time=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_ohlc(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_ohlc(symbol, expiration, strike, right, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| ohlc_tick_to_dict(py, t)).collect())
    }

    /// Fetch all trades for an option contract on a given date.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, start_time=None, end_time=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_trade(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_trade(symbol, expiration, strike, right, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_tick_to_dict(py, t)).collect())
    }

    /// Fetch NBBO quotes for an option contract on a given date.
    #[pyo3(signature = (symbol, expiration, strike, right, date, interval, *, start_time=None, end_time=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_quote(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_quote(symbol, expiration, strike, right, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| quote_tick_to_dict(py, t)).collect())
    }

    /// Fetch combined trade + quote ticks for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, start_time=None, end_time=None, exclusive=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_trade_quote(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        exclusive: Option<bool>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_trade_quote(symbol, expiration, strike, right, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = exclusive {
                request = request.exclusive(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_quote_tick_to_dict(py, t)).collect())
    }

    /// Fetch open interest history for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_open_interest(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_open_interest(symbol, expiration, strike, right, date);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| open_interest_tick_to_dict(py, t)).collect())
    }

    /// Fetch end-of-day Greeks history for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, start_date, end_date, *, annual_dividend=None, rate_type=None, rate_value=None, version=None, underlyer_use_nbbo=None, max_dte=None, strike_range=None))]
    fn option_history_greeks_eod(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        start_date: &str,
        end_date: &str,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        underlyer_use_nbbo: Option<bool>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_greeks_eod(symbol, expiration, strike, right, start_date, end_date);
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = underlyer_use_nbbo {
                request = request.underlyer_use_nbbo(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch all Greeks history for an option contract (intraday, sampled by interval).
    #[pyo3(signature = (symbol, expiration, strike, right, date, interval, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_greeks_all(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_greeks_all(symbol, expiration, strike, right, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch all Greeks on each trade for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_trade_greeks_all(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_trade_greeks_all(symbol, expiration, strike, right, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch first-order Greeks history (intraday, sampled by interval).
    #[pyo3(signature = (symbol, expiration, strike, right, date, interval, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_greeks_first_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_greeks_first_order(symbol, expiration, strike, right, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch first-order Greeks on each trade for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_trade_greeks_first_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_trade_greeks_first_order(symbol, expiration, strike, right, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch second-order Greeks history (intraday, sampled by interval).
    #[pyo3(signature = (symbol, expiration, strike, right, date, interval, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_greeks_second_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_greeks_second_order(symbol, expiration, strike, right, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch second-order Greeks on each trade for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_trade_greeks_second_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_trade_greeks_second_order(symbol, expiration, strike, right, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch third-order Greeks history (intraday, sampled by interval).
    #[pyo3(signature = (symbol, expiration, strike, right, date, interval, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_greeks_third_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_greeks_third_order(symbol, expiration, strike, right, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch third-order Greeks on each trade for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_trade_greeks_third_order(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_trade_greeks_third_order(symbol, expiration, strike, right, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| greeks_tick_to_dict(py, t)).collect())
    }

    /// Fetch implied volatility history (intraday, sampled by interval).
    #[pyo3(signature = (symbol, expiration, strike, right, date, interval, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_greeks_implied_volatility(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_greeks_implied_volatility(symbol, expiration, strike, right, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| iv_tick_to_dict(py, t)).collect())
    }

    /// Fetch implied volatility on each trade for an option contract.
    #[pyo3(signature = (symbol, expiration, strike, right, date, *, start_time=None, end_time=None, annual_dividend=None, rate_type=None, rate_value=None, version=None, max_dte=None, strike_range=None, start_date=None, end_date=None))]
    fn option_history_trade_greeks_implied_volatility(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        date: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        annual_dividend: Option<f64>,
        rate_type: Option<&str>,
        rate_value: Option<f64>,
        version: Option<&str>,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_history_trade_greeks_implied_volatility(symbol, expiration, strike, right, date);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = annual_dividend {
                request = request.annual_dividend(value);
            }
            if let Some(value) = rate_type {
                request = request.rate_type(value);
            }
            if let Some(value) = rate_value {
                request = request.rate_value(value);
            }
            if let Some(value) = version {
                request = request.version(value);
            }
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| iv_tick_to_dict(py, t)).collect())
    }

    /// Fetch the trade at a specific time of day across a date range for an option.
    #[pyo3(signature = (symbol, expiration, strike, right, start_date, end_date, time_of_day, *, max_dte=None, strike_range=None))]
    fn option_at_time_trade(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        start_date: &str,
        end_date: &str,
        time_of_day: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_at_time_trade(symbol, expiration, strike, right, start_date, end_date, time_of_day);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| trade_tick_to_dict(py, t)).collect())
    }

    /// Fetch the quote at a specific time of day across a date range for an option.
    #[pyo3(signature = (symbol, expiration, strike, right, start_date, end_date, time_of_day, *, max_dte=None, strike_range=None))]
    fn option_at_time_quote(
        &self,
        py: Python<'_>,
        symbol: &str,
        expiration: &str,
        strike: &str,
        right: &str,
        start_date: &str,
        end_date: &str,
        time_of_day: &str,
        max_dte: Option<i32>,
        strike_range: Option<i32>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.option_at_time_quote(symbol, expiration, strike, right, start_date, end_date, time_of_day);
            if let Some(value) = max_dte {
                request = request.max_dte(value);
            }
            if let Some(value) = strike_range {
                request = request.strike_range(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| quote_tick_to_dict(py, t)).collect())
    }

    /// List all available index symbols.
    fn index_list_symbols(
        &self,
        py: Python<'_>,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.index_list_symbols().await
                })
                .map_err(to_py_err)
        })
    }

    /// List available dates for an index symbol.
    fn index_list_dates(
        &self,
        py: Python<'_>,
        symbol: &str,
    ) -> PyResult<Vec<String>> {
        py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.index_list_dates(symbol).await
                })
                .map_err(to_py_err)
        })
    }

    /// Get the latest OHLC snapshot for one or more indices.
    #[pyo3(signature = (symbols, *, min_time=None))]
    fn index_snapshot_ohlc(
        &self,
        py: Python<'_>,
        symbols: Vec<String>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();
        let ticks = py.detach(|| {
            let mut request = self.tdx.index_snapshot_ohlc(&refs);
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| ohlc_tick_to_dict(py, t)).collect())
    }

    /// Get the latest price snapshot for one or more indices.
    #[pyo3(signature = (symbols, *, min_time=None))]
    fn index_snapshot_price(
        &self,
        py: Python<'_>,
        symbols: Vec<String>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();
        let ticks = py.detach(|| {
            let mut request = self.tdx.index_snapshot_price(&refs);
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| price_tick_to_dict(py, t)).collect())
    }

    /// Get the latest market value snapshot for one or more indices.
    #[pyo3(signature = (symbols, *, min_time=None))]
    fn index_snapshot_market_value(
        &self,
        py: Python<'_>,
        symbols: Vec<String>,
        min_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();
        let ticks = py.detach(|| {
            let mut request = self.tdx.index_snapshot_market_value(&refs);
            if let Some(value) = min_time {
                request = request.min_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| market_value_tick_to_dict(py, t)).collect())
    }

    /// Fetch end-of-day index data for a date range.
    fn index_history_eod(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.index_history_eod(symbol, start_date, end_date).await
                })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| eod_tick_to_dict(py, t)).collect())
    }

    /// Fetch intraday OHLC bars for an index.
    #[pyo3(signature = (symbol, start_date, end_date, interval, *, start_time=None, end_time=None))]
    fn index_history_ohlc(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.index_history_ohlc(symbol, start_date, end_date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| ohlc_tick_to_dict(py, t)).collect())
    }

    /// Fetch intraday price history for an index.
    #[pyo3(signature = (symbol, date, interval, *, start_time=None, end_time=None, start_date=None, end_date=None))]
    fn index_history_price(
        &self,
        py: Python<'_>,
        symbol: &str,
        date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        start_date: Option<&str>,
        end_date: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.index_history_price(symbol, date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = start_date {
                request = request.start_date(value);
            }
            if let Some(value) = end_date {
                request = request.end_date(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| price_tick_to_dict(py, t)).collect())
    }

    /// Fetch the index price at a specific time of day across a date range.
    fn index_at_time_price(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
        time_of_day: &str,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.index_at_time_price(symbol, start_date, end_date, time_of_day).await
                })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| price_tick_to_dict(py, t)).collect())
    }

    /// Check whether the market is open today.
    fn calendar_open_today(
        &self,
        py: Python<'_>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.calendar_open_today().await
                })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| calendar_day_to_dict(py, t)).collect())
    }

    /// Get calendar information for a specific date.
    fn calendar_on_date(
        &self,
        py: Python<'_>,
        date: &str,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.calendar_on_date(date).await
                })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| calendar_day_to_dict(py, t)).collect())
    }

    /// Get calendar information for an entire year.
    fn calendar_year(
        &self,
        py: Python<'_>,
        year: &str,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.calendar_year(year).await
                })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| calendar_day_to_dict(py, t)).collect())
    }

    /// Fetch end-of-day interest rate history.
    fn interest_rate_history_eod(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            runtime()
                .block_on(async {
                    self.tdx.interest_rate_history_eod(symbol, start_date, end_date).await
                })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| interest_rate_tick_to_dict(py, t)).collect())
    }

    /// Fetch intraday OHLC bars across a date range.
    #[pyo3(signature = (symbol, start_date, end_date, interval, *, start_time=None, end_time=None, venue=None))]
    fn stock_history_ohlc_range(
        &self,
        py: Python<'_>,
        symbol: &str,
        start_date: &str,
        end_date: &str,
        interval: &str,
        start_time: Option<&str>,
        end_time: Option<&str>,
        venue: Option<&str>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let ticks = py.detach(|| {
            let mut request = self.tdx.stock_history_ohlc_range(symbol, start_date, end_date, interval);
            if let Some(value) = start_time {
                request = request.start_time(value);
            }
            if let Some(value) = end_time {
                request = request.end_time(value);
            }
            if let Some(value) = venue {
                request = request.venue(value);
            }
            runtime()
                .block_on(async { request.await })
                .map_err(to_py_err)
        })?;
        Ok(ticks.iter().map(|t| ohlc_tick_to_dict(py, t)).collect())
    }

}
