// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml
// Columnar converters: dict-of-lists instead of list-of-dicts.
// Each function returns a single Python dict where each key maps to a list of values.
// This is the fastest input format for pd.DataFrame().
// Emitted only for the tick types called by the hand-written `*_df`
// wrappers in `lib.rs`; the generic `pyclass_list_to_columnar` covers
// the rest so we do not ship dead code.

fn eod_ticks_to_columnar(py: Python<'_>, ticks: &[tick::EodTick]) -> Py<PyAny> {
    let col_ms_of_day: Vec<i32> = ticks.iter().map(|t| t.ms_of_day).collect();
    let col_ms_of_day2: Vec<i32> = ticks.iter().map(|t| t.ms_of_day2).collect();
    let col_open: Vec<f64> = ticks.iter().map(|t| t.open).collect();
    let col_high: Vec<f64> = ticks.iter().map(|t| t.high).collect();
    let col_low: Vec<f64> = ticks.iter().map(|t| t.low).collect();
    let col_close: Vec<f64> = ticks.iter().map(|t| t.close).collect();
    let col_volume: Vec<i64> = ticks.iter().map(|t| t.volume).collect();
    let col_count: Vec<i64> = ticks.iter().map(|t| t.count).collect();
    let col_bid_size: Vec<i32> = ticks.iter().map(|t| t.bid_size).collect();
    let col_bid_exchange: Vec<i32> = ticks.iter().map(|t| t.bid_exchange).collect();
    let col_bid: Vec<f64> = ticks.iter().map(|t| t.bid).collect();
    let col_bid_condition: Vec<i32> = ticks.iter().map(|t| t.bid_condition).collect();
    let col_ask_size: Vec<i32> = ticks.iter().map(|t| t.ask_size).collect();
    let col_ask_exchange: Vec<i32> = ticks.iter().map(|t| t.ask_exchange).collect();
    let col_ask: Vec<f64> = ticks.iter().map(|t| t.ask).collect();
    let col_ask_condition: Vec<i32> = ticks.iter().map(|t| t.ask_condition).collect();
    let col_date: Vec<i32> = ticks.iter().map(|t| t.date).collect();
    let col_expiration: Vec<i32> = ticks.iter().map(|t| t.expiration).collect();
    let col_strike: Vec<f64> = ticks.iter().map(|t| t.strike).collect();
    let col_right: Vec<&str> = ticks.iter().map(|t| if t.is_call() { "C" } else if t.is_put() { "P" } else { "" }).collect();
    let dict = PyDict::new(py);
    dict.set_item("ms_of_day", col_ms_of_day).unwrap();
    dict.set_item("ms_of_day2", col_ms_of_day2).unwrap();
    dict.set_item("open", col_open).unwrap();
    dict.set_item("high", col_high).unwrap();
    dict.set_item("low", col_low).unwrap();
    dict.set_item("close", col_close).unwrap();
    dict.set_item("volume", col_volume).unwrap();
    dict.set_item("count", col_count).unwrap();
    dict.set_item("bid_size", col_bid_size).unwrap();
    dict.set_item("bid_exchange", col_bid_exchange).unwrap();
    dict.set_item("bid", col_bid).unwrap();
    dict.set_item("bid_condition", col_bid_condition).unwrap();
    dict.set_item("ask_size", col_ask_size).unwrap();
    dict.set_item("ask_exchange", col_ask_exchange).unwrap();
    dict.set_item("ask", col_ask).unwrap();
    dict.set_item("ask_condition", col_ask_condition).unwrap();
    dict.set_item("date", col_date).unwrap();
    dict.set_item("expiration", col_expiration).unwrap();
    dict.set_item("strike", col_strike).unwrap();
    dict.set_item("right", col_right).unwrap();
    dict.into_any().unbind()
}

fn ohlc_ticks_to_columnar(py: Python<'_>, ticks: &[tick::OhlcTick]) -> Py<PyAny> {
    let col_ms_of_day: Vec<i32> = ticks.iter().map(|t| t.ms_of_day).collect();
    let col_open: Vec<f64> = ticks.iter().map(|t| t.open).collect();
    let col_high: Vec<f64> = ticks.iter().map(|t| t.high).collect();
    let col_low: Vec<f64> = ticks.iter().map(|t| t.low).collect();
    let col_close: Vec<f64> = ticks.iter().map(|t| t.close).collect();
    let col_volume: Vec<i64> = ticks.iter().map(|t| t.volume).collect();
    let col_count: Vec<i64> = ticks.iter().map(|t| t.count).collect();
    let col_date: Vec<i32> = ticks.iter().map(|t| t.date).collect();
    let col_expiration: Vec<i32> = ticks.iter().map(|t| t.expiration).collect();
    let col_strike: Vec<f64> = ticks.iter().map(|t| t.strike).collect();
    let col_right: Vec<&str> = ticks.iter().map(|t| if t.is_call() { "C" } else if t.is_put() { "P" } else { "" }).collect();
    let dict = PyDict::new(py);
    dict.set_item("ms_of_day", col_ms_of_day).unwrap();
    dict.set_item("open", col_open).unwrap();
    dict.set_item("high", col_high).unwrap();
    dict.set_item("low", col_low).unwrap();
    dict.set_item("close", col_close).unwrap();
    dict.set_item("volume", col_volume).unwrap();
    dict.set_item("count", col_count).unwrap();
    dict.set_item("date", col_date).unwrap();
    dict.set_item("expiration", col_expiration).unwrap();
    dict.set_item("strike", col_strike).unwrap();
    dict.set_item("right", col_right).unwrap();
    dict.into_any().unbind()
}

fn quote_ticks_to_columnar(py: Python<'_>, ticks: &[tick::QuoteTick]) -> Py<PyAny> {
    let col_ms_of_day: Vec<i32> = ticks.iter().map(|t| t.ms_of_day).collect();
    let col_bid_size: Vec<i32> = ticks.iter().map(|t| t.bid_size).collect();
    let col_bid_exchange: Vec<i32> = ticks.iter().map(|t| t.bid_exchange).collect();
    let col_bid: Vec<f64> = ticks.iter().map(|t| t.bid).collect();
    let col_bid_condition: Vec<i32> = ticks.iter().map(|t| t.bid_condition).collect();
    let col_ask_size: Vec<i32> = ticks.iter().map(|t| t.ask_size).collect();
    let col_ask_exchange: Vec<i32> = ticks.iter().map(|t| t.ask_exchange).collect();
    let col_ask: Vec<f64> = ticks.iter().map(|t| t.ask).collect();
    let col_ask_condition: Vec<i32> = ticks.iter().map(|t| t.ask_condition).collect();
    let col_date: Vec<i32> = ticks.iter().map(|t| t.date).collect();
    let col_midpoint: Vec<f64> = ticks.iter().map(|t| t.midpoint).collect();
    let col_expiration: Vec<i32> = ticks.iter().map(|t| t.expiration).collect();
    let col_strike: Vec<f64> = ticks.iter().map(|t| t.strike).collect();
    let col_right: Vec<&str> = ticks.iter().map(|t| if t.is_call() { "C" } else if t.is_put() { "P" } else { "" }).collect();
    let dict = PyDict::new(py);
    dict.set_item("ms_of_day", col_ms_of_day).unwrap();
    dict.set_item("bid_size", col_bid_size).unwrap();
    dict.set_item("bid_exchange", col_bid_exchange).unwrap();
    dict.set_item("bid", col_bid).unwrap();
    dict.set_item("bid_condition", col_bid_condition).unwrap();
    dict.set_item("ask_size", col_ask_size).unwrap();
    dict.set_item("ask_exchange", col_ask_exchange).unwrap();
    dict.set_item("ask", col_ask).unwrap();
    dict.set_item("ask_condition", col_ask_condition).unwrap();
    dict.set_item("date", col_date).unwrap();
    dict.set_item("midpoint", col_midpoint).unwrap();
    dict.set_item("expiration", col_expiration).unwrap();
    dict.set_item("strike", col_strike).unwrap();
    dict.set_item("right", col_right).unwrap();
    dict.into_any().unbind()
}

fn trade_ticks_to_columnar(py: Python<'_>, ticks: &[tick::TradeTick]) -> Py<PyAny> {
    let col_ms_of_day: Vec<i32> = ticks.iter().map(|t| t.ms_of_day).collect();
    let col_sequence: Vec<i32> = ticks.iter().map(|t| t.sequence).collect();
    let col_ext_condition1: Vec<i32> = ticks.iter().map(|t| t.ext_condition1).collect();
    let col_ext_condition2: Vec<i32> = ticks.iter().map(|t| t.ext_condition2).collect();
    let col_ext_condition3: Vec<i32> = ticks.iter().map(|t| t.ext_condition3).collect();
    let col_ext_condition4: Vec<i32> = ticks.iter().map(|t| t.ext_condition4).collect();
    let col_condition: Vec<i32> = ticks.iter().map(|t| t.condition).collect();
    let col_size: Vec<i32> = ticks.iter().map(|t| t.size).collect();
    let col_exchange: Vec<i32> = ticks.iter().map(|t| t.exchange).collect();
    let col_price: Vec<f64> = ticks.iter().map(|t| t.price).collect();
    let col_condition_flags: Vec<i32> = ticks.iter().map(|t| t.condition_flags).collect();
    let col_price_flags: Vec<i32> = ticks.iter().map(|t| t.price_flags).collect();
    let col_volume_type: Vec<i32> = ticks.iter().map(|t| t.volume_type).collect();
    let col_records_back: Vec<i32> = ticks.iter().map(|t| t.records_back).collect();
    let col_date: Vec<i32> = ticks.iter().map(|t| t.date).collect();
    let col_expiration: Vec<i32> = ticks.iter().map(|t| t.expiration).collect();
    let col_strike: Vec<f64> = ticks.iter().map(|t| t.strike).collect();
    let col_right: Vec<&str> = ticks.iter().map(|t| if t.is_call() { "C" } else if t.is_put() { "P" } else { "" }).collect();
    let dict = PyDict::new(py);
    dict.set_item("ms_of_day", col_ms_of_day).unwrap();
    dict.set_item("sequence", col_sequence).unwrap();
    dict.set_item("ext_condition1", col_ext_condition1).unwrap();
    dict.set_item("ext_condition2", col_ext_condition2).unwrap();
    dict.set_item("ext_condition3", col_ext_condition3).unwrap();
    dict.set_item("ext_condition4", col_ext_condition4).unwrap();
    dict.set_item("condition", col_condition).unwrap();
    dict.set_item("size", col_size).unwrap();
    dict.set_item("exchange", col_exchange).unwrap();
    dict.set_item("price", col_price).unwrap();
    dict.set_item("condition_flags", col_condition_flags).unwrap();
    dict.set_item("price_flags", col_price_flags).unwrap();
    dict.set_item("volume_type", col_volume_type).unwrap();
    dict.set_item("records_back", col_records_back).unwrap();
    dict.set_item("date", col_date).unwrap();
    dict.set_item("expiration", col_expiration).unwrap();
    dict.set_item("strike", col_strike).unwrap();
    dict.set_item("right", col_right).unwrap();
    dict.into_any().unbind()
}

