//! Emit `thetadatadx-ts/src/_generated/tick_classes.rs` — typed `#[napi(object)]`
//! tick structs + `Vec` factories. Replaces the old `serde_json` columnar
//! returns with concrete TypeScript types in `index.d.ts`.
//!
//! Each tick type is emitted as a flat `#[napi(object)]` struct so napi-rs
//! generates a matching TypeScript interface in `index.d.ts`. `Vec<Tick>`
//! returns from endpoint methods become `Tick[]` in TS — every market-data
//! endpoint is fully typed, no `any`.
//!
//! A parallel `{snake_type}_to_class_vec(&[tick::Type]) -> Vec<Type>` helper
//! copies Rust tick structs (the `thetadatadx::*` tick types) into the `#[napi]`
//! types. The helpers are drop-in substitutes for the `..._to_columnar`
//! converters used previously.

use std::fmt::Write as _;

use heck::{ToLowerCamelCase, ToSnakeCase};

use super::idents::rust_field_ident;
use super::python_classes::strip_field_count_from_doc;
use super::schema::{render_for_type, Schema, TickTypeDef};
use super::sorted_type_names;
use super::tdbe_structs::timestamp_accessor_fields;

/// Emitted `BigInt -> i64` decoder for the Arrow-IPC reconstruct path. The
/// sibling of `config_class::bigint_to_u64`: `get_i64`'s `lossless` flag is
/// `false` when the JS `bigint` magnitude does not fit `i64`, so this rejects
/// such a value (with the column name in the diagnostic) instead of letting
/// the wrapped low bits truncate silently into the destination. The
/// `[InvalidParameterError]` prefix routes it to the typed JS subclass.
const BIGINT_TO_I64_HELPER: &str = "\
/// Decode an `i64` from a JS `bigint` Arrow column, rejecting a magnitude that
/// does not fit `i64` rather than truncating its wrapped low bits.
fn bigint_to_i64(name: &str, v: &BigInt) -> napi::Result<i64> {
    let (value, lossless) = v.get_i64();
    if lossless {
        Ok(value)
    } else {
        Err(crate::invalid_parameter_err(format!(
            \"{name}: BigInt magnitude must fit in i64\"
        )))
    }
}
";

/// Emitted once: serialise an Arrow `RecordBatch` to an Arrow IPC stream
/// buffer through a `StreamWriter`. Shared by the full `<tick>ToArrowIpc` and
/// the decode-fed projected `<tick>ToArrowIpcProjected` terminals so the IPC
/// framing lives in one place.
const ARROW_BATCH_TO_IPC_HELPER: &str = "\
/// Serialise an Arrow `RecordBatch` to an Arrow IPC stream buffer (the
/// `apache-arrow` wire form) through a `StreamWriter`. Shared by the full and
/// projected `<tick>ToArrowIpc` terminals.
fn arrow_batch_to_ipc_buffer(
    batch: &arrow_array::RecordBatch,
) -> napi::Result<napi::bindgen_prelude::Buffer> {
    let mut buf: Vec<u8> = Vec::new();
    {
        let mut writer = arrow_ipc::writer::StreamWriter::try_new(
            std::io::Cursor::new(&mut buf),
            &batch.schema(),
        )
        .map_err(|e| napi::Error::from_reason(format!(\"arrow ipc writer init failed: {e}\")))?;
        writer
            .write(batch)
            .map_err(|e| napi::Error::from_reason(format!(\"arrow ipc write failed: {e}\")))?;
        writer
            .finish()
            .map_err(|e| napi::Error::from_reason(format!(\"arrow ipc finish failed: {e}\")))?;
    }
    Ok(napi::bindgen_prelude::Buffer::from(buf))
}
";

/// Renders `thetadatadx-ts/src/_generated/tick_classes.rs` — the `#[napi(object)]` struct, `Vec` factory, and Arrow-IPC terminal per tick type for the TypeScript binding.
pub(super) fn render_ts_tick_classes(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Typed #[napi(object)] tick structs + Vec factories. Replaces the old\n");
    out.push_str(
        "// serde_json columnar returns with concrete TypeScript types in index.d.ts.\n\n",
    );
    // napi-rs requires the `BigInt` wrapper for any i64 field that crosses
    // to JS — pull it in whenever a tick column uses one, or whenever a
    // type carries a `*_timestamp_ms` epoch accessor (epoch milliseconds
    // are i64 and ride the same `Option<BigInt>` field, so a Greeks row
    // with no native i64 column still needs the import).
    let needs_bigint = schema.types.values().any(|def| {
        def.columns
            .iter()
            .any(|col| ts_column_needs_bigint(col.r#type.as_str()))
            || !timestamp_accessor_fields(def).is_empty()
    });
    if needs_bigint {
        out.push_str("use napi::bindgen_prelude::BigInt;\n\n");
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_struct(type_name, def));
        out.push('\n');
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_factory(schema, type_name, def));
        out.push('\n');
    }
    // Checked `BigInt -> i64` decoder for the Arrow-IPC reconstruct path
    // below — only emitted when a tick column is `i64` / `eod_num64`, so a
    // schema with no such column carries no unused helper.
    if schema.types.values().any(|def| {
        def.columns
            .iter()
            .any(|col| ts_column_needs_bigint(col.r#type.as_str()))
    }) {
        out.push_str(BIGINT_TO_I64_HELPER);
        out.push('\n');
    }
    // Arrow-IPC terminals per tick type: the full-schema
    // `<tick>ToArrowIpc(rows)` for a hand-built row vector, plus the decode-fed
    // projected pair `<tick>PresentColumns(headers)` + `<tick>ToArrowIpcProjected(rows, presentColumns, symbol?)`
    // that mirror the C ABI `thetadatadx_<tick>_present_columns` /
    // `_to_arrow_ipc_projected` and Python's projected `<TickName>List.to_arrow()`.
    if !sorted_type_names(schema).is_empty() {
        out.push_str(ARROW_BATCH_TO_IPC_HELPER);
        out.push('\n');
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        let rendered = render_ts_tick_arrow_ipc(type_name, def);
        out.push_str(&rendered);
        out.push('\n');
    }
    out
}

/// Emit the Arrow-IPC terminals for one tick type: the private
/// `<tick>_reconstruct_rows` helper (JS objects -> `Vec<tick::T>`), the
/// full-schema `<tick>ToArrowIpc(rows)`, the `<tick>PresentColumns(headers)`
/// wire-column producer, and the decode-fed `<tick>ToArrowIpcProjected(rows,
/// presentColumns, symbol?)`. The projected pair mirrors the C ABI
/// `thetadatadx_<tick>_present_columns` / `_to_arrow_ipc_projected` and
/// Python's projected `<TickName>List.to_arrow()`.
fn render_ts_tick_arrow_ipc(type_name: &str, def: &TickTypeDef) -> String {
    let snake = type_name.to_snake_case();
    let mut out = String::new();
    out.push_str(&render_ts_arrow_reconstruct_rows(type_name, def));
    out.push('\n');

    // Full-schema terminal: a hand-built row vector never touched a wire, so
    // every column is present.
    let js_name = format!("{}ToArrowIpc", type_name.to_lower_camel_case());
    writeln!(
        out,
        "/// Serialise a hand-built `{type_name}` row vector to a full-schema Arrow"
    )
    .unwrap();
    out.push_str("/// IPC stream (the `apache-arrow` wire form) carrying every column the\n");
    out.push_str("/// tick type defines. For rows decoded from a history response, use\n");
    writeln!(
        out,
        "/// `{}PresentColumns` + `{}ToArrowIpcProjected` for a terminal-exact",
        type_name.to_lower_camel_case(),
        type_name.to_lower_camel_case()
    )
    .unwrap();
    out.push_str("/// frame carrying only the wire's columns, mirroring Python's\n");
    out.push_str("/// projected `<TickName>List.to_arrow()`.\n");
    writeln!(out, "#[napi(js_name = \"{js_name}\")]").unwrap();
    writeln!(
        out,
        "pub fn {snake}_to_arrow_ipc(rows: Vec<{type_name}>) -> napi::Result<napi::bindgen_prelude::Buffer> {{"
    )
    .unwrap();
    writeln!(out, "    let owned = {snake}_reconstruct_rows(rows)?;").unwrap();
    out.push_str(
        "    let batch = thetadatadx::frames::TicksArrowExt::to_arrow(owned.as_slice())\n",
    );
    out.push_str("        .map_err(|e| napi::Error::from_reason(format!(\"arrow conversion failed: {e}\")))?;\n");
    out.push_str("    arrow_batch_to_ipc_buffer(&batch)\n");
    out.push_str("}\n\n");

    // Wire-column producer: resolve a response's header names to the schema
    // columns it carried, through the same `WireColumns::present_columns` the
    // buffered decode path uses.
    let present_js = format!("{}PresentColumns", type_name.to_lower_camel_case());
    writeln!(
        out,
        "/// Resolve a `{type_name}` history response's wire header names to the schema"
    )
    .unwrap();
    out.push_str("/// columns it carried, in schema order. Feed the result to\n");
    writeln!(
        out,
        "/// `{}ToArrowIpcProjected` for a terminal-exact columnar export. Mirrors the",
        type_name.to_lower_camel_case()
    )
    .unwrap();
    out.push_str("/// C ABI `thetadatadx_<tick>_present_columns` producer and Python's\n");
    out.push_str("/// `<TickName>List.columns`.\n");
    writeln!(out, "#[napi(js_name = \"{present_js}\")]").unwrap();
    writeln!(
        out,
        "pub fn {snake}_present_columns(headers: Vec<String>) -> Vec<String> {{"
    )
    .unwrap();
    out.push_str("    let refs: Vec<&str> = headers.iter().map(String::as_str).collect();\n");
    writeln!(
        out,
        "    <tick::{type_name} as thetadatadx::columns::WireColumns>::present_columns(&refs)"
    )
    .unwrap();
    out.push_str("        .present_names()\n");
    out.push_str("        .map(String::from)\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n\n");

    // Decode-fed projected terminal: only the wire's columns (+ optional
    // broadcast symbol), through `TicksArrowExt::to_arrow_projected`.
    let projected_js = format!("{}ToArrowIpcProjected", type_name.to_lower_camel_case());
    writeln!(
        out,
        "/// Serialise a `{type_name}` history result to a projected Arrow IPC stream"
    )
    .unwrap();
    out.push_str("/// carrying ONLY the columns named in `presentColumns` (build it with\n");
    writeln!(
        out,
        "/// `{}PresentColumns` from the response headers), optionally broadcasting",
        type_name.to_lower_camel_case()
    )
    .unwrap();
    out.push_str("/// `symbol` as the leading column, or emitting a per-row `symbols` column\n");
    out.push_str("/// for a multi-symbol snapshot (one value per row; takes precedence over\n");
    out.push_str("/// `symbol`). The decode-fed sibling of\n");
    writeln!(
        out,
        "/// `{}ToArrowIpc`: same wire format, projected to the wire's exact column",
        type_name.to_lower_camel_case()
    )
    .unwrap();
    out.push_str("/// set, matching Python's projected `<TickName>List.to_arrow()` and the C\n");
    out.push_str("/// ABI `thetadatadx_<tick>_to_arrow_ipc_projected`.\n");
    writeln!(out, "#[napi(js_name = \"{projected_js}\")]").unwrap();
    writeln!(out, "pub fn {snake}_to_arrow_ipc_projected(").unwrap();
    writeln!(out, "    rows: Vec<{type_name}>,").unwrap();
    out.push_str("    present_columns: Vec<String>,\n");
    out.push_str("    symbol: Option<String>,\n");
    out.push_str("    symbols: Option<Vec<String>>,\n");
    out.push_str(") -> napi::Result<napi::bindgen_prelude::Buffer> {\n");
    writeln!(out, "    let owned = {snake}_reconstruct_rows(rows)?;").unwrap();
    out.push_str(
        "    let mut columns = thetadatadx::columns::ColumnPresence::from_names(present_columns);\n",
    );
    // Ignore the broadcast symbol when the tick already owns a per-row `symbol`
    // column so the projected schema never carries a duplicate, matching the C
    // ABI serialiser. A per-row `symbols` (a multi-symbol snapshot) takes
    // precedence over the constant `symbol` broadcast.
    out.push_str("    if !columns.contains(\"symbol\") {\n");
    out.push_str("        if let Some(syms) = symbols {\n");
    out.push_str("            columns = columns.with_symbols(syms);\n");
    out.push_str("        } else if let Some(sym) = symbol {\n");
    out.push_str("            columns = columns.with_symbol(sym);\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    let batch = thetadatadx::frames::TicksArrowExt::to_arrow_projected(owned.as_slice(), &columns)\n");
    out.push_str("        .map_err(|e| napi::Error::from_reason(format!(\"arrow conversion failed: {e}\")))?;\n");
    out.push_str("    arrow_batch_to_ipc_buffer(&batch)\n");
    out.push_str("}\n");
    out
}

/// Emit the private `<tick>_reconstruct_rows(rows: Vec<Tick>) ->
/// napi::Result<Vec<tick::T>>` helper: rebuild the columnar `tick::T` rows from
/// the JS objects. Shared by the full and projected Arrow-IPC terminals so the
/// reverse projection lives in one place.
fn render_ts_arrow_reconstruct_rows(type_name: &str, def: &TickTypeDef) -> String {
    let snake = type_name.to_snake_case();
    let mut out = String::new();
    writeln!(
        out,
        "/// Rebuild a `Vec<tick::{type_name}>` from the JS `{type_name}` objects — the"
    )
    .unwrap();
    out.push_str("/// reverse of the forward factory, shared by the full and projected\n");
    out.push_str("/// Arrow-IPC terminals.\n");
    writeln!(
        out,
        "fn {snake}_reconstruct_rows(rows: Vec<{type_name}>) -> napi::Result<Vec<tick::{type_name}>> {{"
    )
    .unwrap();
    // A reconstruct can fail on a too-wide `i64` `BigInt` (`bigint_to_i64`)
    // or an out-of-vocabulary logical-enum string (`right` /
    // `calendar_status`); when the type carries either, the closure is
    // fallible and its results are collected into a `napi::Result<Vec<..>>`
    // and `?`-propagated. Types with neither keep the infallible
    // `.map(..).collect()` so a build that adds no validation pays no
    // wrapping.
    let fallible = ts_arrow_reconstruct_is_fallible(def);
    writeln!(out, "    let owned: Vec<tick::{type_name}> = rows").unwrap();
    out.push_str("        .into_iter()\n");
    if fallible {
        writeln!(
            out,
            "        .map(|r| -> napi::Result<tick::{type_name}> {{"
        )
        .unwrap();
        writeln!(out, "            Ok(tick::{type_name} {{").unwrap();
    } else {
        out.push_str("        .map(|r| {\n");
        writeln!(out, "            tick::{type_name} {{").unwrap();
    }
    for column in &def.columns {
        let field = rust_field_ident(&column.field);
        let expr = ts_arrow_reconstruct_expr(&column.r#type, &field);
        writeln!(out, "                {field}: {expr},").unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("                midpoint: r.midpoint,\n");
    }
    if def.contract_id {
        // Inverse of the factory's `has_contract_id().then_some(..)`: the
        // absent JS `undefined`/`null` round-trips back to the struct's
        // documented zero / NUL fill. `right` validates its inbound string
        // the same way the standalone `right` column does, rejecting any
        // value outside `"C"` / `"P"` (absent / empty → NUL).
        out.push_str("                expiration: r.expiration.unwrap_or(0),\n");
        out.push_str("                strike: r.strike.unwrap_or(0.0),\n");
        out.push_str(
            "                right: match r.right.as_deref() { Some(\"C\") => 'C', Some(\"P\") => 'P', None | Some(\"\") => '\\0', Some(other) => return Err(napi::Error::from_reason(format!(\"[InvalidParameterError] right must be \\\"C\\\" or \\\"P\\\", got {other:?}\"))) },\n",
        );
    }
    if fallible {
        out.push_str("            })\n");
        out.push_str("        })\n");
        writeln!(
            out,
            "        .collect::<napi::Result<Vec<tick::{type_name}>>>()?;"
        )
        .unwrap();
    } else {
        out.push_str("            }\n");
        out.push_str("        })\n");
        out.push_str("        .collect();\n");
    }
    out.push_str("    Ok(owned)\n");
    out.push_str("}\n");
    out
}

/// Reconstruct one columnar field of `tick::T` from the JS object binding
/// `r`. Inverse of the forward factory's per-type projection.
///
/// Logical-enum columns (`right`, `calendar_status`) validate the inbound
/// string against the accepted vocabulary and `return Err(..)` on anything
/// outside it, so an invalid value is rejected rather than silently coerced
/// to a neighbouring variant — the same accepted set and message wording the
/// Python `pyclass_to_tick_expr` reverse projection enforces, keeping the two
/// bindings' rejection behaviour identical. The `napi::Error` carries the
/// `[InvalidParameterError]` prefix so the wrapped free function re-throws it
/// as the typed `InvalidParameterError` subclass. Because these arms emit
/// `return Err(..)`, the surrounding reconstruct runs inside a fallible
/// closure (see [`render_ts_tick_arrow_ipc`]).
fn ts_arrow_reconstruct_expr(column_type: &str, field: &str) -> String {
    match column_type {
        // i64 columns cross from JS as `BigInt`. Reject a magnitude outside
        // `i64` (e.g. `2n ** 100n`) on the `lossless` flag rather than
        // silently truncating the wrapped low bits into the destination —
        // the same guard the config setters apply via `bigint_to_u64`. Runs
        // inside the fallible closure (`ts_arrow_reconstruct_is_fallible`
        // returns `true` for any i64 column).
        "i64" | "eod_num64" => format!("bigint_to_i64(\"{field}\", &r.{field})?"),
        // The logical right char arrives as a one-character string; only
        // `"C"` / `"P"` (and empty → NUL) are accepted, matching Python.
        "right" => format!(
            "match r.{field}.as_str() {{ \"C\" => 'C', \"P\" => 'P', \"\" => '\\0', other => return Err(napi::Error::from_reason(format!(\"[InvalidParameterError] right must be \\\"C\\\" or \\\"P\\\", got {{other:?}}\"))) }}"
        ),
        // The calendar day type arrives as the vendor vocabulary string;
        // round-trip it back through the enum, rejecting anything outside the
        // documented vocabulary rather than mis-classifying schema drift.
        "calendar_status" => format!(
            "match thetadatadx::CalendarStatus::from_wire_text(&r.{field}) {{ Some(status) => status, None => return Err(napi::Error::from_reason(format!(\"[InvalidParameterError] status must be one of open, early_close, full_close, weekend; got {{:?}}\", r.{field}))) }}"
        ),
        // Plain Copy primitives (i32 / f64 / bool) deref straight through.
        _ => format!("r.{field}"),
    }
}

/// `true` when a tick type's Arrow-IPC reconstruction can fail and so emits
/// `?` / `return Err(..)`: an `i64` / `eod_num64` column (rejects a `BigInt`
/// magnitude outside `i64` via `bigint_to_i64`), a logical-enum column
/// (`right` / `calendar_status`), or the appended contract-identity `right`
/// (present whenever `def.contract_id`). Such a reconstruct must run inside a
/// fallible closure; types without any fallible field keep the infallible
/// `.map(..).collect()` form so a build that adds no validation pays no
/// wrapping.
fn ts_arrow_reconstruct_is_fallible(def: &TickTypeDef) -> bool {
    def.contract_id
        || def.columns.iter().any(|column| {
            matches!(
                column.r#type.as_str(),
                "i64" | "eod_num64" | "right" | "calendar_status"
            )
        })
}

fn render_ts_tick_class_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let is_quote_tick = type_name == "QuoteTick";
    // Strip " -- N fields[...]." from the first doc line — see
    // `strip_field_count_from_doc` for rationale. Shared with the Python
    // emitter so both surfaces drift together.
    let doc = strip_field_count_from_doc(&def.doc);
    writeln!(out, "/// {doc}").unwrap();
    // `#[must_use]` — Vec<T> returned from expensive network calls should
    // not be silently dropped on the Rust side (napi-rs generates JS
    // bindings, but any Rust-side accidental drop is still a bug).
    out.push_str("#[must_use]\n");
    out.push_str("#[napi(object)]\n");
    out.push_str("#[derive(Clone)]\n");
    writeln!(out, "pub struct {type_name} {{").unwrap();
    for column in &def.columns {
        let rust_type = ts_class_rust_type(&column.r#type, type_name, &column.field);
        // Rust-side ident escape (`r#type`-style); the JS key napi-rs
        // derives from it is exempt — object keys admit reserved words.
        writeln!(
            out,
            "    pub {}: {},",
            rust_field_ident(&column.field),
            rust_type
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("    pub midpoint: f64,\n");
    }
    if def.contract_id {
        // Contract identity is populated on wildcard queries only —
        // absent identity is undefined/null on the JS surface,
        // matching the streaming `Contract` payload convention.
        out.push_str("    pub expiration: Option<i32>,\n");
        out.push_str("    pub strike: Option<f64>,\n");
        out.push_str("    pub right: Option<String>,\n");
    }
    // Boolean flag-word accessors decoded from the integer condition /
    // flag columns. TypeScript tick rows are `#[napi(object)]` plain
    // data (no methods), so the decoded booleans ride as precomputed
    // fields — the caller reads `tick.isCancelled` instead of
    // hand-decoding `conditionFlags`. The napi object key camelCases the
    // snake_case schema name.
    for flag in &def.flag_accessors {
        writeln!(out, "    /// {}", flag.doc).unwrap();
        writeln!(out, "    pub {}: bool,", flag.name).unwrap();
    }
    // Epoch-instant convenience fields: one per milliseconds-of-day
    // column on types that also carry `date`. Python / C++ expose these
    // as `*_timestamp_ms()` read-side accessors; the method-less napi
    // object surfaces the same values as precomputed `Option<BigInt>`
    // fields (camelCased to `createdTimestampMs` ...), computed once at
    // conversion time through the same DST-aware core. The raw integer
    // milliseconds-of-day columns stay primary; this is a convenience at
    // the epoch boundary, `undefined` when `date` is absent (`0`).
    for (accessor, field) in timestamp_accessor_fields(def) {
        writeln!(
            out,
            "    /// Unix epoch milliseconds (UTC, DST-aware) combining `date` with"
        )
        .unwrap();
        writeln!(
            out,
            "    /// `{field}` (Eastern-Time milliseconds-of-day). `undefined` when"
        )
        .unwrap();
        writeln!(out, "    /// `date` is absent (`0`).").unwrap();
        writeln!(out, "    pub {accessor}: Option<BigInt>,").unwrap();
    }
    out.push_str("}\n");
    out
}

fn render_ts_tick_class_factory(schema: &Schema, type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = ts_tick_class_factory_name(schema, type_name);
    writeln!(
        out,
        "fn {fn_name}(ticks: &[tick::{type_name}]) -> Vec<{type_name}> {{"
    )
    .unwrap();
    out.push_str("    ticks\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|t| {\n");
    writeln!(out, "            {type_name} {{").unwrap();
    for column in &def.columns {
        // String fields must be cloned; primitives are Copy. i64/eod_num64
        // cross to JS as `bigint` via `BigInt::from(...)` (see
        // `ts_class_rust_type`). Logical columns project to the same
        // shapes the Python pyclass surface exposes.
        let expr = match column.r#type.as_str() {
            "String" => format!("t.{field}.clone()", field = column.field),
            "right" => format!(
                "if t.{field} == '\\0' {{ String::new() }} else {{ t.{field}.to_string() }}",
                field = column.field
            ),
            "calendar_status" => {
                format!("t.{field}.as_str().to_string()", field = column.field)
            }
            col_type if ts_column_needs_bigint(col_type) => {
                format!("BigInt::from(t.{field})", field = column.field)
            }
            _ => format!("t.{field}", field = column.field),
        };
        writeln!(
            out,
            "                {}: {expr},",
            rust_field_ident(&column.field)
        )
        .unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("                midpoint: t.midpoint,\n");
    }
    if def.contract_id {
        // Absent contract identity (single-contract queries) crosses
        // to JS as undefined/null — the documented absence convention.
        out.push_str("                expiration: t.has_contract_id().then_some(t.expiration),\n");
        out.push_str("                strike: t.has_contract_id().then_some(t.strike),\n");
        out.push_str(
            "                right: if t.right == '\\0' { None } else { Some(t.right.to_string()) },\n",
        );
    }
    // Decode each flag-word accessor once at conversion time; the result
    // rides as a precomputed boolean field on the JS object.
    for flag in &def.flag_accessors {
        writeln!(
            out,
            "                {}: {},",
            rust_field_ident(&flag.name),
            flag.rust_predicate("t")
        )
        .unwrap();
    }
    // Resolve each `*_timestamp_ms` epoch value once at conversion time
    // through the shared DST-aware core (`thetadatadx::time::date_ms_to_epoch_ms`,
    // the same function the Python accessor and the `thetadatadx_timestamp_ms`
    // FFI call) and ride it as a precomputed `Option<BigInt>` field — no
    // date math is reimplemented in the binding.
    for (accessor, field) in timestamp_accessor_fields(def) {
        writeln!(
            out,
            "                {accessor}: thetadatadx::time::date_ms_to_epoch_ms(t.date, t.{field}).map(BigInt::from),"
        )
        .unwrap();
    }
    out.push_str("            }\n");
    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n");
    out
}

fn ts_tick_class_factory_name<'a>(schema: &'a Schema, type_name: &str) -> &'a str {
    render_for_type(schema, type_name).ts_class_vec.as_str()
}

fn ts_class_rust_type(column_type: &str, type_name: &str, field: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" | "eod_num64" => "BigInt",
        "f64" | "price" | "eod_price" => "f64",
        // Logical char surfaces as a JS one-character string
        // (`"C"` / `"P"`); the calendar day type surfaces as the
        // vendor vocabulary string.
        "String" | "right" | "calendar_status" => "String",
        "bool" => "bool",
        other => panic!("unsupported TS column type '{other}' in {type_name}.{field}"),
    }
}

fn ts_column_needs_bigint(column_type: &str) -> bool {
    matches!(column_type, "i64" | "eod_num64")
}
