//! Build-time codegen for the vendor vocabulary tables.
//!
//! Reads `data/vendor_vocabulary.toml` and emits
//! `src/tdbe/vocabulary/tables_generated.rs` containing one `&[&str]`
//! per vocabulary.
//!
//! The generated file is committed so consumers building from crates.io do
//! not have to re-run codegen unless they edit the TOML source of truth.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Deserialize)]
struct File {
    vocabulary: Vec<Table>,
}

#[derive(Deserialize)]
struct Table {
    name: String,
    names: Vec<String>,
}

/// `DataType` -> `DATA_TYPE`, for the emitted constant name.
fn screaming_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_uppercase());
    }
    out
}

pub fn generate() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let src_toml = manifest_dir.join("data/vendor_vocabulary.toml");
    let out = manifest_dir.join("src/tdbe/vocabulary/tables_generated.rs");

    println!("cargo:rerun-if-changed=data/vendor_vocabulary.toml");

    let src = fs::read_to_string(&src_toml)
        .unwrap_or_else(|e| panic!("read {}: {e}", src_toml.display()));
    let file: File = toml::from_str(&src).expect("vendor_vocabulary.toml: schema mismatch");

    for t in &file.vocabulary {
        assert!(
            !t.names.is_empty(),
            "vendor_vocabulary.toml: {} has no names",
            t.name
        );
        let mut seen = t.names.clone();
        seen.sort_unstable();
        let before = seen.len();
        seen.dedup();
        assert_eq!(
            before,
            seen.len(),
            "vendor_vocabulary.toml: {} repeats a name",
            t.name
        );
        for n in &t.names {
            assert!(
                n.chars()
                    .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_'),
                "vendor_vocabulary.toml: {} has a non-vocabulary name {n:?}",
                t.name
            );
        }
    }

    let mut s = String::new();
    s.push_str("// @generated DO NOT EDIT — regenerated by build.rs from data/*.toml\n");
    s.push_str("//\n");
    s.push_str("// Source-of-truth: thetadatadx-rs/data/vendor_vocabulary.toml\n\n");

    for t in &file.vocabulary {
        let konst = screaming_snake(&t.name);
        let _ = writeln!(
            s,
            "/// The vendor's `{}` vocabulary ({} names).",
            t.name,
            t.names.len()
        );
        let _ = writeln!(s, "pub const {konst}: [&str; {}] = [", t.names.len());
        for n in &t.names {
            let _ = writeln!(s, "    {n:?},");
        }
        s.push_str("];\n\n");
    }

    fs::write(&out, s)?;
    Ok(())
}
