//! Emit `sdks/python/src/_generated/tick_arrow.rs` — Arrow columnar pipeline.
//!
//! Two generator-owned surfaces live in the generated file:
//!
//! 1. `arrow_schema_for_qualname(qualname: &str) -> Option<Arc<Schema>>`
//!    — schema map keyed by tick pyclass `__qualname__`, used by the
//!    per-tick slice builders so every tick type carries the exact
//!    same Arrow field order across endpoints.
//!
//! 2. `<tick>_slice_to_arrow_table(py, &[tick::T]) -> PyResult<Py<PyAny>>`
//!    — one per tick type. Called from the typed `<TickName>List`
//!    wrapper's `.to_arrow()` / `.to_pandas()` / `.to_polars()`
//!    terminals so the decoder-owned `Vec<tick::T>` feeds the column
//!    builders directly — no intermediate pyclass-list allocation.
//!
//! Zero-copy to `pyarrow`: each `RecordBatch` buffer is handed over
//! via the Arrow C Stream Interface at the pyo3 boundary (the batch is
//! exported as an `FFI_ArrowArrayStream` and imported through
//! `pyarrow.RecordBatchReader._import_from_c`). pandas 2.x consumes
//! those buffers in place for all numeric dtypes.

use std::fmt::Write as _;

use super::schema::{Schema, TickTypeDef};
use super::{pyclass_name, sorted_type_names};

/// Renders `sdks/python/src/_generated/tick_arrow.rs` — the qualname-keyed Arrow schema map, the `RecordBatch`-to-pyarrow helper, and one slice-to-Arrow converter per tick type.
pub(super) fn render_python_tick_arrow(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Arrow columnar pipeline. Single RecordBatch per converter, zero-copy to\n");
    out.push_str("// pyarrow via the Arrow C Stream Interface (`FFI_ArrowArrayStream` ->\n");
    out.push_str("// `pyarrow.RecordBatchReader._import_from_c`).\n");
    out.push_str("//\n");
    out.push_str("// Every historical endpoint hands its decoder-owned `Vec<tick::T>`\n");
    out.push_str("// straight to the typed `<TickName>List` wrapper (see `tick_classes.rs`);\n");
    out.push_str("// the wrapper's `.to_arrow()` / `.to_pandas()` / `.to_polars()` terminals\n");
    out.push_str("// call into `slice_arrow::<tick>_slice_to_arrow_table` below.\n");
    out.push_str("// No pyclass-list double-buffer, no free-function round-trip.\n\n");
    // `Arc` is already imported at the `lib.rs` include-site (via
    // `std::sync::{Arc, Mutex}`); referencing `std::sync::Arc` here
    // would shadow. Paths below use fully-qualified `std::sync::Arc`
    // only inside the Schema-building helpers that predate the
    // lib.rs layout -- keep generator output self-sufficient by
    // qualifying the Arc references rather than importing again.
    //
    // Arrow imports (`ArrayRef`, `Float64Array`, `Int32Array`,
    // `Int64Array`, `StringArray`, `DataType`, `Field`, `Schema`,
    // `RecordBatch`) are emitted once at the top of the sibling
    // `tick_classes.rs` -- which is `include!`-ed earlier in
    // `lib.rs` -- so re-importing them here would collide at the
    // splice point. The C Stream Interface types
    // (`FFI_ArrowArrayStream`, `RecordBatchIterator`) are scoped
    // inside the `record_batch_to_pyarrow_table` helper itself, so no
    // module-level arrow import is emitted at this seam.

    // Schema map + slice-to-Arrow converters. The pyclass-list dispatcher
    // and the `ArrowFromPyclassList` trait that used to live here have
    // been removed along with every free-function DataFrame surface — the
    // chained `<TickName>List` terminals are the sole path from decoded
    // ticks to DataFrame output.
    out.push_str(&render_python_arrow_schema_map(schema));
    out.push('\n');
    out.push_str(&render_record_batch_to_pyarrow_helper());
    out.push('\n');
    out.push_str(&render_python_slice_to_arrow_converters(schema));
    out
}

/// Emit the `record_batch_to_pyarrow_table` helper used by the slice
/// converters below AND by `StringList::to_arrow` in `tick_classes.rs`.
/// Single seam — the conversion code is emitted once and every
/// consumer reaches for the same function.
fn render_record_batch_to_pyarrow_helper() -> String {
    include_str!("templates/python_arrow/record_batch_to_pyarrow_table.rs.tmpl").to_string()
}

// ── Slice-to-Arrow converters ───────────────────────────────────────────
//
// One `<tick>_slice_to_arrow_table(py, &[tick::T])` emitter per tick
// type, plus an `ArrowBuilder` trait so the Python-side dispatcher can
// invoke them polymorphically. The slice path is the primary fast
// route used by historical endpoints: the Rust decoder already owns a
// `Vec<tick::T>`, so feeding the column builders directly avoids the
// pyclass-list round-trip that peaks RSS at `2 × n_rows` equivalents
// of tick data.
//
// Field-type mapping mirrors the pyclass path so the resulting Arrow
// schema is bit-identical to the one produced by
// `pyclass_list_to_arrow_table` — callers can freely mix the two
// converters in the same pipeline.

fn render_python_slice_to_arrow_converters(schema: &Schema) -> String {
    let mut out = String::new();
    // Slice-based Arrow fast path: the fluent builder `.arrow()` /
    // `.pandas()` / `.polars()` terminals in `historical_methods.rs`
    // call these converters directly on the decoder-owned
    // `Vec<tick::T>`, skipping the pyclass-list double-buffer. See
    // `build_support/endpoints/render/python.rs::python_slice_arrow_converter`
    // for the dispatch mapping.
    out.push_str("pub(crate) mod slice_arrow {\n");
    out.push_str("    use super::*;\n");
    out.push_str("    use super::tick;\n");
    out.push_str(
        "    use arrow::array::{ArrayRef, BooleanArray, Float64Array, Int32Array, Int64Array, StringArray};\n",
    );
    out.push_str("    use arrow::record_batch::RecordBatch;\n\n");
    // The fluent-builder Arrow terminals in `historical_methods.rs`
    // dispatch on endpoint return type (via
    // `build_support/endpoints/helpers.rs::python_slice_arrow_converter`)
    // directly to the free helper functions below. No intermediate
    // trait is needed — keeping the surface to the free functions
    // means no unused-trait lint and the call sites stay visible in
    // the generated `historical_methods.rs` diff.

    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        // Indent every line of the generated body two spaces so the
        // module braces stay visually clean in the emitted file.
        let body = render_python_slice_reader(type_name, def);
        for line in body.lines() {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
        out.push('\n');
        let helper = render_python_slice_public_helper(type_name);
        for line in helper.lines() {
            out.push_str("    ");
            out.push_str(line);
            out.push('\n');
        }
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

/// Map a `tick::T` field type to the Rust scalar buffered per column
/// before the Arrow array is built. Logical columns buffer their
/// columnar projections: `right` and `calendar_status` buffer `String`
/// (built into `StringArray`), `bool` buffers `bool` (built into
/// `BooleanArray`).
pub(super) fn tick_struct_field_type(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" | "eod_num64" => "i64",
        "f64" | "price" | "eod_price" => "f64",
        "String" | "right" | "calendar_status" => "String",
        "bool" => "bool",
        other => panic!("unsupported tick-struct field type '{other}'"),
    }
}

/// Per-column push expression reading one tick field into its column
/// buffer. Logical columns project here: `right` chars become one-char
/// strings (`'\0'` -> `""`), the calendar status enum becomes its
/// vendor-vocabulary string.
pub(super) fn column_push_expr(column_type: &str, field: &str) -> String {
    match column_type {
        "right" => {
            format!("if t.{field} == '\\0' {{ String::new() }} else {{ t.{field}.to_string() }}")
        }
        "calendar_status" => format!("t.{field}.as_str().to_string()"),
        "String" => format!("t.{field}.clone()"),
        _ => format!("t.{field}"),
    }
}

/// Emit `read_arrow_batch_from_<tick>_slice` — iterates a `&[tick::T]`
/// and builds an Arrow `RecordBatch`. Logical columns are projected to
/// the same shapes the pyclass path exposes so the slice path matches
/// it byte-for-byte; absent contract identity buffers as Arrow nulls.
fn render_python_slice_reader(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = python_slice_reader_fn_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";
    let is_contract = def.contract_id;

    writeln!(
        out,
        "fn {fn_name}(ticks: &[tick::{type_name}]) -> PyResult<RecordBatch> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    let schema = arrow_schema_for_qualname(\"{class}\").expect(\"generated schema must be present for {class}\");",
        class = pyclass_name(type_name)
    )
    .unwrap();
    out.push_str("    let n = ticks.len();\n");

    // Column vectors: match the Arrow schema's concrete types. One
    // pass per column so the inner loop stays branch-free on the hot
    // path.
    let mut column_decls: Vec<(String, String)> = Vec::new();
    for column in &def.columns {
        let rust_ty = tick_struct_field_type(column.r#type.as_str());
        writeln!(
            out,
            "    let mut col_{field}: Vec<{rust_ty}> = Vec::with_capacity(n);",
            field = column.field
        )
        .unwrap();
        column_decls.push((column.field.clone(), column.r#type.clone()));
    }
    if is_quote_tick {
        out.push_str("    let mut col_midpoint: Vec<f64> = Vec::with_capacity(n);\n");
    }
    if is_contract {
        // Absent contract identity (single-contract queries) buffers
        // as Arrow nulls — the columnar mirror of the pyclass `None`
        // convention.
        out.push_str("    let mut col_expiration: Vec<Option<i32>> = Vec::with_capacity(n);\n");
        out.push_str("    let mut col_strike: Vec<Option<f64>> = Vec::with_capacity(n);\n");
        out.push_str("    let mut col_right: Vec<Option<String>> = Vec::with_capacity(n);\n");
    }

    out.push_str("    for t in ticks {\n");
    for (field, column_type) in &column_decls {
        writeln!(
            out,
            "        col_{field}.push({});",
            column_push_expr(column_type, field)
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("        col_midpoint.push(t.midpoint);\n");
    }
    if is_contract {
        out.push_str("        col_expiration.push(t.has_contract_id().then_some(t.expiration));\n");
        out.push_str("        col_strike.push(t.has_contract_id().then_some(t.strike));\n");
        out.push_str(
            "        col_right.push(if t.right == '\\0' { None } else { Some(t.right.to_string()) });\n",
        );
    }
    out.push_str("    }\n");

    // Build columns — same constructor set as the pyclass path so the
    // RecordBatch schemas line up byte-for-byte.
    out.push_str("    let columns: Vec<ArrayRef> = vec![\n");
    for (field, column_type) in &column_decls {
        let ctor = arrow_array_ctor(column_type);
        writeln!(
            out,
            "        Arc::new({ctor}::from(col_{field})) as ArrayRef,"
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("        Arc::new(Float64Array::from(col_midpoint)) as ArrayRef,\n");
    }
    if is_contract {
        out.push_str("        Arc::new(Int32Array::from(col_expiration)) as ArrayRef,\n");
        out.push_str("        Arc::new(Float64Array::from(col_strike)) as ArrayRef,\n");
        out.push_str("        Arc::new(StringArray::from(col_right)) as ArrayRef,\n");
    }
    out.push_str("    ];\n");
    out.push_str(
        "    RecordBatch::try_new(schema, columns).map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(e.to_string()))\n",
    );
    out.push_str("}\n");
    out
}

fn python_slice_reader_fn_name(type_name: &str) -> String {
    format!(
        "read_arrow_batch_from_{}_slice",
        screaming_snake_to_snake(type_name)
    )
}

fn python_slice_helper_fn_name(type_name: &str) -> String {
    format!(
        "{}_slice_to_arrow_table",
        screaming_snake_to_snake(type_name)
    )
}

/// Map `EodTick` -> `eod_tick`, `OHLCTick` -> `o_h_l_c_tick`, etc.
/// Used to derive stable function names from tick pyclass type names.
fn screaming_snake_to_snake(type_name: &str) -> String {
    let mut out = String::new();
    for (i, c) in type_name.chars().enumerate() {
        if c.is_uppercase() {
            if i != 0 {
                out.push('_');
            }
            for lc in c.to_lowercase() {
                out.push(lc);
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Emit the public `<tick>_slice_to_arrow_table(py, &[tick::T])`
/// helper. Thin wrapper over the reader + `record_batch_to_pyarrow_table`.
fn render_python_slice_public_helper(type_name: &str) -> String {
    let mut out = String::new();
    let helper = python_slice_helper_fn_name(type_name);
    let reader = python_slice_reader_fn_name(type_name);
    writeln!(
        out,
        "/// Convert a decoder-owned `&[tick::{type_name}]` slice into a"
    )
    .unwrap();
    writeln!(
        out,
        "/// `pyarrow.Table` without materialising typed pyclass instances."
    )
    .unwrap();
    writeln!(
        out,
        "/// Primary fast path for historical endpoints — avoids the"
    )
    .unwrap();
    writeln!(
        out,
        "/// double-buffering RSS spike of the pyclass-list converter."
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) fn {helper}(py: Python<'_>, ticks: &[tick::{type_name}]) -> PyResult<Py<PyAny>> {{"
    )
    .unwrap();
    writeln!(out, "    let batch = {reader}(ticks)?;").unwrap();
    out.push_str("    record_batch_to_pyarrow_table(py, batch)\n");
    out.push_str("}\n");
    out
}

/// Map a `tick_schema.toml` column `type` to the Arrow `DataType` enum
/// variant we emit into the generated schema. `eod_num` (i32) and
/// `eod_num64` (i64) are distinct on the Rust side because one is
/// widened for volume/count; they preserve that distinction into
/// Arrow.
pub(super) fn arrow_data_type_expr(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "DataType::Int32",
        "i64" | "eod_num64" => "DataType::Int64",
        "f64" | "price" | "eod_price" => "DataType::Float64",
        "String" | "right" | "calendar_status" => "DataType::Utf8",
        "bool" => "DataType::Boolean",
        other => panic!("unsupported Arrow data type for column type '{other}'"),
    }
}

/// Map a `tick_schema.toml` column `type` to the Arrow concrete array
/// constructor we call when materializing a column. Parallel to
/// `arrow_data_type_expr`; the caller wraps the result in
/// `Arc::new(...) as ArrayRef`.
pub(super) fn arrow_array_ctor(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "Int32Array",
        "i64" | "eod_num64" => "Int64Array",
        "f64" | "price" | "eod_price" => "Float64Array",
        "String" | "right" | "calendar_status" => "StringArray",
        "bool" => "BooleanArray",
        other => panic!("unsupported Arrow array ctor for column type '{other}'"),
    }
}

/// Emit `arrow_schema_for_qualname` — a static schema map keyed on
/// pyclass `__qualname__`. Critical for the empty-list case: Arrow
/// cannot construct a `RecordBatch` without a schema, so we need a
/// source of typed field metadata keyed on tick class.
fn render_python_arrow_schema_map(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("/// Typed Arrow schema keyed by the tick pyclass `__qualname__`.\n");
    out.push_str("/// Column order matches the `#[pyo3(get)]` field order emitted into\n");
    out.push_str("/// `tick_classes.rs` by the sibling renderer, so a given tick type\n");
    out.push_str("/// produces stable DataFrame column ordering across endpoints.\n");
    out.push_str(
        "pub(crate) fn arrow_schema_for_qualname(qualname: &str) -> Option<Arc<Schema>> {\n",
    );
    out.push_str("    match qualname {\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        let class = pyclass_name(type_name);
        let is_quote_tick = type_name == "QuoteTick";
        writeln!(
            out,
            "        \"{class}\" => Some(Arc::new(Schema::new(vec!["
        )
        .unwrap();
        for column in &def.columns {
            let dt = arrow_data_type_expr(column.r#type.as_str());
            // Column names carry the public field name (`column.field`)
            // so DataFrame columns line up with row-object attributes;
            // wire spellings (`column.name`) stay in the decode layer.
            // Keyword-escaped attributes (`lambda_`) keep the logical
            // field name here — column names are strings, not
            // identifiers.
            writeln!(
                out,
                "            Field::new(\"{name}\", {dt}, false),",
                name = column.field,
            )
            .unwrap();
        }
        if is_quote_tick {
            out.push_str("            Field::new(\"midpoint\", DataType::Float64, false),\n");
        }
        if def.contract_id {
            // Nullable: contract identity is absent (Arrow null) on
            // single-contract queries — mirrors the pyclass `None`.
            out.push_str("            Field::new(\"expiration\", DataType::Int32, true),\n");
            out.push_str("            Field::new(\"strike\", DataType::Float64, true),\n");
            out.push_str("            Field::new(\"right\", DataType::Utf8, true),\n");
        }
        out.push_str("        ]))),\n");
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}
