//! Emit `sdks/typescript/src/_generated/tick_classes.rs` — typed `#[napi(object)]`
//! tick structs + `Vec` factories. Replaces the old `serde_json` columnar
//! returns with concrete TypeScript types in `index.d.ts`.
//!
//! Each tick type is emitted as a flat `#[napi(object)]` struct so napi-rs
//! generates a matching TypeScript interface in `index.d.ts`. `Vec<Tick>`
//! returns from endpoint methods become `Tick[]` in TS — every historical
//! endpoint is fully typed, no `any`.
//!
//! A parallel `{snake_type}_to_class_vec(&[tick::Type]) -> Vec<Type>` helper
//! copies Rust tick structs (from `tdbe::types::tick`) into the `#[napi]`
//! types. The helpers are drop-in substitutes for the `..._to_columnar`
//! converters used previously.

use std::fmt::Write as _;

use super::idents::rust_field_ident;
use super::python_classes::strip_field_count_from_doc;
use super::schema::{render_for_type, Schema, TickTypeDef};
use super::sorted_type_names;

pub(super) fn render_ts_tick_classes(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Typed #[napi(object)] tick structs + Vec factories. Replaces the old\n");
    out.push_str(
        "// serde_json columnar returns with concrete TypeScript types in index.d.ts.\n\n",
    );
    // napi-rs requires the `BigInt` wrapper for any i64 field that crosses
    // to JS — pull it in whenever a tick column uses one.
    let needs_bigint = schema
        .types
        .values()
        .flat_map(|def| def.columns.iter())
        .any(|col| ts_column_needs_bigint(col.r#type.as_str()));
    if needs_bigint {
        out.push_str("use napi::bindgen_prelude::BigInt;\n\n");
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_struct(type_name, def));
        out.push('\n');
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_factory(schema, type_name, def));
        out.push('\n');
    }
    // Arrow-IPC terminals: one `#[napi] <tick>ToArrowIpc(rows) -> Buffer`
    // per columnar tick type, so a TypeScript history result reaches a
    // dataframe the same way Python does via `<TickName>List.to_arrow()`.
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        if let Some(rendered) = render_ts_tick_arrow_ipc(type_name, def) {
            out.push_str(&rendered);
            out.push('\n');
        }
    }
    out
}

/// Emit a `#[napi] <tick>ToArrowIpc(rows: Tick[]) -> Buffer` free
/// function: reconstruct the columnar `tick::T` rows from the JS objects
/// and serialise them to an Arrow IPC stream through the same
/// `TicksArrowExt::to_arrow` + `StreamWriter` path the FlatFiles terminal
/// uses. Returns `None` for non-columnar types (`OptionContract` carries a
/// heap string and ships no Arrow terminal, matching the C++ / FFI
/// surface).
fn render_ts_tick_arrow_ipc(type_name: &str, def: &TickTypeDef) -> Option<String> {
    if type_name == "OptionContract" {
        return None;
    }
    let fn_name = format!("{}_to_arrow_ipc", to_snake_case(type_name));
    let js_name = format!("{}ToArrowIpc", to_lower_camel(type_name));
    let mut out = String::new();
    writeln!(
        out,
        "/// Serialise a `{type_name}` history result to an Arrow IPC stream"
    )
    .unwrap();
    out.push_str("/// (the `apache-arrow` wire form). Mirrors the FlatFiles\n");
    out.push_str("/// `FlatFileRowList.toArrowIpc()` exit and the Python\n");
    out.push_str("/// `<TickName>List.to_arrow()` terminal so every binding can reach a\n");
    out.push_str("/// dataframe from an in-band history result.\n");
    writeln!(out, "#[napi(js_name = \"{js_name}\")]").unwrap();
    writeln!(
        out,
        "pub fn {fn_name}(rows: Vec<{type_name}>) -> napi::Result<napi::bindgen_prelude::Buffer> {{"
    )
    .unwrap();
    writeln!(out, "    let owned: Vec<tick::{type_name}> = rows").unwrap();
    out.push_str("        .into_iter()\n");
    out.push_str("        .map(|r| {\n");
    writeln!(out, "            tick::{type_name} {{").unwrap();
    for column in &def.columns {
        let field = rust_field_ident(&column.field);
        let expr = ts_arrow_reconstruct_expr(&column.r#type, &field);
        writeln!(out, "                {field}: {expr},").unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("                midpoint: r.midpoint,\n");
    }
    if def.contract_id {
        // Inverse of the factory's `has_contract_id().then_some(..)`: the
        // absent JS `undefined`/`null` round-trips back to the struct's
        // documented zero / NUL fill.
        out.push_str("                expiration: r.expiration.unwrap_or(0),\n");
        out.push_str("                strike: r.strike.unwrap_or(0.0),\n");
        out.push_str(
            "                right: r.right.as_deref().and_then(|s| s.chars().next()).unwrap_or('\\0'),\n",
        );
    }
    out.push_str("            }\n");
    out.push_str("        })\n");
    out.push_str("        .collect();\n");
    out.push_str(
        "    let batch = thetadatadx::frames::TicksArrowExt::to_arrow(owned.as_slice())\n",
    );
    out.push_str("        .map_err(|e| napi::Error::from_reason(format!(\"arrow conversion failed: {e}\")))?;\n");
    out.push_str("    let mut buf: Vec<u8> = Vec::new();\n");
    out.push_str("    {\n");
    out.push_str("        let mut writer = arrow_ipc::writer::StreamWriter::try_new(\n");
    out.push_str("            std::io::Cursor::new(&mut buf),\n");
    out.push_str("            &batch.schema(),\n");
    out.push_str("        )\n");
    out.push_str("        .map_err(|e| napi::Error::from_reason(format!(\"arrow ipc writer init failed: {e}\")))?;\n");
    out.push_str("        writer\n");
    out.push_str("            .write(&batch)\n");
    out.push_str("            .map_err(|e| napi::Error::from_reason(format!(\"arrow ipc write failed: {e}\")))?;\n");
    out.push_str("        writer\n");
    out.push_str("            .finish()\n");
    out.push_str("            .map_err(|e| napi::Error::from_reason(format!(\"arrow ipc finish failed: {e}\")))?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(napi::bindgen_prelude::Buffer::from(buf))\n");
    out.push_str("}\n");
    Some(out)
}

/// Reconstruct one columnar field of `tick::T` from the JS object binding
/// `r`. Inverse of the forward factory's per-type projection.
fn ts_arrow_reconstruct_expr(column_type: &str, field: &str) -> String {
    match column_type {
        // i64 columns cross from JS as `BigInt`; `get_i64` yields the value.
        "i64" | "eod_num64" => format!("{{ let (v, _) = r.{field}.get_i64(); v }}"),
        // The logical right char arrives as a one-character string.
        "right" => format!(
            "r.{field}.chars().next().unwrap_or('\\0')"
        ),
        // The calendar day type arrives as the vendor vocabulary string;
        // round-trip it back through the enum (unknown text → Weekend, the
        // closed-day default, never a phantom open session).
        "calendar_status" => format!(
            "tdbe::types::enums::CalendarStatus::from_wire_text(&r.{field}).unwrap_or(tdbe::types::enums::CalendarStatus::Weekend)"
        ),
        // Plain Copy primitives (i32 / f64 / bool) deref straight through.
        _ => format!("r.{field}"),
    }
}

/// PascalCase tick type name → snake_case fn-name stem (`EodTick` →
/// `eod_tick`).
fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// PascalCase tick type name → lowerCamelCase JS stem (`EodTick` →
/// `eodTick`).
fn to_lower_camel(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_ascii_lowercase().to_string() + chars.as_str(),
        None => String::new(),
    }
}

fn render_ts_tick_class_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let is_quote_tick = type_name == "QuoteTick";
    // Strip " -- N fields[...]." from the first doc line — see
    // `strip_field_count_from_doc` for rationale. Shared with the Python
    // emitter so both surfaces drift together.
    let doc = strip_field_count_from_doc(&def.doc);
    writeln!(out, "/// {doc}").unwrap();
    // `#[must_use]` — Vec<T> returned from expensive network calls should
    // not be silently dropped on the Rust side (napi-rs generates JS
    // bindings, but any Rust-side accidental drop is still a bug).
    out.push_str("#[must_use]\n");
    out.push_str("#[napi(object)]\n");
    out.push_str("#[derive(Clone)]\n");
    writeln!(out, "pub struct {type_name} {{").unwrap();
    for column in &def.columns {
        let rust_type = ts_class_rust_type(&column.r#type, type_name, &column.field);
        // Rust-side ident escape (`r#type`-style); the JS key napi-rs
        // derives from it is exempt — object keys admit reserved words.
        writeln!(
            out,
            "    pub {}: {},",
            rust_field_ident(&column.field),
            rust_type
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("    pub midpoint: f64,\n");
    }
    if def.contract_id {
        // Contract identity is populated on wildcard queries only —
        // absent identity is undefined/null on the JS surface,
        // matching the streaming `Contract` payload convention.
        out.push_str("    pub expiration: Option<i32>,\n");
        out.push_str("    pub strike: Option<f64>,\n");
        out.push_str("    pub right: Option<String>,\n");
    }
    // Boolean flag-word accessors decoded from the integer condition /
    // flag columns. TypeScript tick rows are `#[napi(object)]` plain
    // data (no methods), so the decoded booleans ride as precomputed
    // fields — the caller reads `tick.isCancelled` instead of
    // hand-decoding `conditionFlags`. The napi object key camelCases the
    // snake_case schema name.
    for flag in &def.flag_accessors {
        writeln!(out, "    /// {}", flag.doc).unwrap();
        writeln!(out, "    pub {}: bool,", flag.name).unwrap();
    }
    out.push_str("}\n");
    out
}

fn render_ts_tick_class_factory(schema: &Schema, type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = ts_tick_class_factory_name(schema, type_name);
    writeln!(
        out,
        "fn {fn_name}(ticks: &[tick::{type_name}]) -> Vec<{type_name}> {{"
    )
    .unwrap();
    out.push_str("    ticks\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|t| {\n");
    writeln!(out, "            {type_name} {{").unwrap();
    for column in &def.columns {
        // String fields must be cloned; primitives are Copy. i64/eod_num64
        // cross to JS as `bigint` via `BigInt::from(...)` (see
        // `ts_class_rust_type`). Logical columns project to the same
        // shapes the Python pyclass surface exposes.
        let expr = match column.r#type.as_str() {
            "String" => format!("t.{field}.clone()", field = column.field),
            "right" => format!(
                "if t.{field} == '\\0' {{ String::new() }} else {{ t.{field}.to_string() }}",
                field = column.field
            ),
            "calendar_status" => {
                format!("t.{field}.as_str().to_string()", field = column.field)
            }
            col_type if ts_column_needs_bigint(col_type) => {
                format!("BigInt::from(t.{field})", field = column.field)
            }
            _ => format!("t.{field}", field = column.field),
        };
        writeln!(
            out,
            "                {}: {expr},",
            rust_field_ident(&column.field)
        )
        .unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("                midpoint: t.midpoint,\n");
    }
    if def.contract_id {
        // Absent contract identity (single-contract queries) crosses
        // to JS as undefined/null — the documented absence convention.
        out.push_str("                expiration: t.has_contract_id().then_some(t.expiration),\n");
        out.push_str("                strike: t.has_contract_id().then_some(t.strike),\n");
        out.push_str(
            "                right: if t.right == '\\0' { None } else { Some(t.right.to_string()) },\n",
        );
    }
    // Decode each flag-word accessor once at conversion time; the result
    // rides as a precomputed boolean field on the JS object.
    for flag in &def.flag_accessors {
        writeln!(
            out,
            "                {}: {},",
            rust_field_ident(&flag.name),
            flag.rust_predicate("t")
        )
        .unwrap();
    }
    out.push_str("            }\n");
    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n");
    out
}

fn ts_tick_class_factory_name<'a>(schema: &'a Schema, type_name: &str) -> &'a str {
    render_for_type(schema, type_name).ts_class_vec.as_str()
}

fn ts_class_rust_type(column_type: &str, type_name: &str, field: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" | "eod_num64" => "BigInt",
        "f64" | "price" | "eod_price" => "f64",
        // Logical char surfaces as a JS one-character string
        // (`"C"` / `"P"`); the calendar day type surfaces as the
        // vendor vocabulary string.
        "String" | "right" | "calendar_status" => "String",
        "bool" => "bool",
        other => panic!("unsupported TS column type '{other}' in {type_name}.{field}"),
    }
}

fn ts_column_needs_bigint(column_type: &str) -> bool {
    matches!(column_type, "i64" | "eod_num64")
}
