// @generated DO NOT EDIT — regenerated by build.rs from fpss_event_schema.toml
// Typed #[napi(object)] structs for every `FpssData` variant + a flat
// `FpssEvent` wrapper and the `buffered_event_to_typed` dispatcher.
// Consumers discriminate on `event.kind` and pull the matching optional
// payload field. Control / raw / simple events expose their diagnostic
// strings via `control`, `raw_data`, and `simple` payloads.

use napi::bindgen_prelude::BigInt;

/// FPSS OHLCVC bar. Mirrors `FpssData::Ohlcvc`.
#[napi(object)]
#[derive(Clone)]
pub struct Ohlcvc {
    pub contract_id: i32,
    pub ms_of_day: i32,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: BigInt,
    pub count: BigInt,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS OpenInterest tick. Mirrors `FpssData::OpenInterest`.
#[napi(object)]
#[derive(Clone)]
pub struct OpenInterest {
    pub contract_id: i32,
    pub ms_of_day: i32,
    pub open_interest: i32,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS Quote tick. Mirrors `FpssData::Quote` (symbol-less — `contract_id` is the stable key).
#[napi(object)]
#[derive(Clone)]
pub struct Quote {
    pub contract_id: i32,
    pub ms_of_day: i32,
    pub bid_size: i32,
    pub bid_exchange: i32,
    pub bid: f64,
    pub bid_condition: i32,
    pub ask_size: i32,
    pub ask_exchange: i32,
    pub ask: f64,
    pub ask_condition: i32,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS Trade tick. Mirrors `FpssData::Trade`.
#[napi(object)]
#[derive(Clone)]
pub struct Trade {
    pub contract_id: i32,
    pub ms_of_day: i32,
    pub sequence: i32,
    pub ext_condition1: i32,
    pub ext_condition2: i32,
    pub ext_condition3: i32,
    pub ext_condition4: i32,
    pub condition: i32,
    pub size: i32,
    pub exchange: i32,
    pub price: f64,
    pub condition_flags: i32,
    pub price_flags: i32,
    pub volume_type: i32,
    pub records_back: i32,
    pub date: i32,
    pub received_at_ns: BigInt,
}

/// FPSS control / diagnostic payload (login, disconnect, market open, ...).
#[napi(object)]
#[derive(Clone)]
pub struct FpssControlPayload {
    /// Concrete control event kind (e.g. "login_success", "disconnected").
    pub event_type: String,
    /// Free-form diagnostic detail; empty when the event carries no payload.
    pub detail: Option<String>,
    /// Optional event id (req_id for ReqResponse, contract id for ContractAssigned).
    pub id: Option<i32>,
}

/// FPSS raw-bytes payload for frames the decoder did not recognise.
#[napi(object)]
#[derive(Clone)]
pub struct FpssRawDataPayload {
    pub code: u32,
    pub payload: Vec<u8>,
}

/// A single FPSS event surfaced to JS/TS.
///
/// `kind` is the discriminator — switch on it and read the matching
/// payload field. The shape is stable and every payload is typed, so
/// consumers never fall back to untyped `any`.
#[napi(object)]
#[derive(Clone)]
pub struct FpssEvent {
    /// Discriminator matching one of the typed payload fields below.
    /// Narrowed to a literal union in TS so `switch (event.kind)`
    /// correctly narrows the optional payload fields.
    #[napi(ts_type = "'ohlcvc' | 'open_interest' | 'quote' | 'trade' | 'control' | 'raw_data'")]
    pub kind: String,
    pub ohlcvc: Option<Ohlcvc>,
    pub open_interest: Option<OpenInterest>,
    pub quote: Option<Quote>,
    pub trade: Option<Trade>,
    pub control: Option<FpssControlPayload>,
    pub raw_data: Option<FpssRawDataPayload>,
}

pub(crate) fn buffered_event_to_typed(event: BufferedEvent) -> FpssEvent {
    let mut out = FpssEvent {
        kind: String::new(),
        ohlcvc: None,
        open_interest: None,
        quote: None,
        trade: None,
        control: None,
        raw_data: None,
    };
    match event {
        BufferedEvent::Ohlcvc {
            contract_id,
            ms_of_day,
            open,
            high,
            low,
            close,
            volume,
            count,
            date,
            received_at_ns,
            ..
        } => {
            out.kind = "ohlcvc".to_string();
            out.ohlcvc = Some(Ohlcvc {
                contract_id: contract_id,
                ms_of_day: ms_of_day,
                open: open,
                high: high,
                low: low,
                close: close,
                volume: BigInt::from(volume),
                count: BigInt::from(count),
                date: date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::OpenInterest {
            contract_id,
            ms_of_day,
            open_interest,
            date,
            received_at_ns,
            ..
        } => {
            out.kind = "open_interest".to_string();
            out.open_interest = Some(OpenInterest {
                contract_id: contract_id,
                ms_of_day: ms_of_day,
                open_interest: open_interest,
                date: date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::Quote {
            contract_id,
            ms_of_day,
            bid_size,
            bid_exchange,
            bid,
            bid_condition,
            ask_size,
            ask_exchange,
            ask,
            ask_condition,
            date,
            received_at_ns,
            ..
        } => {
            out.kind = "quote".to_string();
            out.quote = Some(Quote {
                contract_id: contract_id,
                ms_of_day: ms_of_day,
                bid_size: bid_size,
                bid_exchange: bid_exchange,
                bid: bid,
                bid_condition: bid_condition,
                ask_size: ask_size,
                ask_exchange: ask_exchange,
                ask: ask,
                ask_condition: ask_condition,
                date: date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::Trade {
            contract_id,
            ms_of_day,
            sequence,
            ext_condition1,
            ext_condition2,
            ext_condition3,
            ext_condition4,
            condition,
            size,
            exchange,
            price,
            condition_flags,
            price_flags,
            volume_type,
            records_back,
            date,
            received_at_ns,
            ..
        } => {
            out.kind = "trade".to_string();
            out.trade = Some(Trade {
                contract_id: contract_id,
                ms_of_day: ms_of_day,
                sequence: sequence,
                ext_condition1: ext_condition1,
                ext_condition2: ext_condition2,
                ext_condition3: ext_condition3,
                ext_condition4: ext_condition4,
                condition: condition,
                size: size,
                exchange: exchange,
                price: price,
                condition_flags: condition_flags,
                price_flags: price_flags,
                volume_type: volume_type,
                records_back: records_back,
                date: date,
                received_at_ns: BigInt::from(received_at_ns),
            });
        }
        BufferedEvent::RawData { code, payload } => {
            out.kind = "raw_data".to_string();
            out.raw_data = Some(FpssRawDataPayload {
                code: code as u32,
                payload,
            });
        }
        BufferedEvent::Simple { event_type, detail, id } => {
            out.kind = "control".to_string();
            out.control = Some(FpssControlPayload {
                event_type,
                detail,
                id,
            });
        }
    }
    out
}
