// `await using session = await tdx.streaming(callback)` (TC39 explicit
// resource management) wrapper for the ThetaDataDxClient FPSS streaming
// lifecycle.
//
// On `[Symbol.asyncDispose]`, `stopStreaming()` is called and then the
// async drain barrier `awaitDrain(5000)` is awaited so the consumer
// thread is guaranteed to have finished firing the registered callback
// before the JS callback closure can be released. This mirrors the
// C++ RAII destructor in `sdks/cpp/src/thetadx.cpp`.
//
// SSOT: every public method on `ThetaDataDxClient` (subscribe_*,
// unsubscribe_*, activeSubscriptions, droppedEventCount, reconnect,
// ...) is reachable on the session via a `Proxy` `get` trap. There is
// NO hand-listed mirror of subscription methods here -- adding a new
// method to the napi-rs `ThetaDataDxClient` makes it callable through the
// session automatically, with zero drift surface.
//
// Loaded as the package's CommonJS entry point (`main` in
// `package.json`) so consumers get the wrapper when they
// `require('thetadatadx')`. The native loader in `index.js` is
// auto-generated by napi-rs and re-exported untouched.

'use strict';

const native = require('./index.js');

// ── Typed error hierarchy ─────────────────────────────────────────────
//
// The Rust napi binding (`to_napi_err` in `sdks/typescript/src/lib.rs`)
// surfaces every `thetadatadx::Error` as a `napi::Error` whose
// `reason` carries a `[ClassName] ...` prefix. The JS interceptor
// below parses that prefix and re-throws the matching subclass so
// callers can write `catch (e) { if (e instanceof tdx.SubscriptionError)
// { ... } }` rather than substring-matching the message.
//
// The canonical leaf set (`NotFoundError`, `DeadlineExceededError`,
// `UnavailableError`, `InvalidParameterError`, ...) is identical to the
// Python, C++, and C ABI leaf sets, so a `catch` clause ports across
// bindings by class name. Python additionally ships two back-compat
// aliases (`NoDataFoundError` / `TimeoutError`) that do not exist here.
//
// A rate limit carrying a server back-off hint widens the prefix to
// `[RateLimitError retry_after_ms=N] ...`; the interceptor parses the
// hint off and seats it as a `retryAfter` (seconds) property on the
// thrown `RateLimitError`.

class ThetaDataError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ThetaDataError';
  }
}
class AuthenticationError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'AuthenticationError';
  }
}
class InvalidCredentialsError extends AuthenticationError {
  constructor(message) {
    super(message);
    this.name = 'InvalidCredentialsError';
  }
}
class SubscriptionError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'SubscriptionError';
  }
}
class RateLimitError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'RateLimitError';
    // Server-supplied minimum back-off in seconds, parsed from the
    // upstream `google.rpc.RetryInfo` hint, or `null` when none was
    // supplied. Always present so callers can read it unconditionally.
    this.retryAfter = null;
  }
}
class InvalidParameterError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'InvalidParameterError';
  }
}
class NotFoundError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'NotFoundError';
  }
}
class DeadlineExceededError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'DeadlineExceededError';
  }
}
class UnavailableError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'UnavailableError';
  }
}
class NetworkError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'NetworkError';
  }
}
class SchemaMismatchError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'SchemaMismatchError';
  }
}
class StreamError extends ThetaDataError {
  constructor(message) {
    super(message);
    this.name = 'StreamError';
  }
}

const CLASS_BY_NAME = {
  ThetaDataError,
  AuthenticationError,
  InvalidCredentialsError,
  SubscriptionError,
  RateLimitError,
  InvalidParameterError,
  NotFoundError,
  DeadlineExceededError,
  UnavailableError,
  NetworkError,
  SchemaMismatchError,
  StreamError,
};

// `[ClassName] message` or `[ClassName retry_after_ms=N] message`. The
// optional `retry_after_ms` group carries the rate-limit back-off hint
// the Rust shim widens the prefix with; it is parsed off and surfaced
// as `retryAfter` (seconds) on the thrown `RateLimitError`.
const PREFIX_RE = /^\[([A-Za-z]+Error)(?:\s+retry_after_ms=(\d+))?\]\s*(.*)$/s;

/**
 * Re-cast a napi-thrown `Error` as the matching typed subclass when
 * the reason carries the `[ClassName] ...` prefix the Rust shim
 * emits. Anything that doesn't match the prefix surfaces unchanged
 * — preserves the existing `Error` shape for failures from the
 * generic napi machinery (e.g. argument coercion failures inside
 * the bindings).
 */
function rethrowTyped(err) {
  if (!(err instanceof Error) || typeof err.message !== 'string') {
    throw err;
  }
  const match = PREFIX_RE.exec(err.message);
  if (!match) {
    throw err;
  }
  const [, className, retryAfterMs, payload] = match;
  const Cls = CLASS_BY_NAME[className];
  if (!Cls) {
    throw err;
  }
  const typed = new Cls(payload);
  // Seat the rate-limit back-off (ms → seconds) when the prefix carried
  // a `retry_after_ms` hint, so callers can read `err.retryAfter`.
  if (retryAfterMs !== undefined && typed instanceof RateLimitError) {
    typed.retryAfter = Number(retryAfterMs) / 1000;
  }
  // Preserve the stack from the napi-thrown Error so the typed
  // re-throw still carries the original call site.
  typed.stack = err.stack;
  throw typed;
}

// Drain timeout applied on `[Symbol.asyncDispose]`. Matches the C++
// destructor's 5 s budget in `sdks/cpp/src/thetadx.cpp` and the FFI
// free-path budget in `ffi/src/streaming.rs::FREE_DRAIN_TIMEOUT`.
// Cross-binding parity matters more than tunability here -- a slow
// JS callback that needs more than 5 s to drain is already a contract
// violation worth surfacing.
const EXIT_DRAIN_TIMEOUT_MS = 5000;

// Wrapper-defined member names. Lookups for these resolve on the
// session itself; everything else proxies to the underlying
// `ThetaDataDxClient`. Symbol.asyncDispose is included so `await using`
// finds the wrapper's dispose, not anything on the native binding.
const WRAPPER_OWN = new Set(['_tdx', 'constructor']);

class StreamingSession {
  /**
   * Construct a session bound to a `ThetaDataDxClient` instance. Returns a
   * Proxy that forwards every unknown attribute access to the
   * underlying instance, so adding a `subscribe_X` method to the napi
   * binding makes it callable through the session with no drift.
   *
   * @param {InstanceType<typeof native.ThetaDataDxClient>} tdx
   * @returns {StreamingSession}
   */
  constructor(tdx) {
    this._tdx = tdx;
    return new Proxy(this, {
      get(target, prop, receiver) {
        // Wrapper-defined members (Symbol.asyncDispose, _tdx,
        // constructor) take precedence; everything else forwards to
        // the underlying ThetaDataDxClient instance.
        if (WRAPPER_OWN.has(prop) || prop === Symbol.asyncDispose) {
          return Reflect.get(target, prop, receiver);
        }
        if (prop in target && typeof target[prop] !== 'undefined') {
          // Methods explicitly defined on this class (none today
          // beyond the dispose symbol; future hand-written shortcuts
          // would land here).
          const own = Reflect.get(target, prop, receiver);
          if (typeof own === 'function') {
            return own.bind(target);
          }
          return own;
        }
        const tdx = target._tdx;
        const value = tdx[prop];
        // Bind methods to the underlying instance so `this` resolves
        // correctly when the caller invokes them.
        return typeof value === 'function' ? value.bind(tdx) : value;
      },
      has(target, prop) {
        if (WRAPPER_OWN.has(prop) || prop === Symbol.asyncDispose) return true;
        return prop in target._tdx;
      },
    });
  }

  /**
   * TC39 explicit resource management: invoked by `await using session
   * = ...` on scope exit. Stops the streaming connection and awaits
   * the drain barrier so the consumer thread is guaranteed to have
   * finished firing the registered callback before the JS closure can
   * be released. Mirrors the C++ RAII destructor.
   *
   * Drain timeout failures fire `console.warn` rather than throwing;
   * the streaming pipeline is already torn down (`stopStreaming` ran),
   * and the drain barrier is best-effort observability. Throwing here
   * would mask any error from the `using` block body.
   *
   * @returns {Promise<void>}
   */
  async [Symbol.asyncDispose]() {
    this._tdx.stopStreaming();
    const drained = await this._tdx.awaitDrain(EXIT_DRAIN_TIMEOUT_MS);
    if (!drained) {
      console.warn(
        `ThetaDataDxClient streaming drain timed out after ${EXIT_DRAIN_TIMEOUT_MS}ms; ` +
          'consumer callback may still be firing. The JS callback closure ' +
          'will remain referenced until the consumer exits.',
      );
    }
  }
}

// Monkey-patch `streaming(callback)` onto the napi-generated
// `ThetaDataDxClient` class. Returning a `Promise<StreamingSession>` matches
// the spec example (`await using session = await tdx.streaming(cb)`)
// and leaves room for an async startup path in the future without an
// API break.
if (
  native.ThetaDataDxClient &&
  typeof native.ThetaDataDxClient.prototype.streaming !== 'function'
) {
  native.ThetaDataDxClient.prototype.streaming = async function streaming(callback) {
    this.startStreaming(callback);
    return new StreamingSession(this);
  };
}


// Re-export the entire native surface plus the StreamingSession class.
// `Object.assign` rather than spread so non-enumerable properties on
// the napi binding survive.
//
// `Contract` aliases `ContractRef` — napi-rs exposes the fluent
// contract type under the `ContractRef` symbol because `Contract`
// already names the FPSS event-payload data class. The public-facing
// surface documented in the quickstart is `Contract.stock("AAPL")` /
// `Contract.option(...)`, so the alias makes the JS export agree with
// the docs without a second pyclass.
// Patch every method on the native binding's exported classes so
// rejections / throws get re-cast through the typed error hierarchy.
// The shim parses the `[ClassName] ...` prefix the Rust shim emits;
// errors without the prefix surface unchanged.
function wrapMethodsWithTypedErrors(klass) {
  if (!klass || !klass.prototype) return;
  for (const name of Object.getOwnPropertyNames(klass.prototype)) {
    if (name === 'constructor') continue;
    const desc = Object.getOwnPropertyDescriptor(klass.prototype, name);
    if (!desc || typeof desc.value !== 'function') continue;
    const original = desc.value;
    klass.prototype[name] = function patchedNapiMethod(...args) {
      let result;
      try {
        result = original.apply(this, args);
      } catch (err) {
        rethrowTyped(err);
      }
      // napi-rs async methods return a Promise; intercept the
      // rejection without altering the resolved value.
      if (result && typeof result.then === 'function') {
        return result.then(
          (value) => value,
          (err) => rethrowTyped(err),
        );
      }
      return result;
    };
  }
}

for (const klassName of [
  'ThetaDataDxClient',
  'FlatFileRowList',
]) {
  const klass = native[klassName];
  if (klass) wrapMethodsWithTypedErrors(klass);
}

module.exports = Object.assign({}, native, {
  StreamingSession,
  Contract: native.ContractRef,
  ThetaDataError,
  AuthenticationError,
  InvalidCredentialsError,
  SubscriptionError,
  RateLimitError,
  InvalidParameterError,
  NotFoundError,
  DeadlineExceededError,
  UnavailableError,
  NetworkError,
  SchemaMismatchError,
  StreamError,
});
