// @generated DO NOT EDIT — regenerated by build.rs from sdk_surface.toml

fn push_generated_utility_tool_definitions(tools: &mut Vec<Value>) {
    tools.push(json!({
        "name": "ping",
        "description": "Check MCP server status. Returns uptime and connection info without hitting ThetaData servers.",
        "inputSchema": {
            "type": "object",
            "properties": {
            },
            "required": []
        }
    }));
}

async fn try_execute_generated_utility(
    client: Option<&Client>,
    name: &str,
    _args: &Value,
    start_time: std::time::Instant,
) -> Option<Result<Value, ToolError>> {
    match name {
        "ping" => {
            let uptime = start_time.elapsed();
            Some(Ok(json!({
                "status": "ok",
                "server": "thetadatadx-mcp-server",
                "version": VERSION,
                "uptime_secs": uptime.as_secs(),
                "connected": client.is_some(),
            })))
        }
        _ => None,
    }
}
