//! Emitters that write generated Rust artifacts into `OUT_DIR` at build time.
//!
//! These feed the crate's `include!()` sites for the endpoint registry, the
//! shared endpoint dispatch runtime, and the three per-kind MDDS
//! [`MddsClient`] extension impls (list, parsed, streaming), consumed by
//! `crates/thetadatadx/src/mdds/endpoints.rs`. The [`generate_all`] entry
//! point is wired from `build_support::run()`.

use std::fmt::Write as _;
use std::path::Path;

use super::super::helpers::{
    call_arg_name, is_method_call_param, is_simple_list_endpoint, is_streaming_endpoint,
    optional_getter_name, required_getter_name,
};
use super::super::model::{GeneratedEndpoint, GeneratedParam, ParsedEndpoints};
use super::super::parser::load_endpoint_specs;
use super::mdds::{
    generate_mdds_list_endpoint, generate_mdds_parsed_endpoint, generate_mdds_streaming_endpoint,
};

pub fn generate_all() -> Result<(), Box<dyn std::error::Error>> {
    let parsed = load_endpoint_specs()?;
    generate_endpoint_registry(&parsed)?;
    generate_endpoint_runtime(&parsed)?;
    generate_mdds_endpoints(&parsed)?;
    println!("cargo:rerun-if-changed=endpoint_surface.toml");
    println!("cargo:rerun-if-changed=proto/mdds.proto");
    // Validator body templates consumed via `include_str!` by the
    // `render_*_validate` emitters. `include_str!` already registers these
    // as compilation-time dependencies, but we also emit rerun-if-changed
    // so `cargo build` re-triggers the generator when a template is
    // edited.
    for template in VALIDATOR_TEMPLATES {
        println!("cargo:rerun-if-changed=build_support/endpoints/render/templates/{template}");
    }
    Ok(())
}

const VALIDATOR_TEMPLATES: &[&str] = &[
    "validate_python/preamble.py.tmpl",
    "validate_python/cell.py.tmpl",
    "validate_python/postamble.py.tmpl",
    "validate_cli/preamble.py.tmpl",
    "validate_cli/cell.py.tmpl",
    "validate_cli/postamble.py.tmpl",
    "validate_go/preamble.go.tmpl",
    "validate_go/cell.go.tmpl",
    "validate_go/postamble.go.tmpl",
    "validate_cpp/preamble.cpp.tmpl",
    "validate_cpp/cell.cpp.tmpl",
    "validate_cpp/postamble.cpp.tmpl",
    // Emitter body templates (W8).
    "go/with_timeout_ms.go.tmpl",
    "go/with_deadline.go.tmpl",
    "go/int_case.go.tmpl",
    "go/float_case.go.tmpl",
    "go/bool_case.go.tmpl",
    "go/string_case.go.tmpl",
    "cpp/with_timeout_ms.cpp.tmpl",
    "cpp/with_deadline.cpp.tmpl",
    "cpp/option_contracts_convert.cpp.tmpl",
    "cpp/ffi_numeric_case.cpp.tmpl",
    "cpp/ffi_bool_case.cpp.tmpl",
    "cpp/ffi_string_case.cpp.tmpl",
    "python/string_list_dispatch.py.tmpl",
    "python/streaming_dispatch.py.tmpl",
    "ffi/symbols_extract.rs.tmpl",
    "ffi/cstr_extract.rs.tmpl",
    "mdds/stream_method_header.rs.tmpl",
    "mdds/stub_call_error_arm.rs.tmpl",
    "mdds/for_each_chunk_body.rs.tmpl",
    "mdds/metrics_result_block.rs.tmpl",
    // Emitter body templates added in the externalization pass.
    "cpp/endpoint_options_header.cpp.tmpl",
    "ffi/endpoint_options_header.rs.tmpl",
    "build_out/invoke_generated_endpoint_preamble.rs.tmpl",
];

fn generate_endpoint_registry(parsed: &ParsedEndpoints) -> Result<(), Box<dyn std::error::Error>> {
    // ── Generate Rust code ──────────────────────────────────────────────────
    let mut code = String::new();
    code.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    code.push_str("// (validated against proto/mdds.proto)\n\n");
    code.push_str("pub static ENDPOINTS: &[EndpointMeta] = &[\n");

    for endpoint in &parsed.endpoints {
        // Streaming endpoints use chunk-by-chunk callback semantics and are not
        // part of the collect-then-return registry.
        if is_streaming_endpoint(endpoint) {
            continue;
        }
        code.push_str("    EndpointMeta {\n");
        writeln!(code, "        name: \"{}\",", endpoint.name).unwrap();
        writeln!(code, "        description: \"{}\",", endpoint.description).unwrap();
        writeln!(code, "        category: \"{}\",", endpoint.category).unwrap();
        writeln!(code, "        subcategory: \"{}\",", endpoint.subcategory).unwrap();
        writeln!(code, "        rest_path: \"{}\",", endpoint.rest_path).unwrap();

        if endpoint.params.is_empty() {
            code.push_str("        params: &[],\n");
        } else {
            code.push_str("        params: &[\n");
            for param in &endpoint.params {
                code.push_str("            ParamMeta {\n");
                writeln!(code, "                name: \"{}\",", param.name).unwrap();
                writeln!(
                    code,
                    "                description: \"{}\",",
                    param.description
                )
                .unwrap();
                writeln!(
                    code,
                    "                param_type: ParamType::{},",
                    param.param_type
                )
                .unwrap();
                writeln!(code, "                required: {},", param.required).unwrap();
                code.push_str("            },\n");
            }
            code.push_str("        ],\n");
        }

        writeln!(
            code,
            "        returns: ReturnType::{},",
            endpoint.return_type
        )
        .unwrap();
        code.push_str("    },\n");
    }

    code.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("registry_generated.rs");
    std::fs::write(&dest, &code)?;

    Ok(())
}

fn generate_endpoint_runtime(parsed: &ParsedEndpoints) -> Result<(), Box<dyn std::error::Error>> {
    let mut code = String::new();
    code.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    code.push_str("// (validated against proto/mdds.proto)\n\n");
    code.push_str(include_str!(
        "templates/build_out/invoke_generated_endpoint_preamble.rs.tmpl"
    ));

    for endpoint in &parsed.endpoints {
        generate_endpoint_dispatch_arm(&mut code, endpoint);
    }

    code.push_str("        _ => Err(EndpointError::UnknownEndpoint(name.to_string())),\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("endpoint_generated.rs");
    std::fs::write(&dest, &code)?;

    Ok(())
}

fn generate_mdds_endpoints(parsed: &ParsedEndpoints) -> Result<(), Box<dyn std::error::Error>> {
    let mut list_code = String::new();
    let mut parsed_code = String::new();
    let mut stream_code = String::new();
    let header =
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n// (validated against proto/mdds.proto)\n\n";
    list_code.push_str(header);
    list_code.push_str("impl MddsClient {\n");
    parsed_code.push_str(header);
    stream_code.push_str(header);

    for endpoint in &parsed.endpoints {
        if is_simple_list_endpoint(endpoint) {
            generate_mdds_list_endpoint(&mut list_code, endpoint);
        } else if is_streaming_endpoint(endpoint) {
            generate_mdds_streaming_endpoint(&mut stream_code, endpoint);
        } else {
            generate_mdds_parsed_endpoint(&mut parsed_code, endpoint);
        }
    }

    let out_dir = std::env::var("OUT_DIR")?;
    std::fs::write(
        Path::new(&out_dir).join("mdds_list_endpoints_generated.rs"),
        format!("{list_code}}}\n"),
    )?;
    std::fs::write(
        Path::new(&out_dir).join("mdds_parsed_endpoints_generated.rs"),
        &parsed_code,
    )?;
    std::fs::write(
        Path::new(&out_dir).join("mdds_streaming_endpoints_generated.rs"),
        &stream_code,
    )?;

    Ok(())
}

fn generate_endpoint_dispatch_arm(out: &mut String, endpoint: &GeneratedEndpoint) {
    writeln!(out, "        \"{}\" => {{", endpoint.name).unwrap();

    if is_simple_list_endpoint(endpoint) {
        for param in &endpoint.params {
            emit_required_arg(out, endpoint, param);
        }
        let args = endpoint
            .params
            .iter()
            .map(call_arg_name)
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(
            out,
            "            let values = client.{}({args}).await?;",
            endpoint.name
        )
        .unwrap();
        writeln!(
            out,
            "            Ok(EndpointOutput::{}(values))",
            endpoint.return_type
        )
        .unwrap();
        out.push_str("        }\n");
        return;
    }

    let method_call_params = endpoint
        .params
        .iter()
        .filter(|param| is_method_call_param(param))
        .collect::<Vec<_>>();
    let builder_params = endpoint
        .params
        .iter()
        .filter(|param| !is_method_call_param(param))
        .collect::<Vec<_>>();

    for param in &method_call_params {
        emit_required_arg(out, endpoint, param);
    }

    let call_args = method_call_params
        .into_iter()
        .map(call_arg_name)
        .collect::<Vec<_>>()
        .join(", ");

    if is_streaming_endpoint(endpoint) {
        writeln!(
            out,
            "            let mut builder = client.{}({call_args});",
            endpoint.name
        )
        .unwrap();

        for param in builder_params {
            let getter = optional_getter_name(&param.param_type);
            writeln!(
                out,
                "            if let Some(value) = args.{getter}(\"{}\")? {{",
                param.name
            )
            .unwrap();
            writeln!(
                out,
                "                builder = builder.{}(value);",
                param.name
            )
            .unwrap();
            out.push_str("            }\n");
        }

        out.push_str("            let mut result = Vec::new();\n");
        out.push_str("            builder\n");
        out.push_str("                .stream(|chunk| result.extend_from_slice(chunk))\n");
        out.push_str("                .await?;\n");
        writeln!(
            out,
            "            Ok(EndpointOutput::{}(result))",
            endpoint.return_type
        )
        .unwrap();
        out.push_str("        }\n");
        return;
    }

    if builder_params.is_empty() {
        writeln!(
            out,
            "            let result = client.{}({call_args}).await?;",
            endpoint.name
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "            let mut builder = client.{}({call_args});",
            endpoint.name
        )
        .unwrap();

        for param in builder_params {
            let getter = optional_getter_name(&param.param_type);
            writeln!(
                out,
                "            if let Some(value) = args.{getter}(\"{}\")? {{",
                param.name
            )
            .unwrap();
            writeln!(
                out,
                "                builder = builder.{}(value);",
                param.name
            )
            .unwrap();
            out.push_str("            }\n");
        }

        out.push_str("            let result = builder.await?;\n");
    }
    writeln!(
        out,
        "            Ok(EndpointOutput::{}(result))",
        endpoint.return_type
    )
    .unwrap();
    out.push_str("        }\n");
}

fn emit_required_arg(out: &mut String, _endpoint: &GeneratedEndpoint, param: &GeneratedParam) {
    if param.param_type == "Symbols" {
        writeln!(
            out,
            "            let symbol_values = args.required_symbols(\"{}\")?;",
            param.name
        )
        .unwrap();
        out.push_str(
            "            let symbol_refs: Vec<&str> = symbol_values.iter().map(String::as_str).collect();\n",
        );
        return;
    }

    let getter = required_getter_name(&param.param_type);
    writeln!(
        out,
        "            let {} = args.{getter}(\"{}\")?;",
        param.name, param.name
    )
    .unwrap();
}
