//! Python SDK #[pymethods] emitter.
//!
//! Renders `sdks/python/src/historical_methods.rs` — the `ThetaDataDx` impl
//! block that PyO3 compiles into the Python extension.

use std::fmt::Write as _;

use super::super::helpers::{
    builder_params, is_streaming_endpoint, method_params, python_columnar_converter,
    python_method_arg_decl, python_optional_type, sdk_method_arg_name,
};
use super::super::model::GeneratedEndpoint;

pub(super) fn render_python_historical_methods(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT \u{2014} regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    out.push_str("#[pymethods]\n");
    out.push_str("impl ThetaDataDx {\n");
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_python_endpoint_method(endpoint));
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

fn render_python_endpoint_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let mut out = String::new();

    writeln!(out, "    /// {}", endpoint.description).unwrap();
    if !builder_params.is_empty() {
        let mut signature_parts = method_params
            .iter()
            .map(|param| sdk_method_arg_name(param))
            .collect::<Vec<_>>();
        signature_parts.push("*".into());
        signature_parts.extend(
            builder_params
                .iter()
                .map(|param| format!("{}=None", param.name)),
        );
        writeln!(
            out,
            "    #[pyo3(signature = ({}))]",
            signature_parts.join(", ")
        )
        .unwrap();
    }

    writeln!(out, "    fn {}(", endpoint.name).unwrap();
    out.push_str("        &self,\n");
    out.push_str("        py: Python<'_>,\n");
    for param in &method_params {
        writeln!(out, "        {},", python_method_arg_decl(param)).unwrap();
    }
    for param in &builder_params {
        writeln!(
            out,
            "        {}: {},",
            param.name,
            python_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("    ) -> PyResult<");
    if endpoint.return_type == "StringList" {
        out.push_str("Vec<String>> {\n");
    } else {
        out.push_str("Py<PyAny>> {\n");
    }

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str(
            "        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }

    out.push_str("        ");
    if endpoint.return_type == "StringList" {
        out.push_str("py.detach(|| {\n");
    } else {
        out.push_str("let ticks = py.detach(|| {\n");
    }
    if builder_params.is_empty() {
        out.push_str("            runtime()\n");
        out.push_str("                .block_on(async {\n");
        write!(out, "                    self.tdx.{}(", endpoint.name).unwrap();
        out.push_str(
            &method_params
                .iter()
                .map(|param| {
                    if param.param_type == "Symbols" {
                        "&refs".into()
                    } else {
                        sdk_method_arg_name(param)
                    }
                })
                .collect::<Vec<_>>()
                .join(", "),
        );
        out.push_str(").await\n");
        out.push_str("                })\n");
        out.push_str("                .map_err(to_py_err)\n");
    } else {
        write!(
            out,
            "            let mut request = self.tdx.{}(",
            endpoint.name
        )
        .unwrap();
        out.push_str(
            &method_params
                .iter()
                .map(|param| {
                    if param.param_type == "Symbols" {
                        "&refs".into()
                    } else {
                        sdk_method_arg_name(param)
                    }
                })
                .collect::<Vec<_>>()
                .join(", "),
        );
        out.push_str(");\n");
        for param in &builder_params {
            writeln!(out, "            if let Some(value) = {} {{", param.name).unwrap();
            writeln!(
                out,
                "                request = request.{}(value);",
                param.name
            )
            .unwrap();
            out.push_str("            }\n");
        }
        if endpoint.kind == "stream" {
            out.push_str("            let mut collected = Vec::new();\n");
            out.push_str("            runtime()\n");
            out.push_str(
                "                .block_on(request.stream(|chunk| collected.extend_from_slice(chunk)))\n",
            );
            out.push_str("                .map_err(to_py_err)?;\n");
            out.push_str("            pyo3::PyResult::Ok(collected)\n");
        } else {
            out.push_str("            runtime()\n");
            out.push_str("                .block_on(async { request.await })\n");
            out.push_str("                .map_err(to_py_err)\n");
        }
    }
    if endpoint.return_type == "StringList" {
        out.push_str("        })\n");
        out.push_str("    }\n");
        return out;
    }

    out.push_str("        })?;\n");
    writeln!(
        out,
        "        Ok({}(py, &ticks))",
        python_columnar_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n");
    out
}
