//! Python SDK `#[pymethods]` emitter.
//!
//! Renders `sdks/python/src/historical_methods.rs` — the `ThetaDataDx` impl
//! block that PyO3 compiles into the Python extension.
//!
//! Every method takes a `timeout_ms: Optional[int]` kwarg. When set the
//! call is given a deadline; on expiry a `RuntimeError` carrying the
//! `Error::Timeout` message is raised and the underlying gRPC stream is
//! cancelled. The `ThetaDataDx` handle remains usable for subsequent calls.
//!
//! # Three variants per endpoint (sync / async / fluent builder)
//!
//! The v8.0.2 Python-UX surface exposes every historical endpoint in three
//! forms without duplicating the spec:
//!
//! 1. **Sync `fn name(...)`** — original blocking signature; every kwarg is
//!    an `Option<T>`. Runs on the shared `runtime()` singleton (`OnceLock<
//!    tokio::runtime::Runtime>`) through `run_blocking` so Ctrl+C is
//!    honoured during long calls.
//! 2. **Async `fn name_async(...)`** — returns `Bound<'py, PyAny>` backed by
//!    `pyo3_async_runtimes::tokio::future_into_py`. Shares the same runtime
//!    singleton; no second runtime is created per call.
//! 3. **Fluent builder `fn name_builder(...)`** — returns a per-endpoint
//!    `#[pyclass]` whose chainable setters mirror the builder on the Rust
//!    side. Single terminal: `.list()` (and its `_async` companion),
//!    returning a typed list wrapper (`<TickName>List` / `StringList`).
//!    DataFrame terminals (`to_polars`, `to_arrow`, `to_pandas`,
//!    `to_list`) live on the wrapper, so builder users write
//!    `tdx.stock_history_eod_builder(...).list().to_polars()` instead
//!    of four parallel terminal methods.
//!
//! Every docstring in the three variants is produced by `compose_endpoint_doc`
//! + `render_rust_doc_block`, sourcing from `endpoint.description`
//! + `endpoint.vendor_docstring` in `endpoint_surface.toml` — single SSOT for
//!   all three variants so the sync / async / builder docs cannot drift.

use std::fmt::Write as _;

use super::super::helpers::{
    builder_params, compose_endpoint_doc, direct_parser_name, is_snapshot_endpoint,
    is_streaming_endpoint, method_params, python_method_arg_decl, python_optional_type,
    python_pyclass_list_class, python_pyclass_list_converter, python_slice_arrow_converter,
    python_vec_to_pylist_converter, render_rust_doc_block, sdk_method_arg_name, to_pascal_case,
};
use super::super::model::{GeneratedEndpoint, GeneratedParam};

/// Emit `sdks/python/src/decode_bench.rs` — the offline decode hook.
///
/// Exposes `decode_response_bytes(py, endpoint, chunks) -> list[TickClass]`
/// so Python benchmarks can feed recorded gRPC response bytes into the
/// Rust decoder without an MDDS round-trip. The dispatch arms are driven
/// by `endpoint_surface.toml`: every endpoint that today has a typed
/// decoder (i.e. `returns != "StringList"` and not a streaming endpoint)
/// gets a `match` arm automatically, so adding a new endpoint to the
/// TOML requires zero edits to this file.
pub(super) fn render_python_decode_bench(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    out.push_str("//\n");
    out.push_str("// Offline-decode hook used by the external parity bench harness:\n");
    out.push_str("// feed a recorded `Vec<&[u8]>` of `proto::ResponseData` chunks (one\n");
    out.push_str("// per on-the-wire gRPC frame) and receive the same typed pyclass\n");
    out.push_str("// list the corresponding endpoint would have returned. Separates\n");
    out.push_str("// DX decode cost from end-to-end wall time so benchmarks can\n");
    out.push_str("// attribute CPU to the parts of the stack they actually exercise.\n\n");

    // Imports are deliberately minimal: this file is `include!()`-d
    // into `sdks/python/src/lib.rs`, so every PyO3 / pyo3::exceptions
    // / thetadatadx prelude symbol is already in scope at that seam.
    // Reaching for fully-qualified paths (`thetadatadx::decode::…`,
    // `pyo3::exceptions::PyValueError`) keeps the generator's output
    // free of use-statement collisions at the include site.

    // Helper: decode a chunk stream into a merged DataTable. Shared
    // across every dispatch arm.
    out.push_str(include_str!(
        "templates/python/decode_response_bytes_helper.rs.tmpl"
    ));

    // The pyfunction itself.
    out.push_str("/// Decode recorded gRPC response bytes into the same typed pyclass list\n");
    out.push_str("/// the matching `ThetaDataDx` endpoint would have returned.\n");
    out.push_str("///\n");
    out.push_str("/// `endpoint` must match an endpoint name from `endpoint_surface.toml` that\n");
    out.push_str(
        "/// exposes a typed decoder (every entry whose `returns` is not `StringList`).\n",
    );
    out.push_str(
        "/// `chunks` is the recorded byte list — one prost-encoded `proto::ResponseData`\n",
    );
    out.push_str("/// per entry, same frame boundaries tonic hands out of `Streaming::next()`.\n");
    out.push_str("///\n");
    out.push_str("/// Unknown `endpoint` values return [`PyValueError`] — the caller is\n");
    out.push_str("/// expected to stage the right fixture for the right endpoint.\n");
    out.push_str("#[pyfunction]\n");
    out.push_str("#[pyo3(signature = (endpoint, chunks))]\n");
    out.push_str(
        "pub(crate) fn decode_response_bytes(py: Python<'_>, endpoint: &str, chunks: Vec<Vec<u8>>) -> PyResult<Py<PyAny>> {\n",
    );
    out.push_str("    let refs: Vec<&[u8]> = chunks.iter().map(Vec::as_slice).collect();\n");
    out.push_str("    match endpoint {\n");

    // Dispatch arms. Skip streaming endpoints (they don't collect into
    // a single DataTable) and StringList endpoints (those return
    // `Vec<String>`, not a tick list — trivial decode, not worth a
    // bench arm).
    let mut bench_endpoints: Vec<&GeneratedEndpoint> = endpoints
        .iter()
        .filter(|e| !is_streaming_endpoint(e))
        .filter(|e| e.return_type != "StringList")
        .collect();
    bench_endpoints.sort_by(|a, b| a.name.cmp(&b.name));

    for endpoint in bench_endpoints {
        // `direct_parser_name` returns `decode::parse_xxx_ticks`; prefix
        // with `thetadatadx::` so the generator output works from the
        // Python SDK crate (which depends on `thetadatadx` but does not
        // `use` the module at top level — see the include-site comment).
        let parser = direct_parser_name(&endpoint.return_type)
            .strip_prefix("decode::")
            .map(|rest| format!("thetadatadx::decode::{rest}"))
            .unwrap_or_else(|| {
                panic!(
                    "direct_parser_name '{}' must start with 'decode::'",
                    direct_parser_name(&endpoint.return_type)
                )
            });
        let pyclass_fn = python_pyclass_list_converter(&endpoint.return_type);
        writeln!(out, "        \"{name}\" => {{", name = endpoint.name).unwrap();
        writeln!(
            out,
            "            let table = decode_chunks_into_table(&refs)?;"
        )
        .unwrap();
        writeln!(
            out,
            "            let ticks = {parser}(&table).map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(e.to_string()))?;"
        )
        .unwrap();
        // `*_to_pyclass_list` now returns `Py<<TickName>List>`; the public
        // parity-bench hook keeps its `Py<PyAny>` signature, so erase the
        // concrete class on the way out.
        writeln!(out, "            Ok({pyclass_fn}(py, ticks)?.into_any())").unwrap();
        out.push_str("        }\n");
    }

    out.push_str("        other => Err(PyValueError::new_err(format!(\n");
    out.push_str(
        "            \"decode_response_bytes: unknown endpoint `{other}` — extend endpoint_surface.toml and regen `cargo run --bin generate_sdk_surfaces`\"\n",
    );
    out.push_str("        ))),\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

pub(super) fn render_python_historical_methods(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );

    // Per-endpoint fluent builder pyclasses. Emitted BEFORE the `ThetaDataDx`
    // impl block so `add_class::<HistoricalBuilder>()` at module-init time sees
    // the types. One struct per endpoint; each has chained setters for the
    // optional params, required params captured at construction time, and
    // a single terminal `.list()` (+ `.list_async()`) that returns the
    // typed list wrapper. DataFrame terminals (`to_polars`, `to_arrow`,
    // `to_pandas`, `to_list`) live on the wrapper itself.
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_python_endpoint_builder(endpoint));
        out.push('\n');
    }

    // Module-init registrar for the generated builders. Called from
    // `lib.rs::thetadatadx_py` so every builder class lands in the
    // `thetadatadx` Python namespace.
    out.push_str(
        "fn register_generated_historical_builders(m: &Bound<'_, PyModule>) -> PyResult<()> {\n",
    );
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        writeln!(
            out,
            "    m.add_class::<{}>()?;",
            endpoint_builder_struct(&endpoint.name)
        )
        .unwrap();
    }
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    out.push_str("#[pymethods]\n");
    out.push_str("impl ThetaDataDx {\n");
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        // Sync — preserves the pre-v8.0.2 signature byte-for-byte.
        out.push_str(&render_python_endpoint_sync(endpoint));
        out.push('\n');
        // Async — awaitable via pyo3-async-runtimes.
        out.push_str(&render_python_endpoint_async(endpoint));
        out.push('\n');
        // Fluent builder constructor.
        out.push_str(&render_python_builder_constructor(endpoint));
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

// ───────────────────────── Sync (pre-v8.0.2 signature) ─────────────────────

fn render_python_endpoint_sync(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let is_streaming_kind = endpoint.kind == "stream";
    let is_snapshot = is_snapshot_endpoint(endpoint);
    let mut out = String::new();

    let doc = compose_endpoint_doc(endpoint);
    out.push_str(&render_rust_doc_block("    ", &doc));

    let mut signature_parts = method_params
        .iter()
        .map(|param| sdk_method_arg_name(param))
        .collect::<Vec<_>>();
    signature_parts.push("*".into());
    signature_parts.extend(
        builder_params
            .iter()
            .map(|param| format!("{}=None", param.name)),
    );
    signature_parts.push("timeout_ms=None".into());
    writeln!(
        out,
        "    #[pyo3(signature = ({}))]",
        signature_parts.join(", ")
    )
    .unwrap();

    writeln!(out, "    fn {}(", endpoint.name).unwrap();
    out.push_str("        &self,\n");
    out.push_str("        py: Python<'_>,\n");
    for param in &method_params {
        writeln!(out, "        {},", python_method_arg_decl(param)).unwrap();
    }
    for param in &builder_params {
        writeln!(
            out,
            "        {}: {},",
            param.name,
            python_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("        timeout_ms: Option<u64>,\n");
    out.push_str("    ) -> PyResult<");
    if is_string_list {
        // Chained return: `endpoint(...).to_polars()` — `StringList`
        // carries both the `Vec<String>` payload and the DataFrame
        // column name pulled from `endpoint_surface.toml::list_column`.
        out.push_str("Py<StringList>> {\n");
    } else if is_snapshot {
        // Snapshot fast-path: return a plain `Py<PyList>` of typed
        // pyclass rows. Snapshots are ≤ 10 small rows; callers never
        // chain `.to_polars()` on a 1-row calendar result, so we skip
        // the `<TickName>List` wrapper allocation to close the latency
        // gap on <100 ms calls.
        out.push_str("Py<pyo3::types::PyList>> {\n");
    } else {
        // Chained return: `endpoint(...).to_polars()` — typed list
        // wrapper per tick type, holds the decoder-owned `Vec<tick::T>`
        // and exposes `.to_list()` / `.to_arrow()` / `.to_pandas()` /
        // `.to_polars()` terminals.
        writeln!(
            out,
            "Py<{}>> {{",
            python_pyclass_list_class(&endpoint.return_type)
        )
        .unwrap();
    }

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str(
            "        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }

    if is_string_list {
        let positional_args = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "&refs".into()
                } else {
                    sdk_method_arg_name(param)
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        let leading_comma_args = if positional_args.is_empty() {
            String::new()
        } else {
            format!(", {positional_args}")
        };
        let column = endpoint
            .list_column
            .as_deref()
            .expect("list endpoint must declare list_column");
        let _ = leading_comma_args;
        out.push_str("        let values: Vec<String> = run_blocking(py, async move {\n");
        writeln!(
            out,
            "            let call = self.tdx.{}({});",
            endpoint.name, positional_args
        )
        .unwrap();
        out.push_str("            if let Some(ms) = timeout_ms {\n");
        out.push_str("                match tokio::time::timeout(std::time::Duration::from_millis(ms), call).await {\n");
        out.push_str("                    Ok(inner) => inner,\n");
        out.push_str(
            "                    Err(_) => Err(thetadatadx::Error::Timeout { duration_ms: ms }),\n",
        );
        out.push_str("                }\n");
        out.push_str("            } else {\n");
        out.push_str("                call.await\n");
        out.push_str("            }\n");
        out.push_str("        })?;\n");
        writeln!(
            out,
            "        strings_to_string_list(py, values, \"{column}\")"
        )
        .unwrap();
        out.push_str("    }\n");
        return out;
    }

    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                sdk_method_arg_name(param)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "        let mut request = self.tdx.{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "        if let Some(value) = {} {{", param.name).unwrap();
        writeln!(out, "            request = request.{}(value);", param.name).unwrap();
        out.push_str("        }\n");
    }
    out.push_str("        if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "            request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("        }\n");
    if is_streaming_kind {
        out.push_str(include_str!("templates/python/streaming_dispatch.py.tmpl"));
        writeln!(
            out,
            "        {}(py, ticks)",
            python_pyclass_list_converter(&endpoint.return_type)
        )
        .unwrap();
        out.push_str("    }\n");
        return out;
    }
    if is_snapshot {
        // Snapshot fast-path: bounded-timeout future on the shared
        // runtime, no signal-check polling ticker. Materialises a plain
        // `Py<PyList>` of typed pyclass rows directly — no `<T>List`
        // wrapper. See `run_blocking_snapshot` in `sdks/python/src/lib.rs`
        // for the +1-5 ms first-tick-jitter elimination rationale.
        out.push_str(
            "        let ticks = run_blocking_snapshot(py, async move { request.await })?;\n",
        );
        writeln!(
            out,
            "        {}(py, ticks)",
            python_vec_to_pylist_converter(&endpoint.return_type)
        )
        .unwrap();
        out.push_str("    }\n");
        return out;
    }
    out.push_str("        let ticks = run_blocking(py, async move { request.await })?;\n");
    writeln!(
        out,
        "        {}(py, ticks)",
        python_pyclass_list_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n");
    out
}

// ───────────────────────── Async variant (`_async` suffix) ─────────────────

fn render_python_endpoint_async(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let is_streaming_kind = endpoint.kind == "stream";
    let is_snapshot = is_snapshot_endpoint(endpoint);
    let mut out = String::new();

    // Same composed doc as sync — readers of `name_async` see the same
    // vendor notes as readers of `name`. No drift.
    let mut doc = compose_endpoint_doc(endpoint);
    doc.push_str(
        "\n\nAsync companion — returns an awaitable (`asyncio.Future`).\n\
         Shares the same shared tokio runtime as the sync variant; no\n\
         second runtime is created per call.",
    );
    out.push_str(&render_rust_doc_block("    ", &doc));

    let mut signature_parts = method_params
        .iter()
        .map(|param| sdk_method_arg_name(param))
        .collect::<Vec<_>>();
    signature_parts.push("*".into());
    signature_parts.extend(
        builder_params
            .iter()
            .map(|param| format!("{}=None", param.name)),
    );
    signature_parts.push("timeout_ms=None".into());
    writeln!(
        out,
        "    #[pyo3(signature = ({}))]",
        signature_parts.join(", ")
    )
    .unwrap();

    writeln!(out, "    fn {}_async<'py>(", endpoint.name).unwrap();
    out.push_str("        &self,\n");
    out.push_str("        py: Python<'py>,\n");
    // Async variants take owned values (String, not &str) because the
    // future outlives the pymethod call. This is the pyo3-async-runtimes
    // canonical pattern — the closure we pass to `future_into_py` must
    // be `'static + Send`, so references to the GIL-bound args would not
    // survive.
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str("        symbols: Vec<String>,\n");
        } else {
            writeln!(out, "        {}: String,", param.name).unwrap();
        }
    }
    for param in &builder_params {
        writeln!(
            out,
            "        {}: {},",
            param.name,
            python_async_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("        timeout_ms: Option<u64>,\n");
    out.push_str("    ) -> PyResult<Bound<'py, PyAny>> {\n");

    // Clone the Arc<thetadatadx::ThetaDataDx> handle into the closure — the
    // inner client is not Clone but the Arc is, and the builder pyclass
    // pattern elsewhere in this file relies on the same contract.
    out.push_str("        let tdx = self.tdx.clone();\n");

    // `spawn_awaitable` is the hand-written async twin of `run_blocking` —
    // it wraps `pyo3_async_runtimes::tokio::future_into_py`, routes
    // `thetadatadx::Error` through `to_py_err`, and invokes `convert` with
    // a held GIL. One call per `*_async` emit keeps the generator output
    // symmetric with the sync path (one `run_blocking` per emit).
    out.push_str("        spawn_awaitable(py, async move {\n");

    if is_string_list {
        // List endpoints: call the `_with_deadline` variant when caller set
        // timeout_ms; otherwise the deadline-less call. The future returns
        // `Result<Vec<String>, thetadatadx::Error>`; `spawn_awaitable`
        // routes the error through `to_py_err` and hands the `Vec<String>`
        // to the `convert` closure with the GIL held.
        let has_symbols = method_params
            .iter()
            .any(|param| param.param_type == "Symbols");
        if has_symbols {
            out.push_str(
                "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
            );
        }
        let positional_args = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "&refs".into()
                } else {
                    format!("&{}", param.name)
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        let leading_comma_args = if positional_args.is_empty() {
            String::new()
        } else {
            format!(", {positional_args}")
        };
        let column = endpoint
            .list_column
            .as_deref()
            .expect("list endpoint must declare list_column");
        let _ = leading_comma_args;
        writeln!(
            out,
            "            let call = tdx.{}({});",
            endpoint.name, positional_args
        )
        .unwrap();
        out.push_str("            if let Some(ms) = timeout_ms {\n");
        out.push_str("                match tokio::time::timeout(std::time::Duration::from_millis(ms), call).await {\n");
        out.push_str("                    Ok(inner) => inner,\n");
        out.push_str(
            "                    Err(_) => Err(thetadatadx::Error::Timeout { duration_ms: ms }),\n",
        );
        out.push_str("                }\n");
        out.push_str("            } else {\n");
        out.push_str("                call.await\n");
        out.push_str("            }\n");
        // Wrap the returned `Vec<String>` in a typed `StringList` with
        // the semantic column name so the caller can chain `.to_polars()`
        // into a single-column frame with a sensible header. `.into_any()`
        // coerces the `Py<StringList>` up to the `Py<PyAny>` the helper
        // signature demands.
        writeln!(
            out,
            "        }}, |py, values| strings_to_string_list(py, values, \"{column}\").map(|p| p.into_any()))"
        )
        .unwrap();
        out.push_str("    }\n");
        return out;
    }

    // Builder-backed endpoints: chain optional setters on the owned future.
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str(
            "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "            let mut request = tdx.{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "            if let Some(value) = {} {{", param.name).unwrap();
        writeln!(
            out,
            "                request = request.{}({});",
            param.name,
            async_setter_arg(param)
        )
        .unwrap();
        out.push_str("            }\n");
    }
    out.push_str("            if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "                request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("            }\n");
    if is_streaming_kind {
        // Async streaming endpoints collect the full stream into a Vec<T>
        // inside the future body; `spawn_awaitable` then runs `convert`
        // with the GIL held. The inner `?` on `request.stream(...).await`
        // propagates `thetadatadx::Error` unchanged into the helper.
        out.push_str("            let mut collected = Vec::new();\n");
        out.push_str(
            "            request.stream(|chunk| collected.extend_from_slice(chunk)).await?;\n",
        );
        out.push_str("            Ok(collected)\n");
    } else {
        out.push_str("            request.await\n");
    }
    // Convert back on the Python thread with GIL held. Snapshot
    // endpoints materialise a plain `Py<PyList>` of typed pyclass rows
    // (no `<T>List` wrapper); parsed list endpoints keep the wrapper so
    // callers can chain `.to_polars()` off the awaited value. `.into_any()`
    // coerces either return type up to `Py<PyAny>` for the helper signature.
    if is_snapshot {
        writeln!(
            out,
            "        }}, |py, ticks| {}(py, ticks).map(|p| p.into_any()))",
            python_vec_to_pylist_converter(&endpoint.return_type)
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "        }}, |py, ticks| {}(py, ticks).map(|p| p.into_any()))",
            python_pyclass_list_converter(&endpoint.return_type)
        )
        .unwrap();
    }
    out.push_str("    }\n");
    out
}

/// Async variants take owned `String` / `Option<String>` so the future owns
/// its captures (future_into_py requires `'static + Send`). This mirrors
/// `python_optional_type` but substitutes String for &str on the owned
/// path.
fn python_async_optional_type(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" => "Option<i32>",
        "Float" => "Option<f64>",
        "Bool" => "Option<bool>",
        _ => "Option<String>",
    }
}

/// For the async path we need `&value` when the builder setter expects `&str`.
fn async_setter_arg(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" | "Float" | "Bool" => "value",
        _ => "&value",
    }
}

// ───────────────────────── Fluent builder (per-endpoint #[pyclass]) ────────
//
// The builder pattern is a Python-side ergonomics layer: chain setters,
// terminate with `.arrow()` / `.list()` / `.polars()` / `.pandas()`. The
// builder struct clones an `Arc<thetadatadx::ThetaDataDx>` from the owning
// `ThetaDataDx` pyclass (see lib.rs where the field is wrapped in Arc for
// exactly this reason), so terminal calls can drive the existing endpoint
// methods on the underlying client without re-authenticating or copying
// configuration. State captured at builder construction time: required
// args + accumulated optional kwargs + timeout_ms.

/// The name of the `#[pyclass]` builder emitted for this endpoint.
fn endpoint_builder_struct(name: &str) -> String {
    format!("{}Builder", to_pascal_case(name))
}

/// Setter field type inside the builder pyclass.
fn builder_field_optional_type(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" => "Option<i32>",
        "Float" => "Option<f64>",
        "Bool" => "Option<bool>",
        _ => "Option<String>",
    }
}

/// Setter parameter type on the builder pymethod (what Python passes in).
fn builder_setter_arg_type(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" => "i32",
        "Float" => "f64",
        "Bool" => "bool",
        _ => "&str",
    }
}

/// Convert the setter arg into the stored field.
fn builder_setter_store_expr(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" | "Float" | "Bool" => "Some(value)",
        _ => "Some(value.to_string())",
    }
}

/// Render the per-endpoint `#[pyclass]` builder. Emits the struct + its
/// `#[pymethods]` impl (setters + terminals).
fn render_python_endpoint_builder(endpoint: &GeneratedEndpoint) -> String {
    let struct_name = endpoint_builder_struct(&endpoint.name);
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let is_streaming_kind = endpoint.kind == "stream";
    let mut out = String::new();

    // Struct definition. Setters mutate through `PyRefMut<'_, Self>`.
    let doc = compose_endpoint_doc(endpoint);
    out.push_str(&render_rust_doc_block("", &doc));
    writeln!(
        out,
        "#[pyclass(module = \"thetadatadx\", name = \"{}\")]",
        struct_name
    )
    .unwrap();
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    // Same Arc the parent `ThetaDataDx` pyclass stores — cheap to clone,
    // so the async terminal can move it into the future.
    out.push_str("    tdx: std::sync::Arc<thetadatadx::ThetaDataDx>,\n");
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str("    symbols: Vec<String>,\n");
        } else {
            writeln!(out, "    {}: String,", param.name).unwrap();
        }
    }
    for param in &builder_params {
        writeln!(
            out,
            "    {}: {},",
            param.name,
            builder_field_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("    timeout_ms: Option<u64>,\n");
    out.push_str("}\n\n");

    // Impl block.
    out.push_str("#[pymethods]\n");
    writeln!(out, "impl {struct_name} {{").unwrap();

    // Builder setters for optional params — chainable, mutate in place.
    for param in &builder_params {
        writeln!(out, "    /// Set `{}` on the pending request.", param.name).unwrap();
        writeln!(
            out,
            "    fn {}<'py>(mut slf: PyRefMut<'py, Self>, value: {}) -> PyRefMut<'py, Self> {{",
            param.name,
            builder_setter_arg_type(param)
        )
        .unwrap();
        writeln!(
            out,
            "        slf.{} = {};",
            param.name,
            builder_setter_store_expr(param)
        )
        .unwrap();
        out.push_str("        slf\n");
        out.push_str("    }\n\n");
    }

    // Required-param setters — allow chain `.symbol("AAPL").symbol("MSFT")`
    // to retarget a builder. Opt-in: callers happily compose at the
    // constructor site today.
    for param in &method_params {
        writeln!(
            out,
            "    /// Replace the required `{}` on the pending request.",
            param.name
        )
        .unwrap();
        if param.param_type == "Symbols" {
            writeln!(
                out,
                "    fn symbols<'py>(mut slf: PyRefMut<'py, Self>, value: Vec<String>) -> PyRefMut<'py, Self> {{"
            )
            .unwrap();
            out.push_str("        slf.symbols = value;\n");
            out.push_str("        slf\n");
            out.push_str("    }\n\n");
        } else {
            writeln!(
                out,
                "    fn {}<'py>(mut slf: PyRefMut<'py, Self>, value: &str) -> PyRefMut<'py, Self> {{",
                param.name
            )
            .unwrap();
            writeln!(out, "        slf.{} = value.to_string();", param.name).unwrap();
            out.push_str("        slf\n");
            out.push_str("    }\n\n");
        }
    }

    // Per-request deadline setter.
    out.push_str("    /// Apply a per-request deadline in milliseconds.\n");
    out.push_str(
        "    fn timeout_ms<'py>(mut slf: PyRefMut<'py, Self>, value: u64) -> PyRefMut<'py, Self> {\n",
    );
    out.push_str("        slf.timeout_ms = Some(value);\n");
    out.push_str("        slf\n");
    out.push_str("    }\n\n");

    // Single terminal per builder: `.list()` (sync) + `.list_async()`.
    // Returns the typed list wrapper (`StringList` or `<TickName>List`);
    // callers chain `.to_arrow()` / `.to_pandas()` / `.to_polars()` /
    // `.to_list()` off the wrapper to cross into the DataFrame world.
    // One terminal, one SSOT path, no drift across four variants.
    if is_string_list {
        let column = endpoint
            .list_column
            .as_deref()
            .expect("list endpoint must declare list_column");
        out.push_str("    /// Execute the request and return a typed `StringList` wrapper.\n");
        out.push_str("    ///\n");
        out.push_str(
            "    /// Chain `.to_polars()` / `.to_pandas()` / `.to_arrow()` / `.to_list()`\n",
        );
        out.push_str("    /// on the result to convert to the downstream representation.\n");
        out.push_str("    fn list(&self, py: Python<'_>) -> PyResult<Py<StringList>> {\n");
        write_sync_list_dispatch(&mut out, endpoint, &method_params, "        ");
        out.push_str("?;\n");
        writeln!(
            out,
            "        strings_to_string_list(py, values, \"{column}\")"
        )
        .unwrap();
        out.push_str("    }\n\n");

        out.push_str(
            "    /// Async companion to `list()` — awaitable yields the `StringList` wrapper.\n",
        );
        out.push_str(
            "    fn list_async<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {\n",
        );
        write_async_list_dispatch(&mut out, endpoint, &method_params, column, "        ");
        out.push_str("    }\n");
        out.push_str("}\n");
        return out;
    }

    // Parsed endpoint: builder runs the request and wraps the decoder-owned
    // `Vec<tick::T>` in a `<TickName>List`. The wrapper owns the terminals
    // (`to_list`, `to_arrow`, `to_pandas`, `to_polars`) so there is exactly
    // one path from decoded ticks to DataFrame output; no four-way drift.
    let list_class = python_pyclass_list_class(&endpoint.return_type);
    out.push_str("    /// Execute the request and return a typed list wrapper.\n");
    out.push_str("    ///\n");
    out.push_str("    /// Chain `.to_polars()` / `.to_pandas()` / `.to_arrow()` / `.to_list()`\n");
    out.push_str("    /// on the result to convert to the downstream representation.\n");
    writeln!(
        out,
        "    fn list(&self, py: Python<'_>) -> PyResult<Py<{list_class}>> {{"
    )
    .unwrap();
    write_sync_parsed_dispatch(
        &mut out,
        endpoint,
        &method_params,
        &builder_params,
        is_streaming_kind,
        "        ",
    );
    writeln!(
        out,
        "        {}(py, ticks)",
        python_pyclass_list_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n\n");

    // Async terminal. Clones the Arc + state into the future; the closure
    // is `'static + Send` so no references survive.
    out.push_str(
        "    /// Async companion to `list()` — awaitable yields the typed list wrapper.\n",
    );
    out.push_str(
        "    fn list_async<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {\n",
    );
    write_async_parsed_dispatch(
        &mut out,
        endpoint,
        &method_params,
        &builder_params,
        is_streaming_kind,
        "        ",
    );
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Builder constructor emitted on `ThetaDataDx` — `tdx.name_builder(...)` is
/// the Python entry point that yields a `NameBuilder`. Required params are
/// passed positionally (same order as the typed endpoint); optionals are
/// chained after construction.
fn render_python_builder_constructor(endpoint: &GeneratedEndpoint) -> String {
    let struct_name = endpoint_builder_struct(&endpoint.name);
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let mut out = String::new();

    let mut doc = format!(
        "Create a fluent-builder for `{}`. Chain setters then call `.list()`\n\
         (or `.list_async()`) to execute the request; the returned typed list\n\
         wrapper exposes the chainable terminals `.to_list()` / `.to_arrow()`\n\
         / `.to_pandas()` / `.to_polars()`.",
        endpoint.name
    );
    doc.push_str("\n\nSee `");
    doc.push_str(&endpoint.name);
    doc.push_str("()` for the sync signature; `");
    doc.push_str(&endpoint.name);
    doc.push_str("_async()` for the awaitable companion.");
    out.push_str(&render_rust_doc_block("    ", &doc));

    let signature_parts = method_params
        .iter()
        .map(|param| sdk_method_arg_name(param))
        .collect::<Vec<_>>();
    writeln!(
        out,
        "    #[pyo3(signature = ({}))]",
        signature_parts.join(", ")
    )
    .unwrap();

    writeln!(out, "    fn {}_builder(", endpoint.name).unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str("        symbols: Vec<String>,\n");
        } else {
            writeln!(out, "        {}: String,", param.name).unwrap();
        }
    }
    writeln!(out, "    ) -> {} {{", struct_name).unwrap();
    writeln!(out, "        {} {{", struct_name).unwrap();
    out.push_str("            tdx: self.tdx.clone(),\n");
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str("            symbols,\n");
        } else {
            writeln!(out, "            {},", param.name).unwrap();
        }
    }
    for param in &builder_params {
        writeln!(out, "            {}: None,", param.name).unwrap();
    }
    out.push_str("            timeout_ms: None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    // The `_ = builder_params` discard is a concession to the "unused
    // `method_params` alias" warning when `builder_params` is empty
    // (list endpoints). Consolidating the let-binding keeps the emitter
    // linear and avoids per-endpoint conditional code.
    let _ = builder_params;

    out
}

// ───────────────────────── Shared dispatch writers ─────────────────────────

fn write_sync_list_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        writeln!(
            out,
            "{indent}let refs: Vec<&str> = self.symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("self.{}.as_str()", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let leading_comma_args = if positional_args.is_empty() {
        String::new()
    } else {
        format!(", {positional_args}")
    };
    writeln!(out, "{indent}let tdx = self.tdx.clone();").unwrap();
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    // Rebuild the args vector inside the closure so the closure owns every
    // dependency at move time.
    if has_symbols {
        writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
    } else {
        for param in method_params {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    // Emits `let values: Vec<String> = run_blocking(...)` — no trailing
    // `?;` or semicolon; the caller appends `?;` and chains the
    // `strings_to_string_list` wrap.
    writeln!(
        out,
        "{indent}let values: Vec<String> = run_blocking(py, async move {{"
    )
    .unwrap();
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    // Rebuild positional args to reference the moved-in owned values.
    let positional_args_closure = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let leading_comma_args_closure = if positional_args_closure.is_empty() {
        String::new()
    } else {
        format!(", {positional_args_closure}")
    };
    let _ = leading_comma_args;
    let _ = positional_args;
    let _ = leading_comma_args_closure;
    writeln!(
        out,
        "{indent}    let call = tdx.{}({});",
        endpoint.name, positional_args_closure
    )
    .unwrap();
    writeln!(out, "{indent}    if let Some(ms) = timeout_ms {{").unwrap();
    writeln!(
        out,
        "{indent}        match tokio::time::timeout(std::time::Duration::from_millis(ms), call).await {{"
    )
    .unwrap();
    writeln!(out, "{indent}            Ok(inner) => inner,").unwrap();
    writeln!(
        out,
        "{indent}            Err(_) => Err(thetadatadx::Error::Timeout {{ duration_ms: ms }}),"
    )
    .unwrap();
    writeln!(out, "{indent}        }}").unwrap();
    writeln!(out, "{indent}    }} else {{").unwrap();
    writeln!(out, "{indent}        call.await").unwrap();
    writeln!(out, "{indent}    }}").unwrap();
    write!(out, "{indent}}})").unwrap();
}

fn write_async_list_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    column_name: &str,
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    writeln!(out, "{indent}let tdx = self.tdx.clone();").unwrap();
    if has_symbols {
        writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
    } else {
        for param in method_params {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    // `spawn_awaitable` wraps `pyo3_async_runtimes::tokio::future_into_py`,
    // routes `thetadatadx::Error` through `to_py_err`, and runs the convert
    // closure under `Python::attach`. One call per builder `list_async`
    // emit keeps this path symmetric with the free-function `_async` emit.
    writeln!(out, "{indent}spawn_awaitable(py, async move {{").unwrap();
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let leading_comma_args = if positional_args.is_empty() {
        String::new()
    } else {
        format!(", {positional_args}")
    };
    let _ = leading_comma_args;
    writeln!(
        out,
        "{indent}    let call = tdx.{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    writeln!(out, "{indent}    if let Some(ms) = timeout_ms {{").unwrap();
    writeln!(
        out,
        "{indent}        match tokio::time::timeout(std::time::Duration::from_millis(ms), call).await {{"
    )
    .unwrap();
    writeln!(out, "{indent}            Ok(inner) => inner,").unwrap();
    writeln!(
        out,
        "{indent}            Err(_) => Err(thetadatadx::Error::Timeout {{ duration_ms: ms }}),"
    )
    .unwrap();
    writeln!(out, "{indent}        }}").unwrap();
    writeln!(out, "{indent}    }} else {{").unwrap();
    writeln!(out, "{indent}        call.await").unwrap();
    writeln!(out, "{indent}    }}").unwrap();
    // Convert the resolved `Vec<String>` into the typed `StringList` and
    // coerce up to `Py<PyAny>` to satisfy the helper's convert signature.
    writeln!(
        out,
        "{indent}}}, |py, values| strings_to_string_list(py, values, \"{column_name}\").map(|p| p.into_any()))"
    )
    .unwrap();
}

fn write_sync_parsed_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
    is_streaming_kind: bool,
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    writeln!(out, "{indent}let tdx = self.tdx.clone();").unwrap();
    if has_symbols {
        writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
    } else {
        for param in method_params {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    for param in builder_params {
        writeln!(
            out,
            "{indent}let {} = self.{}{};",
            param.name,
            param.name,
            builder_field_clone_expr(param)
        )
        .unwrap();
    }
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    if is_streaming_kind {
        writeln!(out, "{indent}let ticks = runtime().block_on(async move {{").unwrap();
    } else {
        writeln!(out, "{indent}let ticks = run_blocking(py, async move {{").unwrap();
    }
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "{indent}    let mut request = tdx.{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in builder_params {
        writeln!(out, "{indent}    if let Some(value) = &{} {{", param.name).unwrap();
        writeln!(
            out,
            "{indent}        request = request.{}({});",
            param.name,
            builder_apply_self_value(param)
        )
        .unwrap();
        writeln!(out, "{indent}    }}").unwrap();
    }
    writeln!(out, "{indent}    if let Some(ms) = timeout_ms {{").unwrap();
    writeln!(
        out,
        "{indent}        request = request.with_deadline(std::time::Duration::from_millis(ms));"
    )
    .unwrap();
    writeln!(out, "{indent}    }}").unwrap();
    if is_streaming_kind {
        writeln!(out, "{indent}    let mut collected = Vec::new();").unwrap();
        writeln!(
            out,
            "{indent}    request.stream(|chunk| collected.extend_from_slice(chunk)).await.map_err(to_py_err)?;"
        )
        .unwrap();
        writeln!(out, "{indent}    Ok::<_, PyErr>(collected)").unwrap();
        writeln!(out, "{indent}}})?;").unwrap();
    } else {
        writeln!(out, "{indent}    request.await").unwrap();
        writeln!(out, "{indent}}})?;").unwrap();
    }
}

/// Stored-value-to-setter-arg converter for the builder pyclass dispatch.
fn builder_apply_self_value(param: &GeneratedParam) -> String {
    match param.param_type.as_str() {
        "Int" | "Float" | "Bool" => "*value".into(),
        _ => "value.as_str()".into(),
    }
}

/// Return `true` if the builder-stored type for this param implements
/// `Copy` (so we can skip `.clone()` — clippy flags clone-on-Copy).
fn builder_stored_is_copy(param: &GeneratedParam) -> bool {
    matches!(param.param_type.as_str(), "Int" | "Float" | "Bool")
}

/// Clone or move expression for transferring a builder field into the
/// `async move` closure, avoiding the `clone_on_copy` clippy error.
fn builder_field_clone_expr(param: &GeneratedParam) -> &'static str {
    if builder_stored_is_copy(param) {
        ""
    } else {
        ".clone()"
    }
}

fn write_async_parsed_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
    is_streaming_kind: bool,
    indent: &str,
) {
    writeln!(out, "{indent}let tdx = self.tdx.clone();").unwrap();
    for param in method_params {
        if param.param_type == "Symbols" {
            writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
        } else {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    for param in builder_params {
        writeln!(
            out,
            "{indent}let {} = self.{}{};",
            param.name,
            param.name,
            builder_field_clone_expr(param)
        )
        .unwrap();
    }
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    // `spawn_awaitable` owns the `future_into_py` + `to_py_err` + GIL-held
    // convert plumbing; one call per builder `list_async` emit keeps this
    // path symmetric with the free-function `_async` emit.
    writeln!(out, "{indent}spawn_awaitable(py, async move {{").unwrap();
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "{indent}    let mut request = tdx.{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in builder_params {
        writeln!(out, "{indent}    if let Some(value) = &{} {{", param.name).unwrap();
        writeln!(
            out,
            "{indent}        request = request.{}({});",
            param.name,
            builder_apply_self_value(param)
        )
        .unwrap();
        writeln!(out, "{indent}    }}").unwrap();
    }
    writeln!(out, "{indent}    if let Some(ms) = timeout_ms {{").unwrap();
    writeln!(
        out,
        "{indent}        request = request.with_deadline(std::time::Duration::from_millis(ms));"
    )
    .unwrap();
    writeln!(out, "{indent}    }}").unwrap();
    if is_streaming_kind {
        // Streaming builders: collect the full stream in the future and let
        // `spawn_awaitable` wrap the error + convert under the GIL.
        writeln!(out, "{indent}    let mut collected = Vec::new();").unwrap();
        writeln!(
            out,
            "{indent}    request.stream(|chunk| collected.extend_from_slice(chunk)).await?;"
        )
        .unwrap();
        writeln!(out, "{indent}    Ok(collected)").unwrap();
    } else {
        writeln!(out, "{indent}    request.await").unwrap();
    }
    // Single terminal path — wrap the decoder-owned Vec in the typed
    // `<TickName>List` and coerce to `Py<PyAny>` for the helper signature.
    // The caller chains `.to_polars()` / etc. off the awaited value.
    writeln!(
        out,
        "{indent}}}, |py, ticks| {}(py, ticks).map(|p| p.into_any()))",
        python_pyclass_list_converter(&endpoint.return_type)
    )
    .unwrap();
}
