//! TypeScript SDK napi-rs emitter.
//!
//! Renders `sdks/typescript/src/historical_methods.rs` — the `ThetaDataDx`
//! impl block that napi-rs compiles into the Node.js native addon.
//!
//! Every method takes an optional `timeout_ms` parameter. When set, the call
//! is given a deadline; on expiry a JS error is thrown and the underlying gRPC
//! stream is cancelled. The `ThetaDataDx` handle remains usable.

use std::fmt::Write as _;

use super::super::helpers::compose_endpoint_doc;
use super::super::helpers::render_rust_doc_block;
use super::super::helpers::{
    builder_params, is_streaming_endpoint, is_time_arg, method_params, sdk_method_arg_name,
    to_camel_case, ts_class_name, ts_class_vec_converter,
};
use super::super::model::GeneratedEndpoint;

pub(super) fn render_typescript_historical_methods(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    out.push_str("#[napi]\n");
    out.push_str("impl ThetaDataDx {\n");
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_typescript_endpoint_method(endpoint));
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

fn render_typescript_endpoint_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let builder_params = if is_string_list {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    let is_streaming_kind = endpoint.kind == "stream";
    let camel_name = to_camel_case(&endpoint.name);
    let mut out = String::new();

    out.push_str(&render_rust_doc_block("    ", &compose_endpoint_doc(endpoint)));
    writeln!(out, "    #[napi(js_name = \"{camel_name}\")]").unwrap();
    writeln!(out, "    pub fn {name}(", name = endpoint.name).unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(
            out,
            "        {}: {},",
            sdk_method_arg_name(param),
            ts_napi_arg_type(param)
        )
        .unwrap();
    }
    for param in &builder_params {
        writeln!(
            out,
            "        {}: {},",
            param.name,
            ts_napi_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("        timeout_ms: Option<f64>,\n");

    if is_string_list {
        out.push_str("    ) -> napi::Result<Vec<String>> {\n");
    } else {
        writeln!(
            out,
            "    ) -> napi::Result<Vec<{}>> {{",
            ts_class_name(&endpoint.return_type)
        )
        .unwrap();
    }

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str("        let symbols = normalize_symbols(symbols);\n");
        out.push_str(
            "        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }
    for param in &method_params {
        let arg_name = sdk_method_arg_name(param);
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(out, "        let {arg_name} = normalize_date({arg_name});").unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(out, "        let {arg_name} = normalize_time({arg_name});").unwrap();
            }
            _ => {}
        }
    }
    for param in &builder_params {
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_date({});",
                    param.name, param.name
                )
                .unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_time({});",
                    param.name, param.name
                )
                .unwrap();
            }
            _ => {}
        }
    }

    if is_string_list {
        let positional_args = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "&refs".into()
                } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                    || is_time_arg(param)
                {
                    format!("{}.as_str()", sdk_method_arg_name(param))
                } else {
                    format!("&{}", sdk_method_arg_name(param))
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        let leading_comma_args = if positional_args.is_empty() {
            String::new()
        } else {
            format!(", {positional_args}")
        };
        let _ = leading_comma_args;
        out.push_str("        runtime().block_on(async {\n");
        writeln!(
            out,
            "            let call = self.tdx.{name}({positional_args});",
            name = endpoint.name,
        )
        .unwrap();
        out.push_str("            if let Some(ms) = timeout_ms {\n");
        out.push_str("                match tokio::time::timeout(std::time::Duration::from_millis(ms as u64), call).await {\n");
        out.push_str("                    Ok(inner) => inner,\n");
        out.push_str("                    Err(_) => Err(thetadatadx::Error::Timeout { duration_ms: ms as u64 }),\n");
        out.push_str("                }\n");
        out.push_str("            } else {\n");
        out.push_str("                call.await\n");
        out.push_str("            }\n");
        out.push_str("        }).map_err(to_napi_err)\n");
        out.push_str("    }\n");
        return out;
    }

    // Builder-backed endpoints.
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                || is_time_arg(param)
            {
                format!("{}.as_str()", sdk_method_arg_name(param))
            } else {
                format!("&{}", sdk_method_arg_name(param))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "        let mut request = self.tdx.{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "        if let Some(value) = {} {{", param.name).unwrap();
        let setter_arg = match param.param_type.as_str() {
            "Int" | "Float" | "Bool" => "value".to_string(),
            _ => "value.as_str()".to_string(),
        };
        writeln!(
            out,
            "            request = request.{}({});",
            param.name, setter_arg
        )
        .unwrap();
        out.push_str("        }\n");
    }
    out.push_str("        if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "            request = request.with_deadline(std::time::Duration::from_millis(ms as u64));\n",
    );
    out.push_str("        }\n");

    if is_streaming_kind {
        out.push_str("        let mut collected = Vec::new();\n");
        out.push_str("        runtime()\n");
        out.push_str(
            "            .block_on(request.stream(|chunk| collected.extend_from_slice(chunk)))\n",
        );
        out.push_str("            .map_err(to_napi_err)?;\n");
        writeln!(
            out,
            "        Ok({}(&collected))",
            ts_class_vec_converter(&endpoint.return_type)
        )
        .unwrap();
        out.push_str("    }\n");
        return out;
    }

    out.push_str(
        "        let ticks = runtime().block_on(async move { request.await }).map_err(to_napi_err)?;\n",
    );
    writeln!(
        out,
        "        Ok({}(&ticks))",
        ts_class_vec_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n");
    out
}

fn ts_napi_arg_type(param: &super::super::model::GeneratedParam) -> &'static str {
    if param.param_type == "Symbols" {
        "Either<String, Vec<String>>"
    } else if matches!(param.param_type.as_str(), "Date" | "Expiration") || is_time_arg(param) {
        "Either<String, chrono::DateTime<chrono::Utc>>"
    } else {
        "String"
    }
}

fn ts_napi_optional_type(param: &super::super::model::GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" => "Option<i32>",
        "Float" => "Option<f64>",
        "Bool" => "Option<bool>",
        "Date" | "Expiration" => "Option<Either<String, chrono::DateTime<chrono::Utc>>>",
        _ if is_time_arg(param) => "Option<Either<String, chrono::DateTime<chrono::Utc>>>",
        _ => "Option<String>",
    }
}
