//! C mirror header emitter (`sdks/cpp/include/fpss_event_structs.h.inc`).
//!
//! Emits one C struct per `kind = "control"` schema entry, alongside the
//! data-variant structs. The tagged `ThetaDataDxStreamEvent` embeds all of them by
//! value; consumers dispatch on `event.kind` and read the matching
//! `event.<variant>` field.

use std::fmt::Write as _;

use super::common::{c_ffi_scalar, is_byte_buffer, snake_case};
use super::schema::{
    sorted_control_events, sorted_data_events, sorted_event_names, EventDef, Schema,
};

/// Emit the `ThetaDataDxStreamEventKind` C enum. One discriminant per variant,
/// schema-driven.
fn render_kind_enum_c(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(
        "/* Stream event kind tag. Schema-driven from fpss_event_schema.toml.\n\
 * Check `event.kind` then read the matching `event.<variant>` field on\n\
 * `ThetaDataDxStreamEvent`. Values are stable across the current C ABI but may\n\
 * renumber on a future major bump. */\n",
    );
    out.push_str("typedef enum {\n");
    for (idx, name) in sorted_event_names(schema).iter().enumerate() {
        // C-side identifier: `THETADATADX_STREAM_<SCREAMING_SNAKE>`.
        let upper = snake_case(name).to_uppercase();
        writeln!(out, "    THETADATADX_STREAM_{upper} = {idx},").unwrap();
    }
    out.push_str("} ThetaDataDxStreamEventKind;\n\n");
    out
}

/// Emit the C `ThetaDataDxContract` struct mirrored from the Rust
/// `#[repr(C)] ThetaDataDxContract`. Layout must match field-for-field with
/// `render_contract_struct_rust` in `ffi_rust.rs`.
fn render_contract_struct_c() -> &'static str {
    "/* Streaming Contract shared across every data event. `symbol` is a\n\
 * NUL-terminated C string (may be null when not yet resolved);\n\
 * optional option fields use a tagged-present bool because C has no\n\
 * Option<T>. `right` is `'C'` / `'P'` (NUL when `has_right` is false)\n\
 * and `strike` is the option strike in dollars — the same notation\n\
 * the public option builder takes. Layout is byte-identical to Rust's\n\
 * #[repr(C)] ThetaDataDxContract.\n\
 */\n\
typedef struct {\n\
    const char *symbol;\n\
    int32_t sec_type;\n\
    bool has_expiration;\n\
    int32_t expiration;\n\
    bool has_right;\n\
    char right;\n\
    bool has_strike;\n\
    double strike;\n\
    int32_t strike_thousandths;\n\
} ThetaDataDxContract;\n\n"
}

/// Emit one `typedef struct { ... } ThetaDataDxStream<Variant>;` for a data or
/// control variant. Empty (unit) control variants get a single
/// `uint8_t _padding;` so MSVC / Clang / GCC all agree on `sizeof == 1`.
fn render_event_struct_c(out: &mut String, event_name: &str, def: &EventDef) {
    if !def.doc.is_empty() {
        for line in def.doc.lines() {
            writeln!(out, "/* {line} */").unwrap();
        }
    }
    out.push_str("typedef struct {\n");
    if def.columns.is_empty() {
        out.push_str("    /* Placeholder so the struct has portable size 1. */\n");
        out.push_str("    uint8_t _padding;\n");
    } else {
        for column in &def.columns {
            if is_byte_buffer(&column.r#type) {
                writeln!(out, "    const uint8_t *{};", column.name).unwrap();
                writeln!(out, "    size_t {}_len;", column.name).unwrap();
            } else {
                let ty = c_ffi_scalar(&column.r#type, event_name, &column.name);
                writeln!(out, "    {ty} {};", column.name).unwrap();
            }
        }
    }
    writeln!(out, "}} ThetaDataDxStream{event_name};\n").unwrap();
}

/// Emit the C mirror of the Rust FFI event structs. `#include`'d from
/// `sdks/cpp/include/thetadatadx.h` for the C++ SDK. Keeps field order and
/// padding identical to the Rust `#[repr(C)]` layout by using the same
/// schema column ordering on both sides.
pub(super) fn render_c_fpss_event_header(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(
        "/* @generated DO NOT EDIT — regenerated by build.rs from fpss_event_schema.toml */\n",
    );
    out.push_str("/* C mirror of the Rust FFI streaming event structs. #include'd from\n");
    out.push_str(" * sdks/cpp/include/thetadatadx.h (C++ SDK). Plain C typedefs.\n");
    out.push_str(" * Do not hand-edit. */\n\n");

    // `<stdbool.h>` is needed for the `bool` type used by the Contract
    // struct's `has_*` tagged-optional flags. Safe to include repeatedly
    // at the `.h.inc` level — `<stdbool.h>` is idempotent.
    out.push_str("#include <stdbool.h>\n\n");

    out.push_str(&render_kind_enum_c(schema));
    out.push_str(render_contract_struct_c());

    for (event_name, def) in sorted_data_events(schema) {
        render_event_struct_c(&mut out, event_name, def);
    }
    for (event_name, def) in sorted_control_events(schema) {
        render_event_struct_c(&mut out, event_name, def);
    }

    out.push_str("/* Tagged streaming event. Read `kind` first, then access only the\n");
    out.push_str(" * matching `event.<variant>` field. Per-variant control payloads\n");
    out.push_str(" * mirror the Rust `StreamControl::*` enum one-for-one. */\n");
    out.push_str("typedef struct {\n");
    out.push_str("    ThetaDataDxStreamEventKind kind;\n");
    for (event_name, _) in sorted_data_events(schema) {
        let field = snake_case(event_name);
        writeln!(out, "    ThetaDataDxStream{event_name} {field};").unwrap();
    }
    for (event_name, _) in sorted_control_events(schema) {
        let field = snake_case(event_name);
        writeln!(out, "    ThetaDataDxStream{event_name} {field};").unwrap();
    }
    out.push_str("} ThetaDataDxStreamEvent;\n");

    out
}
