//! Python type-stub emitter for the `HistoricalView` endpoint surface.
//!
//! Renders the body of `class HistoricalView` in
//! `thetadatadx-py/python/thetadatadx/__init__.pyi`. The runtime
//! `HistoricalView` carries every historical endpoint as a real
//! `#[pymethods]` method (sync, `*_async`, and `*_builder`), generated by
//! the sibling `python` emitter from the same `endpoint_surface.toml`.
//! This emitter projects the identical surface into precise type stubs so
//! `client.historical.<endpoint>(...)` and its `_async` / `_builder`
//! companions type-check under mypy / pyright, and so `mypy.stubtest`
//! verifies the stub against the runtime without relying on the
//! missing-stub escape hatch.
//!
//! The signatures mirror the `#[pyo3(signature = ...)]` on each generated
//! pymethod exactly: required parameters stay positional, every optional
//! builder kwarg and `timeout_ms` is keyword-only (after `*`) with a
//! `None` default. Return types follow the same three shapes the runtime
//! produces: the chainable `<Tick>List` wrapper for parsed lists, a
//! `StringList` for list-of-string endpoints, and a plain `List[<row>]`
//! for the snapshot fast path.

use std::fmt::Write as _;

use super::super::helpers::{compose_endpoint_doc, is_streaming_endpoint, to_pascal_case};
use super::super::model::{GeneratedEndpoint, GeneratedParam};
use super::super::sdk_helpers::{
    builder_params, is_snapshot_endpoint, is_time_arg, method_params, python_pyclass_list_class,
    python_pyclass_row_class, sdk_method_arg_name,
};

/// Marker comments bounding the generated module-scope region that holds
/// the result-type aliases and the entire `HistoricalView` class. Everything
/// between the two markers is owned by this emitter; the rest of
/// `__init__.pyi` stays hand-maintained.
pub(super) const STUB_BEGIN_MARKER: &str =
    "# --- BEGIN GENERATED HISTORICAL VIEW (endpoint_surface.toml) ---";
pub(super) const STUB_END_MARKER: &str = "# --- END GENERATED HISTORICAL VIEW ---";

/// Render the generated region (markers included): the result-type aliases
/// plus the full `HistoricalView` class with one precise stub per endpoint
/// method (sync, `*_async`, `*_builder`). Spliced into `__init__.pyi`
/// between the two markers by [`super::sdk_files`].
pub(super) fn render_python_historical_view_stub(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(STUB_BEGIN_MARKER);
    out.push('\n');
    out.push_str(
        "# Generated from endpoint_surface.toml; do not edit by hand. Run\n\
         # `cargo run -p thetadatadx --bin generate_sdk_surfaces` to refresh.\n\
         #\n\
         # The typed list wrappers and fluent builder classes returned below are\n\
         # registered at runtime by the compiled extension and resolve through\n\
         # the module-level `__getattr__`; they are aliased to `Any` here so the\n\
         # method signatures stay precise without re-enumerating every wrapper's\n\
         # converter surface.\n",
    );

    for alias in collect_result_type_aliases(endpoints) {
        writeln!(out, "{alias} = Any").unwrap();
    }

    out.push('\n');
    out.push_str("@final\n");
    out.push_str("class HistoricalView:\n");
    out.push_str(
        "    \"\"\"Historical-data sub-namespace returned by :attr:`Client.historical`.\n\
         \n\
         \x20   Exposes every historical / list / snapshot / at-time endpoint as a\n\
         \x20   method: the synchronous call, its ``*_async`` awaitable companion,\n\
         \x20   and a ``*_builder`` fluent constructor. The surface is projected\n\
         \x20   from the same endpoint definition that drives the runtime methods,\n\
         \x20   so the stubs cannot drift from the installed extension.\n\
         \x20   \"\"\"\n",
    );

    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push('\n');
        out.push_str(&render_stub_sync(endpoint));
        out.push('\n');
        out.push_str(&render_stub_async(endpoint));
        out.push('\n');
        out.push_str(&render_stub_builder(endpoint));
    }

    out.push('\n');
    out.push_str(STUB_END_MARKER);
    out
}

/// Distinct return / builder class names referenced by the generated
/// signatures, in first-appearance order. Each name is aliased to `Any` so
/// the precise method signatures compile without enumerating every
/// wrapper's converter surface.
fn collect_result_type_aliases(endpoints: &[GeneratedEndpoint]) -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    let mut aliases = Vec::new();
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        let return_type = stub_return_type(endpoint);
        for name in referenced_class_names(&return_type) {
            if seen.insert(name.clone()) {
                aliases.push(name);
            }
        }
        let builder = endpoint_builder_class(&endpoint.name);
        if seen.insert(builder.clone()) {
            aliases.push(builder);
        }
    }
    aliases
}

/// Extract the bare class identifiers from a return annotation, stripping
/// the `List[...]` wrapper used by the snapshot fast path.
fn referenced_class_names(annotation: &str) -> Vec<String> {
    let inner = annotation
        .strip_prefix("List[")
        .and_then(|rest| rest.strip_suffix(']'))
        .unwrap_or(annotation);
    vec![inner.to_string()]
}

// ───────────────────────── Per-variant stub bodies ─────────────────────────

fn render_stub_sync(endpoint: &GeneratedEndpoint) -> String {
    let mut out = String::new();
    let return_type = stub_return_type(endpoint);
    write_signature(
        &mut out,
        &endpoint.name,
        endpoint,
        &return_type,
        SignatureKind::SyncMethod,
    );
    write_docstring(&mut out, &compose_endpoint_doc(endpoint));
    out
}

fn render_stub_async(endpoint: &GeneratedEndpoint) -> String {
    let mut out = String::new();
    let return_type = format!("Awaitable[{}]", stub_return_type(endpoint));
    let mut doc = compose_endpoint_doc(endpoint);
    doc.push_str(
        "\n\nAwaitable companion of the sync variant. The returned object \
         resolves the request off the calling thread so a running event \
         loop keeps servicing other coroutines.",
    );
    write_signature(
        &mut out,
        &format!("{}_async", endpoint.name),
        endpoint,
        &return_type,
        SignatureKind::AsyncMethod,
    );
    write_docstring(&mut out, &doc);
    out
}

fn render_stub_builder(endpoint: &GeneratedEndpoint) -> String {
    let mut out = String::new();
    let return_type = endpoint_builder_class(&endpoint.name);
    let doc = format!(
        "Fluent builder for `{name}`. Chain the optional setters, then \
         call `.list()` (or `.list_async()`) to execute; the returned \
         typed list wrapper exposes `.to_list()` / `.to_arrow()` / \
         `.to_pandas()` / `.to_polars()`.",
        name = endpoint.name
    );
    write_signature(
        &mut out,
        &format!("{}_builder", endpoint.name),
        endpoint,
        &return_type,
        SignatureKind::Builder,
    );
    write_docstring(&mut out, &doc);
    out
}

// ───────────────────────── Signature writer ────────────────────────────────

enum SignatureKind {
    /// Sync endpoint method: required positional args, then a keyword-only
    /// block of optional builder kwargs and `timeout_ms`. Scalar kwargs
    /// carry the upstream default so the stub matches the runtime
    /// `#[pyo3(signature = ...)]` exactly.
    SyncMethod,
    /// Async endpoint method: same shape as the sync variant, but every
    /// kwarg defaults to `None` (the runtime resolves the upstream default
    /// inside the awaitable, matching the generated `*_async` signature).
    AsyncMethod,
    /// `*_builder` constructor: required positional args only.
    Builder,
}

fn write_signature(
    out: &mut String,
    method_name: &str,
    endpoint: &GeneratedEndpoint,
    return_type: &str,
    kind: SignatureKind,
) {
    let method_params = method_params(endpoint);
    let builder_params = if endpoint.return_type == "StringList" {
        Vec::new()
    } else {
        builder_params(endpoint)
    };

    let positional: Vec<String> = method_params
        .iter()
        .map(|param| format!("{}: {}", sdk_method_arg_name(param), stub_arg_type(param)))
        .collect();

    let honor_defaults = matches!(kind, SignatureKind::SyncMethod);
    let keyword_only: Vec<String> = match kind {
        SignatureKind::Builder => Vec::new(),
        SignatureKind::SyncMethod | SignatureKind::AsyncMethod => {
            let mut kwargs: Vec<String> = builder_params
                .iter()
                .map(|param| {
                    format!(
                        "{}: Optional[{}] = {}",
                        param.name,
                        stub_optional_inner_type(param),
                        stub_kwarg_default(param, honor_defaults)
                    )
                })
                .collect();
            kwargs.push("timeout_ms: Optional[int] = None".to_string());
            kwargs
        }
    };

    // Single-line form when the whole signature fits comfortably; the
    // hand-written stub keeps short methods on one line, so match that.
    let inline = positional.is_empty() && keyword_only.len() <= 1;
    if inline && keyword_only.is_empty() {
        writeln!(out, "    def {method_name}(self) -> {return_type}:").unwrap();
        return;
    }

    writeln!(out, "    def {method_name}(").unwrap();
    out.push_str("        self,\n");
    for param in &positional {
        writeln!(out, "        {param},").unwrap();
    }
    if !keyword_only.is_empty() {
        out.push_str("        *,\n");
        for kwarg in &keyword_only {
            writeln!(out, "        {kwarg},").unwrap();
        }
    }
    writeln!(out, "    ) -> {return_type}:").unwrap();
}

fn write_docstring(out: &mut String, doc: &str) {
    let lines: Vec<&str> = doc.lines().collect();
    if lines.len() == 1 {
        writeln!(out, "        \"\"\"{}\"\"\"", lines[0]).unwrap();
        out.push_str("        ...\n");
        return;
    }
    out.push_str("        \"\"\"");
    for (idx, line) in lines.iter().enumerate() {
        if idx == 0 {
            writeln!(out, "{line}").unwrap();
        } else if line.is_empty() {
            out.push('\n');
        } else {
            writeln!(out, "        {line}").unwrap();
        }
    }
    out.push_str("        \"\"\"\n");
    out.push_str("        ...\n");
}

// ───────────────────────── Type tables ─────────────────────────────────────

/// Python type annotation for a required positional endpoint argument.
/// Mirrors the runtime coercion: date / time arguments accept the
/// matching `datetime` objects as well as the wire string, and the
/// multi-symbol argument accepts a single symbol or a sequence.
fn stub_arg_type(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Symbols" => "Union[str, Sequence[str]]",
        "Date" | "Expiration" => "Union[str, date, datetime]",
        _ if is_time_arg(param) => "Union[str, time, datetime]",
        _ => "str",
    }
}

/// Inner type of an optional keyword-only argument (wrapped in
/// `Optional[...]` by the caller). Scalar kwargs map to their Python
/// scalar; date / time kwargs accept the matching `datetime` objects.
fn stub_optional_inner_type(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" => "int",
        "Float" => "float",
        "Bool" => "bool",
        "Date" | "Expiration" => "Union[str, date, datetime]",
        _ if is_time_arg(param) => "Union[str, time, datetime]",
        _ => "str",
    }
}

/// Return-type annotation for the sync endpoint method. The async variant
/// wraps this in `Awaitable[...]`. Matches the three runtime shapes:
/// `StringList`, the snapshot `list[<row>]` fast path, and the chainable
/// `<Tick>List` wrapper.
fn stub_return_type(endpoint: &GeneratedEndpoint) -> String {
    if endpoint.return_type == "StringList" {
        return "StringList".to_string();
    }
    if is_snapshot_endpoint(endpoint) {
        return format!("List[{}]", python_pyclass_row_class(&endpoint.return_type));
    }
    python_pyclass_list_class(&endpoint.return_type)
}

/// Name of the per-endpoint `*_builder` return class, matching the
/// `#[pyclass(name = ...)]` the runtime emitter assigns.
fn endpoint_builder_class(name: &str) -> String {
    format!("{}Builder", to_pascal_case(name))
}

/// Default expression for an optional keyword-only argument. Mirrors the
/// runtime `python_signature_kwarg`: when `honor_defaults` is set (the sync
/// variant) a scalar param surfaces its upstream default; otherwise — and
/// for every non-scalar param — the default is `None`. Bool literals are
/// rendered in Python casing.
fn stub_kwarg_default(param: &GeneratedParam, honor_defaults: bool) -> String {
    if !honor_defaults {
        return "None".to_string();
    }
    let Some(default) = param.default.as_deref() else {
        return "None".to_string();
    };
    match param.param_type.as_str() {
        "Bool" => match default {
            "true" => "True".to_string(),
            "false" => "False".to_string(),
            other => other.to_string(),
        },
        "Int" | "Float" => default.to_string(),
        _ => "None".to_string(),
    }
}
