//! TypeScript SDK napi-rs emitter.
//!
//! Renders `thetadatadx-ts/src/_generated/historical_methods.rs` — the
//! shared per-endpoint options structs plus one `impl` block per
//! historical napi class (`Client`, the unified handle, and
//! `HistoricalClient`, the standalone historical-only handle). Both carry the
//! identical method bodies (every body references `self.client`), so the
//! historical surface stays in lockstep across the two at zero
//! per-method cost. napi-rs compiles the result into the Node.js native
//! addon.
//!
//! Every endpoint method is an `async fn`: napi-rs returns a JS Promise
//! and resolves it off the runtime's execution thread, so the network
//! round-trip never holds the Node event loop for the duration of a
//! fetch. The returned Promise resolves with the same typed row array
//! the synchronous shape returned before; the element types are
//! unchanged. The blocking round-trip is handed to a worker via
//! `spawn_endpoint_task` so timers, queued promises, and concurrent
//! requests keep advancing while a fetch is in flight.
//!
//! Each method takes its required parameters positionally, followed by
//! ONE optional trailing options object (the JavaScript idiom for
//! multiple optional parameters — positional `undefined` holes silently
//! shift later arguments onto the wrong parameter). Each endpoint gets a
//! dedicated `#[napi(object)] <Method>Options` struct whose keys are the
//! camelCase parameter names; absent keys behave exactly like an omitted
//! parameter. `timeoutMs` rides in the same object: when set, the call is
//! given a deadline; on expiry the Promise rejects and the underlying
//! request is cancelled. The `Client` handle remains usable.
//!
//! Every history endpoint that returns a typed row collection also gets a
//! `<endpoint>Stream(...args, options, callback)` server-stream companion
//! (the TypeScript surface of the Python builders' `.stream(handler)`).
//! Instead of buffering the whole response, it pumps each decoded gRPC
//! chunk to `callback(chunk: Tick[])` through a napi-rs
//! `ThreadsafeFunction`, so peak memory tracks one chunk rather than the
//! full result — the path the `Config.setWarnOnBufferedThresholdBytes`
//! warning points oversized buffered pulls at. The coverage set mirrors
//! the Python streaming builders exactly (non-snapshot, non-FPSS-kind
//! endpoints that decode to a row collection); snapshot endpoints and the
//! flat `StringList` list endpoints have no stream companion.

use std::fmt::Write as _;

use heck::ToLowerCamelCase as _;

use super::super::helpers::{compose_endpoint_doc, endpoint_streams, is_streaming_endpoint};
use super::super::model::GeneratedEndpoint;
use super::super::sdk_helpers::{
    builder_params, is_time_arg, method_params, render_rust_doc_block, sdk_method_arg_name,
    to_camel_case, to_pascal_case, ts_class_name, ts_class_vec_converter, write_timeout_call,
};

/// napi classes that carry the historical endpoint surface. Both expose a
/// `client_handle(&self) -> napi::Result<Arc<thetadatadx::Client>>` accessor,
/// so the generated method bodies (which resolve the handle via
/// `self.client_handle()?`) compile unchanged against either receiver.
/// `HistoricalView` co-owns its `Arc` (always `Ok`, surviving a parent
/// `Client::close`); `HistoricalClient` holds the handle behind an `Option` and
/// rejects with "client is closed" once its own `close()` has released it.
///
/// `Client` is the unified handle (historical + FPSS
/// streaming); `HistoricalClient` is the standalone historical-only handle
/// that never opens the FPSS transport. The standalone client mirrors
/// the Python `HistoricalClient` (`thetadatadx-py/src/mdds_client.rs`), the C++
/// `thetadatadx::Client`, and the C ABI `thetadatadx_client_*` entry points: the same
/// MDDS/Nexus surface with no streaming methods reachable. Emitting the
/// identical method bodies onto both keeps the historical surface in
/// lockstep at zero per-method cost — adding an endpoint to
/// `endpoint_surface.toml` lands it on both classes automatically.
///
/// The unified client exposes these through the `client.historical`
/// sub-namespace, so the generated block targets `HistoricalView` (the
/// view returned by the `historical` getter); the standalone
/// `HistoricalClient` keeps its flat historical surface.
const HISTORICAL_IMPL_CLASSES: &[&str] = &["HistoricalView", "HistoricalClient"];

/// Renders the TypeScript historical surface: the per-endpoint options
/// structs and one napi `impl` block per historical class, each carrying
/// every endpoint method and its server-stream companion.
pub(super) fn render_typescript_historical_methods(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    // Per-endpoint options objects first (shared across every historical
    // class — they carry no receiver), then one impl block per class.
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_typescript_endpoint_options_struct(endpoint));
        out.push('\n');
    }
    // One `<Tick>WithColumns` return object per distinct columnar return type —
    // the `{ rows, presentColumns, symbol? }` shape the `<method>WithColumns`
    // variant returns, so a live caller can drive the projected Arrow-IPC exit
    // from the response's own column set. `StringList` endpoints carry no
    // column set and get none.
    let mut seen_return_types = std::collections::HashSet::new();
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
        .filter(|endpoint| endpoint.return_type != "StringList")
    {
        if seen_return_types.insert(endpoint.return_type.clone()) {
            out.push_str(&render_typescript_with_columns_struct(
                &endpoint.return_type,
            ));
            out.push('\n');
        }
    }
    for class_name in HISTORICAL_IMPL_CLASSES {
        out.push_str(&render_typescript_historical_impl_block(
            endpoints, class_name,
        ));
    }
    out
}

/// Emit a single `#[napi] impl <ClassName> { ... }` block carrying every
/// historical endpoint method (and its server-stream companion). The
/// method bodies resolve the client via `self.client_handle()?`, so the block
/// compiles against any napi class that exposes a
/// `client_handle(&self) -> napi::Result<Arc<thetadatadx::Client>>` accessor.
/// Parameterising over the class name lets the generator
/// project the identical surface onto the unified `Client` and
/// the standalone `HistoricalClient` without duplicating the per-endpoint
/// rendering.
fn render_typescript_historical_impl_block(
    endpoints: &[GeneratedEndpoint],
    class_name: &str,
) -> String {
    let mut out = String::new();
    out.push_str("#[napi]\n");
    writeln!(out, "impl {class_name} {{").unwrap();
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_typescript_endpoint_method(endpoint));
        out.push('\n');
        // Server-stream terminal companion. Emitted for every endpoint
        // that gets `.stream(handler)` / `.stream_async(handler)` on the
        // Python parsed builders (see `python.rs::write_sync_stream_terminal`):
        // a non-snapshot, non-streaming-kind history endpoint that returns a
        // typed row collection. Snapshot endpoints (≤10 rows) and the
        // `StringList` list endpoints (which return bare strings, not a tick
        // collection) are excluded — streaming a handful of rows or a flat
        // string list buys nothing over the buffered method. The stream
        // companion pumps decoded gRPC history chunks (not FPSS events), so
        // it stays on the MDDS-only surface like every other historical
        // method.
        if endpoint_streams(endpoint) {
            out.push_str(&render_typescript_endpoint_stream_method(endpoint));
            out.push('\n');
        }
        // Presence-carrying variant: the same query returning the rows plus the
        // response's projected column set (and the broadcast `symbol` when the
        // wire carried one), so the projected Arrow-IPC exit is reachable from a
        // live call. `StringList` endpoints carry no column set and get none.
        if endpoint.return_type != "StringList" {
            out.push_str(&render_typescript_endpoint_with_columns_method(endpoint));
            out.push('\n');
        }
    }
    out.push_str("}\n");
    out
}

/// `stock_history_eod` -> `StockHistoryEodOptions`.
fn options_struct_name(endpoint: &GeneratedEndpoint) -> String {
    format!("{}Options", to_pascal_case(&endpoint.name))
}

/// Emit the per-endpoint `#[napi(object)]` options struct: one optional
/// key per optional endpoint parameter plus `timeoutMs`. All fields are
/// `Option`, so `Default` derives and an omitted object behaves exactly
/// like an empty one.
fn render_typescript_endpoint_options_struct(endpoint: &GeneratedEndpoint) -> String {
    let camel_name = to_camel_case(&endpoint.name);
    let struct_name = options_struct_name(endpoint);
    let builder_params = if endpoint.return_type == "StringList" {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    let mut out = String::new();
    writeln!(
        out,
        "/// Optional parameters for the `{camel_name}` method. Keys are"
    )
    .unwrap();
    out.push_str("/// the camelCase parameter names; absent keys behave exactly like an\n");
    out.push_str("/// omitted parameter. `timeoutMs` bounds the whole call: on expiry the\n");
    out.push_str("/// returned Promise rejects and the underlying request is cancelled.\n");
    out.push_str("#[napi(object)]\n");
    out.push_str("#[derive(Default)]\n");
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    for param in &builder_params {
        // Per-field doc so the parameter's units and meaning reach the
        // generated `.d.ts` interface member (napi-rs propagates `///`
        // comments onto interface fields). Without this the options
        // object would list bare `annualDividend?: number` with no unit.
        super::doc::doc_lines(&mut out, "    ", &param.description);
        writeln!(
            out,
            "    pub {}: {},",
            param.name,
            ts_napi_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("    /// Per-call deadline as a non-negative whole number of milliseconds;\n");
    out.push_str("    /// on expiry the returned Promise rejects and the underlying request\n");
    out.push_str("    /// is cancelled. A non-finite, negative, or fractional value is\n");
    out.push_str("    /// rejected with `InvalidParameterError` rather than coerced.\n");
    out.push_str("    pub timeout_ms: Option<f64>,\n");
    out.push_str("}\n");
    out
}

fn render_typescript_endpoint_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let camel_name = to_camel_case(&endpoint.name);
    let struct_name = options_struct_name(endpoint);
    let mut out = String::new();

    out.push_str(&render_rust_doc_block(
        "    ",
        &compose_endpoint_doc(endpoint),
    ));
    writeln!(out, "    #[napi(js_name = \"{camel_name}\")]").unwrap();
    // The method is `async`: napi-rs returns a JS Promise and drives the
    // future on its own runtime, so the network round-trip never runs on
    // the V8 execution thread and the Node event loop stays free for the
    // call's whole duration.
    writeln!(out, "    pub async fn {name}(", name = endpoint.name).unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(
            out,
            "        {}: {},",
            sdk_method_arg_name(param),
            ts_napi_arg_type(param)
        )
        .unwrap();
    }
    writeln!(out, "        options: Option<{struct_name}>,").unwrap();

    if is_string_list {
        out.push_str("    ) -> napi::Result<Vec<String>> {\n");
    } else {
        writeln!(
            out,
            "    ) -> napi::Result<Vec<{}>> {{",
            ts_class_name(&endpoint.return_type)
        )
        .unwrap();
    }

    write_ts_request_prelude(&mut out, endpoint, is_string_list);

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");

    if is_string_list {
        let positional_args = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "&refs".into()
                } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                    || is_time_arg(param)
                {
                    format!("{}.as_str()", sdk_method_arg_name(param))
                } else {
                    format!("&{}", sdk_method_arg_name(param))
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        // The builder borrows `client` and the owned params, so it is
        // constructed and awaited inside the spawned future where those
        // values live for `'static`.
        out.push_str("        spawn_endpoint_task(async move {\n");
        if has_symbols {
            out.push_str(
                "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
            );
        }
        writeln!(
            out,
            "            let call = client.historical().{name}({positional_args});",
            name = endpoint.name,
        )
        .unwrap();
        write_timeout_call(&mut out, "            ");
        out.push_str("        })\n");
        out.push_str("        .await\n");
        out.push_str("    }\n");
        return out;
    }

    // Builder-backed endpoints.
    write_ts_builder_request(&mut out, endpoint);
    writeln!(
        out,
        "        Ok({}(&ticks))",
        ts_class_vec_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n");
    out
}

/// Emit the shared method prelude: `options` unwrap, deadline validation,
/// client-handle clone, and the argument / builder-parameter normalization.
/// Byte-identical across the buffered `Array<Tick>` method, the `StringList`
/// list method, and the presence-carrying `<method>WithColumns` variant, so
/// they share one source of the request setup.
fn write_ts_request_prelude(out: &mut String, endpoint: &GeneratedEndpoint, is_string_list: bool) {
    let method_params = method_params(endpoint);
    let builder_params = if is_string_list {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    out.push_str("        let options = options.unwrap_or_default();\n");

    // Validate the per-call deadline up front, before the request task
    // is spawned: the option rides in as a JS `number` (f64), and an
    // `as u64` cast would silently rewrite a non-finite, negative, or
    // fractional value instead of rejecting it. `validate_timeout_ms`
    // returns the integer-domain `u64` the other bindings take, or an
    // `InvalidParameterError`; `?` rejects the Promise synchronously.
    out.push_str("        let timeout_ms = match options.timeout_ms {\n");
    out.push_str("            Some(ms) => Some(validate_timeout_ms(ms)?),\n");
    out.push_str("            None => None,\n");
    out.push_str("        };\n");

    // Clone the `Arc` client handle so the spawned future owns a
    // `'static` borrow source: the request builder borrows the client,
    // and that borrow must outlive the V8 stack frame the Promise
    // detaches from.
    out.push_str("        let client = self.client_handle()?;\n");

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str("        let symbols = normalize_symbols(symbols);\n");
    }
    for param in &method_params {
        let arg_name = sdk_method_arg_name(param);
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(out, "        let {arg_name} = normalize_date({arg_name});").unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(out, "        let {arg_name} = normalize_time({arg_name});").unwrap();
            }
            _ => {}
        }
    }
    for param in &builder_params {
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_date(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_time(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            "Int" => {
                // Validate + narrow the JS `number` to `i32`, rejecting a
                // non-finite, negative, fractional, or out-of-range value
                // with `InvalidParameterError` instead of V8-wrapping it.
                writeln!(
                    out,
                    "        let {name} = validate_optional_nonneg_i32(\"{camel}\", options.{name})?;",
                    name = param.name,
                    camel = napi_field_camel(&param.name),
                )
                .unwrap();
            }
            _ => {
                writeln!(out, "        let {} = options.{};", param.name, param.name).unwrap();
            }
        }
    }
}

/// Emit the builder construction, spawn, and `.await?` for a builder-backed
/// (non-`StringList`) endpoint, binding the decoded `ticks` — a core
/// `Ticks<T>` carrying the response's column presence (`ticks.columns()`).
/// Shared by the buffered `Array<Tick>` method and the `<method>WithColumns`
/// variant, which read the presence off the same `ticks` binding.
fn write_ts_builder_request(out: &mut String, endpoint: &GeneratedEndpoint) {
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                || is_time_arg(param)
            {
                format!("{}.as_str()", sdk_method_arg_name(param))
            } else {
                format!("&{}", sdk_method_arg_name(param))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    // The builder borrows `client` and the owned params, so it is
    // constructed and awaited inside the spawned future where those
    // values live for `'static`.
    out.push_str("        let ticks = spawn_endpoint_task(async move {\n");
    if has_symbols {
        out.push_str(
            "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }
    writeln!(
        out,
        "            let mut request = client.historical().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "            if let Some(value) = {} {{", param.name).unwrap();
        let setter_arg = match param.param_type.as_str() {
            "Int" | "Float" | "Bool" => "value".to_string(),
            _ => "value.as_str()".to_string(),
        };
        writeln!(
            out,
            "                request = request.{}({});",
            param.name, setter_arg
        )
        .unwrap();
        out.push_str("            }\n");
    }
    out.push_str("            if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "                request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("            }\n");
    out.push_str("            request.await\n");
    out.push_str("        })\n");
    out.push_str("        .await?;\n");
}

/// `TradeTick` (the collection's element class) -> `TradeTickWithColumns`, the
/// `#[napi(object)]` return shape of the `<method>WithColumns` variant.
fn with_columns_struct_name(return_type: &str) -> String {
    format!("{}WithColumns", ts_class_name(return_type))
}

/// Emit the `#[napi(object)] <Tick>WithColumns` return struct: the decoded
/// rows plus the response's projected column set and optional broadcast
/// `symbol`. A live caller feeds `presentColumns` (and `symbol`) straight into
/// `<tick>ToArrowIpcProjected` for a terminal-exact columnar frame, without
/// hand-supplying the header list.
fn render_typescript_with_columns_struct(return_type: &str) -> String {
    let tick_class = ts_class_name(return_type);
    let struct_name = with_columns_struct_name(return_type);
    let mut out = String::new();
    writeln!(
        out,
        "/// A decoded history result paired with the columns the response's wire"
    )
    .unwrap();
    out.push_str("/// actually carried. Returned by the `<method>WithColumns` variant so a\n");
    out.push_str("/// live caller can serialize a projected Arrow-IPC frame (only the wire's\n");
    out.push_str("/// columns, matching the terminal's columnar output) without hand-supplying\n");
    writeln!(
        out,
        "/// the header list: pass `presentColumns` and `symbol` to `{}ToArrowIpcProjected`.",
        tick_class.to_lower_camel_case()
    )
    .unwrap();
    out.push_str("#[napi(object)]\n");
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    out.push_str("    /// The decoded rows, identical to the `Array<Tick>` the buffered\n");
    out.push_str("    /// method returns.\n");
    writeln!(out, "    pub rows: Vec<{tick_class}>,").unwrap();
    out.push_str("    /// The schema-column names the response's wire carried, in schema\n");
    out.push_str("    /// order — the projection set for a terminal-exact Arrow frame.\n");
    out.push_str("    pub present_columns: Vec<String>,\n");
    out.push_str("    /// The response's constant `symbol` (root) when the wire carried one\n");
    out.push_str("    /// (option and index responses), else `undefined` (stock responses).\n");
    out.push_str("    pub symbol: Option<String>,\n");
    out.push_str("}\n");
    out
}

/// Emit the `<endpoint>WithColumns` method: the same query as the buffered
/// method, returning the rows plus the response's projected column set and
/// broadcast `symbol` (a `<Tick>WithColumns` object) so the projected
/// Arrow-IPC exit is reachable from a live call — the TypeScript analogue of
/// the C `_with_options` presence out-param and Python's presence-carrying
/// `<Tick>List`. Only emitted for builder-backed (non-`StringList`) endpoints.
fn render_typescript_endpoint_with_columns_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let camel_name = to_camel_case(&endpoint.name);
    let struct_name = options_struct_name(endpoint);
    let return_struct = with_columns_struct_name(&endpoint.return_type);
    let converter = ts_class_vec_converter(&endpoint.return_type);
    let mut out = String::new();

    let doc = format!(
        "Run the `{camel}` query and return the rows together with the columns the \
         response's wire carried, so a projected Arrow-IPC frame is drivable from a \
         live call. Same parameters and result rows as the `{camel}` method; the \
         returned object adds `presentColumns` (the schema columns the wire sent, in \
         schema order) and `symbol` (the response's constant root, set for option and \
         index responses). Feed both to `{tick_camel}ToArrowIpcProjected` for a \
         terminal-exact columnar export that omits the columns the wire omitted.",
        camel = camel_name,
        tick_camel = ts_class_name(&endpoint.return_type).to_lower_camel_case(),
    );
    out.push_str(&render_rust_doc_block("    ", &doc));
    writeln!(out, "    #[napi(js_name = \"{camel_name}WithColumns\")]").unwrap();
    writeln!(
        out,
        "    pub async fn {name}_with_columns(",
        name = endpoint.name
    )
    .unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(
            out,
            "        {}: {},",
            sdk_method_arg_name(param),
            ts_napi_arg_type(param)
        )
        .unwrap();
    }
    writeln!(out, "        options: Option<{struct_name}>,").unwrap();
    writeln!(out, "    ) -> napi::Result<{return_struct}> {{").unwrap();

    write_ts_request_prelude(&mut out, endpoint, false);
    write_ts_builder_request(&mut out, endpoint);

    // The core `Ticks<T>` carries the response's `ColumnPresence`: emit its
    // present schema columns and broadcast `symbol` alongside the converted
    // rows so the projected Arrow terminal is drivable without a header list.
    writeln!(out, "        Ok({return_struct} {{").unwrap();
    writeln!(out, "            rows: {converter}(&ticks),").unwrap();
    out.push_str(
        "            present_columns: ticks.columns().present_names().map(String::from).collect(),\n",
    );
    out.push_str("            symbol: ticks.columns().symbol().map(String::from),\n");
    out.push_str("        })\n");
    out.push_str("    }\n");
    out
}

/// Emit the `<endpoint>Stream(...callback)` server-stream terminal — the
/// TypeScript companion to the Python parsed builder's `.stream(handler)`.
///
/// The method takes the endpoint's required positional parameters, then the
/// same trailing `Options` object the buffered method takes (so `timeoutMs`
/// and every optional builder param ride along identically), and finally a
/// JS `callback`. Each decoded gRPC chunk is converted to the typed row
/// array (`Tick[]`) and delivered to `callback` through a napi-rs
/// `ThreadsafeFunction`, which routes the call onto the Node main thread —
/// the only thread allowed to execute V8. The decoder-owned chunk is dropped
/// the moment the converter returns, so peak memory tracks one chunk, never
/// the full response: the memory-bounded path the `Config` doc points
/// buffered callers at.
///
/// The callback is the LAST positional argument (after the options object)
/// rather than riding inside the options object: a `ThreadsafeFunction`
/// cannot be a `#[napi(object)]` field, and a trailing function argument is
/// the JavaScript idiom for a stream sink. `callback(chunk: Tick[]) => void`
/// is invoked once per gRPC chunk; a slow callback applies bounded
/// back-pressure (`Blocking` call mode) rather than dropping rows.
fn render_typescript_endpoint_stream_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let camel_name = to_camel_case(&endpoint.name);
    let stream_camel = format!("{camel_name}Stream");
    let struct_name = options_struct_name(endpoint);
    let tick_class = ts_class_name(&endpoint.return_type);
    let vec_converter = ts_class_vec_converter(&endpoint.return_type);
    let mut out = String::new();

    let doc = format!(
        "Stream `{name}` rows into `callback` without materialising the full \
         response in memory. `callback(chunk: {tick}[]) => void` is invoked once \
         per server chunk; the chunk is freed before the next is fetched, so peak \
         memory tracks a single chunk rather than the whole result. This is the \
         memory-bounded companion to the `{camel}` method — prefer it \
         for multi-day or full-universe pulls. The returned Promise resolves when \
         the stream drains and rejects (typed like the buffered method) on a wire \
         or decode error. Cancelling the Promise drops the in-flight request. \
         `options` carries the same optional builder parameters and `timeoutMs` \
         as the buffered method; the `callback` is the trailing argument.",
        name = endpoint.name,
        tick = tick_class,
        camel = camel_name,
    );
    out.push_str(&render_rust_doc_block("    ", &doc));
    writeln!(out, "    #[napi(js_name = \"{stream_camel}\")]").unwrap();
    writeln!(out, "    pub async fn {name}_stream(", name = endpoint.name).unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(
            out,
            "        {}: {},",
            sdk_method_arg_name(param),
            ts_napi_arg_type(param)
        )
        .unwrap();
    }
    writeln!(out, "        options: Option<{struct_name}>,").unwrap();
    // `ErrorStrategy::Fatal` (the `false` const generic): the chunk array is
    // passed to `call` directly, not as a `Result`, and a JS-callback throw
    // surfaces through Node's own `uncaughtException` — matching the FPSS
    // streaming callback contract on this same client.
    writeln!(
        out,
        "        callback: napi::threadsafe_function::ThreadsafeFunction<Vec<{tick_class}>, (), Vec<{tick_class}>, napi::Status, false>,"
    )
    .unwrap();
    out.push_str("    ) -> napi::Result<()> {\n");

    out.push_str("        let options = options.unwrap_or_default();\n");
    out.push_str("        let timeout_ms = match options.timeout_ms {\n");
    out.push_str("            Some(ms) => Some(validate_timeout_ms(ms)?),\n");
    out.push_str("            None => None,\n");
    out.push_str("        };\n");
    out.push_str("        let client = self.client_handle()?;\n");

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str("        let symbols = normalize_symbols(symbols);\n");
    }
    for param in &method_params {
        let arg_name = sdk_method_arg_name(param);
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(out, "        let {arg_name} = normalize_date({arg_name});").unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(out, "        let {arg_name} = normalize_time({arg_name});").unwrap();
            }
            _ => {}
        }
    }
    for param in &builder_params {
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_date(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_time(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            "Int" => {
                // Validate + narrow the JS `number` to `i32`, rejecting a
                // non-finite, negative, fractional, or out-of-range value
                // with `InvalidParameterError` instead of V8-wrapping it.
                writeln!(
                    out,
                    "        let {name} = validate_optional_nonneg_i32(\"{camel}\", options.{name})?;",
                    name = param.name,
                    camel = napi_field_camel(&param.name),
                )
                .unwrap();
            }
            _ => {
                writeln!(out, "        let {} = options.{};", param.name, param.name).unwrap();
            }
        }
    }

    // Bind the callback behind an `Arc`: the `FnMut(&[Tick]) + Send` chunk
    // closure the core `request.stream` takes captures the handle, and
    // `ThreadsafeFunction` is `Send + Sync` but does not implement `Clone`
    // in napi-rs 3.x — the outer `Arc` is the canonical share path (same as
    // the FPSS `startStreaming` registration on this client).
    out.push_str("        let callback = std::sync::Arc::new(callback);\n");

    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                || is_time_arg(param)
            {
                format!("{}.as_str()", sdk_method_arg_name(param))
            } else {
                format!("&{}", sdk_method_arg_name(param))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");

    // The builder + the gRPC server-stream run on `runtime()` (the reactor
    // that owns the connection's sockets), spawned off the V8 thread exactly
    // like the buffered method, so the Node event loop stays free for the
    // whole drain.
    out.push_str("        spawn_endpoint_task(async move {\n");
    if has_symbols {
        out.push_str(
            "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }
    writeln!(
        out,
        "            let mut request = client.historical().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "            if let Some(value) = {} {{", param.name).unwrap();
        let setter_arg = match param.param_type.as_str() {
            "Int" | "Float" | "Bool" => "value".to_string(),
            _ => "value.as_str()".to_string(),
        };
        writeln!(
            out,
            "                request = request.{}({});",
            param.name, setter_arg
        )
        .unwrap();
        out.push_str("            }\n");
    }
    out.push_str("            if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "                request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("            }\n");
    // Per-chunk: convert the decoder-owned `&[Tick]` to the typed napi row
    // array and hand it to the `ThreadsafeFunction`. `Blocking` applies
    // bounded back-pressure when the tsfn queue is full (a stalled Node
    // event loop) instead of silently dropping rows; the converted `Vec`
    // and the wire chunk are both dropped before the next chunk is fetched.
    out.push_str("            request\n");
    out.push_str("                .stream(|chunk| {\n");
    writeln!(
        out,
        "                    let rows = {vec_converter}(chunk);"
    )
    .unwrap();
    out.push_str("                    callback.call(rows, napi::threadsafe_function::ThreadsafeFunctionCallMode::Blocking);\n");
    out.push_str("                })\n");
    out.push_str("                .await\n");
    out.push_str("        })\n");
    out.push_str("        .await\n");
    out.push_str("    }\n");
    out
}

fn ts_napi_arg_type(param: &super::super::model::GeneratedParam) -> &'static str {
    if param.param_type == "Symbols" {
        "Either<String, Vec<String>>"
    } else if matches!(param.param_type.as_str(), "Date" | "Expiration") || is_time_arg(param) {
        "Either<String, chrono::DateTime<chrono::Utc>>"
    } else {
        "String"
    }
}

/// Convert a snake_case field name to the lowerCamelCase key napi-rs emits
/// for a `#[napi(object)]` field (`max_dte` -> `maxDte`,
/// `strike_range` -> `strikeRange`). Unlike `to_camel_case`, this performs
/// no acronym uppercasing, so the name matches the literal key a JS caller
/// passes — the key a validation rejection message must echo back.
fn napi_field_camel(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn ts_napi_optional_type(param: &super::super::model::GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        // `Int` filters ride in as a JS `number` (f64) and are validated +
        // narrowed to `i32` in the method body via `validate_optional_nonneg_i32`,
        // rather than typed `i32` here where V8's `ToInt32` would silently
        // wrap a hostile or oversized input instead of rejecting it.
        "Int" => "Option<f64>",
        "Float" => "Option<f64>",
        "Bool" => "Option<bool>",
        "Date" | "Expiration" => "Option<Either<String, chrono::DateTime<chrono::Utc>>>",
        _ if is_time_arg(param) => "Option<Either<String, chrono::DateTime<chrono::Utc>>>",
        _ => "Option<String>",
    }
}
