//! Build-time generator orchestration for `thetadatadx`.
//!
//! The build pipeline has three responsibilities:
//! - compile `proto/mdds.proto` and emit in-house gRPC client stubs
//!   (`grpc::run` drives `prost-build` with our custom service
//!   generator — no `tonic-build`);
//! - generate tick decoders from `tick_schema.toml`;
//! - generate endpoint-facing surfaces from the explicit endpoint
//!   spec plus the upstream wire contract in `proto/mdds.proto`.

mod endpoints;
mod grpc;
mod ticks;

pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    grpc::run()?;
    // Drift check runs unconditionally: prost-build re-emits the
    // generated stubs into `$OUT_DIR/beta_endpoints.rs`, and we
    // confirm the regenerated bytes match the file already on disk.
    // The check is strictly read-only — when the snapshot needs to
    // change, contributors run the `refresh_grpc_snapshot` binary
    // (see the module docs in `grpc/mod.rs`). The build script never
    // writes to the source tree.
    grpc::check()?;
    endpoints::generate_all()?;
    ticks::generate()?;
    Ok(())
}
