// Reason: shared between build.rs (which calls `generate`) and the
// `generate_sdk_surfaces` binary (which calls only the `*_sdk_generated_files`
// entry points) via `#[path]`. Not every helper is reachable from both
// entry points, so mark the whole module as allowed-dead once rather than
// annotating each helper individually.
#![allow(dead_code, unused_imports)]

// ─────────────────────────────────────────────────────────────────────────────
//  Code-generate tick structs + parsers from tick_schema.toml
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct Schema {
    types: HashMap<String, TickTypeDef>,
}

/// Parsed from tick_schema.toml. `doc`, `copy`, and `align` exist in the
/// TOML for documentation / FFI layout hints but are not used by the parser
/// generator — tick structs live in `tdbe::types::tick` (hand-written).
#[derive(Debug, Deserialize)]
struct TickTypeDef {
    doc: String,
    copy: bool,
    #[serde(default)]
    align: Option<u32>,
    parser: String,
    #[serde(default)]
    required: Vec<String>,
    #[serde(default)]
    eod_style: bool,
    #[serde(default)]
    contract_id: bool,
    columns: Vec<ColumnDef>,
}

#[derive(Debug, Deserialize)]
struct ColumnDef {
    name: String,
    field: String,
    r#type: String,
}

pub fn generate() -> Result<(), Box<dyn std::error::Error>> {
    let schema_path = "tick_schema.toml";
    let schema_str = std::fs::read_to_string(schema_path)?;
    let schema: Schema = toml::from_str(&schema_str)?;

    let out_dir = std::env::var("OUT_DIR")?;

    // Collect type names and sort for deterministic output.
    let mut type_names: Vec<&String> = schema.types.keys().collect();
    type_names.sort();

    // ── Generate decode_generated.rs (parser functions) ──────────────────────
    // Struct definitions now live in the `tdbe` crate (crates/tdbe/src/types/tick.rs).
    // Only parser functions are generated here. Parsers return
    // `Result<Vec<Tick>, DecodeError>`; each cell access threads `?` so that a
    // type mismatch in one row fails the whole table, matching Java terminal
    // semantics (see PojoMessageUtils.convert).
    let mut parsers = String::new();
    parsers
        .push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n\n");
    // Note: tick types are imported by decode.rs via `use tdbe::types::tick::*;`
    // No additional imports needed in the generated code.

    for type_name in &type_names {
        let def = &schema.types[*type_name];
        generate_parser(&mut parsers, type_name, def);
    }

    let parsers_dest = Path::new(&out_dir).join("decode_generated.rs");
    std::fs::write(&parsers_dest, &parsers)?;

    // Rerun if schema changes
    println!("cargo:rerun-if-changed={schema_path}");

    Ok(())
}

/// Generate a single parser function.
///
/// Price columns are decoded to `f64` during extraction using the wire
/// `price_type` (internally fetched, never exposed on the public struct).
/// The emitted parser returns `Result<Vec<T>, DecodeError>` and threads `?`
/// on every cell access so a type mismatch in one row fails the whole table.
// Reason: code generator -- the match dispatch over column types cannot be meaningfully split.
#[allow(clippy::too_many_lines)]
fn generate_parser(out: &mut String, type_name: &str, def: &TickTypeDef) {
    let fn_name = &def.parser;

    writeln!(
        out,
        "pub fn {fn_name}(table: &crate::proto::DataTable) -> Result<Vec<{type_name}>, DecodeError> {{"
    )
    .unwrap();

    // If eod_style, emit the local EOD helpers inline.
    if def.eod_style {
        out.push_str(
            "    // EOD numeric/time fields may arrive as Price, Number, or Timestamp cells.\n",
        );
        out.push_str("    fn eod_num(row: &crate::proto::DataValueList, idx: usize) -> Result<i32, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as i32),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(p.value),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(crate::decode::timestamp_to_ms_of_day(ts.epoch_ms)),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD date fields may arrive as Price, Number, or Timestamp cells.\n");
        out.push_str("    fn eod_date(row: &crate::proto::DataValueList, idx: usize) -> Result<i32, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as i32),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(p.value),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(crate::decode::timestamp_to_date(ts.epoch_ms)),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD price field: decode to f64 from Price or Number cell.\n");
        out.push_str("    fn eod_price(row: &crate::proto::DataValueList, idx: usize) -> Result<f64, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str("            Some(crate::proto::data_value::DataType::Price(p)) => Ok(tdbe::types::price::Price::new(p.value, p.r#type).to_f64()),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as f64),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0.0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Price|Number\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Price|Number\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");
    }

    out.push_str("    let h: Vec<&str> = table.headers.iter().map(|s| s.as_str()).collect();\n");

    // For eod_style, use the shared find_header() from decode.rs.
    if def.eod_style {
        out.push_str("    let find = |name: &str| find_header(&h, name);\n\n");
    }

    // Determine which columns need helpers.
    let needs_opt_number = def
        .columns
        .iter()
        .any(|c| c.r#type == "i32" && !def.required.contains(&c.name) && c.field != "date");
    let needs_opt_float = def
        .columns
        .iter()
        .any(|c| c.r#type == "f64" && !def.required.contains(&c.name));
    let needs_opt_i64 = def
        .columns
        .iter()
        .any(|c| c.r#type == "i64" && !def.required.contains(&c.name));

    // Emit opt_number / opt_float / opt_i64 helpers (non-eod only). Each
    // returns `Result<T, DecodeError>`: absent column or NullValue → default,
    // type mismatch → error propagated.
    if !def.eod_style {
        if needs_opt_number {
            out.push_str("    fn opt_number(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<i32, DecodeError> {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_number(row, i)?.unwrap_or(0)),\n");
            out.push_str("            None => Ok(0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_float {
            // `f64` columns (greeks, IV, interest rates) legitimately arrive
            // as Price or Number on the v3 MDDS server; dispatch on the wire
            // type the same way Java's `dataValue2Object` does (PRICE →
            // BigDecimal, NUMBER → Long). See `row_price_f64` for the
            // accept-list.
            out.push_str("    fn opt_float(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<f64, DecodeError> {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_price_f64(row, i)?.unwrap_or(0.0)),\n");
            out.push_str("            None => Ok(0.0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_i64 {
            out.push_str(
                "    fn opt_i64(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<i64, DecodeError> {\n",
            );
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_number_i64(row, i)?.unwrap_or(0)),\n");
            out.push_str("            None => Ok(0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
    }

    // Required header guards (non-eod only).
    if !def.eod_style {
        for req in &def.required {
            let var = format!("{req}_idx");
            writeln!(out,
                "    let Some({var}) = find_header(&h, \"{req}\") else {{\n        return Ok(vec![]);\n    }};"
            ).unwrap();
        }
        if !def.required.is_empty() {
            out.push('\n');
        }
    }

    // Declare index variables for all columns.
    for col in &def.columns {
        let var = format!("{}_idx", col.name);
        if def.eod_style {
            writeln!(out, "    let {var} = find(\"{}\");", col.name).unwrap();
        } else if def.required.contains(&col.name) {
            // Already declared above as required.
        } else {
            writeln!(out, "    let {var} = find_header(&h, \"{}\");", col.name).unwrap();
        }
    }

    // Contract identification columns (wildcard queries inject expiration/strike/right).
    if def.contract_id {
        out.push_str("    let _cid_exp_idx = h.iter().position(|c| *c == \"expiration\");\n");
        out.push_str("    let _cid_strike_idx = h.iter().position(|c| *c == \"strike\");\n");
        out.push_str("    let _cid_right_idx = h.iter().position(|c| *c == \"right\");\n");
        out.push_str("    let _cid_strike_is_typed = _cid_strike_idx.is_some() && h.contains(&\"strike\");\n");
    }

    // Check if this is QuoteTick (needs midpoint computation).
    let is_quote_tick = type_name == "QuoteTick";

    out.push('\n');

    // Emit the row mapping. Each row produces a `Result<Tick, DecodeError>`;
    // `.collect::<Result<Vec<_>, _>>()` short-circuits on the first error.
    out.push_str("    table\n");
    out.push_str("        .data_table\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|row| {\n");

    // Struct literal.
    if is_quote_tick {
        writeln!(out, "            let _tick = {type_name} {{").unwrap();
    } else {
        writeln!(out, "            Ok({type_name} {{").unwrap();
    }

    for col in &def.columns {
        let var = format!("{}_idx", col.name);
        let is_required = def.required.contains(&col.name);

        match col.r#type.as_str() {
            "i32" => {
                if def.eod_style {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => eod_num(row, i)?, None => 0 }},",
                        col.field
                    )
                    .unwrap();
                } else if is_required {
                    if col.field == "date" {
                        writeln!(
                            out,
                            "                {}: row_date(row, {var})?.unwrap_or(0),",
                            col.field
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            out,
                            "                {}: row_number(row, {var})?.unwrap_or(0),",
                            col.field
                        )
                        .unwrap();
                    }
                } else if col.field == "date" {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => row_date(row, i)?.unwrap_or(0), None => 0 }},",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: opt_number(row, {var})?,",
                        col.field
                    )
                    .unwrap();
                }
            }
            "i64" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_number_i64(row, {var})?.unwrap_or(0),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(out, "                {}: opt_i64(row, {var})?,", col.field).unwrap();
                }
            }
            "f64" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_price_f64(row, {var})?.unwrap_or(0.0),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: opt_float(row, {var})?,",
                        col.field
                    )
                    .unwrap();
                }
            }
            "String" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_text(row, {var})?.unwrap_or_default(),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => row_text(row, i)?.unwrap_or_default(), None => String::new() }},",
                        col.field
                    )
                    .unwrap();
                }
            }
            "price" => {
                // Decode price to f64 at parse time.
                let field = &col.field;
                if is_required {
                    writeln!(
                        out,
                        "                {field}: row_price_f64(row, {var})?.unwrap_or(0.0),"
                    )
                    .unwrap();
                } else {
                    writeln!(out, "                {field}: match {var} {{").unwrap();
                    out.push_str(
                        "                    Some(i) => row_price_f64(row, i)?.unwrap_or(0.0),\n",
                    );
                    out.push_str("                    None => 0.0,\n");
                    out.push_str("                },\n");
                }
            }
            "eod_num" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_num(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_date" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_date(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_price" => {
                // EOD price field: decode to f64 from Price or Number cell.
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_price(row, i)?, None => 0.0 }},",
                    col.field
                )
                .unwrap();
            }
            other => panic!("unknown column type '{other}' in parser for {type_name}"),
        }
    }

    // Contract identification fields (injected when contract_id = true). The
    // `expiration` column legitimately arrives as Number (YYYYMMDD) or Text
    // (ISO "2026-04-13") depending on upstream version — dispatch on the
    // cell's own type rather than coalescing silently.
    if def.contract_id {
        out.push_str("                expiration: match _cid_exp_idx {\n");
        out.push_str("                    Some(i) => {\n");
        out.push_str("                        let dv = row.values.get(i).ok_or(DecodeError::MissingCell { column: i })?;\n");
        out.push_str("                        match dv.data_type.as_ref() {\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Number(n)) => *n as i32,\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Text(s)) => parse_iso_date(s),\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::NullValue(_)) => 0,\n");
        out.push_str(
            "                            None => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str("                                observed: \"Unset\",\n");
        out.push_str("                            }),\n");
        out.push_str(
            "                            other => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str(
            "                                observed: crate::decode::observed_name(other),\n",
        );
        out.push_str("                            }),\n");
        out.push_str("                        }\n");
        out.push_str("                    }\n");
        out.push_str("                    None => 0,\n");
        out.push_str("                },\n");
        // strike: decode to f64
        out.push_str("                strike: match _cid_strike_idx {\n");
        out.push_str(
            "                    Some(i) if _cid_strike_is_typed => row_price_f64(row, i)?.unwrap_or(0.0),\n",
        );
        out.push_str("                    Some(i) => row_number(row, i)?.unwrap_or(0) as f64,\n");
        out.push_str("                    None => 0.0,\n");
        out.push_str("                },\n");
        // right: ASCII code (Number) or text (Text) — strict dispatch.
        out.push_str("                right: match _cid_right_idx {\n");
        out.push_str("                    Some(i) => {\n");
        out.push_str("                        let dv = row.values.get(i).ok_or(DecodeError::MissingCell { column: i })?;\n");
        out.push_str("                        match dv.data_type.as_ref() {\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Number(n)) => *n as i32,\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Text(s)) => match s.as_str() {\n");
        out.push_str("                                \"CALL\" | \"C\" => 67,\n");
        out.push_str("                                \"PUT\" | \"P\" => 80,\n");
        out.push_str("                                _ => 0,\n");
        out.push_str("                            },\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::NullValue(_)) => 0,\n");
        out.push_str(
            "                            None => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str("                                observed: \"Unset\",\n");
        out.push_str("                            }),\n");
        out.push_str(
            "                            other => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str(
            "                                observed: crate::decode::observed_name(other),\n",
        );
        out.push_str("                            }),\n");
        out.push_str("                        }\n");
        out.push_str("                    }\n");
        out.push_str("                    None => 0,\n");
        out.push_str("                },\n");
    }

    if is_quote_tick {
        // QuoteTick gets midpoint computed from bid + ask.
        out.push_str("                midpoint: 0.0, // placeholder, set below\n");
        out.push_str("            };\n");
        out.push_str("            let mut _tick = _tick;\n");
        out.push_str("            _tick.midpoint = (_tick.bid + _tick.ask) / 2.0;\n");
        out.push_str("            Ok(_tick)\n");
    } else {
        out.push_str("            })\n");
    }

    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n\n");
}

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

use serde::Deserialize;

pub struct GeneratedSourceFile {
    pub relative_path: &'static str,
    pub contents: String,
}

pub fn write_sdk_generated_files(repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    for file in render_sdk_generated_files()? {
        let path = repo_root.join(file.relative_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, file.contents)?;
    }
    Ok(())
}

pub fn check_sdk_generated_files(repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    for file in render_sdk_generated_files()? {
        let path = repo_root.join(file.relative_path);
        let actual = std::fs::read_to_string(&path)?;
        if actual.replace("\r\n", "\n") != file.contents {
            return Err(format!(
                "generated SDK surface '{}' is stale; run `cargo run -p thetadatadx --bin generate_sdk_surfaces` to refresh",
                file.relative_path
            )
            .into());
        }
    }
    Ok(())
}

fn render_sdk_generated_files() -> Result<Vec<GeneratedSourceFile>, Box<dyn std::error::Error>> {
    let schema = load_schema()?;
    Ok(vec![
        GeneratedSourceFile {
            relative_path: "sdks/python/src/tick_columnar.rs",
            contents: render_python_tick_columnar(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/python/src/tick_classes.rs",
            contents: render_python_tick_classes(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/go/tick_converters.go",
            contents: render_go_tick_converters(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/go/tick_structs.go",
            contents: render_go_tick_structs(&schema),
        },
        GeneratedSourceFile {
            relative_path: "tools/cli/src/raw_headers_generated.rs",
            contents: render_cli_raw_headers(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/typescript/src/tick_columnar.rs",
            contents: render_ts_tick_columnar(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/typescript/src/tick_classes.rs",
            contents: render_ts_tick_classes(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/typescript/src/types.ts",
            contents: render_ts_tick_types(&schema),
        },
    ])
}

fn load_schema() -> Result<Schema, Box<dyn std::error::Error>> {
    let schema_path = "tick_schema.toml";
    let schema_str = std::fs::read_to_string(schema_path)?;
    let schema: Schema = toml::from_str(&schema_str)?;
    Ok(schema)
}

fn sorted_type_names(schema: &Schema) -> Vec<&str> {
    let mut names = schema.types.keys().map(String::as_str).collect::<Vec<_>>();
    names.sort();
    names
}

fn render_python_tick_columnar(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Columnar converters: dict-of-lists instead of list-of-dicts.\n");
    out.push_str(
        "// Each function returns a single Python dict where each key maps to a list of values.\n",
    );
    out.push_str("// This is the fastest input format for pd.DataFrame().\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_python_tick_columnar_fn(type_name, def));
        out.push('\n');
    }
    out
}

fn render_cli_raw_headers(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        let const_name = cli_raw_header_const_name(type_name);
        let headers = cli_raw_headers(type_name, def);
        writeln!(out, "pub(crate) const {const_name}: &[&str] = &[").unwrap();
        for header in headers {
            writeln!(out, "    {header:?},").unwrap();
        }
        out.push_str("];\n\n");
    }
    out
}

fn cli_raw_header_const_name(type_name: &str) -> &'static str {
    match type_name {
        "CalendarDay" => "CALENDAR_DAY_RAW_HEADERS",
        "EodTick" => "EOD_TICK_RAW_HEADERS",
        "GreeksTick" => "GREEKS_TICK_RAW_HEADERS",
        "InterestRateTick" => "INTEREST_RATE_TICK_RAW_HEADERS",
        "IvTick" => "IV_TICK_RAW_HEADERS",
        "MarketValueTick" => "MARKET_VALUE_TICK_RAW_HEADERS",
        "OhlcTick" => "OHLC_TICK_RAW_HEADERS",
        "OpenInterestTick" => "OPEN_INTEREST_TICK_RAW_HEADERS",
        "OptionContract" => "OPTION_CONTRACT_RAW_HEADERS",
        "PriceTick" => "PRICE_TICK_RAW_HEADERS",
        "QuoteTick" => "QUOTE_TICK_RAW_HEADERS",
        "TradeQuoteTick" => "TRADE_QUOTE_TICK_RAW_HEADERS",
        "TradeTick" => "TRADE_TICK_RAW_HEADERS",
        other => panic!("unsupported CLI raw-header type: {other}"),
    }
}

fn cli_raw_headers(type_name: &str, def: &TickTypeDef) -> Vec<String> {
    let mut headers: Vec<String> = def
        .columns
        .iter()
        .map(|column| column.name.clone())
        .collect();
    if type_name == "QuoteTick" {
        headers.push("midpoint".to_string());
    }
    if def.contract_id {
        headers.extend(
            ["expiration", "strike", "right"]
                .into_iter()
                .map(std::string::ToString::to_string),
        );
    }
    headers
}

fn render_python_tick_columnar_fn(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = match type_name {
        "EodTick" => "eod_ticks_to_columnar",
        "OhlcTick" => "ohlc_ticks_to_columnar",
        "TradeTick" => "trade_ticks_to_columnar",
        "QuoteTick" => "quote_ticks_to_columnar",
        "TradeQuoteTick" => "trade_quote_ticks_to_columnar",
        "OpenInterestTick" => "open_interest_ticks_to_columnar",
        "MarketValueTick" => "market_value_ticks_to_columnar",
        "GreeksTick" => "greeks_ticks_to_columnar",
        "IvTick" => "iv_ticks_to_columnar",
        "PriceTick" => "price_ticks_to_columnar",
        "CalendarDay" => "calendar_days_to_columnar",
        "InterestRateTick" => "interest_rate_ticks_to_columnar",
        "OptionContract" => "option_contracts_to_columnar",
        other => panic!("unsupported Python tick columnar type: {other}"),
    };

    writeln!(
        out,
        "fn {fn_name}(py: Python<'_>, ticks: &[tick::{type_name}]) -> Py<PyAny> {{"
    )
    .unwrap();
    out.push_str("    let n = ticks.len();\n");

    // Collect each column into a Vec.
    for column in &def.columns {
        let col_type = match column.r#type.as_str() {
            "i32" | "eod_num" | "eod_date" => "i32",
            "i64" => "i64",
            "f64" | "price" | "eod_price" => "f64",
            "String" => "String",
            other => panic!("unsupported column type '{other}' in columnar for {type_name}"),
        };
        if col_type == "String" {
            writeln!(
                out,
                "    let col_{}: Vec<String> = ticks.iter().map(|t| t.{}.clone()).collect();",
                column.field, column.field
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "    let col_{}: Vec<{col_type}> = Vec::with_capacity(n);",
                column.field
            )
            .unwrap();
        }
    }

    // Wait, I need to actually collect. Let me redo this properly.
    // Actually the with_capacity approach is wrong since I'm not pushing. Let me use map/collect.
    // Rewrite: all columns use map/collect.

    // Actually let me clear what I just wrote and re-approach cleanly.
    out.clear();

    writeln!(
        out,
        "fn {fn_name}(py: Python<'_>, ticks: &[tick::{type_name}]) -> Py<PyAny> {{"
    )
    .unwrap();

    // For QuoteTick, also need midpoint.
    let is_quote_tick = type_name == "QuoteTick";

    // Collect each column.
    for column in &def.columns {
        let rust_type = match column.r#type.as_str() {
            "i32" | "eod_num" | "eod_date" => "i32",
            "i64" => "i64",
            "f64" | "price" | "eod_price" => "f64",
            "String" => "String",
            other => panic!("unsupported column type '{other}' in columnar for {type_name}"),
        };
        if rust_type == "String" {
            writeln!(
                out,
                "    let col_{field}: Vec<&str> = ticks.iter().map(|t| t.{field}.as_str()).collect();",
                field = column.field
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "    let col_{field}: Vec<{rust_type}> = ticks.iter().map(|t| t.{field}).collect();",
                field = column.field
            )
            .unwrap();
        }
    }

    // Midpoint for QuoteTick.
    if is_quote_tick {
        out.push_str(
            "    let col_midpoint: Vec<f64> = ticks.iter().map(|t| t.midpoint).collect();\n",
        );
    }

    // Contract ID columns (conditional -- only rows where expiration != 0 have them,
    // but for columnar we always include the columns; 0/"" for non-contract ticks).
    if def.contract_id {
        out.push_str(
            "    let col_expiration: Vec<i32> = ticks.iter().map(|t| t.expiration).collect();\n",
        );
        out.push_str("    let col_strike: Vec<f64> = ticks.iter().map(|t| t.strike).collect();\n");
        out.push_str(
            "    let col_right: Vec<&str> = ticks.iter().map(|t| if t.is_call() { \"C\" } else if t.is_put() { \"P\" } else { \"\" }).collect();\n",
        );
    }

    // Build the dict.
    out.push_str("    let dict = PyDict::new(py);\n");
    for column in &def.columns {
        writeln!(
            out,
            "    dict.set_item({:?}, col_{}).unwrap();",
            column.name, column.field
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("    dict.set_item(\"midpoint\", col_midpoint).unwrap();\n");
    }
    if def.contract_id {
        out.push_str("    dict.set_item(\"expiration\", col_expiration).unwrap();\n");
        out.push_str("    dict.set_item(\"strike\", col_strike).unwrap();\n");
        out.push_str("    dict.set_item(\"right\", col_right).unwrap();\n");
    }
    out.push_str("    dict.into_any().unbind()\n");
    out.push_str("}\n");
    out
}

// ── Python typed-pyclass tick path ────────────────────────────────────────
//
// Generates one `#[pyclass]` struct per tick schema plus a per-tick
// `*_to_pyclass_list` converter that returns a `Py<PyList>` of those classes.
// This is the primary return shape for all historical endpoint methods —
// matches the typed-struct approach already used by Rust core, TypeScript,
// Go, and C++ FFI. The existing `*_to_columnar` converters above remain for
// internal DataFrame-helper use.

fn pyclass_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "EodTick",
        "OhlcTick" => "OhlcTick",
        "TradeTick" => "TradeTick",
        "QuoteTick" => "QuoteTick",
        "TradeQuoteTick" => "TradeQuoteTick",
        "OpenInterestTick" => "OpenInterestTick",
        "MarketValueTick" => "MarketValueTick",
        "GreeksTick" => "GreeksTick",
        "IvTick" => "IvTick",
        "PriceTick" => "PriceTick",
        "CalendarDay" => "CalendarDay",
        "InterestRateTick" => "InterestRateTick",
        "OptionContract" => "OptionContract",
        other => panic!("unsupported Python pyclass type: {other}"),
    }
}

fn python_list_fn_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "eod_ticks_to_pyclass_list",
        "OhlcTick" => "ohlc_ticks_to_pyclass_list",
        "TradeTick" => "trade_ticks_to_pyclass_list",
        "QuoteTick" => "quote_ticks_to_pyclass_list",
        "TradeQuoteTick" => "trade_quote_ticks_to_pyclass_list",
        "OpenInterestTick" => "open_interest_ticks_to_pyclass_list",
        "MarketValueTick" => "market_value_ticks_to_pyclass_list",
        "GreeksTick" => "greeks_ticks_to_pyclass_list",
        "IvTick" => "iv_ticks_to_pyclass_list",
        "PriceTick" => "price_ticks_to_pyclass_list",
        "CalendarDay" => "calendar_days_to_pyclass_list",
        "InterestRateTick" => "interest_rate_ticks_to_pyclass_list",
        "OptionContract" => "option_contracts_to_pyclass_list",
        other => panic!("unsupported Python list fn: {other}"),
    }
}

fn render_python_tick_classes(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Typed pyclass structs per tick type + list converters.\n");
    out.push_str("// Matches the typed-struct approach used by Rust core, TypeScript, Go,\n");
    out.push_str("// and C++ FFI. Primary return shape for historical endpoint methods.\n\n");

    let type_names = sorted_type_names(schema);

    // Structs + pymethods.
    for type_name in &type_names {
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_class_struct(type_name, def));
        out.push('\n');
    }

    // List converters.
    for type_name in &type_names {
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_class_list_fn(type_name, def));
        out.push('\n');
    }

    // Registration helper.
    out.push_str(
        "pub(crate) fn register_tick_classes(m: &Bound<'_, PyModule>) -> PyResult<()> {\n",
    );
    for type_name in &type_names {
        writeln!(out, "    m.add_class::<{}>()?;", pyclass_name(type_name)).unwrap();
    }
    out.push_str("    Ok(())\n}\n");
    out
}

fn render_python_tick_class_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";
    let doc_text = if def.doc.is_empty() {
        format!("Typed {type_name} record.")
    } else {
        def.doc.clone()
    };
    for line in doc_text.lines() {
        writeln!(out, "/// {line}").unwrap();
    }
    out.push_str("#[pyclass(module = \"thetadatadx\", frozen)]\n");
    out.push_str("#[derive(Clone)]\n");
    writeln!(out, "pub(crate) struct {class} {{").unwrap();
    for column in &def.columns {
        // Special case: `OptionContract.right` is stored on the wire as
        // `i32` (ASCII 67/80), but every other tick surfaces `right` as
        // a Python `"C" | "P" | ""` string (via the contract_id injection
        // below). Emit it as String here too so the two paths match and
        // consumer code doesn't get an integer on one endpoint and a
        // string on the others.
        let rust_type = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            pyclass_field_type(column.r#type.as_str(), type_name)
        };
        writeln!(out, "    #[pyo3(get)] pub {}: {},", column.field, rust_type).unwrap();
    }
    if is_quote_tick {
        out.push_str("    #[pyo3(get)] pub midpoint: f64,\n");
    }
    if def.contract_id {
        out.push_str("    #[pyo3(get)] pub expiration: i32,\n");
        out.push_str("    #[pyo3(get)] pub strike: f64,\n");
        out.push_str("    #[pyo3(get)] pub right: String,\n");
    }
    out.push_str("}\n");

    // __repr__ for discoverability.
    writeln!(out, "#[pymethods]").unwrap();
    writeln!(out, "impl {class} {{").unwrap();
    writeln!(
        out,
        "    fn __repr__(&self) -> String {{ format!(\"{class}(...)\") }}"
    )
    .unwrap();
    out.push_str("}\n");
    out
}

fn pyclass_field_type(column_type: &str, type_name: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" => "i64",
        "f64" | "price" | "eod_price" => "f64",
        "String" => "String",
        other => panic!("unsupported column type '{other}' in pyclass for {type_name}"),
    }
}

fn render_python_tick_class_list_fn(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let fn_name = python_list_fn_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";

    writeln!(
        out,
        "pub(crate) fn {fn_name}(py: Python<'_>, ticks: &[tick::{type_name}]) -> PyResult<Py<PyAny>> {{"
    )
    .unwrap();
    out.push_str("    let list = pyo3::types::PyList::empty(py);\n");
    out.push_str("    for t in ticks {\n");
    writeln!(out, "        let obj = {class} {{").unwrap();
    for column in &def.columns {
        // Special case: `OptionContract.right` emits as a
        // `"C" | "P" | ""` string (see struct emitter above). Other
        // ticks get the String `right` from the contract_id injection
        // below; this keeps the standalone OptionContract endpoint in
        // sync so consumers never see a raw `67` / `80` / `0` on one
        // endpoint and a character on every other.
        if type_name == "OptionContract" && column.field == "right" {
            out.push_str(
                "            right: (if t.is_call() { \"C\" } else if t.is_put() { \"P\" } else { \"\" }).to_string(),\n",
            );
            continue;
        }
        let rust_type = pyclass_field_type(column.r#type.as_str(), type_name);
        if rust_type == "String" {
            writeln!(
                out,
                "            {}: t.{}.clone(),",
                column.field, column.field
            )
            .unwrap();
        } else {
            writeln!(out, "            {}: t.{},", column.field, column.field).unwrap();
        }
    }
    if is_quote_tick {
        out.push_str("            midpoint: t.midpoint,\n");
    }
    if def.contract_id {
        out.push_str("            expiration: t.expiration,\n");
        out.push_str("            strike: t.strike,\n");
        out.push_str(
            "            right: (if t.is_call() { \"C\" } else if t.is_put() { \"P\" } else { \"\" }).to_string(),\n",
        );
    }
    out.push_str("        };\n");
    out.push_str("        list.append(Py::new(py, obj)?)?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(list.into_any().unbind())\n");
    out.push_str("}\n");
    out
}

// ── TypeScript tick columnar converters (serde_json) ──────────────────────

fn render_ts_tick_columnar(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Columnar converters: JSON object where each key maps to an array.\n");
    out.push_str("// Returned as serde_json::Value for napi serialization.\n");
    out.push_str("//\n");
    out.push_str("// Opt-in path kept alongside the typed tick classes so DataFrame-style\n");
    out.push_str("// consumers can still get column arrays in one allocation. Each function\n");
    out.push_str("// is `#[allow(dead_code)]` because the default endpoint surface now\n");
    out.push_str("// returns typed `Vec<Tick>` instead.\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_columnar_fn(type_name, def));
        out.push('\n');
    }
    out
}

fn render_ts_tick_columnar_fn(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = match type_name {
        "EodTick" => "eod_ticks_to_columnar",
        "OhlcTick" => "ohlc_ticks_to_columnar",
        "TradeTick" => "trade_ticks_to_columnar",
        "QuoteTick" => "quote_ticks_to_columnar",
        "TradeQuoteTick" => "trade_quote_ticks_to_columnar",
        "OpenInterestTick" => "open_interest_ticks_to_columnar",
        "MarketValueTick" => "market_value_ticks_to_columnar",
        "GreeksTick" => "greeks_ticks_to_columnar",
        "IvTick" => "iv_ticks_to_columnar",
        "PriceTick" => "price_ticks_to_columnar",
        "CalendarDay" => "calendar_days_to_columnar",
        "InterestRateTick" => "interest_rate_ticks_to_columnar",
        "OptionContract" => "option_contracts_to_columnar",
        other => panic!("unsupported TypeScript tick columnar type: {other}"),
    };

    out.push_str("#[allow(dead_code)]\n");
    writeln!(
        out,
        "fn {fn_name}(ticks: &[tick::{type_name}]) -> serde_json::Value {{"
    )
    .unwrap();

    let is_quote_tick = type_name == "QuoteTick";

    // Collect each column.
    for column in &def.columns {
        let rust_type = match column.r#type.as_str() {
            "i32" | "eod_num" | "eod_date" => "i32",
            "i64" => "i64",
            "f64" | "price" | "eod_price" => "f64",
            "String" => "String",
            other => panic!("unsupported column type '{other}' in TS columnar for {type_name}"),
        };
        if rust_type == "String" {
            writeln!(
                out,
                "    let col_{field}: Vec<&str> = ticks.iter().map(|t| t.{field}.as_str()).collect();",
                field = column.field
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "    let col_{field}: Vec<{rust_type}> = ticks.iter().map(|t| t.{field}).collect();",
                field = column.field
            )
            .unwrap();
        }
    }

    if is_quote_tick {
        out.push_str(
            "    let col_midpoint: Vec<f64> = ticks.iter().map(|t| t.midpoint).collect();\n",
        );
    }

    if def.contract_id {
        out.push_str(
            "    let col_expiration: Vec<i32> = ticks.iter().map(|t| t.expiration).collect();\n",
        );
        out.push_str("    let col_strike: Vec<f64> = ticks.iter().map(|t| t.strike).collect();\n");
        out.push_str(
            "    let col_right: Vec<&str> = ticks.iter().map(|t| if t.is_call() { \"C\" } else if t.is_put() { \"P\" } else { \"\" }).collect();\n",
        );
    }

    out.push_str("    serde_json::json!({\n");
    for column in &def.columns {
        writeln!(out, "        {:?}: col_{},", column.name, column.field).unwrap();
    }
    if is_quote_tick {
        out.push_str("        \"midpoint\": col_midpoint,\n");
    }
    if def.contract_id {
        out.push_str("        \"expiration\": col_expiration,\n");
        out.push_str("        \"strike\": col_strike,\n");
        out.push_str("        \"right\": col_right,\n");
    }
    out.push_str("    })\n");
    out.push_str("}\n");
    out
}

// ── TypeScript tick classes (#[napi(object)] structs) ────────────────────
//
// Each tick type is emitted as a flat `#[napi(object)]` struct so napi-rs
// generates a matching TypeScript interface in `index.d.ts`. Vec<Tick>
// returns from endpoint methods become `Tick[]` in TS — every historical
// endpoint is fully typed, no `any`.
//
// A parallel `{snake_type}_to_class_vec(&[tick::Type]) -> Vec<Type>` helper
// copies Rust tick structs (from `tdbe::types::tick`) into the #[napi]
// types. The helpers are drop-in substitutes for the `..._to_columnar`
// converters used previously.

fn render_ts_tick_classes(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Typed #[napi(object)] tick structs + Vec factories. Replaces the old\n");
    out.push_str(
        "// serde_json columnar returns with concrete TypeScript types in index.d.ts.\n\n",
    );
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_struct(type_name, def));
        out.push('\n');
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_factory(type_name, def));
        out.push('\n');
    }
    out
}

fn render_ts_tick_class_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let is_quote_tick = type_name == "QuoteTick";
    // Strip " -- N fields[...]." from doc so the TS class reflects true field
    // count once contract-id columns + midpoint are appended.
    let first_line = def.doc.lines().next().unwrap_or("");
    let doc = if let Some(pos) = first_line.find(" -- ") {
        let after_dash = &first_line[pos + 4..];
        if after_dash.starts_with(|c: char| c.is_ascii_digit()) {
            let rest = after_dash
                .find(". ")
                .map(|i| &after_dash[i + 2..])
                .unwrap_or("");
            if rest.is_empty() {
                format!("{}.", &first_line[..pos])
            } else {
                format!("{}. {rest}", &first_line[..pos])
            }
        } else {
            first_line.to_string()
        }
    } else {
        first_line.to_string()
    };
    writeln!(out, "/// {doc}").unwrap();
    out.push_str("#[napi(object)]\n");
    out.push_str("#[derive(Clone)]\n");
    writeln!(out, "pub struct {type_name} {{").unwrap();
    for column in &def.columns {
        let rust_type = ts_class_rust_type(&column.r#type, type_name, &column.field);
        writeln!(out, "    pub {}: {},", column.field, rust_type).unwrap();
    }
    if is_quote_tick {
        out.push_str("    pub midpoint: f64,\n");
    }
    if def.contract_id {
        out.push_str("    pub expiration: i32,\n");
        out.push_str("    pub strike: f64,\n");
        out.push_str("    pub right: String,\n");
    }
    out.push_str("}\n");
    out
}

fn render_ts_tick_class_factory(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = ts_tick_class_factory_name(type_name);
    writeln!(
        out,
        "fn {fn_name}(ticks: &[tick::{type_name}]) -> Vec<{type_name}> {{"
    )
    .unwrap();
    out.push_str("    ticks\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|t| {\n");
    writeln!(out, "            {type_name} {{").unwrap();
    for column in &def.columns {
        // String fields must be cloned; primitives are Copy.
        let expr = match column.r#type.as_str() {
            "String" => format!("t.{field}.clone()", field = column.field),
            _ => format!("t.{field}", field = column.field),
        };
        writeln!(out, "                {}: {expr},", column.field).unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("                midpoint: t.midpoint,\n");
    }
    if def.contract_id {
        out.push_str("                expiration: t.expiration,\n");
        out.push_str("                strike: t.strike,\n");
        // right is stored as the raw ASCII code (67='C', 80='P') on the
        // Rust tick; project it to a JS-friendly string using the same
        // is_call/is_put helpers the columnar emitter already relies on.
        out.push_str(
            "                right: if t.is_call() { \"C\".to_string() } else if t.is_put() { \"P\".to_string() } else { String::new() },\n",
        );
    }
    out.push_str("            }\n");
    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n");
    out
}

pub(crate) fn ts_tick_class_factory_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "eod_ticks_to_class_vec",
        "OhlcTick" => "ohlc_ticks_to_class_vec",
        "TradeTick" => "trade_ticks_to_class_vec",
        "QuoteTick" => "quote_ticks_to_class_vec",
        "TradeQuoteTick" => "trade_quote_ticks_to_class_vec",
        "OpenInterestTick" => "open_interest_ticks_to_class_vec",
        "MarketValueTick" => "market_value_ticks_to_class_vec",
        "GreeksTick" => "greeks_ticks_to_class_vec",
        "IvTick" => "iv_ticks_to_class_vec",
        "PriceTick" => "price_ticks_to_class_vec",
        "CalendarDay" => "calendar_days_to_class_vec",
        "InterestRateTick" => "interest_rate_ticks_to_class_vec",
        "OptionContract" => "option_contracts_to_class_vec",
        other => panic!("unsupported TypeScript tick class factory type: {other}"),
    }
}

fn ts_class_rust_type(column_type: &str, type_name: &str, field: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" => "i64",
        "f64" | "price" | "eod_price" => "f64",
        "String" => "String",
        other => panic!("unsupported TS class column type '{other}' in {type_name}.{field}"),
    }
}

// ── TypeScript tick type definitions ─────────────────────────────────────

fn render_ts_tick_types(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// TypeScript interfaces for columnar tick data returned by the native addon.\n");
    out.push_str("// Each property is an array — one entry per tick row.\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_type_interface(type_name, def));
        out.push('\n');
    }
    out
}

fn render_ts_tick_type_interface(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let is_quote_tick = type_name == "QuoteTick";

    // Strip " -- N fields[...]." from the doc — the TS interface includes
    // contract-id columns not counted in the TOML doc string.
    let first_line = def.doc.lines().next().unwrap_or("");
    let doc = if let Some(pos) = first_line.find(" -- ") {
        let after_dash = &first_line[pos + 4..];
        if after_dash.starts_with(|c: char| c.is_ascii_digit()) {
            let rest = after_dash
                .find(". ")
                .map(|i| &after_dash[i + 2..])
                .unwrap_or("");
            if rest.is_empty() {
                format!("{}.", &first_line[..pos])
            } else {
                format!("{}. {rest}", &first_line[..pos])
            }
        } else {
            first_line.to_string()
        }
    } else {
        first_line.to_string()
    };
    writeln!(out, "/** {doc} */").unwrap();
    writeln!(out, "export interface {type_name}Columnar {{").unwrap();
    for column in &def.columns {
        let ts_type = match column.r#type.as_str() {
            "i32" | "i64" | "eod_num" | "eod_date" => "number[]",
            "f64" | "price" | "eod_price" => "number[]",
            "String" => "string[]",
            other => panic!("unsupported column type '{other}' in TS interface for {type_name}"),
        };
        writeln!(out, "  {}: {};", column.name, ts_type).unwrap();
    }
    if is_quote_tick {
        out.push_str("  midpoint: number[];\n");
    }
    if def.contract_id {
        out.push_str("  expiration: number[];\n");
        out.push_str("  strike: number[];\n");
        out.push_str("  right: string[];\n");
    }
    out.push_str("}\n");
    out
}

fn render_go_tick_converters(schema: &Schema) -> String {
    let mut out = String::new();
    // Go spec header: `^// Code generated .* DO NOT EDIT\.$` — see
    // https://golang.org/s/generatedcode. Required for go vet / gofmt /
    // staticcheck to recognize this as machine-generated. Non-Go
    // emitters keep the uniform `@generated` form.
    out.push_str("// Code generated by build.rs from tick_schema.toml; DO NOT EDIT.\n\n");
    out.push_str("package thetadatadx\n\n");
    out.push_str("/*\n#include \"ffi_bridge.h\"\n*/\nimport \"C\"\n\n");
    out.push_str("import \"unsafe\"\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_go_tick_converter(type_name, def));
        out.push('\n');
    }
    out
}

fn render_go_tick_converter(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let (func_name, arr_type, ffi_type, public_type) = match type_name {
        "EodTick" => ("convertEodTicks", "C.TdxTickArray", "cEodTick", "EodTick"),
        "OhlcTick" => (
            "convertOhlcTicks",
            "C.TdxTickArray",
            "cOhlcTick",
            "OhlcTick",
        ),
        "TradeTick" => (
            "convertTradeTicks",
            "C.TdxTickArray",
            "cTradeTick",
            "TradeTick",
        ),
        "QuoteTick" => (
            "convertQuoteTicks",
            "C.TdxTickArray",
            "cQuoteTick",
            "QuoteTick",
        ),
        "TradeQuoteTick" => (
            "convertTradeQuoteTicks",
            "C.TdxTickArray",
            "cTradeQuoteTick",
            "TradeQuoteTick",
        ),
        "OpenInterestTick" => (
            "convertOpenInterestTicks",
            "C.TdxTickArray",
            "cOpenInterestTick",
            "OpenInterestTick",
        ),
        "MarketValueTick" => (
            "convertMarketValueTicks",
            "C.TdxTickArray",
            "cMarketValueTick",
            "MarketValueTick",
        ),
        "GreeksTick" => (
            "convertGreeksTicks",
            "C.TdxTickArray",
            "cGreeksTick",
            "GreeksTick",
        ),
        "IvTick" => ("convertIvTicks", "C.TdxTickArray", "cIvTick", "IVTick"),
        "PriceTick" => (
            "convertPriceTicks",
            "C.TdxTickArray",
            "cPriceTick",
            "PriceTick",
        ),
        "CalendarDay" => (
            "convertCalendarDays",
            "C.TdxTickArray",
            "cCalendarDay",
            "CalendarDay",
        ),
        "InterestRateTick" => (
            "convertInterestRateTicks",
            "C.TdxTickArray",
            "cInterestRateTick",
            "InterestRateTick",
        ),
        "OptionContract" => (
            "convertOptionContracts",
            "C.TdxOptionContractArray",
            "cOptionContract",
            "OptionContract",
        ),
        other => panic!("unsupported Go tick converter type: {other}"),
    };

    writeln!(out, "func {func_name}(arr {arr_type}) []{public_type} {{").unwrap();
    out.push_str("    if arr.data == nil || arr.len == 0 {\n");
    out.push_str("        return nil\n");
    out.push_str("    }\n");
    out.push_str("    n := int(arr.len)\n");
    writeln!(out, "    src := unsafe.Slice((*{ffi_type})(arr.data), n)").unwrap();
    writeln!(out, "    result := make([]{public_type}, n)").unwrap();
    out.push_str("    for i, t := range src {\n");
    if type_name == "OptionContract" {
        out.push_str("        root := \"\"\n");
        out.push_str("        if t.Root != 0 {\n");
        out.push_str("            root = C.GoString((*C.char)(unsafe.Pointer(t.Root)))\n");
        out.push_str("        }\n");
    }
    writeln!(out, "        result[i] = {public_type}{{").unwrap();
    for column in &def.columns {
        let public_field = go_public_field_name(type_name, &column.field);
        let source_expr = go_source_expr(type_name, &column.field, &column.r#type);
        writeln!(out, "            {public_field}: {source_expr},").unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("            Midpoint: t.Midpoint,\n");
    }
    if def.contract_id {
        out.push_str("            Expiration: t.Expiration,\n");
        out.push_str("            Strike: t.Strike,\n");
        out.push_str("            Right: RightStr(t.Right),\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return result\n");
    out.push_str("}\n");
    out
}

fn go_public_field_name(type_name: &str, field: &str) -> &'static str {
    match (type_name, field) {
        ("GreeksTick", "implied_volatility") => "IV",
        ("IvTick", "implied_volatility") => "IV",
        (_, "iv_error") => "IVError",
        ("MarketValueTick", "market_bid") => "MarketBid",
        ("MarketValueTick", "market_ask") => "MarketAsk",
        ("MarketValueTick", "market_price") => "MarketPrice",
        (_, "ms_of_day") => "MsOfDay",
        (_, "ms_of_day2") => "MsOfDay2",
        (_, "quote_ms_of_day") => "QuoteMsOfDay",
        (_, "ext_condition1") => "ExtCondition1",
        (_, "ext_condition2") => "ExtCondition2",
        (_, "ext_condition3") => "ExtCondition3",
        (_, "ext_condition4") => "ExtCondition4",
        (_, "condition_flags") => "ConditionFlags",
        (_, "price_flags") => "PriceFlags",
        (_, "volume_type") => "VolumeType",
        (_, "records_back") => "RecordsBack",
        (_, "bid_size") => "BidSize",
        (_, "bid_exchange") => "BidExchange",
        (_, "bid_condition") => "BidCondition",
        (_, "ask_size") => "AskSize",
        (_, "ask_exchange") => "AskExchange",
        (_, "ask_condition") => "AskCondition",
        (_, "open_interest") => "OpenInterest",
        (_, "market_bid") => "MarketBid",
        (_, "market_ask") => "MarketAsk",
        (_, "market_price") => "MarketPrice",
        (_, "dual_delta") => "DualDelta",
        (_, "dual_gamma") => "DualGamma",
        (_, "is_open") => "IsOpen",
        other => Box::leak(go_pascal_case(other.1).into_boxed_str()),
    }
}

fn go_source_expr(type_name: &str, field: &str, kind: &str) -> String {
    let ffi_field = go_ffi_field_name(field);
    match (type_name, field, kind) {
        ("OptionContract", "root", "String") => "root".into(),
        ("OptionContract", "right", "i32") => "RightStr(t.Right)".into(),
        (_, "right", "i32") => "RightStr(t.Right)".into(),
        (_, "is_open", "i32") => "t.IsOpen != 0".into(),
        ("OptionContract", _, "i32") => format!("int(t.{ffi_field})"),
        (_, _, "i32") if field == "expiration" => format!("t.{ffi_field}"),
        (_, _, "i32") | (_, _, "eod_num") | (_, _, "eod_date") => format!("int(t.{ffi_field})"),
        (_, _, "i64") | (_, _, "f64") | (_, _, "price") | (_, _, "eod_price") => {
            format!("t.{ffi_field}")
        }
        (_, _, "String") => format!("t.{ffi_field}"),
        _ => panic!("unsupported Go source expression for {type_name}.{field}:{kind}"),
    }
}

fn go_ffi_field_name(field: &str) -> &'static str {
    match field {
        "implied_volatility" => "ImpliedVolatility",
        "iv_error" => "IvError",
        "market_bid" => "MarketBid",
        "market_ask" => "MarketAsk",
        "market_price" => "MarketPrice",
        "ms_of_day" => "MsOfDay",
        "ms_of_day2" => "MsOfDay2",
        "quote_ms_of_day" => "QuoteMsOfDay",
        "ext_condition1" => "ExtCondition1",
        "ext_condition2" => "ExtCondition2",
        "ext_condition3" => "ExtCondition3",
        "ext_condition4" => "ExtCondition4",
        "condition_flags" => "ConditionFlags",
        "price_flags" => "PriceFlags",
        "volume_type" => "VolumeType",
        "records_back" => "RecordsBack",
        "bid_size" => "BidSize",
        "bid_exchange" => "BidExchange",
        "bid_condition" => "BidCondition",
        "ask_size" => "AskSize",
        "ask_exchange" => "AskExchange",
        "ask_condition" => "AskCondition",
        "open_interest" => "OpenInterest",
        "dual_delta" => "DualDelta",
        "dual_gamma" => "DualGamma",
        "is_open" => "IsOpen",
        other => Box::leak(go_pascal_case(other).into_boxed_str()),
    }
}

fn go_pascal_case(value: &str) -> String {
    value
        .split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| match segment {
            "iv" => "IV".to_string(),
            other => {
                let mut chars = other.chars();
                match chars.next() {
                    Some(first) => first.to_uppercase().to_string() + chars.as_str(),
                    None => String::new(),
                }
            }
        })
        .collect::<String>()
}

// ── Go public tick struct generation ──────────────────────────────────────────

/// Map a tick_schema.toml column type to the Go public struct field type.
fn go_public_field_type(type_name: &str, field: &str, kind: &str) -> &'static str {
    // CalendarDay.is_open is a bool in the public API
    if type_name == "CalendarDay" && field == "is_open" {
        return "bool";
    }
    // OptionContract.right is i32 in the schema but exposed as string via RightStr()
    if type_name == "OptionContract" && field == "right" {
        return "string";
    }
    match kind {
        "i32" | "eod_num" | "eod_date" => "int",
        "i64" => "int64",
        "f64" | "price" | "eod_price" => "float64",
        "String" => "string",
        _ => panic!("unsupported Go public type for {type_name}.{field}:{kind}"),
    }
}

/// Map a tick_schema.toml column to the JSON tag for the Go public struct.
fn go_json_tag(field: &str) -> String {
    field.to_string()
}

fn render_go_tick_structs(schema: &Schema) -> String {
    let mut out = String::new();
    // Go spec header (see render_go_tick_converters for the rationale).
    out.push_str("// Code generated by build.rs from tick_schema.toml; DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str("// Public Go tick types, RightStr helper, and Greeks struct.\n");
    out.push_str("// C-mirror (FFI) structs live in tick_ffi_mirrors.go (hand-written).\n\n");
    out.push_str("package thetadatadx\n\n");

    // Emit public Go structs for each tick type
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_go_public_struct(type_name, def));
        out.push('\n');
    }

    // RightStr helper
    out.push_str("// RightStr converts the raw right code to a string.\n");
    out.push_str("// 67='C' (Call), 80='P' (Put), 0=\"\" (not set).\n");
    out.push_str("func RightStr(code int32) string {\n");
    out.push_str("\tswitch code {\n");
    out.push_str("\tcase 67:\n");
    out.push_str("\t\treturn \"C\"\n");
    out.push_str("\tcase 80:\n");
    out.push_str("\t\treturn \"P\"\n");
    out.push_str("\tdefault:\n");
    out.push_str("\t\treturn \"\"\n");
    out.push_str("\t}\n");
    out.push_str("}\n\n");

    // Greeks struct (offline utility, not a tick type — matches tdbe::Greeks)
    out.push_str("// Greeks holds the 22 Black-Scholes greeks + IV from all_greeks().\n");
    out.push_str("type Greeks struct {\n");
    for field in &[
        ("Value", "value"),
        ("Delta", "delta"),
        ("Gamma", "gamma"),
        ("Theta", "theta"),
        ("Vega", "vega"),
        ("Rho", "rho"),
        ("IV", "iv"),
        ("IVError", "iv_error"),
        ("Vanna", "vanna"),
        ("Charm", "charm"),
        ("Vomma", "vomma"),
        ("Veta", "veta"),
        ("Speed", "speed"),
        ("Zomma", "zomma"),
        ("Color", "color"),
        ("Ultima", "ultima"),
        ("D1", "d1"),
        ("D2", "d2"),
        ("DualDelta", "dual_delta"),
        ("DualGamma", "dual_gamma"),
        ("Epsilon", "epsilon"),
        ("Lambda", "lambda"),
    ] {
        writeln!(out, "\t{:9} float64 `json:\"{}\"`", field.0, field.1).unwrap();
    }
    out.push_str("}\n");

    out
}

fn render_go_public_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let go_type = match type_name {
        "IvTick" => "IVTick",
        other => other,
    };
    writeln!(
        out,
        "// {} — {}",
        go_type,
        def.doc.lines().next().unwrap_or("")
    )
    .unwrap();
    writeln!(out, "type {go_type} struct {{").unwrap();

    for column in &def.columns {
        let public_field = go_public_field_name(type_name, &column.field);
        let go_type_str = go_public_field_type(type_name, &column.field, &column.r#type);
        let json_tag = go_json_tag(&column.name);
        writeln!(
            out,
            "\t{:14} {:<8} `json:\"{json_tag}\"`",
            public_field, go_type_str
        )
        .unwrap();
    }
    // QuoteTick gets a Midpoint field
    if type_name == "QuoteTick" {
        out.push_str("\tMidpoint       float64  `json:\"midpoint\"`\n");
    }
    // contract_id fields
    if def.contract_id {
        out.push_str("\tExpiration     int32    `json:\"expiration,omitempty\"`\n");
        out.push_str("\tStrike         float64  `json:\"strike,omitempty\"`\n");
        out.push_str("\tRight          string   `json:\"right,omitempty\"`\n");
    }
    out.push_str("}\n");
    out
}
