// Reason: shared between build.rs (which calls `generate`) and the
// `generate_sdk_surfaces` binary (which calls only the `*_sdk_generated_files`
// entry points) via `#[path]`. Not every helper is reachable from both
// entry points, so mark the whole module as allowed-dead once rather than
// annotating each helper individually.
#![allow(dead_code, unused_imports)]

// ─────────────────────────────────────────────────────────────────────────────
//  Code-generate tick structs + parsers from tick_schema.toml
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct Schema {
    types: HashMap<String, TickTypeDef>,
}

/// Parsed from tick_schema.toml. `doc`, `copy`, and `align` exist in the
/// TOML for documentation / FFI layout hints but are not used by the parser
/// generator — tick structs live in `tdbe::types::tick` (hand-written).
#[derive(Debug, Deserialize)]
struct TickTypeDef {
    doc: String,
    copy: bool,
    #[serde(default)]
    align: Option<u32>,
    parser: String,
    #[serde(default)]
    required: Vec<String>,
    #[serde(default)]
    eod_style: bool,
    #[serde(default)]
    contract_id: bool,
    columns: Vec<ColumnDef>,
}

#[derive(Debug, Deserialize)]
struct ColumnDef {
    name: String,
    field: String,
    r#type: String,
}

pub fn generate() -> Result<(), Box<dyn std::error::Error>> {
    let schema_path = "tick_schema.toml";
    let schema_str = std::fs::read_to_string(schema_path)?;
    let schema: Schema = toml::from_str(&schema_str)?;

    let out_dir = std::env::var("OUT_DIR")?;

    // Collect type names and sort for deterministic output.
    let mut type_names: Vec<&String> = schema.types.keys().collect();
    type_names.sort();

    // ── Generate decode_generated.rs (parser functions) ──────────────────────
    // Struct definitions now live in the `tdbe` crate (crates/tdbe/src/types/tick.rs).
    // Only parser functions are generated here. Parsers return
    // `Result<Vec<Tick>, DecodeError>`; each cell access threads `?` so that a
    // type mismatch in one row fails the whole table, matching Java terminal
    // semantics (see PojoMessageUtils.convert).
    let mut parsers = String::new();
    parsers
        .push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n\n");
    // Note: tick types are imported by decode.rs via `use tdbe::types::tick::*;`
    // No additional imports needed in the generated code.

    for type_name in &type_names {
        let def = &schema.types[*type_name];
        generate_parser(&mut parsers, type_name, def);
    }

    let parsers_dest = Path::new(&out_dir).join("decode_generated.rs");
    std::fs::write(&parsers_dest, &parsers)?;

    // Rerun if schema changes
    println!("cargo:rerun-if-changed={schema_path}");

    Ok(())
}

/// Generate a single parser function.
///
/// Price columns are decoded to `f64` during extraction using the wire
/// `price_type` (internally fetched, never exposed on the public struct).
/// The emitted parser returns `Result<Vec<T>, DecodeError>` and threads `?`
/// on every cell access so a type mismatch in one row fails the whole table.
// Reason: code generator -- the match dispatch over column types cannot be meaningfully split.
#[allow(clippy::too_many_lines)]
fn generate_parser(out: &mut String, type_name: &str, def: &TickTypeDef) {
    let fn_name = &def.parser;

    writeln!(
        out,
        "pub fn {fn_name}(table: &crate::proto::DataTable) -> Result<Vec<{type_name}>, DecodeError> {{"
    )
    .unwrap();

    // If eod_style, emit the local EOD helpers inline.
    if def.eod_style {
        out.push_str(
            "    // EOD numeric/time fields may arrive as Price, Number, or Timestamp cells.\n",
        );
        out.push_str("    fn eod_num(row: &crate::proto::DataValueList, idx: usize) -> Result<i32, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as i32),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(p.value),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(crate::decode::timestamp_to_ms_of_day(ts.epoch_ms)),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD numeric field widened to i64 (for volume/count) — same cell types as eod_num, i64 target.\n");
        out.push_str("    fn eod_num64(row: &crate::proto::DataValueList, idx: usize) -> Result<i64, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(i64::from(p.value)),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(i64::from(crate::decode::timestamp_to_ms_of_day(ts.epoch_ms))),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD date fields may arrive as Price, Number, or Timestamp cells.\n");
        out.push_str("    fn eod_date(row: &crate::proto::DataValueList, idx: usize) -> Result<i32, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as i32),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Price(p)) => Ok(p.value),\n",
        );
        out.push_str("            Some(crate::proto::data_value::DataType::Timestamp(ts)) => Ok(crate::decode::timestamp_to_date(ts.epoch_ms)),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Number|Price|Timestamp\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD price field: decode to f64 from Price or Number cell.\n");
        out.push_str("    fn eod_price(row: &crate::proto::DataValueList, idx: usize) -> Result<f64, DecodeError> {\n");
        out.push_str("        let Some(dv) = row.values.get(idx) else {\n");
        out.push_str("            return Err(DecodeError::MissingCell { column: idx });\n");
        out.push_str("        };\n");
        out.push_str("        match dv.data_type.as_ref() {\n");
        out.push_str("            Some(crate::proto::data_value::DataType::Price(p)) => Ok(tdbe::types::price::Price::new(p.value, p.r#type).to_f64()),\n");
        out.push_str(
            "            Some(crate::proto::data_value::DataType::Number(n)) => Ok(*n as f64),\n",
        );
        out.push_str(
            "            Some(crate::proto::data_value::DataType::NullValue(_)) => Ok(0.0),\n",
        );
        out.push_str("            None => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Price|Number\",\n");
        out.push_str("                observed: \"Unset\",\n");
        out.push_str("            }),\n");
        out.push_str("            other => Err(DecodeError::TypeMismatch {\n");
        out.push_str("                column: idx,\n");
        out.push_str("                expected: \"Price|Number\",\n");
        out.push_str("                observed: crate::decode::observed_name(other),\n");
        out.push_str("            }),\n");
        out.push_str("        }\n");
        out.push_str("    }\n\n");
    }

    out.push_str("    let h: Vec<&str> = table.headers.iter().map(|s| s.as_str()).collect();\n");

    // For eod_style, use the shared find_header() from decode.rs.
    if def.eod_style {
        out.push_str("    let find = |name: &str| find_header(&h, name);\n\n");
    }

    // Determine which columns need helpers.
    let needs_opt_number = def
        .columns
        .iter()
        .any(|c| c.r#type == "i32" && !def.required.contains(&c.name) && c.field != "date");
    let needs_opt_float = def
        .columns
        .iter()
        .any(|c| c.r#type == "f64" && !def.required.contains(&c.name));
    let needs_opt_i64 = def
        .columns
        .iter()
        .any(|c| c.r#type == "i64" && !def.required.contains(&c.name));

    // Emit opt_number / opt_float / opt_i64 helpers (non-eod only). Each
    // returns `Result<T, DecodeError>`: absent column or NullValue → default,
    // type mismatch → error propagated.
    if !def.eod_style {
        if needs_opt_number {
            out.push_str("    fn opt_number(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<i32, DecodeError> {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_number(row, i)?.unwrap_or(0)),\n");
            out.push_str("            None => Ok(0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_float {
            // `f64` columns (greeks, IV, interest rates) legitimately arrive
            // as Price or Number on the v3 MDDS server; dispatch on the wire
            // type the same way Java's `dataValue2Object` does (PRICE →
            // BigDecimal, NUMBER → Long). See `row_price_f64` for the
            // accept-list.
            out.push_str("    fn opt_float(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<f64, DecodeError> {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_price_f64(row, i)?.unwrap_or(0.0)),\n");
            out.push_str("            None => Ok(0.0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_i64 {
            out.push_str(
                "    fn opt_i64(row: &crate::proto::DataValueList, idx: Option<usize>) -> Result<i64, DecodeError> {\n",
            );
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => Ok(row_number_i64(row, i)?.unwrap_or(0)),\n");
            out.push_str("            None => Ok(0),\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
    }

    // Required header guards (non-eod only).
    if !def.eod_style {
        for req in &def.required {
            let var = format!("{req}_idx");
            writeln!(out,
                "    let Some({var}) = find_header(&h, \"{req}\") else {{\n        return Ok(vec![]);\n    }};"
            ).unwrap();
        }
        if !def.required.is_empty() {
            out.push('\n');
        }
    }

    // Declare index variables for all columns.
    for col in &def.columns {
        let var = format!("{}_idx", col.name);
        if def.eod_style {
            writeln!(out, "    let {var} = find(\"{}\");", col.name).unwrap();
        } else if def.required.contains(&col.name) {
            // Already declared above as required.
        } else {
            writeln!(out, "    let {var} = find_header(&h, \"{}\");", col.name).unwrap();
        }
    }

    // Contract identification columns (wildcard queries inject expiration/strike/right).
    if def.contract_id {
        out.push_str("    let _cid_exp_idx = h.iter().position(|c| *c == \"expiration\");\n");
        out.push_str("    let _cid_strike_idx = h.iter().position(|c| *c == \"strike\");\n");
        out.push_str("    let _cid_right_idx = h.iter().position(|c| *c == \"right\");\n");
        out.push_str("    let _cid_strike_is_typed = _cid_strike_idx.is_some() && h.contains(&\"strike\");\n");
    }

    // Check if this is QuoteTick (needs midpoint computation).
    let is_quote_tick = type_name == "QuoteTick";

    out.push('\n');

    // Emit the row mapping. Each row produces a `Result<Tick, DecodeError>`;
    // `.collect::<Result<Vec<_>, _>>()` short-circuits on the first error.
    out.push_str("    table\n");
    out.push_str("        .data_table\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|row| {\n");

    // Struct literal.
    if is_quote_tick {
        writeln!(out, "            let _tick = {type_name} {{").unwrap();
    } else {
        writeln!(out, "            Ok({type_name} {{").unwrap();
    }

    for col in &def.columns {
        let var = format!("{}_idx", col.name);
        let is_required = def.required.contains(&col.name);

        match col.r#type.as_str() {
            "i32" => {
                if def.eod_style {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => eod_num(row, i)?, None => 0 }},",
                        col.field
                    )
                    .unwrap();
                } else if is_required {
                    if col.field == "date" {
                        writeln!(
                            out,
                            "                {}: row_date(row, {var})?.unwrap_or(0),",
                            col.field
                        )
                        .unwrap();
                    } else {
                        writeln!(
                            out,
                            "                {}: row_number(row, {var})?.unwrap_or(0),",
                            col.field
                        )
                        .unwrap();
                    }
                } else if col.field == "date" {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => row_date(row, i)?.unwrap_or(0), None => 0 }},",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: opt_number(row, {var})?,",
                        col.field
                    )
                    .unwrap();
                }
            }
            "i64" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_number_i64(row, {var})?.unwrap_or(0),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(out, "                {}: opt_i64(row, {var})?,", col.field).unwrap();
                }
            }
            "f64" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_price_f64(row, {var})?.unwrap_or(0.0),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: opt_float(row, {var})?,",
                        col.field
                    )
                    .unwrap();
                }
            }
            "String" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_text(row, {var})?.unwrap_or_default(),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: match {var} {{ Some(i) => row_text(row, i)?.unwrap_or_default(), None => String::new() }},",
                        col.field
                    )
                    .unwrap();
                }
            }
            "price" => {
                // Decode price to f64 at parse time.
                let field = &col.field;
                if is_required {
                    writeln!(
                        out,
                        "                {field}: row_price_f64(row, {var})?.unwrap_or(0.0),"
                    )
                    .unwrap();
                } else {
                    writeln!(out, "                {field}: match {var} {{").unwrap();
                    out.push_str(
                        "                    Some(i) => row_price_f64(row, i)?.unwrap_or(0.0),\n",
                    );
                    out.push_str("                    None => 0.0,\n");
                    out.push_str("                },\n");
                }
            }
            "eod_num" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_num(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_num64" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_num64(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_date" => {
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_date(row, i)?, None => 0 }},",
                    col.field
                )
                .unwrap();
            }
            "eod_price" => {
                // EOD price field: decode to f64 from Price or Number cell.
                writeln!(
                    out,
                    "                {}: match {var} {{ Some(i) => eod_price(row, i)?, None => 0.0 }},",
                    col.field
                )
                .unwrap();
            }
            other => panic!("unknown column type '{other}' in parser for {type_name}"),
        }
    }

    // Contract identification fields (injected when contract_id = true). The
    // `expiration` column legitimately arrives as Number (YYYYMMDD) or Text
    // (ISO "2026-04-13") depending on upstream version — dispatch on the
    // cell's own type rather than coalescing silently.
    if def.contract_id {
        out.push_str("                expiration: match _cid_exp_idx {\n");
        out.push_str("                    Some(i) => {\n");
        out.push_str("                        let dv = row.values.get(i).ok_or(DecodeError::MissingCell { column: i })?;\n");
        out.push_str("                        match dv.data_type.as_ref() {\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Number(n)) => *n as i32,\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Text(s)) => parse_iso_date(s),\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::NullValue(_)) => 0,\n");
        out.push_str(
            "                            None => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str("                                observed: \"Unset\",\n");
        out.push_str("                            }),\n");
        out.push_str(
            "                            other => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str(
            "                                observed: crate::decode::observed_name(other),\n",
        );
        out.push_str("                            }),\n");
        out.push_str("                        }\n");
        out.push_str("                    }\n");
        out.push_str("                    None => 0,\n");
        out.push_str("                },\n");
        // strike: decode to f64
        out.push_str("                strike: match _cid_strike_idx {\n");
        out.push_str(
            "                    Some(i) if _cid_strike_is_typed => row_price_f64(row, i)?.unwrap_or(0.0),\n",
        );
        out.push_str("                    Some(i) => row_number(row, i)?.unwrap_or(0) as f64,\n");
        out.push_str("                    None => 0.0,\n");
        out.push_str("                },\n");
        // right: ASCII code (Number) or text (Text) — strict dispatch.
        out.push_str("                right: match _cid_right_idx {\n");
        out.push_str("                    Some(i) => {\n");
        out.push_str("                        let dv = row.values.get(i).ok_or(DecodeError::MissingCell { column: i })?;\n");
        out.push_str("                        match dv.data_type.as_ref() {\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Number(n)) => *n as i32,\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::Text(s)) => match s.as_str() {\n");
        out.push_str("                                \"CALL\" | \"C\" => 67,\n");
        out.push_str("                                \"PUT\" | \"P\" => 80,\n");
        out.push_str("                                _ => 0,\n");
        out.push_str("                            },\n");
        out.push_str("                            Some(crate::proto::data_value::DataType::NullValue(_)) => 0,\n");
        out.push_str(
            "                            None => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str("                                observed: \"Unset\",\n");
        out.push_str("                            }),\n");
        out.push_str(
            "                            other => return Err(DecodeError::TypeMismatch {\n",
        );
        out.push_str("                                column: i,\n");
        out.push_str("                                expected: \"Number|Text\",\n");
        out.push_str(
            "                                observed: crate::decode::observed_name(other),\n",
        );
        out.push_str("                            }),\n");
        out.push_str("                        }\n");
        out.push_str("                    }\n");
        out.push_str("                    None => 0,\n");
        out.push_str("                },\n");
    }

    if is_quote_tick {
        // QuoteTick gets midpoint computed from bid + ask.
        out.push_str("                midpoint: 0.0, // placeholder, set below\n");
        out.push_str("            };\n");
        out.push_str("            let mut _tick = _tick;\n");
        out.push_str("            _tick.midpoint = (_tick.bid + _tick.ask) / 2.0;\n");
        out.push_str("            Ok(_tick)\n");
    } else {
        out.push_str("            })\n");
    }

    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n\n");
}

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

use serde::Deserialize;

pub struct GeneratedSourceFile {
    pub relative_path: &'static str,
    pub contents: String,
}

pub fn write_sdk_generated_files(repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    for file in render_sdk_generated_files()? {
        let path = repo_root.join(file.relative_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, file.contents)?;
    }
    Ok(())
}

pub fn check_sdk_generated_files(repo_root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    for file in render_sdk_generated_files()? {
        let path = repo_root.join(file.relative_path);
        let actual = std::fs::read_to_string(&path)?;
        if actual.replace("\r\n", "\n") != file.contents {
            return Err(format!(
                "generated SDK surface '{}' is stale; run `cargo run -p thetadatadx --bin generate_sdk_surfaces` to refresh",
                file.relative_path
            )
            .into());
        }
    }
    Ok(())
}

fn render_sdk_generated_files() -> Result<Vec<GeneratedSourceFile>, Box<dyn std::error::Error>> {
    let schema = load_schema()?;
    // `tick_columnar.rs` is intentionally NOT emitted. The previous
    // specialized `*_ticks_to_columnar` helpers returned `Py<PyDict>`
    // (dict-of-lists) to feed `pandas.DataFrame`. The user-mandate is
    // typed pyclass everywhere, so the `*_df` convenience wrappers were
    // removed in favor of the unified
    // `thetadatadx.to_dataframe(client.stock_history_eod(...))` path
    // backed by `pyclass_list_to_columnar` — a single thin
    // pandas-adapter lives in `sdks/python/src/lib.rs` and is
    // documented there.
    Ok(vec![
        GeneratedSourceFile {
            // Arrow columnar pipeline -- replaces the old `tick_columnar.rs`
            // (dict-of-lists) with schema-generated `*_ticks_to_arrow_batch`
            // + `pyclass_list_to_arrow_table` dispatcher + typed Arrow
            // schema map. Single alloc per column, zero-copy to pyarrow.
            relative_path: "sdks/python/src/tick_arrow.rs",
            contents: render_python_tick_arrow(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/python/src/tick_classes.rs",
            contents: render_python_tick_classes(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/go/tick_converters.go",
            contents: render_go_tick_converters(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/go/tick_structs.go",
            contents: render_go_tick_structs(&schema),
        },
        GeneratedSourceFile {
            relative_path: "tools/cli/src/raw_headers_generated.rs",
            contents: render_cli_raw_headers(&schema),
        },
        GeneratedSourceFile {
            relative_path: "sdks/typescript/src/tick_classes.rs",
            contents: render_ts_tick_classes(&schema),
        },
    ])
}

fn load_schema() -> Result<Schema, Box<dyn std::error::Error>> {
    let schema_path = "tick_schema.toml";
    let schema_str = std::fs::read_to_string(schema_path)?;
    let schema: Schema = toml::from_str(&schema_str)?;
    Ok(schema)
}

fn sorted_type_names(schema: &Schema) -> Vec<&str> {
    let mut names = schema.types.keys().map(String::as_str).collect::<Vec<_>>();
    names.sort();
    names
}

/// Tick types that the Python SDK's hand-written `*_df` convenience
/// wrappers in `lib.rs` call directly. Only these need the fast-path
/// `*_ticks_to_arrow_batch` converter from `&[tick::T]` — everything
/// else routes through the generic `pyclass_list_to_arrow_table`
/// dispatcher which reads `#[pyo3(get)]` fields off the typed pyclass
/// list. Keeping this list tight avoids generating dead code that
/// would otherwise require `#[allow(dead_code)]` to ship under
/// `-D warnings`.
const PYTHON_TICK_ARROW_DIRECT_TYPES: &[&str] = &["EodTick", "OhlcTick", "QuoteTick", "TradeTick"];

/// Emit `sdks/python/src/tick_arrow.rs`. The file contains three
/// generator-owned surfaces:
///
/// 1. `*_ticks_to_arrow_batch(ticks: &[tick::T]) -> Result<RecordBatch, ArrowError>`
///    — fast path from the Rust tick struct slice. Only emitted for
///    tick types reached by the hand-written `*_df` wrappers in
///    `lib.rs` (see `PYTHON_TICK_ARROW_DIRECT_TYPES`).
///
/// 2. `pyclass_list_to_arrow_table(py, ticks, empty_qualname_hint)
///    -> PyResult<Py<PyAny>>` — dispatcher used by the public
///    `to_arrow` / `to_dataframe` / `to_polars` entry points. Reads
///    `#[pyo3(get)]` fields off the typed pyclass instances directly
///    into Arrow builders — no Rust-tick-struct roundtrip, so it's
///    strictly faster than the old dict-of-lists pivot.
///
/// 3. `arrow_schema_for_qualname(qualname: &str) -> Option<Arc<Schema>>`
///    — schema map so the empty-list case returns an empty
///    `pyarrow.Table` with the correct typed schema (not a bare dict).
///
/// Zero-copy to `pyarrow`: each `RecordBatch` buffer is handed over
/// via the Arrow C Data Interface at the pyo3 boundary (courtesy of
/// `arrow_pyarrow::IntoPyArrow`). pandas 2.x consumes those buffers
/// in place for all numeric dtypes.
fn render_python_tick_arrow(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Arrow columnar pipeline. Single RecordBatch per converter, zero-copy to\n");
    out.push_str("// pyarrow via the Arrow C Data Interface (`arrow_pyarrow::IntoPyArrow`).\n");
    out.push_str("// Replaces the old dict-of-lists `PyDict` path; same schema, native Arrow\n");
    out.push_str("// typing, ~6x wall-clock speedup at 100k ticks.\n\n");
    // `Arc` is already imported at the `lib.rs` include-site (via
    // `std::sync::{Arc, Mutex}`); referencing `std::sync::Arc` here
    // would shadow. Paths below use fully-qualified `std::sync::Arc`
    // only inside the Schema-building helpers that predate the
    // lib.rs layout -- keep generator output self-sufficient by
    // qualifying the Arc references rather than importing again.
    //
    // `arrow::pyarrow` is the re-export exposed by the `pyarrow`
    // feature of the `arrow` crate; we go through it rather than
    // depending on `arrow-pyarrow` directly so the compat matrix is
    // single-sourced on `arrow`'s own version pin.
    out.push_str(
        "use arrow::array::{ArrayRef, Float64Array, Int32Array, Int64Array, StringArray};\n",
    );
    out.push_str("use arrow::datatypes::{DataType, Field, Schema};\n");
    out.push_str("use arrow::pyarrow::IntoPyArrow;\n");
    out.push_str("use arrow::record_batch::RecordBatch;\n\n");

    // Per-type fast-path `*_ticks_to_arrow_batch(&[tick::T])` helpers
    // are intentionally NOT emitted — they were called only from the
    // `stock_history_*_df` convenience wrappers in `lib.rs`, which were
    // removed for SSOT purity. The sole public DataFrame path goes
    // through `pyclass_list_to_arrow_table` (trait-driven, one surface
    // covering every tick type) + the public `to_dataframe` / `to_polars`
    // / `to_arrow` adapters.

    // Schema map + pyclass dispatcher (one surface covering every tick type).
    out.push_str(&render_python_arrow_schema_map(schema));
    out.push('\n');
    out.push_str(&render_python_pyclass_to_arrow_dispatcher(schema));
    out
}

/// Map a `tick_schema.toml` column `type` to the Arrow `DataType` enum
/// variant we emit into the generated schema. `eod_num` (i32) and
/// `eod_num64` (i64) are distinct on the Rust side because one is
/// widened for volume/count; they preserve that distinction into
/// Arrow.
fn arrow_data_type_expr(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "DataType::Int32",
        "i64" | "eod_num64" => "DataType::Int64",
        "f64" | "price" | "eod_price" => "DataType::Float64",
        "String" => "DataType::Utf8",
        other => panic!("unsupported Arrow data type for column type '{other}'"),
    }
}

/// Map a `tick_schema.toml` column `type` to the Arrow concrete array
/// constructor we call when materializing a column. Parallel to
/// `arrow_data_type_expr`; the caller wraps the result in
/// `Arc::new(...) as ArrayRef`.
fn arrow_array_ctor(column_type: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "Int32Array",
        "i64" | "eod_num64" => "Int64Array",
        "f64" | "price" | "eod_price" => "Float64Array",
        "String" => "StringArray",
        other => panic!("unsupported Arrow array ctor for column type '{other}'"),
    }
}

/// Per-tick-type fast-path emitter. Walks the schema columns plus the
/// midpoint / contract-id injections, builds one `Arc<dyn Array>` per
/// column via `from_iter`, and wraps them in a single `RecordBatch`.
fn render_python_tick_arrow_batch_fn(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = match type_name {
        "EodTick" => "eod_ticks_to_arrow_batch",
        "OhlcTick" => "ohlc_ticks_to_arrow_batch",
        "TradeTick" => "trade_ticks_to_arrow_batch",
        "QuoteTick" => "quote_ticks_to_arrow_batch",
        other => panic!("unsupported Python Arrow direct type: {other}"),
    };
    let is_quote_tick = type_name == "QuoteTick";
    let class = pyclass_name(type_name);

    writeln!(
        out,
        "pub(crate) fn {fn_name}(ticks: &[tick::{type_name}]) -> Result<RecordBatch, ArrowError> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    let schema = arrow_schema_for_qualname(\"{class}\")\n        .expect(\"generated schema must be present for {class}\");",
    )
    .unwrap();

    // Emit one Arc<dyn Array> per column into a Vec<ArrayRef>.
    out.push_str("    let columns: Vec<ArrayRef> = vec![\n");
    for column in &def.columns {
        let ctor = arrow_array_ctor(column.r#type.as_str());
        let field = &column.field;
        match column.r#type.as_str() {
            "String" => {
                writeln!(
                    out,
                    "        Arc::new({ctor}::from_iter_values(ticks.iter().map(|t| t.{field}.as_str()))) as ArrayRef,"
                )
                .unwrap();
            }
            _ => {
                writeln!(
                    out,
                    "        Arc::new({ctor}::from_iter_values(ticks.iter().map(|t| t.{field}))) as ArrayRef,"
                )
                .unwrap();
            }
        }
    }
    if is_quote_tick {
        out.push_str(
            "        Arc::new(Float64Array::from_iter_values(ticks.iter().map(|t| t.midpoint))) as ArrayRef,\n",
        );
    }
    if def.contract_id {
        out.push_str(
            "        Arc::new(Int32Array::from_iter_values(ticks.iter().map(|t| t.expiration))) as ArrayRef,\n",
        );
        out.push_str(
            "        Arc::new(Float64Array::from_iter_values(ticks.iter().map(|t| t.strike))) as ArrayRef,\n",
        );
        // `right` is an ASCII code on the Rust tick (67='C', 80='P'); project
        // to a string to match the pyclass surface and the historical
        // DataFrame contract consumers already depend on.
        out.push_str(
            "        Arc::new(StringArray::from_iter_values(ticks.iter().map(|t| if t.is_call() { \"C\" } else if t.is_put() { \"P\" } else { \"\" }))) as ArrayRef,\n",
        );
    }
    out.push_str("    ];\n");
    out.push_str("    RecordBatch::try_new(schema, columns)\n");
    out.push_str("}\n");
    out
}

/// Emit `arrow_schema_for_qualname` — a static schema map keyed on
/// pyclass `__qualname__`. Critical for the empty-list case: Arrow
/// cannot construct a `RecordBatch` without a schema, so we need a
/// source of typed field metadata keyed on tick class.
fn render_python_arrow_schema_map(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("/// Typed Arrow schema keyed by the tick pyclass `__qualname__`.\n");
    out.push_str("/// Column order matches the `#[pyo3(get)]` field order emitted into\n");
    out.push_str("/// `tick_classes.rs` by the sibling renderer, so a given tick type\n");
    out.push_str("/// produces the same DataFrame column ordering through both the\n");
    out.push_str("/// Rust-slice fast path and the pyclass-list dispatcher.\n");
    out.push_str(
        "pub(crate) fn arrow_schema_for_qualname(qualname: &str) -> Option<Arc<Schema>> {\n",
    );
    out.push_str("    match qualname {\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        let class = pyclass_name(type_name);
        let is_quote_tick = type_name == "QuoteTick";
        writeln!(
            out,
            "        \"{class}\" => Some(Arc::new(Schema::new(vec!["
        )
        .unwrap();
        for column in &def.columns {
            // Mirror the pyclass projection: `OptionContract.right` surfaces
            // as a Python string (`"C"`/`"P"`/`""`) on the pyclass even
            // though the schema records it as `i32`. See
            // `render_python_tick_class_struct` for the matching rule.
            let dt = if type_name == "OptionContract" && column.field == "right" {
                "DataType::Utf8"
            } else {
                arrow_data_type_expr(column.r#type.as_str())
            };
            writeln!(
                out,
                "            Field::new(\"{name}\", {dt}, false),",
                name = column.name,
            )
            .unwrap();
        }
        if is_quote_tick {
            out.push_str("            Field::new(\"midpoint\", DataType::Float64, false),\n");
        }
        if def.contract_id {
            out.push_str("            Field::new(\"expiration\", DataType::Int32, false),\n");
            out.push_str("            Field::new(\"strike\", DataType::Float64, false),\n");
            out.push_str("            Field::new(\"right\", DataType::Utf8, false),\n");
        }
        out.push_str("        ]))),\n");
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Emit `pyclass_list_to_arrow_table` — the generic dispatcher used
/// by `to_arrow` / `to_dataframe` / `to_polars`. The caller hands us
/// a `Py<PyList>` of tick pyclass instances and an optional qualname
/// hint for the empty-list case.
///
/// The match arms read `#[pyo3(get)]` fields off each pyclass into
/// typed Arrow builders. This skips the `__dir__` / `getattr` round-
/// trip the old `PyDict` path relied on.
fn render_python_pyclass_to_arrow_dispatcher(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("/// Dispatch a list of typed tick pyclasses into a single `pyarrow.Table`.\n");
    out.push_str("/// Zero-copy at the pyo3 boundary courtesy of `arrow_pyarrow::IntoPyArrow`;\n");
    out.push_str("/// pandas 2.x then aliases the underlying Arrow buffers for all numeric\n");
    out.push_str("/// columns.\n");
    out.push_str("///\n");
    out.push_str("/// # Empty-list behaviour\n");
    out.push_str("///\n");
    out.push_str(
        "/// * non-empty list -> schema from `arrow_schema_for_qualname(first.qualname)`;\n",
    );
    out.push_str("///   mixed-type lists raise `PyRuntimeError`.\n");
    out.push_str("/// * empty list + hint -> schema from the hint, zero-row table (pandas /\n");
    out.push_str("///   polars still infer dtypes).\n");
    out.push_str("/// * empty list + no hint -> zero-column `pyarrow.Table` (public API:\n");
    out.push_str("///   see `to_arrow` docstring).\n");
    out.push_str("pub(crate) fn pyclass_list_to_arrow_table<'py>(\n");
    out.push_str("    py: Python<'py>,\n");
    out.push_str("    ticks: &Bound<'py, pyo3::types::PyList>,\n");
    out.push_str("    empty_qualname_hint: Option<&str>,\n");
    out.push_str(") -> PyResult<Py<PyAny>> {\n");
    out.push_str("    let qualname: Option<String> = if ticks.len() == 0 {\n");
    out.push_str("        empty_qualname_hint.map(std::string::ToString::to_string)\n");
    out.push_str("    } else {\n");
    out.push_str("        let first = ticks.get_item(0)?;\n");
    out.push_str("        Some(first.get_type().qualname()?.extract()?)\n");
    out.push_str("    };\n");
    out.push_str("    let Some(qualname) = qualname else {\n");
    out.push_str("        // Empty list + no hint -> zero-column Table (documented contract).\n");
    out.push_str("        let schema = Arc::new(Schema::empty());\n");
    out.push_str("        let batch = RecordBatch::new_empty(schema);\n");
    out.push_str("        return record_batch_to_pyarrow_table(py, batch);\n");
    out.push_str("    };\n");
    out.push_str("    let batch = match qualname.as_str() {\n");
    for type_name in sorted_type_names(schema) {
        let class = pyclass_name(type_name);
        writeln!(out, "        \"{class}\" => {{").unwrap();
        writeln!(
            out,
            "            <{class} as ArrowFromPyclassList>::read_batch(ticks)?"
        )
        .unwrap();
        out.push_str("        }\n");
    }
    out.push_str("        other => {\n");
    out.push_str("            return Err(pyo3::exceptions::PyRuntimeError::new_err(format!(\n");
    out.push_str(
        "                \"pyclass_list_to_arrow_table: unknown tick type `{other}` -- \\\n",
    );
    out.push_str("                 expected a value from `thetadatadx`'s typed tick classes\"\n");
    out.push_str("            )));\n");
    out.push_str("        }\n");
    out.push_str("    };\n");
    out.push_str("    record_batch_to_pyarrow_table(py, batch)\n");
    out.push_str("}\n");

    // Shared helper: convert RecordBatch -> pyarrow.Table via the C Data
    // Interface. The conversion is zero-copy: the RecordBatch buffers are
    // exported through an ArrowArrayStream whose lifetime pyarrow assumes.
    out.push('\n');
    out.push_str("/// Zero-copy RecordBatch -> pyarrow.Table via `arrow::pyarrow::IntoPyArrow`\n");
    out.push_str("/// on `arrow::pyarrow::Table`. One batch in, one Table out; pyarrow owns\n");
    out.push_str("/// the buffers afterwards. The conversion goes through the Arrow C Data\n");
    out.push_str("/// Interface -- Rust hands pyarrow an `ArrowArrayStream` FFI pointer and\n");
    out.push_str("/// the Python side aliases the underlying buffers in place.\n");
    out.push_str("pub(crate) fn record_batch_to_pyarrow_table(py: Python<'_>, batch: RecordBatch) -> PyResult<Py<PyAny>> {\n");
    out.push_str("    let schema = batch.schema();\n");
    out.push_str("    let table = arrow::pyarrow::Table::try_new(vec![batch], schema)\n");
    out.push_str(
        "        .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(e.to_string()))?;\n",
    );
    out.push_str("    let obj = table.into_pyarrow(py)?;\n");
    out.push_str("    Ok(obj.unbind())\n");
    out.push_str("}\n");

    // Per-class pyclass reader -- one helper per tick class. Casts each list
    // item down to the concrete pyclass and reads every #[pyo3(get)] field
    // via `.borrow().field` (no Python-level getattr roundtrip).
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_python_arrow_from_pyclass_reader(type_name, def));
        out.push('\n');
    }

    // Trait + impls -- lets each dispatcher arm call
    // `<ClassType as ArrowFromPyclassList>::read_batch(ticks)` without
    // re-emitting the body in every match arm.
    out.push_str("/// Trait impl'd by every generated tick pyclass so the qualname match\n");
    out.push_str("/// in `pyclass_list_to_arrow_table` dispatches straight to a typed\n");
    out.push_str("/// per-class reader instead of duplicating the body per arm.\n");
    out.push_str("trait ArrowFromPyclassList: pyo3::PyClass {\n");
    out.push_str(
        "    fn read_batch<'py>(ticks: &Bound<'py, pyo3::types::PyList>) -> PyResult<RecordBatch>;\n",
    );
    out.push_str("}\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_python_arrow_trait_impl(type_name, def));
        out.push('\n');
    }
    out
}

/// Emit a per-class reader function name for the dispatcher.
fn python_arrow_reader_fn_name(type_name: &str) -> String {
    format!(
        "read_arrow_batch_from_{}_pyclass_list",
        screaming_snake_to_snake(type_name)
    )
}

/// Map `EodTick` -> `eod_tick`, `OHLCTick` -> `o_h_l_c_tick`, etc.
/// Shared with `render_python_arrow_trait_impl`.
fn screaming_snake_to_snake(type_name: &str) -> String {
    let mut out = String::new();
    for (i, c) in type_name.chars().enumerate() {
        if c.is_uppercase() {
            if i != 0 {
                out.push('_');
            }
            for lc in c.to_lowercase() {
                out.push(lc);
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Emit a per-class reader function that walks the `PyList`, casts
/// each element down to the concrete pyclass, and collects every
/// `#[pyo3(get)]` field into a typed Arrow array. One pass over the
/// list per column -- cheap because each pyclass field access is a
/// direct C-offset read.
fn render_python_arrow_from_pyclass_reader(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let fn_name = python_arrow_reader_fn_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";
    let is_contract = def.contract_id;

    writeln!(
        out,
        "fn {fn_name}<'py>(ticks: &Bound<'py, pyo3::types::PyList>) -> PyResult<RecordBatch> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    let schema = arrow_schema_for_qualname(\"{class}\").expect(\"generated schema must be present for {class}\");"
    )
    .unwrap();
    out.push_str("    let n = ticks.len();\n");

    // Pre-size typed Vecs; one pass per column. `OptionContract.right`
    // is the single column whose pyclass-visible type differs from its
    // schema type (String on the pyclass, `i32` in the TOML); see the
    // matching rules in `render_python_tick_class_struct` /
    // `render_python_tick_class_list_fn`. Mirror that projection here so
    // the Arrow array buffer matches what the pyclass actually exposes.
    let mut column_decls: Vec<(String, String)> = Vec::new(); // (ident, effective type)
    for column in &def.columns {
        let effective_type: &str = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            column.r#type.as_str()
        };
        let rust_ty = match effective_type {
            "i32" | "eod_num" | "eod_date" => "i32",
            "i64" | "eod_num64" => "i64",
            "f64" | "price" | "eod_price" => "f64",
            "String" => "String",
            other => panic!("unsupported column type '{other}' in pyclass reader for {type_name}"),
        };
        writeln!(
            out,
            "    let mut col_{field}: Vec<{rust_ty}> = Vec::with_capacity(n);",
            field = column.field
        )
        .unwrap();
        column_decls.push((column.field.clone(), effective_type.to_string()));
    }
    if is_quote_tick {
        out.push_str("    let mut col_midpoint: Vec<f64> = Vec::with_capacity(n);\n");
    }
    if is_contract {
        out.push_str("    let mut col_expiration: Vec<i32> = Vec::with_capacity(n);\n");
        out.push_str("    let mut col_strike: Vec<f64> = Vec::with_capacity(n);\n");
        out.push_str("    let mut col_right: Vec<String> = Vec::with_capacity(n);\n");
    }

    out.push_str("    for i in 0..n {\n");
    out.push_str("        let item = ticks.get_item(i)?;\n");
    writeln!(
        out,
        "        let typed: pyo3::PyRef<'_, {class}> = item.extract().map_err(|_| {{"
    )
    .unwrap();
    writeln!(
        out,
        "            pyo3::exceptions::PyRuntimeError::new_err(format!("
    )
    .unwrap();
    writeln!(
        out,
        "                \"pyclass_list_to_arrow_table: expected all items to be `{class}`, \\\n                 got `{{}}` at index {{}}\", item.get_type().qualname().unwrap_or_else(|_| pyo3::types::PyString::new(ticks.py(), \"?\")), i"
    )
    .unwrap();
    out.push_str("            ))\n");
    out.push_str("        })?;\n");
    for column in &def.columns {
        let field = &column.field;
        // `OptionContract.right` is a `String` on the pyclass even though
        // its schema type is `i32`; see the projection in
        // `render_python_tick_class_struct`. Match the pyclass type, not
        // the raw column type, so `typed.right.clone()` compiles.
        let effective_type: &str = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            column.r#type.as_str()
        };
        match effective_type {
            "String" => {
                writeln!(out, "        col_{field}.push(typed.{field}.clone());").unwrap();
            }
            _ => {
                writeln!(out, "        col_{field}.push(typed.{field});").unwrap();
            }
        }
    }
    if is_quote_tick {
        out.push_str("        col_midpoint.push(typed.midpoint);\n");
    }
    if is_contract {
        out.push_str("        col_expiration.push(typed.expiration);\n");
        out.push_str("        col_strike.push(typed.strike);\n");
        out.push_str("        col_right.push(typed.right.clone());\n");
    }
    out.push_str("    }\n");

    // Build arrays.
    out.push_str("    let columns: Vec<ArrayRef> = vec![\n");
    for (field, column_type) in &column_decls {
        let ctor = arrow_array_ctor(column_type);
        writeln!(
            out,
            "        Arc::new({ctor}::from(col_{field})) as ArrayRef,"
        )
        .unwrap();
    }
    if is_quote_tick {
        out.push_str("        Arc::new(Float64Array::from(col_midpoint)) as ArrayRef,\n");
    }
    if is_contract {
        out.push_str("        Arc::new(Int32Array::from(col_expiration)) as ArrayRef,\n");
        out.push_str("        Arc::new(Float64Array::from(col_strike)) as ArrayRef,\n");
        out.push_str("        Arc::new(StringArray::from(col_right)) as ArrayRef,\n");
    }
    out.push_str("    ];\n");
    out.push_str(
        "    RecordBatch::try_new(schema, columns).map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(e.to_string()))\n",
    );
    out.push_str("}\n");
    out
}

/// Emit the `ArrowFromPyclassList` trait impl for each tick pyclass.
fn render_python_arrow_trait_impl(type_name: &str, _def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let reader = python_arrow_reader_fn_name(type_name);
    writeln!(out, "impl ArrowFromPyclassList for {class} {{").unwrap();
    out.push_str(
        "    fn read_batch<'py>(ticks: &Bound<'py, pyo3::types::PyList>) -> PyResult<RecordBatch> {\n",
    );
    writeln!(out, "        {reader}(ticks)").unwrap();
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn render_cli_raw_headers(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        let const_name = cli_raw_header_const_name(type_name);
        let headers = cli_raw_headers(type_name, def);
        writeln!(out, "pub(crate) const {const_name}: &[&str] = &[").unwrap();
        for header in headers {
            writeln!(out, "    {header:?},").unwrap();
        }
        out.push_str("];\n\n");
    }
    out
}

fn cli_raw_header_const_name(type_name: &str) -> &'static str {
    match type_name {
        "CalendarDay" => "CALENDAR_DAY_RAW_HEADERS",
        "EodTick" => "EOD_TICK_RAW_HEADERS",
        "GreeksTick" => "GREEKS_TICK_RAW_HEADERS",
        "InterestRateTick" => "INTEREST_RATE_TICK_RAW_HEADERS",
        "IvTick" => "IV_TICK_RAW_HEADERS",
        "MarketValueTick" => "MARKET_VALUE_TICK_RAW_HEADERS",
        "OhlcTick" => "OHLC_TICK_RAW_HEADERS",
        "OpenInterestTick" => "OPEN_INTEREST_TICK_RAW_HEADERS",
        "OptionContract" => "OPTION_CONTRACT_RAW_HEADERS",
        "PriceTick" => "PRICE_TICK_RAW_HEADERS",
        "QuoteTick" => "QUOTE_TICK_RAW_HEADERS",
        "TradeQuoteTick" => "TRADE_QUOTE_TICK_RAW_HEADERS",
        "TradeTick" => "TRADE_TICK_RAW_HEADERS",
        other => panic!("unsupported CLI raw-header type: {other}"),
    }
}

fn cli_raw_headers(type_name: &str, def: &TickTypeDef) -> Vec<String> {
    let mut headers: Vec<String> = def
        .columns
        .iter()
        .map(|column| column.name.clone())
        .collect();
    if type_name == "QuoteTick" {
        headers.push("midpoint".to_string());
    }
    if def.contract_id {
        headers.extend(
            ["expiration", "strike", "right"]
                .into_iter()
                .map(std::string::ToString::to_string),
        );
    }
    headers
}

// ── Python typed-pyclass tick path ────────────────────────────────────────
//
// Generates one `#[pyclass]` struct per tick schema plus a per-tick
// `*_to_pyclass_list` converter that returns a `Py<PyList>` of those classes.
// This is the primary return shape for all historical endpoint methods —
// matches the typed-struct approach already used by Rust core, TypeScript,
// Go, and C++ FFI. The existing `*_to_columnar` converters above remain for
// internal DataFrame-helper use.

fn pyclass_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "EodTick",
        "OhlcTick" => "OhlcTick",
        "TradeTick" => "TradeTick",
        "QuoteTick" => "QuoteTick",
        "TradeQuoteTick" => "TradeQuoteTick",
        "OpenInterestTick" => "OpenInterestTick",
        "MarketValueTick" => "MarketValueTick",
        "GreeksTick" => "GreeksTick",
        "IvTick" => "IvTick",
        "PriceTick" => "PriceTick",
        "CalendarDay" => "CalendarDay",
        "InterestRateTick" => "InterestRateTick",
        "OptionContract" => "OptionContract",
        other => panic!("unsupported Python pyclass type: {other}"),
    }
}

fn python_list_fn_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "eod_ticks_to_pyclass_list",
        "OhlcTick" => "ohlc_ticks_to_pyclass_list",
        "TradeTick" => "trade_ticks_to_pyclass_list",
        "QuoteTick" => "quote_ticks_to_pyclass_list",
        "TradeQuoteTick" => "trade_quote_ticks_to_pyclass_list",
        "OpenInterestTick" => "open_interest_ticks_to_pyclass_list",
        "MarketValueTick" => "market_value_ticks_to_pyclass_list",
        "GreeksTick" => "greeks_ticks_to_pyclass_list",
        "IvTick" => "iv_ticks_to_pyclass_list",
        "PriceTick" => "price_ticks_to_pyclass_list",
        "CalendarDay" => "calendar_days_to_pyclass_list",
        "InterestRateTick" => "interest_rate_ticks_to_pyclass_list",
        "OptionContract" => "option_contracts_to_pyclass_list",
        other => panic!("unsupported Python list fn: {other}"),
    }
}

fn render_python_tick_classes(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Typed pyclass structs per tick type + list converters.\n");
    out.push_str("// Matches the typed-struct approach used by Rust core, TypeScript, Go,\n");
    out.push_str("// and C++ FFI. Primary return shape for historical endpoint methods.\n\n");

    let type_names = sorted_type_names(schema);

    // Structs + pymethods.
    for type_name in &type_names {
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_class_struct(type_name, def));
        out.push('\n');
    }

    // List converters.
    for type_name in &type_names {
        let def = &schema.types[*type_name];
        out.push_str(&render_python_tick_class_list_fn(type_name, def));
        out.push('\n');
    }

    // Registration helper.
    out.push_str(
        "pub(crate) fn register_tick_classes(m: &Bound<'_, PyModule>) -> PyResult<()> {\n",
    );
    for type_name in &type_names {
        writeln!(out, "    m.add_class::<{}>()?;", pyclass_name(type_name)).unwrap();
    }
    out.push_str("    Ok(())\n}\n\n");

    // Note: the `columns_for_qualname` dispatcher that used to live
    // here has been subsumed by `arrow_schema_for_qualname` in
    // `tick_arrow.rs` -- the Arrow schema carries the column names
    // AND types in one typed surface, so the bare name list became
    // redundant.
    out
}

/// Strip " -- N fields[...]." from the first doc line so the rendered
/// comment reflects the actual field set once `contract_id` and
/// `QuoteTick` midpoint get appended to `def.columns`. Words stay stable
/// even when a schema edit adds/removes a column, so we drop the numeric
/// count instead of recomputing it per surface.
fn strip_field_count_from_doc(doc: &str) -> String {
    let first_line = doc.lines().next().unwrap_or("");
    if let Some(pos) = first_line.find(" -- ") {
        let after_dash = &first_line[pos + 4..];
        if after_dash.starts_with(|c: char| c.is_ascii_digit()) {
            let rest = after_dash
                .find(". ")
                .map(|i| &after_dash[i + 2..])
                .unwrap_or("");
            if rest.is_empty() {
                return format!("{}.", &first_line[..pos]);
            }
            return format!("{}. {rest}", &first_line[..pos]);
        }
    }
    first_line.to_string()
}

/// Pick the first few fields for `__repr__` rendering. Caps at
/// `max_fields` to keep output one-line readable in REPL / debugger
/// transcripts. Contract-id fields are appended after the schema
/// columns on the emitted struct, so we mirror that order here — the
/// first few real columns come first (e.g. `ms_of_day`, `open`,
/// `high`, `low`), never the trailing `expiration`/`strike`/`right`
/// triple which is identical across a result set and carries no
/// per-row diagnostic signal.
fn repr_fields_for_tick<'a>(
    type_name: &str,
    def: &'a TickTypeDef,
    max_fields: usize,
) -> Vec<ReprField<'a>> {
    let mut fields: Vec<ReprField<'a>> = Vec::new();
    for column in &def.columns {
        if fields.len() >= max_fields {
            break;
        }
        // `OptionContract.right` is surfaced as a String (see
        // `render_python_tick_class_struct`), so prefer `{:?}` so the
        // quotes are visible — consistent with other String fields
        // like `QuoteTick` never exposing `right` directly.
        let is_string = (type_name == "OptionContract" && column.field == "right")
            || matches!(column.r#type.as_str(), "String");
        fields.push(ReprField {
            name: &column.field,
            is_string,
        });
    }
    fields
}

struct ReprField<'a> {
    name: &'a str,
    is_string: bool,
}

fn render_python_tick_class_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";
    let doc_text = if def.doc.is_empty() {
        format!("Typed {type_name} record.")
    } else {
        let stripped = strip_field_count_from_doc(&def.doc);
        // Preserve any trailing doc lines (e.g. `OptionContract`'s "Cannot
        // be `Copy` ..." note) by splicing the stripped first line back
        // onto the rest of the original doc. Lines after the first rarely
        // carry field-count language.
        let mut combined = stripped;
        for line in def.doc.lines().skip(1) {
            combined.push('\n');
            combined.push_str(line);
        }
        combined
    };
    for line in doc_text.lines() {
        writeln!(out, "/// {line}").unwrap();
    }
    // `#[must_use]` — these ticks come from expensive network calls; dropping
    // the result silently is a bug. `skip_from_py_object` opts out of the
    // auto-derived `FromPyObject` impl (deprecated for `Clone` pyclasses in
    // pyo3 0.28+); these classes are returned FROM Rust to Python but never
    // consumed AS arguments INTO Rust, so `FromPyObject` is dead weight.
    out.push_str("#[must_use]\n");
    out.push_str("#[pyclass(module = \"thetadatadx\", frozen, skip_from_py_object)]\n");
    out.push_str("#[derive(Clone)]\n");
    writeln!(out, "pub(crate) struct {class} {{").unwrap();
    for column in &def.columns {
        // Special case: `OptionContract.right` is stored on the wire as
        // `i32` (ASCII 67/80), but every other tick surfaces `right` as
        // a Python `"C" | "P" | ""` string (via the contract_id injection
        // below). Emit it as String here too so the two paths match and
        // consumer code doesn't get an integer on one endpoint and a
        // string on the others.
        let rust_type = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            pyclass_field_type(column.r#type.as_str(), type_name)
        };
        writeln!(out, "    #[pyo3(get)] pub {}: {},", column.field, rust_type).unwrap();
    }
    if is_quote_tick {
        out.push_str("    #[pyo3(get)] pub midpoint: f64,\n");
    }
    if def.contract_id {
        out.push_str("    #[pyo3(get)] pub expiration: i32,\n");
        out.push_str("    #[pyo3(get)] pub strike: f64,\n");
        out.push_str("    #[pyo3(get)] pub right: String,\n");
    }
    out.push_str("}\n");

    // `__repr__` shows the first six schema fields with their live
    // values so REPLs and debuggers (pdb, IDE watch windows, pytest
    // short-repr) surface per-instance data instead of a useless
    // `"<EodTick(...)>"`. Six is a readable cap; `contract_id` columns
    // (`expiration`/`strike`/`right`) are identical across a result
    // set and carry no per-row signal, so we skip them.
    //
    // `#[new]` constructor accepts every field as a kwarg defaulting
    // to zero / empty-string. Tick classes are primarily returned
    // from the network endpoints so users rarely need to build them
    // manually; the one exception is test fixtures -- the Arrow
    // DataFrame adapter test suite constructs known lists in Python
    // and round-trips them through `to_arrow` / `to_dataframe` /
    // `to_polars` to verify value preservation. Without this ctor
    // there is no way to drive that test.
    writeln!(out, "#[pymethods]").unwrap();
    writeln!(out, "impl {class} {{").unwrap();
    out.push_str(&render_python_tick_class_new(type_name, def));
    let repr_fields = repr_fields_for_tick(type_name, def, 6);
    if repr_fields.is_empty() {
        // Unlikely (every tick has columns), but keep the fallback so
        // a future schema type without columns still compiles.
        writeln!(
            out,
            "    fn __repr__(&self) -> String {{ \"{class}()\".to_string() }}"
        )
        .unwrap();
    } else {
        let mut fmt_string = String::new();
        for (idx, field) in repr_fields.iter().enumerate() {
            if idx > 0 {
                fmt_string.push_str(", ");
            }
            fmt_string.push_str(field.name);
            fmt_string.push('=');
            // `{:?}` quotes strings (`right="C"`), `{}` for numerics —
            // matches the shape an engineer expects in a debugger line.
            fmt_string.push_str(if field.is_string { "{:?}" } else { "{}" });
        }
        let args = repr_fields
            .iter()
            .map(|f| format!("self.{}", f.name))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "    fn __repr__(&self) -> String {{").unwrap();
        writeln!(out, "        format!(\"{class}({fmt_string})\", {args})").unwrap();
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    out
}

fn pyclass_field_type(column_type: &str, type_name: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        "i64" | "eod_num64" => "i64",
        "f64" | "price" | "eod_price" => "f64",
        "String" => "String",
        other => panic!("unsupported column type '{other}' in pyclass for {type_name}"),
    }
}

/// Emit a `#[new]` kwarg constructor so Python test fixtures can
/// build tick instances. Every field accepts a default (0 / 0.0 /
/// empty-string) so callers can pass just the fields they care
/// about: `EodTick(ms_of_day=1, volume=1_000)`.
fn render_python_tick_class_new(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    struct CtorField<'a> {
        name: &'a str,
        rust_type: &'a str,
        default: &'static str,
    }
    let mut fields: Vec<CtorField> = Vec::new();
    for column in &def.columns {
        // Same OptionContract.right special case as the struct emitter.
        let rust_type = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            pyclass_field_type(column.r#type.as_str(), type_name)
        };
        let default = match rust_type {
            "i32" => "0i32",
            "i64" => "0i64",
            "f64" => "0.0f64",
            "String" => "String::new()",
            other => panic!("unhandled pyclass ctor default for {other}"),
        };
        fields.push(CtorField {
            name: column.field.as_str(),
            rust_type,
            default,
        });
    }
    if type_name == "QuoteTick" {
        fields.push(CtorField {
            name: "midpoint",
            rust_type: "f64",
            default: "0.0f64",
        });
    }
    if def.contract_id {
        fields.push(CtorField {
            name: "expiration",
            rust_type: "i32",
            default: "0i32",
        });
        fields.push(CtorField {
            name: "strike",
            rust_type: "f64",
            default: "0.0f64",
        });
        fields.push(CtorField {
            name: "right",
            rust_type: "String",
            default: "String::new()",
        });
    }

    // `#[pyo3(signature = (*, a=..., b=...))]` forces keyword-only args so
    // the argument order in tests doesn't hard-code the schema field order.
    out.push_str("    #[new]\n");
    out.push_str("    #[pyo3(signature = (*,");
    for (idx, f) in fields.iter().enumerate() {
        if idx > 0 {
            out.push(',');
        }
        // pyo3 accepts literal Rust expressions for kwarg defaults.
        out.push_str(&format!(" {} = {}", f.name, f.default));
    }
    out.push_str("))]\n");
    // `too_many_arguments` is suppressed at the crate build command
    // (`cargo clippy ... -A clippy::too_many_arguments` in the
    // validation checklist) rather than per-function -- the project
    // policy forbids per-item `#[allow(...)]` additions.
    out.push_str("    fn new(");
    for (idx, f) in fields.iter().enumerate() {
        if idx > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{}: {}", f.name, f.rust_type));
    }
    out.push_str(") -> Self {\n");
    writeln!(out, "        Self {{").unwrap();
    for f in &fields {
        writeln!(out, "            {n},", n = f.name).unwrap();
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out
}

fn render_python_tick_class_list_fn(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let class = pyclass_name(type_name);
    let fn_name = python_list_fn_name(type_name);
    let is_quote_tick = type_name == "QuoteTick";

    writeln!(
        out,
        "pub(crate) fn {fn_name}(py: Python<'_>, ticks: &[tick::{type_name}]) -> PyResult<Py<PyAny>> {{"
    )
    .unwrap();
    out.push_str("    let list = pyo3::types::PyList::empty(py);\n");
    out.push_str("    for t in ticks {\n");
    writeln!(out, "        let obj = {class} {{").unwrap();
    for column in &def.columns {
        // Special case: `OptionContract.right` emits as a
        // `"C" | "P" | ""` string (see struct emitter above). Other
        // ticks get the String `right` from the contract_id injection
        // below; this keeps the standalone OptionContract endpoint in
        // sync so consumers never see a raw `67` / `80` / `0` on one
        // endpoint and a character on every other.
        if type_name == "OptionContract" && column.field == "right" {
            out.push_str(
                "            right: (if t.is_call() { \"C\" } else if t.is_put() { \"P\" } else { \"\" }).to_string(),\n",
            );
            continue;
        }
        let rust_type = pyclass_field_type(column.r#type.as_str(), type_name);
        if rust_type == "String" {
            writeln!(
                out,
                "            {}: t.{}.clone(),",
                column.field, column.field
            )
            .unwrap();
        } else {
            writeln!(out, "            {}: t.{},", column.field, column.field).unwrap();
        }
    }
    if is_quote_tick {
        out.push_str("            midpoint: t.midpoint,\n");
    }
    if def.contract_id {
        out.push_str("            expiration: t.expiration,\n");
        out.push_str("            strike: t.strike,\n");
        out.push_str(
            "            right: (if t.is_call() { \"C\" } else if t.is_put() { \"P\" } else { \"\" }).to_string(),\n",
        );
    }
    out.push_str("        };\n");
    out.push_str("        list.append(Py::new(py, obj)?)?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(list.into_any().unbind())\n");
    out.push_str("}\n");
    out
}

// ── TypeScript tick columnar converters (serde_json) ──────────────────────

// TypeScript columnar converters were removed: the typed class-vec path
// (see `render_ts_tick_classes`) is the only surface consumed by the
// TypeScript SDK. Keeping dead `*_to_columnar` fns behind `#[allow(dead_code)]`
// violates the project's "no band-aid" quality rule.

// ── TypeScript tick classes (#[napi(object)] structs) ────────────────────
//
// Each tick type is emitted as a flat `#[napi(object)]` struct so napi-rs
// generates a matching TypeScript interface in `index.d.ts`. Vec<Tick>
// returns from endpoint methods become `Tick[]` in TS — every historical
// endpoint is fully typed, no `any`.
//
// A parallel `{snake_type}_to_class_vec(&[tick::Type]) -> Vec<Type>` helper
// copies Rust tick structs (from `tdbe::types::tick`) into the #[napi]
// types. The helpers are drop-in substitutes for the `..._to_columnar`
// converters used previously.

fn render_ts_tick_classes(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str("// @generated DO NOT EDIT — regenerated by build.rs from tick_schema.toml\n");
    out.push_str("// Typed #[napi(object)] tick structs + Vec factories. Replaces the old\n");
    out.push_str(
        "// serde_json columnar returns with concrete TypeScript types in index.d.ts.\n\n",
    );
    // napi-rs requires the `BigInt` wrapper for any i64 field that crosses
    // to JS — pull it in whenever a tick column uses one.
    let needs_bigint = schema
        .types
        .values()
        .flat_map(|def| def.columns.iter())
        .any(|col| ts_column_needs_bigint(col.r#type.as_str()));
    if needs_bigint {
        out.push_str("use napi::bindgen_prelude::BigInt;\n\n");
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_struct(type_name, def));
        out.push('\n');
    }
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_ts_tick_class_factory(type_name, def));
        out.push('\n');
    }
    out
}

fn render_ts_tick_class_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let is_quote_tick = type_name == "QuoteTick";
    // Strip " -- N fields[...]." from the first doc line — see
    // `strip_field_count_from_doc` for rationale. Shared with the Python
    // emitter so both surfaces drift together.
    let doc = strip_field_count_from_doc(&def.doc);
    writeln!(out, "/// {doc}").unwrap();
    // `#[must_use]` — Vec<T> returned from expensive network calls should
    // not be silently dropped on the Rust side (napi-rs generates JS
    // bindings, but any Rust-side accidental drop is still a bug).
    out.push_str("#[must_use]\n");
    out.push_str("#[napi(object)]\n");
    out.push_str("#[derive(Clone)]\n");
    writeln!(out, "pub struct {type_name} {{").unwrap();
    for column in &def.columns {
        // Special case: `OptionContract.right` is `i32` (ASCII 67/80) on
        // the wire, but every other tick surfaces `right` as a JS string
        // ("C" | "P" | "") via the `contract_id` injection below. Emit
        // String here too so the two paths match — otherwise consumers
        // get a number on `optionListContracts` and a string elsewhere.
        let rust_type = if type_name == "OptionContract" && column.field == "right" {
            "String"
        } else {
            ts_class_rust_type(&column.r#type, type_name, &column.field)
        };
        writeln!(out, "    pub {}: {},", column.field, rust_type).unwrap();
    }
    if is_quote_tick {
        out.push_str("    pub midpoint: f64,\n");
    }
    if def.contract_id {
        out.push_str("    pub expiration: i32,\n");
        out.push_str("    pub strike: f64,\n");
        out.push_str("    pub right: String,\n");
    }
    out.push_str("}\n");
    out
}

fn render_ts_tick_class_factory(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let fn_name = ts_tick_class_factory_name(type_name);
    writeln!(
        out,
        "fn {fn_name}(ticks: &[tick::{type_name}]) -> Vec<{type_name}> {{"
    )
    .unwrap();
    out.push_str("    ticks\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|t| {\n");
    writeln!(out, "            {type_name} {{").unwrap();
    for column in &def.columns {
        // See `render_ts_tick_class_struct`: OptionContract.right is
        // projected to "C" / "P" / "" so the standalone endpoint matches
        // the contract_id-injected right field on every other tick.
        if type_name == "OptionContract" && column.field == "right" {
            out.push_str(
                "                right: if t.is_call() { \"C\".to_string() } else if t.is_put() { \"P\".to_string() } else { String::new() },\n",
            );
            continue;
        }
        // String fields must be cloned; primitives are Copy. i64/eod_num64
        // cross to JS as `bigint` via `BigInt::from(...)` (see
        // `ts_class_rust_type`).
        let expr = match column.r#type.as_str() {
            "String" => format!("t.{field}.clone()", field = column.field),
            col_type if ts_column_needs_bigint(col_type) => {
                format!("BigInt::from(t.{field})", field = column.field)
            }
            _ => format!("t.{field}", field = column.field),
        };
        writeln!(out, "                {}: {expr},", column.field).unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("                midpoint: t.midpoint,\n");
    }
    if def.contract_id {
        out.push_str("                expiration: t.expiration,\n");
        out.push_str("                strike: t.strike,\n");
        // right is stored as the raw ASCII code (67='C', 80='P') on the
        // Rust tick; project it to a JS-friendly string using the same
        // is_call/is_put helpers the columnar emitter already relies on.
        out.push_str(
            "                right: if t.is_call() { \"C\".to_string() } else if t.is_put() { \"P\".to_string() } else { String::new() },\n",
        );
    }
    out.push_str("            }\n");
    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n");
    out
}

pub(crate) fn ts_tick_class_factory_name(type_name: &str) -> &'static str {
    match type_name {
        "EodTick" => "eod_ticks_to_class_vec",
        "OhlcTick" => "ohlc_ticks_to_class_vec",
        "TradeTick" => "trade_ticks_to_class_vec",
        "QuoteTick" => "quote_ticks_to_class_vec",
        "TradeQuoteTick" => "trade_quote_ticks_to_class_vec",
        "OpenInterestTick" => "open_interest_ticks_to_class_vec",
        "MarketValueTick" => "market_value_ticks_to_class_vec",
        "GreeksTick" => "greeks_ticks_to_class_vec",
        "IvTick" => "iv_ticks_to_class_vec",
        "PriceTick" => "price_ticks_to_class_vec",
        "CalendarDay" => "calendar_days_to_class_vec",
        "InterestRateTick" => "interest_rate_ticks_to_class_vec",
        "OptionContract" => "option_contracts_to_class_vec",
        other => panic!("unsupported TypeScript tick class factory type: {other}"),
    }
}

fn ts_class_rust_type(column_type: &str, type_name: &str, field: &str) -> &'static str {
    match column_type {
        "i32" | "eod_num" | "eod_date" => "i32",
        // napi-rs 3.x: `i64` must surface as JS `bigint` to preserve full
        // precision past `Number.MAX_SAFE_INTEGER` (2^53 - 1). High-volume
        // symbols can easily exceed 2.1B cumulative volume, so `number`
        // (f64) would silently lose low-order bits. Use the `BigInt`
        // wrapper the FPSS event classes already rely on.
        "i64" | "eod_num64" => "BigInt",
        "f64" | "price" | "eod_price" => "f64",
        "String" => "String",
        other => panic!("unsupported TS class column type '{other}' in {type_name}.{field}"),
    }
}

/// Returns `true` when a tick column surfaces as `BigInt` in the TS typed
/// struct (i.e. crosses to JS as `bigint` via `BigInt::from(...)`).
fn ts_column_needs_bigint(column_type: &str) -> bool {
    matches!(column_type, "i64" | "eod_num64")
}

// TypeScript columnar-interface file (`src/types.ts`) was removed with
// the columnar Rust path. Consumers get typed shapes from `index.d.ts`
// (emitted by napi-rs from the `#[napi(object)]` tick classes) instead.

fn render_go_tick_converters(schema: &Schema) -> String {
    let mut out = String::new();
    // Go spec header: `^// Code generated .* DO NOT EDIT\.$` — see
    // https://golang.org/s/generatedcode. Required for go vet / gofmt /
    // staticcheck to recognize this as machine-generated. Non-Go
    // emitters keep the uniform `@generated` form.
    out.push_str("// Code generated by build.rs from tick_schema.toml; DO NOT EDIT.\n\n");
    out.push_str("package thetadatadx\n\n");
    out.push_str("/*\n#include \"ffi_bridge.h\"\n*/\nimport \"C\"\n\n");
    out.push_str("import \"unsafe\"\n\n");
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_go_tick_converter(type_name, def));
        out.push('\n');
    }
    out
}

fn render_go_tick_converter(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let (func_name, arr_type, ffi_type, public_type) = match type_name {
        "EodTick" => ("convertEodTicks", "C.TdxTickArray", "cEodTick", "EodTick"),
        "OhlcTick" => (
            "convertOhlcTicks",
            "C.TdxTickArray",
            "cOhlcTick",
            "OhlcTick",
        ),
        "TradeTick" => (
            "convertTradeTicks",
            "C.TdxTickArray",
            "cTradeTick",
            "TradeTick",
        ),
        "QuoteTick" => (
            "convertQuoteTicks",
            "C.TdxTickArray",
            "cQuoteTick",
            "QuoteTick",
        ),
        "TradeQuoteTick" => (
            "convertTradeQuoteTicks",
            "C.TdxTickArray",
            "cTradeQuoteTick",
            "TradeQuoteTick",
        ),
        "OpenInterestTick" => (
            "convertOpenInterestTicks",
            "C.TdxTickArray",
            "cOpenInterestTick",
            "OpenInterestTick",
        ),
        "MarketValueTick" => (
            "convertMarketValueTicks",
            "C.TdxTickArray",
            "cMarketValueTick",
            "MarketValueTick",
        ),
        "GreeksTick" => (
            "convertGreeksTicks",
            "C.TdxTickArray",
            "cGreeksTick",
            "GreeksTick",
        ),
        "IvTick" => ("convertIvTicks", "C.TdxTickArray", "cIvTick", "IVTick"),
        "PriceTick" => (
            "convertPriceTicks",
            "C.TdxTickArray",
            "cPriceTick",
            "PriceTick",
        ),
        "CalendarDay" => (
            "convertCalendarDays",
            "C.TdxTickArray",
            "cCalendarDay",
            "CalendarDay",
        ),
        "InterestRateTick" => (
            "convertInterestRateTicks",
            "C.TdxTickArray",
            "cInterestRateTick",
            "InterestRateTick",
        ),
        "OptionContract" => (
            "convertOptionContracts",
            "C.TdxOptionContractArray",
            "cOptionContract",
            "OptionContract",
        ),
        other => panic!("unsupported Go tick converter type: {other}"),
    };

    writeln!(out, "func {func_name}(arr {arr_type}) []{public_type} {{").unwrap();
    out.push_str("    if arr.data == nil || arr.len == 0 {\n");
    out.push_str("        return nil\n");
    out.push_str("    }\n");
    out.push_str("    n := int(arr.len)\n");
    writeln!(out, "    src := unsafe.Slice((*{ffi_type})(arr.data), n)").unwrap();
    writeln!(out, "    result := make([]{public_type}, n)").unwrap();
    out.push_str("    for i, t := range src {\n");
    if type_name == "OptionContract" {
        out.push_str("        root := \"\"\n");
        out.push_str("        if t.Root != 0 {\n");
        out.push_str("            root = C.GoString((*C.char)(unsafe.Pointer(t.Root)))\n");
        out.push_str("        }\n");
    }
    writeln!(out, "        result[i] = {public_type}{{").unwrap();
    for column in &def.columns {
        let public_field = go_public_field_name(type_name, &column.field);
        let source_expr = go_source_expr(type_name, &column.field, &column.r#type);
        writeln!(out, "            {public_field}: {source_expr},").unwrap();
    }
    if type_name == "QuoteTick" {
        out.push_str("            Midpoint: t.Midpoint,\n");
    }
    if def.contract_id {
        out.push_str("            Expiration: t.Expiration,\n");
        out.push_str("            Strike: t.Strike,\n");
        out.push_str("            Right: RightStr(t.Right),\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    return result\n");
    out.push_str("}\n");
    out
}

fn go_public_field_name(type_name: &str, field: &str) -> &'static str {
    match (type_name, field) {
        ("GreeksTick", "implied_volatility") => "IV",
        ("IvTick", "implied_volatility") => "IV",
        (_, "iv_error") => "IVError",
        ("MarketValueTick", "market_bid") => "MarketBid",
        ("MarketValueTick", "market_ask") => "MarketAsk",
        ("MarketValueTick", "market_price") => "MarketPrice",
        (_, "ms_of_day") => "MsOfDay",
        (_, "ms_of_day2") => "MsOfDay2",
        (_, "quote_ms_of_day") => "QuoteMsOfDay",
        (_, "ext_condition1") => "ExtCondition1",
        (_, "ext_condition2") => "ExtCondition2",
        (_, "ext_condition3") => "ExtCondition3",
        (_, "ext_condition4") => "ExtCondition4",
        (_, "condition_flags") => "ConditionFlags",
        (_, "price_flags") => "PriceFlags",
        (_, "volume_type") => "VolumeType",
        (_, "records_back") => "RecordsBack",
        (_, "bid_size") => "BidSize",
        (_, "bid_exchange") => "BidExchange",
        (_, "bid_condition") => "BidCondition",
        (_, "ask_size") => "AskSize",
        (_, "ask_exchange") => "AskExchange",
        (_, "ask_condition") => "AskCondition",
        (_, "open_interest") => "OpenInterest",
        (_, "market_bid") => "MarketBid",
        (_, "market_ask") => "MarketAsk",
        (_, "market_price") => "MarketPrice",
        (_, "dual_delta") => "DualDelta",
        (_, "dual_gamma") => "DualGamma",
        (_, "is_open") => "IsOpen",
        other => Box::leak(go_pascal_case(other.1).into_boxed_str()),
    }
}

fn go_source_expr(type_name: &str, field: &str, kind: &str) -> String {
    let ffi_field = go_ffi_field_name(field);
    match (type_name, field, kind) {
        ("OptionContract", "root", "String") => "root".into(),
        ("OptionContract", "right", "i32") => "RightStr(t.Right)".into(),
        (_, "right", "i32") => "RightStr(t.Right)".into(),
        (_, "is_open", "i32") => "t.IsOpen != 0".into(),
        ("OptionContract", _, "i32") => format!("int(t.{ffi_field})"),
        (_, _, "i32") if field == "expiration" => format!("t.{ffi_field}"),
        (_, _, "i32") | (_, _, "eod_num") | (_, _, "eod_date") => format!("int(t.{ffi_field})"),
        (_, _, "i64")
        | (_, _, "eod_num64")
        | (_, _, "f64")
        | (_, _, "price")
        | (_, _, "eod_price") => format!("t.{ffi_field}"),
        (_, _, "String") => format!("t.{ffi_field}"),
        _ => panic!("unsupported Go source expression for {type_name}.{field}:{kind}"),
    }
}

fn go_ffi_field_name(field: &str) -> &'static str {
    match field {
        "implied_volatility" => "ImpliedVolatility",
        "iv_error" => "IvError",
        "market_bid" => "MarketBid",
        "market_ask" => "MarketAsk",
        "market_price" => "MarketPrice",
        "ms_of_day" => "MsOfDay",
        "ms_of_day2" => "MsOfDay2",
        "quote_ms_of_day" => "QuoteMsOfDay",
        "ext_condition1" => "ExtCondition1",
        "ext_condition2" => "ExtCondition2",
        "ext_condition3" => "ExtCondition3",
        "ext_condition4" => "ExtCondition4",
        "condition_flags" => "ConditionFlags",
        "price_flags" => "PriceFlags",
        "volume_type" => "VolumeType",
        "records_back" => "RecordsBack",
        "bid_size" => "BidSize",
        "bid_exchange" => "BidExchange",
        "bid_condition" => "BidCondition",
        "ask_size" => "AskSize",
        "ask_exchange" => "AskExchange",
        "ask_condition" => "AskCondition",
        "open_interest" => "OpenInterest",
        "dual_delta" => "DualDelta",
        "dual_gamma" => "DualGamma",
        "is_open" => "IsOpen",
        other => Box::leak(go_pascal_case(other).into_boxed_str()),
    }
}

fn go_pascal_case(value: &str) -> String {
    value
        .split('_')
        .filter(|segment| !segment.is_empty())
        .map(|segment| match segment {
            "iv" => "IV".to_string(),
            other => {
                let mut chars = other.chars();
                match chars.next() {
                    Some(first) => first.to_uppercase().to_string() + chars.as_str(),
                    None => String::new(),
                }
            }
        })
        .collect::<String>()
}

// ── Go public tick struct generation ──────────────────────────────────────────

/// Map a tick_schema.toml column type to the Go public struct field type.
fn go_public_field_type(type_name: &str, field: &str, kind: &str) -> &'static str {
    // CalendarDay.is_open is a bool in the public API
    if type_name == "CalendarDay" && field == "is_open" {
        return "bool";
    }
    // OptionContract.right is i32 in the schema but exposed as string via RightStr()
    if type_name == "OptionContract" && field == "right" {
        return "string";
    }
    match kind {
        "i32" | "eod_num" | "eod_date" => "int",
        "i64" | "eod_num64" => "int64",
        "f64" | "price" | "eod_price" => "float64",
        "String" => "string",
        _ => panic!("unsupported Go public type for {type_name}.{field}:{kind}"),
    }
}

/// Map a tick_schema.toml column to the JSON tag for the Go public struct.
fn go_json_tag(field: &str) -> String {
    field.to_string()
}

fn render_go_tick_structs(schema: &Schema) -> String {
    let mut out = String::new();
    // Go spec header (see render_go_tick_converters for the rationale).
    out.push_str("// Code generated by build.rs from tick_schema.toml; DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str("// Public Go tick types, RightStr helper, and Greeks struct.\n");
    out.push_str("// C-mirror (FFI) structs live in tick_ffi_mirrors.go (hand-written).\n\n");
    out.push_str("package thetadatadx\n\n");

    // Emit public Go structs for each tick type
    for type_name in sorted_type_names(schema) {
        let def = &schema.types[type_name];
        out.push_str(&render_go_public_struct(type_name, def));
        out.push('\n');
    }

    // RightStr helper
    out.push_str("// RightStr converts the raw right code to a string.\n");
    out.push_str("// 67='C' (Call), 80='P' (Put), 0=\"\" (not set).\n");
    out.push_str("func RightStr(code int32) string {\n");
    out.push_str("\tswitch code {\n");
    out.push_str("\tcase 67:\n");
    out.push_str("\t\treturn \"C\"\n");
    out.push_str("\tcase 80:\n");
    out.push_str("\t\treturn \"P\"\n");
    out.push_str("\tdefault:\n");
    out.push_str("\t\treturn \"\"\n");
    out.push_str("\t}\n");
    out.push_str("}\n\n");

    // Greeks struct (offline utility, not a tick type — matches tdbe::Greeks)
    out.push_str("// Greeks holds the 22 Black-Scholes greeks + IV from all_greeks().\n");
    out.push_str("type Greeks struct {\n");
    for field in &[
        ("Value", "value"),
        ("Delta", "delta"),
        ("Gamma", "gamma"),
        ("Theta", "theta"),
        ("Vega", "vega"),
        ("Rho", "rho"),
        ("IV", "iv"),
        ("IVError", "iv_error"),
        ("Vanna", "vanna"),
        ("Charm", "charm"),
        ("Vomma", "vomma"),
        ("Veta", "veta"),
        ("Speed", "speed"),
        ("Zomma", "zomma"),
        ("Color", "color"),
        ("Ultima", "ultima"),
        ("D1", "d1"),
        ("D2", "d2"),
        ("DualDelta", "dual_delta"),
        ("DualGamma", "dual_gamma"),
        ("Epsilon", "epsilon"),
        ("Lambda", "lambda"),
    ] {
        writeln!(out, "\t{:9} float64 `json:\"{}\"`", field.0, field.1).unwrap();
    }
    out.push_str("}\n");

    out
}

fn render_go_public_struct(type_name: &str, def: &TickTypeDef) -> String {
    let mut out = String::new();
    let go_type = match type_name {
        "IvTick" => "IVTick",
        other => other,
    };
    writeln!(
        out,
        "// {} — {}",
        go_type,
        def.doc.lines().next().unwrap_or("")
    )
    .unwrap();
    writeln!(out, "type {go_type} struct {{").unwrap();

    for column in &def.columns {
        let public_field = go_public_field_name(type_name, &column.field);
        let go_type_str = go_public_field_type(type_name, &column.field, &column.r#type);
        let json_tag = go_json_tag(&column.name);
        writeln!(
            out,
            "\t{:14} {:<8} `json:\"{json_tag}\"`",
            public_field, go_type_str
        )
        .unwrap();
    }
    // QuoteTick gets a Midpoint field
    if type_name == "QuoteTick" {
        out.push_str("\tMidpoint       float64  `json:\"midpoint\"`\n");
    }
    // contract_id fields
    if def.contract_id {
        out.push_str("\tExpiration     int32    `json:\"expiration,omitempty\"`\n");
        out.push_str("\tStrike         float64  `json:\"strike,omitempty\"`\n");
        out.push_str("\tRight          string   `json:\"right,omitempty\"`\n");
    }
    out.push_str("}\n");
    out
}
