// ─────────────────────────────────────────────────────────────────────────────
//  Code-generate tick structs + parsers from tick_schema.toml
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct Schema {
    types: HashMap<String, TickTypeDef>,
}

/// Parsed from tick_schema.toml. `doc`, `copy`, and `align` exist in the
/// TOML for documentation / FFI layout hints but are not used by the parser
/// generator — tick structs live in `tdbe::types::tick` (hand-written).
#[derive(Debug, Deserialize)]
struct TickTypeDef {
    #[allow(dead_code)]
    doc: String,
    #[allow(dead_code)]
    copy: bool,
    #[serde(default)]
    #[allow(dead_code)]
    align: Option<u32>,
    parser: String,
    #[serde(default)]
    required: Vec<String>,
    #[serde(default)]
    eod_style: bool,
    #[serde(default)]
    contract_id: bool,
    columns: Vec<ColumnDef>,
}

#[derive(Debug, Deserialize)]
struct ColumnDef {
    name: String,
    field: String,
    r#type: String,
}

pub fn generate() -> Result<(), Box<dyn std::error::Error>> {
    let schema_path = "tick_schema.toml";
    let schema_str = std::fs::read_to_string(schema_path)?;
    let schema: Schema = toml::from_str(&schema_str)?;

    let out_dir = std::env::var("OUT_DIR")?;

    // Collect type names and sort for deterministic output.
    let mut type_names: Vec<&String> = schema.types.keys().collect();
    type_names.sort();

    // ── Generate decode_generated.rs (parser functions) ──────────────────────
    // Struct definitions now live in the `tdbe` crate (crates/tdbe/src/types/tick.rs).
    // Only parser functions are generated here.
    let mut parsers = String::new();
    parsers.push_str(
        "// Auto-generated by build.rs from tick_schema.toml \u{2014} do not edit manually.\n\n",
    );
    // Note: tick types are imported by decode.rs via `use tdbe::types::tick::*;`
    // No additional imports needed in the generated code.

    for type_name in &type_names {
        let def = &schema.types[*type_name];
        generate_parser(&mut parsers, type_name, def);
    }

    let parsers_dest = Path::new(&out_dir).join("decode_generated.rs");
    std::fs::write(&parsers_dest, &parsers)?;

    // Rerun if schema changes
    println!("cargo:rerun-if-changed={schema_path}");

    Ok(())
}

/// Generate a single parser function.
///
/// Price columns are decoded to `f64` during extraction using the wire
/// `price_type` (internally fetched, never exposed on the public struct).
// Reason: code generator -- the match dispatch over column types cannot be meaningfully split.
#[allow(clippy::too_many_lines)]
fn generate_parser(out: &mut String, type_name: &str, def: &TickTypeDef) {
    let fn_name = &def.parser;

    writeln!(
        out,
        "pub fn {fn_name}(table: &crate::proto::DataTable) -> Vec<{type_name}> {{"
    )
    .unwrap();

    // If eod_style, emit the local EOD helpers inline.
    if def.eod_style {
        out.push_str(
            "    // EOD numeric/time fields may arrive as Price, Number, or Timestamp cells.\n",
        );
        out.push_str("    fn eod_num(row: &crate::proto::DataValueList, idx: usize) -> i32 {\n");
        out.push_str("        row.values\n");
        out.push_str("            .get(idx)\n");
        out.push_str("            .and_then(|dv| dv.data_type.as_ref())\n");
        out.push_str("            .and_then(|dt| match dt {\n");
        out.push_str(
            "                crate::proto::data_value::DataType::Number(n) => Some(*n as i32),\n",
        );
        out.push_str(
            "                crate::proto::data_value::DataType::Price(p) => Some(p.value),\n",
        );
        out.push_str(
            "                crate::proto::data_value::DataType::Timestamp(ts) => Some(crate::decode::timestamp_to_ms_of_day(ts.epoch_ms)),\n",
        );
        out.push_str("                _ => None,\n");
        out.push_str("            })\n");
        out.push_str("            .unwrap_or(0)\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD date fields may arrive as Price, Number, or Timestamp cells.\n");
        out.push_str("    fn eod_date(row: &crate::proto::DataValueList, idx: usize) -> i32 {\n");
        out.push_str("        row.values\n");
        out.push_str("            .get(idx)\n");
        out.push_str("            .and_then(|dv| dv.data_type.as_ref())\n");
        out.push_str("            .and_then(|dt| match dt {\n");
        out.push_str(
            "                crate::proto::data_value::DataType::Number(n) => Some(*n as i32),\n",
        );
        out.push_str(
            "                crate::proto::data_value::DataType::Price(p) => Some(p.value),\n",
        );
        out.push_str(
            "                crate::proto::data_value::DataType::Timestamp(ts) => Some(crate::decode::timestamp_to_date(ts.epoch_ms)),\n",
        );
        out.push_str("                _ => None,\n");
        out.push_str("            })\n");
        out.push_str("            .unwrap_or(0)\n");
        out.push_str("    }\n\n");

        out.push_str("    // EOD price field: decode to f64 from Price or Number cell.\n");
        out.push_str("    fn eod_price(row: &crate::proto::DataValueList, idx: usize) -> f64 {\n");
        out.push_str("        row.values\n");
        out.push_str("            .get(idx)\n");
        out.push_str("            .and_then(|dv| dv.data_type.as_ref())\n");
        out.push_str("            .map(|dt| match dt {\n");
        out.push_str("                crate::proto::data_value::DataType::Price(p) => {\n");
        out.push_str(
            "                    tdbe::types::price::Price::new(p.value, p.r#type).to_f64()\n",
        );
        out.push_str("                }\n");
        out.push_str(
            "                crate::proto::data_value::DataType::Number(n) => *n as f64,\n",
        );
        out.push_str("                _ => 0.0,\n");
        out.push_str("            })\n");
        out.push_str("            .unwrap_or(0.0)\n");
        out.push_str("    }\n\n");
    }

    out.push_str("    let h: Vec<&str> = table.headers.iter().map(|s| s.as_str()).collect();\n");

    // For eod_style, use the shared find_header() from decode.rs.
    if def.eod_style {
        out.push_str("    let find = |name: &str| find_header(&h, name);\n\n");
    }

    // Determine which columns need helpers.
    let needs_opt_number = def
        .columns
        .iter()
        .any(|c| c.r#type == "i32" && !def.required.contains(&c.name) && c.field != "date");
    let needs_opt_float = def
        .columns
        .iter()
        .any(|c| c.r#type == "f64" && !def.required.contains(&c.name));
    let needs_opt_i64 = def
        .columns
        .iter()
        .any(|c| c.r#type == "i64" && !def.required.contains(&c.name));

    // Emit opt_number / opt_float / opt_i64 helpers (non-eod only).
    if !def.eod_style {
        if needs_opt_number {
            out.push_str("    fn opt_number(row: &crate::proto::DataValueList, idx: Option<usize>) -> i32 {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => row_number(row, i),\n");
            out.push_str("            None => 0,\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_float {
            out.push_str("    fn opt_float(row: &crate::proto::DataValueList, idx: Option<usize>) -> f64 {\n");
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => row_float(row, i),\n");
            out.push_str("            None => 0.0,\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
        if needs_opt_i64 {
            out.push_str(
                "    fn opt_i64(row: &crate::proto::DataValueList, idx: Option<usize>) -> i64 {\n",
            );
            out.push_str("        match idx {\n");
            out.push_str("            Some(i) => row_number_i64(row, i),\n");
            out.push_str("            None => 0,\n");
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }
    }

    // Required header guards (non-eod only).
    if !def.eod_style {
        for req in &def.required {
            let var = idx_var_name(req);
            writeln!(out,
                "    let Some({var}) = find_header(&h, \"{req}\") else {{\n        return vec![];\n    }};"
            ).unwrap();
        }
        if !def.required.is_empty() {
            out.push('\n');
        }
    }

    // Declare index variables for all columns.
    for col in &def.columns {
        let var = idx_var_name(&col.name);
        if def.eod_style {
            writeln!(out, "    let {var} = find(\"{}\");", col.name).unwrap();
        } else if def.required.contains(&col.name) {
            // Already declared above as required.
        } else {
            writeln!(out, "    let {var} = find_header(&h, \"{}\");", col.name).unwrap();
        }
    }

    // Contract identification columns (wildcard queries inject expiration/strike/right).
    if def.contract_id {
        out.push_str("    let _cid_exp_idx = h.iter().position(|c| *c == \"expiration\");\n");
        out.push_str("    let _cid_strike_idx = h.iter().position(|c| *c == \"strike\");\n");
        out.push_str("    let _cid_right_idx = h.iter().position(|c| *c == \"right\");\n");
        out.push_str("    let _cid_strike_is_typed = _cid_strike_idx.is_some() && h.contains(&\"strike\");\n");
    }

    // Check if this is QuoteTick (needs midpoint computation).
    let is_quote_tick = type_name == "QuoteTick";

    out.push('\n');

    // Emit the row mapping.
    out.push_str("    table\n");
    out.push_str("        .data_table\n");
    out.push_str("        .iter()\n");
    out.push_str("        .map(|row| {\n");

    // Struct literal.
    if is_quote_tick {
        writeln!(out, "            let _tick = {type_name} {{").unwrap();
    } else {
        writeln!(out, "            {type_name} {{").unwrap();
    }

    for col in &def.columns {
        let var = idx_var_name(&col.name);
        let is_required = def.required.contains(&col.name);

        match col.r#type.as_str() {
            "i32" => {
                if def.eod_style {
                    writeln!(
                        out,
                        "                {}: {var}.map(|i| eod_num(row, i)).unwrap_or(0),",
                        col.field
                    )
                    .unwrap();
                } else if is_required {
                    let accessor = if col.field == "date" {
                        "row_date"
                    } else {
                        "row_number"
                    };
                    writeln!(
                        out,
                        "                {}: {accessor}(row, {var}),",
                        col.field
                    )
                    .unwrap();
                } else if col.field == "date" {
                    writeln!(
                        out,
                        "                {}: {var}.map(|i| row_date(row, i)).unwrap_or(0),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: opt_number(row, {var}),",
                        col.field
                    )
                    .unwrap();
                }
            }
            "i64" => {
                if is_required {
                    writeln!(
                        out,
                        "                {}: row_number_i64(row, {var}),",
                        col.field
                    )
                    .unwrap();
                } else {
                    writeln!(out, "                {}: opt_i64(row, {var}),", col.field).unwrap();
                }
            }
            "f64" => {
                if is_required {
                    writeln!(out, "                {}: row_float(row, {var}),", col.field).unwrap();
                } else {
                    writeln!(out, "                {}: opt_float(row, {var}),", col.field).unwrap();
                }
            }
            "String" => {
                if is_required {
                    writeln!(out, "                {}: row_text(row, {var}),", col.field).unwrap();
                } else {
                    writeln!(
                        out,
                        "                {}: {var}.map(|i| row_text(row, i)).unwrap_or_default(),",
                        col.field
                    )
                    .unwrap();
                }
            }
            "price" => {
                // Decode price to f64 at parse time.
                let field = &col.field;
                if is_required {
                    writeln!(out, "                {field}: row_price_f64(row, {var}),").unwrap();
                } else {
                    writeln!(out, "                {field}: match {var} {{").unwrap();
                    out.push_str("                    Some(i) => row_price_f64(row, i),\n");
                    out.push_str("                    None => 0.0,\n");
                    out.push_str("                },\n");
                }
            }
            "eod_num" => {
                writeln!(
                    out,
                    "                {}: {var}.map(|i| eod_num(row, i)).unwrap_or(0),",
                    col.field
                )
                .unwrap();
            }
            "eod_date" => {
                writeln!(
                    out,
                    "                {}: {var}.map(|i| eod_date(row, i)).unwrap_or(0),",
                    col.field
                )
                .unwrap();
            }
            "eod_price" => {
                // EOD price field: decode to f64 from Price or Number cell.
                writeln!(
                    out,
                    "                {}: {var}.map(|i| eod_price(row, i)).unwrap_or(0.0),",
                    col.field
                )
                .unwrap();
            }
            other => panic!("unknown column type '{other}' in parser for {type_name}"),
        }
    }

    // Contract identification fields (injected when contract_id = true).
    if def.contract_id {
        out.push_str(
            "                expiration: _cid_exp_idx.map(|i| { let n = row_number(row, i); if n != 0 { n } else { let s = row_text(row, i); parse_iso_date(&s) } }).unwrap_or(0),\n",
        );
        // strike: decode to f64
        out.push_str("                strike: match _cid_strike_idx {\n");
        out.push_str(
            "                    Some(i) if _cid_strike_is_typed => row_price_f64(row, i),\n",
        );
        out.push_str("                    Some(i) => row_number(row, i) as f64,\n");
        out.push_str("                    None => 0.0,\n");
        out.push_str("                },\n");
        out.push_str("                right: _cid_right_idx.map(|i| {\n");
        out.push_str("                    let s = row_text(row, i);\n");
        out.push_str(
            "                    if s.is_empty() { 0i32 } else { s.as_bytes()[0] as i32 }\n",
        );
        out.push_str("                }).unwrap_or(0),\n");
    }

    if is_quote_tick {
        // QuoteTick gets midpoint computed from bid + ask.
        out.push_str("                midpoint: 0.0, // placeholder, set below\n");
        out.push_str("            };\n");
        out.push_str("            let mut _tick = _tick;\n");
        out.push_str("            _tick.midpoint = (_tick.bid + _tick.ask) / 2.0;\n");
        out.push_str("            _tick\n");
    } else {
        out.push_str("            }\n");
    }

    out.push_str("        })\n");
    out.push_str("        .collect()\n");
    out.push_str("}\n\n");
}

/// Convert a column name to a consistent index variable name.
fn idx_var_name(name: &str) -> String {
    format!("{name}_idx")
}
use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::Path;

use serde::Deserialize;
