//! C++ layout-assert emitter for FPSS C mirror structs.

use std::fmt::Write as _;

use super::layout::{c_struct_offsets, c_struct_size, fpss_event_offsets, fpss_event_size};
use super::schema::{sorted_data_events, Schema};

pub(super) fn render_cpp_fpss_layout_asserts(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(
        "/* @generated DO NOT EDIT — regenerated by build.rs from fpss_event_schema.toml */\n\n",
    );

    for (event_name, def) in sorted_data_events(schema) {
        for (field_name, offset) in c_struct_offsets(&def.columns) {
            writeln!(
                out,
                "static_assert(offsetof(TdxFpss{event_name}, {field_name}) == {offset},"
            )
            .unwrap();
            writeln!(
                out,
                "              \"TdxFpss{event_name}::{field_name} offset drifted\");"
            )
            .unwrap();
        }
        writeln!(
            out,
            "static_assert(sizeof(TdxFpss{event_name}) == {},",
            c_struct_size(&def.columns)
        )
        .unwrap();
        writeln!(
            out,
            "              \"TdxFpss{event_name} total size drifted\");"
        )
        .unwrap();
        out.push('\n');
    }

    for (name, size, fields) in [
        (
            "Control",
            16usize,
            vec![("kind", 0usize), ("id", 4usize), ("detail", 8usize)],
        ),
        (
            "RawData",
            24usize,
            vec![
                ("code", 0usize),
                ("payload", 8usize),
                ("payload_len", 16usize),
            ],
        ),
    ] {
        for (field_name, offset) in fields {
            writeln!(
                out,
                "static_assert(offsetof(TdxFpss{name}, {field_name}) == {offset},"
            )
            .unwrap();
            writeln!(
                out,
                "              \"TdxFpss{name}::{field_name} offset drifted\");"
            )
            .unwrap();
        }
        writeln!(out, "static_assert(sizeof(TdxFpss{name}) == {size},").unwrap();
        writeln!(out, "              \"TdxFpss{name} total size drifted\");").unwrap();
        out.push('\n');
    }

    for (field_name, offset) in fpss_event_offsets(schema) {
        writeln!(
            out,
            "static_assert(offsetof(TdxFpssEvent, {field_name}) == {offset},"
        )
        .unwrap();
        writeln!(
            out,
            "              \"TdxFpssEvent::{field_name} offset drifted\");"
        )
        .unwrap();
    }
    writeln!(
        out,
        "static_assert(sizeof(TdxFpssEvent) == {},",
        fpss_event_size(schema)
    )
    .unwrap();
    out.push_str("              \"TdxFpssEvent total size drifted\");\n");

    out
}
