//! C mirror header emitter (`sdks/go/fpss_event_structs.h.inc` +
//! `sdks/cpp/include/fpss_event_structs.h.inc`).

use std::fmt::Write as _;

use super::common::{c_ffi_scalar, snake_case};
use super::schema::{sorted_data_events, Schema};

/// Emit the C `TdxContract` struct mirrored from the Rust
/// `#[repr(C)] TdxContract`. Layout must match field-for-field with
/// `render_contract_struct_rust` in `ffi_rust.rs`.
///
/// Field names follow the v3 vendor surface (`symbol`, `expiration`)
/// per <https://docs.thetadata.us/Articles/Getting-Started/v2-migration-guide.html#_5-parameter-mapping>.
fn render_contract_struct_c() -> &'static str {
    "/* FPSS Contract shared across every data event. `symbol` is a\n\
 * NUL-terminated C string (may be null when not yet resolved);\n\
 * optional option fields use a tagged-present bool because C has no\n\
 * Option<T>. Layout is byte-identical to Rust's #[repr(C)] TdxContract.\n\
 */\n\
typedef struct {\n\
    const char *symbol;\n\
    int32_t sec_type;\n\
    bool has_expiration;\n\
    int32_t expiration;\n\
    bool has_is_call;\n\
    bool is_call;\n\
    bool has_strike;\n\
    int32_t strike;\n\
} TdxContract;\n\n"
}

/// Emit the C mirror of the Rust FFI event structs. `#include`'d from
/// `sdks/go/ffi_bridge.h` for Go's cgo consumption AND from
/// `sdks/cpp/include/thetadx.h` for the C++ SDK. Keeps field order and
/// padding identical to the Rust `#[repr(C)]` layout by using the same
/// schema column ordering on both sides — the old hand-written C++ block
/// in `thetadx.h` drifted from Rust (wrong field order in `TdxFpssEvent`
/// silently corrupted every FPSS event the C++ SDK read), so the
/// generator now owns both copies.
pub(super) fn render_c_fpss_event_header(schema: &Schema) -> String {
    let mut out = String::new();
    out.push_str(
        "/* @generated DO NOT EDIT — regenerated by build.rs from fpss_event_schema.toml */\n",
    );
    out.push_str("/* C mirror of the Rust FFI FPSS event structs. #include'd from\n");
    out.push_str(" * sdks/go/ffi_bridge.h (Go cgo) and sdks/cpp/include/thetadx.h\n");
    out.push_str(" * (C++ SDK). Plain C typedefs — both surfaces see byte-identical\n");
    out.push_str(" * layout. Do not hand-edit. */\n\n");

    // `<stdbool.h>` is needed for the `bool` type used by the Contract
    // struct's `has_*` tagged-optional flags. Safe to include repeatedly
    // at the `.h.inc` level — `<stdbool.h>` is idempotent.
    out.push_str("#include <stdbool.h>\n\n");
    out.push_str(include_str!("templates/ffi_c/kind_enum.h.tmpl"));
    out.push_str(render_contract_struct_c());

    for (event_name, def) in sorted_data_events(schema) {
        out.push_str("typedef struct {\n");
        for column in &def.columns {
            let ty = c_ffi_scalar(&column.r#type, event_name, &column.name);
            writeln!(out, "    {ty} {};", column.name).unwrap();
        }
        writeln!(out, "}} TdxFpss{event_name};\n").unwrap();
    }

    out.push_str(include_str!("templates/ffi_c/control_and_raw_data.h.tmpl"));

    out.push_str("typedef struct {\n");
    out.push_str("    TdxFpssEventKind kind;\n");
    for (event_name, _) in sorted_data_events(schema) {
        let field = snake_case(event_name);
        writeln!(out, "    TdxFpss{event_name} {field};").unwrap();
    }
    out.push_str("    TdxFpssControl control;\n");
    out.push_str("    TdxFpssRawData raw_data;\n");
    out.push_str("} TdxFpssEvent;\n");

    out
}
