//! Property-based fuzz of the FPSS frame decoder pipeline.
//!
//! Drives the full `read_frame_into → decode_frame` pipeline against
//! arbitrary byte sequences generated by `proptest`. The contract
//! every random input must satisfy:
//!
//! - The reader never panics, regardless of input.
//! - The reader terminates in bounded steps (no infinite loop on a
//!   pathological byte sequence).
//! - The decoder never panics on any frame the reader hands it.
//! - Memory stays bounded — `frame_buf.len() <= MAX_PAYLOAD_LEN` at
//!   every step.
//!
//! `cargo fuzz` (libFuzzer) requires a nightly toolchain plus a
//! standalone `fuzz/` workspace. The CI runner here is stable-only,
//! so we use proptest — already a dev-dependency for the existing
//! data-layer property tests — for a regression gate that runs in
//! seconds, not minutes. This is NOT exhaustive coverage; it is a
//! shape guard against panics from new variants slipping into the
//! decoder dispatch.

use std::collections::HashMap;
use std::io::Cursor;
use std::sync::atomic::AtomicBool;
use std::sync::Arc;

use proptest::prelude::*;

use thetadatadx::fpss::__test_internals::{
    decode_frame, read_frame_into, DeltaState, FrameReadState, MAX_PAYLOAD_LEN,
};
use thetadatadx::fpss::protocol::Contract;
use thetadatadx::StreamMsgType;

/// Drive arbitrary bytes through the read+decode pipeline and assert
/// the only observable outcomes are: bounded number of frames yielded,
/// or a typed error. No panic, no unbounded memory growth.
fn drive_fuzz_input(bytes: Vec<u8>) {
    // Cap iterations so a hypothetical infinite loop trips a panic
    // rather than wedging the test binary.
    const MAX_FRAMES: usize = 4096;

    let mut cursor = Cursor::new(bytes);
    let authenticated = AtomicBool::new(true);
    let shutdown = AtomicBool::new(false);
    let mut local_contracts: HashMap<i32, Arc<Contract>> = HashMap::new();
    let mut delta_state = DeltaState::new();
    let mut buf: Vec<u8> = Vec::with_capacity(MAX_PAYLOAD_LEN);
    let mut state = FrameReadState::new();

    for _ in 0..MAX_FRAMES {
        match read_frame_into(&mut cursor, &mut buf, &mut state) {
            Ok(Some((code, n))) => {
                // Frame buffer must never exceed the wire-protocol cap.
                assert!(
                    n <= MAX_PAYLOAD_LEN,
                    "decoded payload {n} exceeds MAX_PAYLOAD_LEN={MAX_PAYLOAD_LEN}",
                );
                assert!(
                    buf.len() == n,
                    "buf length {} does not match payload_len {n}",
                    buf.len()
                );
                let _ = decode_frame(
                    code,
                    &buf[..n],
                    &authenticated,
                    &mut local_contracts,
                    &shutdown,
                    &mut delta_state,
                    /* derive_ohlcvc */ true,
                );
            }
            Ok(None) | Err(_) => return, // bounded termination
        }
    }
}

/// Build a fixed-shape probabilistic frame stream. Each iteration
/// either picks a known opcode + small payload, or splices in random
/// bytes. This is significantly more dense in interesting inputs than
/// pure-random byte streams (which have a vanishingly small chance of
/// producing a parseable header).
fn structured_input_strategy() -> impl Strategy<Value = Vec<u8>> {
    // Up to 24 frames per session.
    prop::collection::vec(frame_strategy(), 0..24).prop_map(|frames| {
        let mut out = Vec::new();
        for f in frames {
            out.extend_from_slice(&f);
        }
        out
    })
}

fn frame_strategy() -> impl Strategy<Value = Vec<u8>> {
    let known_codes = prop::sample::select(vec![
        StreamMsgType::Connected as u8,
        StreamMsgType::Metadata as u8,
        StreamMsgType::Ping as u8,
        StreamMsgType::Disconnected as u8,
        StreamMsgType::Contract as u8,
        StreamMsgType::Quote as u8,
        StreamMsgType::Trade as u8,
        StreamMsgType::OpenInterest as u8,
        StreamMsgType::Ohlcvc as u8,
        // MarketValue runs a derived bid/ask calculation over the decoded
        // quote cells; a degenerate frame can drive those cells to the i32
        // bounds, so the arm must be reached to guard its arithmetic.
        StreamMsgType::MarketValue as u8,
        StreamMsgType::Start as u8,
        StreamMsgType::Stop as u8,
        // Plus an unknown opcode so the unknown-frame skip path is
        // exercised.
        99u8,
    ]);
    (
        any::<u8>(),                               // arbitrary length byte (0..=255)
        known_codes,                               // mostly-known opcode
        prop::collection::vec(any::<u8>(), 0..32), // small random payload
    )
        .prop_map(|(len_byte, code, payload)| {
            let mut out = Vec::with_capacity(2 + payload.len());
            out.push(len_byte); // may not match payload.len() — that's the point
            out.push(code);
            out.extend_from_slice(&payload);
            out
        })
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        .. ProptestConfig::default()
    })]

    /// Random bytes — the worst case. Most inputs trip an early
    /// truncation error; the property is that none of them panic.
    #[test]
    fn random_bytes_never_panic(bytes in prop::collection::vec(any::<u8>(), 0..1024)) {
        drive_fuzz_input(bytes);
    }

    /// Structured frame-shaped streams. Higher hit-rate on the decode
    /// dispatch arms because most opcodes match a real `StreamMsgType`.
    #[test]
    fn structured_streams_never_panic(bytes in structured_input_strategy()) {
        drive_fuzz_input(bytes);
    }
}
