// Code generated by generate_sdk_surfaces from endpoint_surface.toml; DO NOT EDIT.

package thetadatadx

import (
	"fmt"
	"strings"
)

// ValidateAllEndpoints calls every non-stream endpoint with dummy-but-valid args.
// Returns (pass, skip, fail) counts.
func ValidateAllEndpoints(c *Client) (int, int, int) {
	pass, skip, fail := 0, 0, 0
	var err error

	_, err = c.StockListSymbols()
	classify("stock_list_symbols", err, &pass, &skip, &fail)

	_, err = c.StockListDates("TRADE", "AAPL")
	classify("stock_list_dates", err, &pass, &skip, &fail)

	_, err = c.StockSnapshotOHLC([]string{"AAPL"})
	classify("stock_snapshot_ohlc", err, &pass, &skip, &fail)

	_, err = c.StockSnapshotTrade([]string{"AAPL"})
	classify("stock_snapshot_trade", err, &pass, &skip, &fail)

	_, err = c.StockSnapshotQuote([]string{"AAPL"})
	classify("stock_snapshot_quote", err, &pass, &skip, &fail)

	_, err = c.StockSnapshotMarketValue([]string{"AAPL"})
	classify("stock_snapshot_market_value", err, &pass, &skip, &fail)

	_, err = c.StockHistoryEOD("AAPL", "20260401", "20260401")
	classify("stock_history_eod", err, &pass, &skip, &fail)

	_, err = c.StockHistoryOHLC("AAPL", "20260401", "60000")
	classify("stock_history_ohlc", err, &pass, &skip, &fail)

	_, err = c.StockHistoryTrade("AAPL", "20260401")
	classify("stock_history_trade", err, &pass, &skip, &fail)

	_, err = c.StockHistoryQuote("AAPL", "20260401", "60000")
	classify("stock_history_quote", err, &pass, &skip, &fail)

	_, err = c.StockHistoryTradeQuote("AAPL", "20260401")
	classify("stock_history_trade_quote", err, &pass, &skip, &fail)

	_, err = c.StockAtTimeTrade("AAPL", "20260401", "20260401", "12:00:00.000")
	classify("stock_at_time_trade", err, &pass, &skip, &fail)

	_, err = c.StockAtTimeQuote("AAPL", "20260401", "20260401", "12:00:00.000")
	classify("stock_at_time_quote", err, &pass, &skip, &fail)

	_, err = c.OptionListSymbols()
	classify("option_list_symbols", err, &pass, &skip, &fail)

	_, err = c.OptionListDates("TRADE", "AAPL", "20260620", "500", "C")
	classify("option_list_dates", err, &pass, &skip, &fail)

	_, err = c.OptionListExpirations("AAPL")
	classify("option_list_expirations", err, &pass, &skip, &fail)

	_, err = c.OptionListStrikes("AAPL", "20260620")
	classify("option_list_strikes", err, &pass, &skip, &fail)

	_, err = c.OptionListContracts("TRADE", "AAPL", "20260401")
	classify("option_list_contracts", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotOHLC("AAPL", "20260620", "500", "C")
	classify("option_snapshot_ohlc", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotTrade("AAPL", "20260620", "500", "C")
	classify("option_snapshot_trade", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotQuote("AAPL", "20260620", "500", "C")
	classify("option_snapshot_quote", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotOpenInterest("AAPL", "20260620", "500", "C")
	classify("option_snapshot_open_interest", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotMarketValue("AAPL", "20260620", "500", "C")
	classify("option_snapshot_market_value", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotGreeksImpliedVolatility("AAPL", "20260620", "500", "C")
	classify("option_snapshot_greeks_implied_volatility", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotGreeksAll("AAPL", "20260620", "500", "C")
	classify("option_snapshot_greeks_all", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotGreeksFirstOrder("AAPL", "20260620", "500", "C")
	classify("option_snapshot_greeks_first_order", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotGreeksSecondOrder("AAPL", "20260620", "500", "C")
	classify("option_snapshot_greeks_second_order", err, &pass, &skip, &fail)

	_, err = c.OptionSnapshotGreeksThirdOrder("AAPL", "20260620", "500", "C")
	classify("option_snapshot_greeks_third_order", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryEOD("AAPL", "20260620", "500", "C", "20260401", "20260401")
	classify("option_history_eod", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryOHLC("AAPL", "20260620", "500", "C", "20260401", "60000")
	classify("option_history_ohlc", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryTrade("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_trade", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryQuote("AAPL", "20260620", "500", "C", "20260401", "60000")
	classify("option_history_quote", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryTradeQuote("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_trade_quote", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryOpenInterest("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_open_interest", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryGreeksEOD("AAPL", "20260620", "500", "C", "20260401", "20260401")
	classify("option_history_greeks_eod", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryGreeksAll("AAPL", "20260620", "500", "C", "20260401", "60000")
	classify("option_history_greeks_all", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryTradeGreeksAll("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_trade_greeks_all", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryGreeksFirstOrder("AAPL", "20260620", "500", "C", "20260401", "60000")
	classify("option_history_greeks_first_order", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryTradeGreeksFirstOrder("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_trade_greeks_first_order", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryGreeksSecondOrder("AAPL", "20260620", "500", "C", "20260401", "60000")
	classify("option_history_greeks_second_order", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryTradeGreeksSecondOrder("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_trade_greeks_second_order", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryGreeksThirdOrder("AAPL", "20260620", "500", "C", "20260401", "60000")
	classify("option_history_greeks_third_order", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryTradeGreeksThirdOrder("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_trade_greeks_third_order", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryGreeksImpliedVolatility("AAPL", "20260620", "500", "C", "20260401", "60000")
	classify("option_history_greeks_implied_volatility", err, &pass, &skip, &fail)

	_, err = c.OptionHistoryTradeGreeksImpliedVolatility("AAPL", "20260620", "500", "C", "20260401")
	classify("option_history_trade_greeks_implied_volatility", err, &pass, &skip, &fail)

	_, err = c.OptionAtTimeTrade("AAPL", "20260620", "500", "C", "20260401", "20260401", "12:00:00.000")
	classify("option_at_time_trade", err, &pass, &skip, &fail)

	_, err = c.OptionAtTimeQuote("AAPL", "20260620", "500", "C", "20260401", "20260401", "12:00:00.000")
	classify("option_at_time_quote", err, &pass, &skip, &fail)

	_, err = c.IndexListSymbols()
	classify("index_list_symbols", err, &pass, &skip, &fail)

	_, err = c.IndexListDates("AAPL")
	classify("index_list_dates", err, &pass, &skip, &fail)

	_, err = c.IndexSnapshotOHLC([]string{"AAPL"})
	classify("index_snapshot_ohlc", err, &pass, &skip, &fail)

	_, err = c.IndexSnapshotPrice([]string{"AAPL"})
	classify("index_snapshot_price", err, &pass, &skip, &fail)

	_, err = c.IndexSnapshotMarketValue([]string{"AAPL"})
	classify("index_snapshot_market_value", err, &pass, &skip, &fail)

	_, err = c.IndexHistoryEOD("AAPL", "20260401", "20260401")
	classify("index_history_eod", err, &pass, &skip, &fail)

	_, err = c.IndexHistoryOHLC("AAPL", "20260401", "20260401", "60000")
	classify("index_history_ohlc", err, &pass, &skip, &fail)

	_, err = c.IndexHistoryPrice("AAPL", "20260401", "60000")
	classify("index_history_price", err, &pass, &skip, &fail)

	_, err = c.IndexAtTimePrice("AAPL", "20260401", "20260401", "12:00:00.000")
	classify("index_at_time_price", err, &pass, &skip, &fail)

	_, err = c.CalendarOpenToday()
	classify("calendar_open_today", err, &pass, &skip, &fail)

	_, err = c.CalendarOnDate("20260401")
	classify("calendar_on_date", err, &pass, &skip, &fail)

	_, err = c.CalendarYear("2026")
	classify("calendar_year", err, &pass, &skip, &fail)

	_, err = c.InterestRateHistoryEOD("AAPL", "20260401", "20260401")
	classify("interest_rate_history_eod", err, &pass, &skip, &fail)

	_, err = c.StockHistoryOHLCRange("AAPL", "20260401", "20260401", "60000")
	classify("stock_history_ohlc_range", err, &pass, &skip, &fail)

	return pass, skip, fail
}

func classify(name string, err error, pass, skip, fail *int) {
	if err == nil {
		fmt.Printf("  %-45s PASS\n", name)
		*pass++
	} else if strings.Contains(strings.ToLower(err.Error()), "permission") ||
		strings.Contains(strings.ToLower(err.Error()), "subscription") {
		fmt.Printf("  %-45s SKIP  (tier)\n", name)
		*skip++
	} else {
		fmt.Printf("  %-45s FAIL  %v\n", name, err)
		*fail++
	}
}
