// @generated DO NOT EDIT — regenerated by build.rs from sdk_surface.toml

/// Names of every FPSS-touching method emitted on `StreamView`.
/// SSOT for cross-class block-list drift checks (see `mdds_client.rs`).
pub(crate) const PYTHON_UNIFIED_FPSS_METHODS: &[&str] = &[
    "start_streaming",
    "is_streaming",
    "batches",
    "active_subscriptions",
    "reconnect",
    "stop_streaming",
    "shutdown",
    "await_drain",
];

#[pymethods]
impl StreamView {
    /// Start streaming and register a Python callback for incoming events.
    ///
    /// The dispatcher thread acquires the GIL
    /// via `Python::attach` to call `callback(event)` for
    /// every typed streaming event, with each invocation wrapped
    /// in `catch_unwind`. `callback` must accept exactly one
    /// positional argument — a typed streaming event class
    /// (`Quote`, `Trade`, `Ohlcvc`, `OpenInterest`,
    /// `LoginSuccess`, `ContractAssigned`, `ReqResponse`,
    /// `MarketOpen`, `MarketClose`, `ServerError`,
    /// `Disconnected`, `Reconnecting`, `Reconnected`, `Error`,
    /// `UnknownFrame`, `Connected`, `Ping`, `ReconnectedServer`,
    /// `Restart`, `UnknownControl`). Dispatch via
    /// `match event: case Quote(): ...`. Truncated / unrecognised
    /// wire frames are filtered before the callback fires and
    /// accounted on the `thetadatadx.fpss.decode_failures` metric.
    ///
    /// Events flow from the streaming reader thread into the
    /// streaming ring (`Producer::try_publish`) and out
    /// to the consumer thread that runs `callback`. The
    /// reader never blocks on user code; if the callback
    /// falls behind, ring-overflow events are dropped and
    /// counted via `dropped_event_count()`.
    ///
    /// Exceptions raised inside `callback` are caught by the
    /// `catch_unwind` boundary and routed through
    /// `PyErr::write_unraisable` (visible in `sys.stderr` and
    /// the unraisable hook); each one bumps `panic_count()`.
    pub(crate) fn start_streaming(&self, py: Python<'_>, callback: Py<PyAny>) -> PyResult<()> {
        // Hold the user callable in a `Mutex<Option<Py<PyAny>>>` so
        // `stop_streaming` can drop it without leaking a Python
        // reference, and so a subsequent `start_streaming` /
        // `reconnect` cycle replaces the previous registration cleanly.
        let mut cb_guard = self.callback.lock().unwrap_or_else(|e| e.into_inner());
        // Reject double-registration with a clear PyRuntimeError. The
        // underlying `Client::start_streaming` would also error,
        // but matching the PyO3 binding's own state first gives a
        // language-idiomatic message.
        if cb_guard.is_some() {
            return Err(PyRuntimeError::new_err(
                "streaming already started -- call stop_streaming() before start_streaming() again",
            ));
        }
        // Bind the callable behind a cheap `Arc` so the FPSS callback
        // closure (`Fn(&StreamEvent) + Send + 'static`) can clone the
        // handle into each per-event invocation. `Py<PyAny>` itself is
        // `Send + Sync` once the GIL is released, so the Arc is purely
        // a reference-count lifetime aid.
        let callback_arc: Arc<Py<PyAny>> = Arc::new(callback);
        let dispatch_cb = Arc::clone(&callback_arc);
        // Capture a clone of the Rust client so the dispatcher closure can
        // call `record_panic()` when the Python callback raises an exception.
        // A `PyErr` is not a Rust panic; it does not unwind through
        // `catch_unwind`, so the core counter is only bumped here.
        let panic_recorder = Arc::clone(&self.client);

        // Never hold the GIL across the blocking network connect.
        // `start_streaming_scoped` performs the FPSS TLS socket connect
        // and the `CREDENTIALS` handshake synchronously on the calling
        // thread before it spawns the dispatcher, so the whole call is
        // released from the interpreter lock via `py.detach`. A sibling
        // Python thread keeps running while the handshake is in flight.
        // The connect path and the resulting `Result` are pure Rust — no
        // Python object is touched inside the detached region; the typed
        // exception mapping (`to_py_err`) runs AFTER the GIL is
        // re-acquired, leaving the error surface unchanged.
        //
        // GIL once per batch, not per event. The dispatcher scope below
        // re-acquires the GIL via `Python::attach` for each consumer
        // batch drain, holds it across every event in the batch, then
        // releases it across the idle inter-batch wait. The per-event
        // `Python::attach` is the cheap reentrant fast path (the GIL is
        // already held by the scope), not a full acquire-from-detached
        // every event — which is what lifts sustained drain throughput.
        // The no-GIL discipline holds: the lock never spans the blocking
        // connect and never spans the idle wait.
        //
        // The consumer is not the FPSS TLS reader thread; a slow Python
        // callback at most fills the streaming ring and bumps
        // `dropped_event_count()`, it cannot back-pressure the TLS reader
        // and trigger a vendor-side disconnect. The core SDK wraps the
        // user callback in `catch_unwind`, so a Rust panic is counted on
        // `panic_count()` and written to `sys.stderr` via
        // `PyErr::write_unraisable` rather than killing the consumer.
        // Python exceptions raised by the callback are caught via `call1`
        // returning `Err` and are also counted on `panic_count()` via
        // `panic_recorder.record_panic()` below.
        py.detach(|| {
            self.client.stream().start_streaming_scoped(
                move |event: &fpss::StreamEvent| {
                    Python::attach(|py| {
                        // Convert the borrowed `&StreamEvent` straight to its
                        // typed pyclass — no owned intermediate. The
                        // contract is stored inline on the event; the
                        // nested `ContractRef` Python object is built only
                        // if the callback reads `event.contract`. `call1`
                        // with a 1-tuple takes pyo3's vectorcall fast path
                        // (no heap argument tuple).
                        let typed = match fpss_event_to_typed(py, event) {
                            Ok(obj) => obj,
                            Err(err) => {
                                // Don't propagate from the dispatcher
                                // thread — there's no Python frame to
                                // raise into. Surface via the standard
                                // PyErr -> sys.stderr writer so logging
                                // pipelines and Jupyter both see it.
                                err.write_unraisable(py, None);
                                return;
                            }
                        };
                        if let Err(err) = dispatch_cb.call1(py, (typed,)) {
                            err.write_unraisable(py, None);
                            panic_recorder.stream().record_panic();
                        }
                    });
                },
                |drain| Python::attach(|_py| drain()),
            )
        })
        .map_err(to_py_err)?;

        // The dispatcher closure already captured a clone of
        // `callback_arc` (via `dispatch_cb`), so the Arc ref-count is
        // guaranteed >=2 by the time we reach this line — `try_unwrap`
        // would always fail. Lift a fresh owned handle under the GIL
        // for storage on `cb_guard`.
        *cb_guard = Some(Python::attach(|py| callback_arc.clone_ref(py)));
        Ok(())
    }

    /// Whether the streaming connection is active.
    fn is_streaming(&self) -> bool {
        self.client.stream().is_streaming()
    }

    /// Open a pull-based columnar reader over the live stream, a sibling to the per-event callback. Returns a reader of Apache Arrow record batches under a fixed schema; the same subscriptions feed it. Tune batch_size, linger, and backpressure on the returned builder/reader.
    /// Open a pull-based columnar reader over the live stream.
    ///
    /// Returns a `RecordBatchStream` — a sibling to the per-event
    /// `start_streaming(callback)`. The same subscriptions feed it,
    /// but market-data events arrive as `pyarrow.RecordBatch`
    /// values under a fixed schema. The reader is both a
    /// synchronous `Iterable` (the blocking pull releases the GIL)
    /// and an `AsyncIterable` (`async for`), and a sync / async
    /// context manager that closes the stream on exit. Subscribe on
    /// this same surface first, then open the reader.
    ///
    /// `batch_size` rows per batch (default 65536); `linger_ms`
    /// flushes a partial batch on a quiet stream (default 50);
    /// `backpressure` is `"block"` (default, lossless) or
    /// `"drop_oldest"`; `capacity` bounds the drop-oldest buffer.
    #[pyo3(signature = (*, batch_size=None, linger_ms=None, backpressure=None, capacity=None))]
    fn batches(
        &self,
        py: Python<'_>,
        batch_size: Option<usize>,
        linger_ms: Option<u64>,
        backpressure: Option<&str>,
        capacity: Option<usize>,
    ) -> PyResult<crate::streaming_batches::RecordBatchStream> {
        crate::streaming_batches::open_reader(py, &self.client, batch_size, linger_ms, backpressure, capacity)
    }

    /// Get a snapshot of currently active subscriptions.
    fn active_subscriptions(&self) -> PyResult<Vec<crate::fluent::PySubscription>> {
        self.client
            .stream()
            .active_subscriptions()
            .map(|subs| {
                subs.into_iter()
                    .map(|(kind, contract)| crate::fluent::PySubscription {
                        inner: fpss::protocol::Subscription::Contract { contract, kind },
                    })
                    .collect()
            })
            .map_err(to_py_err)
    }

    /// Reconnect streaming and re-register the previously installed callback.
    ///
    /// Requires a prior `start_streaming(callback)`; raises
    /// `RuntimeError` if no callback is registered. All
    /// active subscriptions are restored on the new
    /// connection — see `thetadatadx::Client::reconnect_streaming`
    /// for partial-failure semantics.
    ///
    /// # Callback lifetime across `stop_streaming`
    ///
    /// `stop_streaming()` and `shutdown()` clear the registered
    /// callback. To resume streaming on this client after
    /// `stop_streaming()`, you MUST call `start_streaming(callback)`
    /// again with a freshly bound callable; `reconnect()` raises
    /// `RuntimeError` because no callback is held.
    ///
    /// This explicit-handoff model matches the C++ wrapper's RAII
    /// destructor and the Python `with` block's `__exit__`: the
    /// resource (the callback closure plus its captured environment)
    /// is cleared at the same scope boundary the user observes. The
    /// unified C API preserves the callback across stop/reconnect,
    /// but the Python and TypeScript bindings deliberately diverge
    /// to enforce the explicit handoff and avoid retaining captured
    /// references past a teardown the application has already
    /// observed.
    fn reconnect(&self, py: Python<'_>) -> PyResult<()> {
        // `reconnect` re-registers the previously installed callback
        // on a fresh FPSS connection. We require a prior
        // `start_streaming(callback)` so the Python surface stays
        // consistent: there is no implicit zero-callback streaming
        // mode on this binding.
        let stored = {
            let guard = self.callback.lock().unwrap_or_else(|e| e.into_inner());
            match guard.as_ref() {
                Some(cb) => Python::attach(|py| cb.clone_ref(py)),
                None => {
                    return Err(PyRuntimeError::new_err(
                        "no callback registered -- call start_streaming(callback) before reconnect()",
                    ));
                }
            }
        };
        let callback_arc: Arc<Py<PyAny>> = Arc::new(stored);
        let dispatch_cb = Arc::clone(&callback_arc);
        let panic_recorder = Arc::clone(&self.client);

        // Never hold the GIL across the blocking network reconnect.
        // `reconnect_streaming_scoped` tears the old session down, opens a
        // fresh FPSS TLS connection, re-runs the `CREDENTIALS` handshake,
        // and paces the saved-subscription replay (sleeping
        // `replay_pace_ms` between bursts) — all synchronously on the
        // calling thread. The whole call is released from the interpreter
        // lock via `py.detach` so a sibling Python thread keeps running
        // while the reconnect is in flight. The reconnect path and its
        // `Result` are pure Rust; `to_py_err` maps the failure AFTER the
        // GIL is re-acquired.
        //
        // GIL once per batch, not per event — see `start_streaming`. The
        // dispatcher scope holds the GIL across each batch drain and
        // releases it across the idle wait; the per-event
        // `Python::attach` is the cheap reentrant fast path.
        py.detach(|| {
            self.client.stream().reconnect_streaming_scoped(
                move |event: &fpss::StreamEvent| {
                    Python::attach(|py| {
                        // Borrowed `&StreamEvent` → typed pyclass in one
                        // pass; contract stored inline, ContractRef built
                        // only on `event.contract` access. `call1` with a
                        // 1-tuple uses pyo3's vectorcall fast path.
                        let typed = match fpss_event_to_typed(py, event) {
                            Ok(obj) => obj,
                            Err(err) => {
                                err.write_unraisable(py, None);
                                return;
                            }
                        };
                        if let Err(err) = dispatch_cb.call1(py, (typed,)) {
                            err.write_unraisable(py, None);
                            panic_recorder.stream().record_panic();
                        }
                    });
                },
                |drain| Python::attach(|_py| drain()),
            )
        })
        .map_err(to_py_err)?;

        // Replace the stored callable with a freshly owned handle so
        // the next reconnect / shutdown sees the same state shape.
        // The dispatcher closure already captured a clone of
        // `callback_arc` (via `dispatch_cb`); the ref-count is >=2
        // here so `try_unwrap` would always fail.
        let mut guard = self.callback.lock().unwrap_or_else(|e| e.into_inner());
        *guard = Some(Python::attach(|py| callback_arc.clone_ref(py)));
        Ok(())
    }

    /// Stop streaming while keeping the historical client usable.
    ///
    /// Clears the registered callback. To resume streaming, start streaming again with a freshly bound callback -- reconnect will fail because no callback is held. See the reconnect docs for the rationale: the callback is released at the same scope boundary the application observes, so a stopped session never retains a captured reference past a teardown the caller has already seen.
    pub(crate) fn stop_streaming(&self, py: Python<'_>) {
        py.detach(|| self.client.stream().stop_streaming());
        let mut guard = self.callback.lock().unwrap_or_else(|e| e.into_inner());
        *guard = None;
    }

    /// Shut down the streaming connection.
    ///
    /// On the Python and TypeScript bindings, this clears the registered callback (same explicit-handoff semantics as stopping the stream); reconnect will then fail until the caller starts streaming again with a freshly bound callback. The C++ binding preserves the underlying connection's behaviour.
    pub(crate) fn shutdown(&self, py: Python<'_>) {
        py.detach(|| self.client.stream().stop_streaming());
        let mut guard = self.callback.lock().unwrap_or_else(|e| e.into_inner());
        *guard = None;
    }

    /// Block until the previous streaming session's consumer thread has finished firing the registered callback. Returns true if the drain completed within the timeout, false otherwise.
    pub(crate) fn await_drain(&self, py: Python<'_>, timeout_ms: u64) -> bool {
        py.detach(|| {
            self.client.stream().await_drain(std::time::Duration::from_millis(timeout_ms))
        })
    }

}
