// @generated DO NOT EDIT — regenerated by build.rs from sdk_surface.toml

/// All 23 Black-Scholes Greeks + IV in a single frozen typed
/// pyclass. Mirrors `thetadatadx::greeks::GreeksResult`; replaces the
/// earlier `PyDict`-returning path for cross-SDK parity.
#[must_use]
#[pyclass(module = "thetadatadx", frozen, skip_from_py_object)]
#[derive(Clone, Debug)]
pub(crate) struct AllGreeks {
    #[pyo3(get)]
    pub value: f64,
    #[pyo3(get)]
    pub iv: f64,
    #[pyo3(get)]
    pub iv_error: f64,
    #[pyo3(get)]
    pub delta: f64,
    #[pyo3(get)]
    pub gamma: f64,
    #[pyo3(get)]
    pub theta: f64,
    #[pyo3(get)]
    pub vega: f64,
    #[pyo3(get)]
    pub rho: f64,
    #[pyo3(get)]
    pub vanna: f64,
    #[pyo3(get)]
    pub charm: f64,
    #[pyo3(get)]
    pub vomma: f64,
    #[pyo3(get)]
    pub veta: f64,
    #[pyo3(get)]
    pub vera: f64,
    #[pyo3(get)]
    pub speed: f64,
    #[pyo3(get)]
    pub zomma: f64,
    #[pyo3(get)]
    pub color: f64,
    #[pyo3(get)]
    pub ultima: f64,
    #[pyo3(get)]
    pub d1: f64,
    #[pyo3(get)]
    pub d2: f64,
    #[pyo3(get)]
    pub dual_delta: f64,
    #[pyo3(get)]
    pub dual_gamma: f64,
    #[pyo3(get)]
    pub epsilon: f64,
    #[pyo3(get)]
    pub lambda_: f64,
}

#[pymethods]
impl AllGreeks {
    fn __repr__(&self) -> String {
        format!(
"AllGreeks(value={}, iv={}, delta={}, gamma={}, theta={}, vega={})",
self.value, self.iv, self.delta, self.gamma, self.theta, self.vega
)
    }
}

/// Compute all 23 Black-Scholes Greeks + IV in one call.
#[pyfunction]
#[allow(clippy::too_many_arguments)] // Reason: mirrors Black-Scholes parameter set expected by SDK callers
fn all_greeks(
    spot: f64,
    strike: f64,
    rate: f64,
    div_yield: f64,
    tte: f64,
    option_price: f64,
    right: &str,
) -> PyResult<AllGreeks> {
    let g = thetadatadx::greeks::all_greeks(spot, strike, rate, div_yield, tte, option_price, right).map_err(thetadatadx::Error::from).map_err(to_py_err)?;
    Ok(AllGreeks {
        value: g.value,
        iv: g.iv,
        iv_error: g.iv_error,
        delta: g.delta,
        gamma: g.gamma,
        theta: g.theta,
        vega: g.vega,
        rho: g.rho,
        vanna: g.vanna,
        charm: g.charm,
        vomma: g.vomma,
        veta: g.veta,
        vera: g.vera,
        speed: g.speed,
        zomma: g.zomma,
        color: g.color,
        ultima: g.ultima,
        d1: g.d1,
        d2: g.d2,
        dual_delta: g.dual_delta,
        dual_gamma: g.dual_gamma,
        epsilon: g.epsilon,
        lambda_: g.lambda,
    })
}

/// Compute implied volatility via bisection.
#[pyfunction]
#[allow(clippy::too_many_arguments)] // Reason: mirrors Black-Scholes parameter set expected by SDK callers
fn implied_volatility(
    spot: f64,
    strike: f64,
    rate: f64,
    div_yield: f64,
    tte: f64,
    option_price: f64,
    right: &str,
) -> PyResult<(f64, f64)> {
    thetadatadx::greeks::implied_volatility(spot, strike, rate, div_yield, tte, option_price, right).map_err(thetadatadx::Error::from).map_err(to_py_err)
}

fn register_generated_utility_functions(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<AllGreeks>()?;
    m.add_function(wrap_pyfunction!(all_greeks, m)?)?;
    m.add_function(wrap_pyfunction!(implied_volatility, m)?)?;
    Ok(())
}

#[pyfunction]
fn condition_name(code: i32) -> &'static str {
    thetadatadx::utils::conditions::condition_name(code)
}

#[pyfunction]
fn condition_description(code: i32) -> &'static str {
    thetadatadx::utils::conditions::condition_description(code)
}

#[pyfunction]
fn is_cancel(code: i32) -> bool {
    thetadatadx::utils::conditions::is_cancel(code)
}

#[pyfunction]
fn updates_volume(code: i32) -> bool {
    thetadatadx::utils::conditions::updates_volume(code)
}

#[pyfunction]
fn quote_condition_name(code: i32) -> &'static str {
    thetadatadx::utils::conditions::quote_condition_name(code)
}

#[pyfunction]
fn quote_condition_description(code: i32) -> &'static str {
    thetadatadx::utils::conditions::quote_condition_description(code)
}

#[pyfunction]
fn is_firm(code: i32) -> bool {
    thetadatadx::utils::conditions::is_firm(code)
}

#[pyfunction]
fn is_halted(code: i32) -> bool {
    thetadatadx::utils::conditions::is_halted(code)
}

#[pyfunction]
fn exchange_name(code: i32) -> &'static str {
    thetadatadx::utils::exchange::exchange_name(code)
}

#[pyfunction]
fn exchange_symbol(code: i32) -> &'static str {
    thetadatadx::utils::exchange::exchange_symbol(code)
}

/// Vendor vocabulary text for a calendar-day `status` code (`0` ->
/// `"open"`, `1` -> `"early_close"`, `2` -> `"full_close"`, `3` ->
/// `"weekend"`). Returns the literal `"UNKNOWN"` for codes outside the
/// table. Mirrors the C++ `thetadatadx::calendar_status_name` and the C ABI
/// `thetadatadx_calendar_status_name`.
#[pyfunction]
fn calendar_status_name(code: i32) -> &'static str {
    thetadatadx::CalendarStatus::from_code(code)
        .map_or("UNKNOWN", thetadatadx::CalendarStatus::as_str)
}

/// Combine an Eastern-Time `YYYYMMDD` date and milliseconds-of-day into
/// Unix epoch milliseconds (UTC, DST-aware). Usable with any
/// `(date, *_ms_of_day)` pair on the tick structs. Returns `None` when
/// `date` is absent (`0`) or either input is out of domain — the same
/// `std::nullopt` contract the C++ `thetadatadx::timestamp_ms` returns (the C
/// ABI `thetadatadx_timestamp_ms` encodes that absence as the `-1` sentinel).
#[pyfunction]
fn timestamp_ms(date: i32, ms_of_day: i32) -> Option<i64> {
    thetadatadx::time::date_ms_to_epoch_ms(date, ms_of_day)
}

/// Convert a signed wire-encoded trade-sequence value to its unsigned
/// monotonic form. `signed_value` must lie in the i32 wire range
/// (`-2_147_483_648 ..= 2_147_483_647`): the upstream terminal encodes
/// trade sequences as i32, so a value outside that domain is not a wire
/// sequence and is rejected with `ValueError` rather than silently
/// reinterpreted into a look-correct-but-wrong id. A value that does not
/// fit the `i64` parameter type still surfaces as the built-in
/// `OverflowError` from argument coercion, unchanged.
#[pyfunction]
fn sequence_signed_to_unsigned(signed_value: i64) -> PyResult<u64> {
    if !(thetadatadx::utils::sequences::SEQUENCE_MIN..=thetadatadx::utils::sequences::SEQUENCE_MAX)
        .contains(&signed_value)
    {
        return Err(PyValueError::new_err(format!(
            "sequence_signed_to_unsigned: {signed_value} is outside the i32 wire range \
             (-2_147_483_648 ..= 2_147_483_647)"
        )));
    }
    Ok(thetadatadx::utils::sequences::signed_to_unsigned(
        signed_value,
    ))
}

/// Convert an unsigned monotonic trade-sequence value back to its signed
/// wire encoding. `unsigned_value` must lie in the unsigned wire range
/// (`0 ..= 2^32 - 1`): the monotonic sequence id is never wider than one
/// i32 cycle, so a value above that domain is rejected with `ValueError`
/// rather than silently reinterpreted. A negative argument still
/// surfaces as the built-in `OverflowError` from `u64` coercion,
/// unchanged.
#[pyfunction]
fn sequence_unsigned_to_signed(unsigned_value: u64) -> PyResult<i64> {
    if unsigned_value > u64::from(u32::MAX) {
        return Err(PyValueError::new_err(format!(
            "sequence_unsigned_to_signed: {unsigned_value} is above the unsigned wire range \
             (0 ..= 2^32 - 1)"
        )));
    }
    Ok(thetadatadx::utils::sequences::unsigned_to_signed(
        unsigned_value,
    ))
}

/// Register the `thetadatadx.util` submodule on the parent module.
///
/// All functions are added to a child PyModule named `util`, then that
/// child is registered both as a submodule of the parent and (so
/// `import thetadatadx.util` works) inserted into `sys.modules` under
/// the dotted name. This is the standard pyo3 idiom for native Python
/// submodules.
pub(crate) fn register_generated_util_submodule(parent: &Bound<'_, PyModule>) -> PyResult<()> {
    let py = parent.py();
    let util = PyModule::new(py, "util")?;
    util.add_function(wrap_pyfunction!(condition_name, &util)?)?;
    util.add_function(wrap_pyfunction!(condition_description, &util)?)?;
    util.add_function(wrap_pyfunction!(is_cancel, &util)?)?;
    util.add_function(wrap_pyfunction!(updates_volume, &util)?)?;
    util.add_function(wrap_pyfunction!(quote_condition_name, &util)?)?;
    util.add_function(wrap_pyfunction!(quote_condition_description, &util)?)?;
    util.add_function(wrap_pyfunction!(is_firm, &util)?)?;
    util.add_function(wrap_pyfunction!(is_halted, &util)?)?;
    util.add_function(wrap_pyfunction!(exchange_name, &util)?)?;
    util.add_function(wrap_pyfunction!(exchange_symbol, &util)?)?;
    util.add_function(wrap_pyfunction!(calendar_status_name, &util)?)?;
    util.add_function(wrap_pyfunction!(timestamp_ms, &util)?)?;
    util.add_function(wrap_pyfunction!(sequence_signed_to_unsigned, &util)?)?;
    util.add_function(wrap_pyfunction!(sequence_unsigned_to_signed, &util)?)?;

    // Insert under the dotted name so `import thetadatadx.util` works
    // identically to a pure-Python submodule.
    let sys_modules = py.import("sys")?.getattr("modules")?;
    sys_modules.set_item("thetadatadx.util", &util)?;

    parent.add_submodule(&util)?;
    Ok(())
}
