// @generated DO NOT EDIT — regenerated by build.rs from fpss_event_schema.toml
// Rust FFI `#[repr(C)]` FPSS event structs + ZERO_* consts + tagged
// `ThetaDataDxStreamEvent`. `include!`'d from `ffi/src/lib.rs`; do not hand-edit.
// Expects `std::os::raw::c_char`, `std::ptr` already in scope at the
// include site.

/// FPSS event kind tag. Check this to determine which field of
/// `ThetaDataDxStreamEvent` is valid. One discriminant per data variant
/// (Quote / Trade / OpenInterest / Ohlcvc) and one per control
/// variant (LoginSuccess / ContractAssigned / ...). Schema-driven
/// from `fpss_event_schema.toml`; values are stable for the
/// lifetime of the current C ABI but may renumber on a future major
/// bump.
#[repr(C)]
pub enum ThetaDataDxStreamEventKind {
    /// `Connected` event; the `connected` field carries its payload.
    Connected = 0,
    /// `ContractAssigned` event; the `contract_assigned` field carries its payload.
    ContractAssigned = 1,
    /// `Disconnected` event; the `disconnected` field carries its payload.
    Disconnected = 2,
    /// `LoginSuccess` event; the `login_success` field carries its payload.
    LoginSuccess = 3,
    /// `MarketClose` event; the `market_close` field carries its payload.
    MarketClose = 4,
    /// `MarketOpen` event; the `market_open` field carries its payload.
    MarketOpen = 5,
    /// `MarketValue` event; the `market_value` field carries its payload.
    MarketValue = 6,
    /// `Ohlcvc` event; the `ohlcvc` field carries its payload.
    Ohlcvc = 7,
    /// `OpenInterest` event; the `open_interest` field carries its payload.
    OpenInterest = 8,
    /// `ParseError` event; the `parse_error` field carries its payload.
    ParseError = 9,
    /// `Ping` event; the `ping` field carries its payload.
    Ping = 10,
    /// `Quote` event; the `quote` field carries its payload.
    Quote = 11,
    /// `Reconnected` event; the `reconnected` field carries its payload.
    Reconnected = 12,
    /// `ReconnectedServer` event; the `reconnected_server` field carries its payload.
    ReconnectedServer = 13,
    /// `Reconnecting` event; the `reconnecting` field carries its payload.
    Reconnecting = 14,
    /// `ReconnectsExhausted` event; the `reconnects_exhausted` field carries its payload.
    ReconnectsExhausted = 15,
    /// `ReqResponse` event; the `req_response` field carries its payload.
    ReqResponse = 16,
    /// `Restart` event; the `restart` field carries its payload.
    Restart = 17,
    /// `ServerError` event; the `server_error` field carries its payload.
    ServerError = 18,
    /// `Trade` event; the `trade` field carries its payload.
    Trade = 19,
    /// `UnknownControl` event; the `unknown_control` field carries its payload.
    UnknownControl = 20,
    /// `UnknownFrame` event; the `unknown_frame` field carries its payload.
    UnknownFrame = 21,
}

/// FPSS `Contract` shared across every data event.
/// 
/// `symbol` is a NUL-terminated C string; may be null when the SDK has not
/// yet resolved the server-assigned contract_id to a `ContractAssigned`
/// frame. Optional option fields (`expiration`, `right`, `strike`) use a
/// tagged-present bool because `#[repr(C)]` cannot express `Option<T>`
/// directly. `right` is the ASCII byte `b'C'` / `b'P'` (`0` when
/// `has_right` is false) and `strike` is the option strike in dollars —
/// the same notation the public option builder takes.
#[repr(C)]
pub struct ThetaDataDxContract {
/// Ticker symbol (e.g. "AAPL"). Null until ContractAssigned arrives.
pub symbol: *const c_char,
/// Security type code — matches `thetadatadx::SecType`.
pub sec_type: i32,
/// Whether `expiration` is meaningful (options only).
pub has_expiration: bool,
/// Option expiration date as `YYYYMMDD` (0 when `has_expiration` is false).
pub expiration: i32,
/// Whether `right` is meaningful (options only).
pub has_right: bool,
/// Option side as ASCII: `b'C'` / `b'P'` (`0` when `has_right` is false).
pub right: c_char,
/// Whether `strike` is meaningful (options only).
pub has_strike: bool,
/// Option strike price in dollars (0.0 when `has_strike` is false).
pub strike: f64,
/// Option strike in thousandths of a dollar (a `$550.00` strike is
/// `550000`; `0` when `has_strike` is false). The exact integer the
/// wire carries — read this for an exact key, `strike` for dollars.
pub strike_thousandths: i32,
}

/// Zeroed `ThetaDataDxContract` literal: null symbol, all-false presence flags, zero scalars.
pub(crate) const ZERO_CONTRACT_STRUCT: ThetaDataDxContract = ThetaDataDxContract {
symbol: ptr::null(),
sec_type: 0,
has_expiration: false,
expiration: 0,
has_right: false,
right: 0,
has_strike: false,
strike: 0.0,
strike_thousandths: 0,
};

/// Streaming MarketValue tick (wire code 25). A calculated theoretical market value derived from the real-time bid/ask — `market_bid` / `market_ask` are the quote bid/ask after a size-imbalance + spread-aware nudge, `market_price` is their integer midpoint. Per-contract only (no full-stream variant).
#[repr(C)]
pub struct ThetaDataDxStreamMarketValue {
    /// Contract this event refers to.
    pub contract: ThetaDataDxContract,
    /// Milliseconds since midnight Eastern Time when the event was recorded.
    pub ms_of_day: i32,
    /// Calculated market bid (dollars), nudged from the quote bid.
    pub market_bid: f64,
    /// Calculated market ask (dollars), nudged from the quote ask.
    pub market_ask: f64,
    /// Integer midpoint of `market_bid` / `market_ask` (dollars).
    pub market_price: f64,
    /// Trading date as `YYYYMMDD`.
    pub date: i32,
    /// Wall-clock nanoseconds since UNIX epoch, captured at frame decode time.
    pub received_at_ns: u64,
}

/// Streaming OHLCVC bar.
#[repr(C)]
pub struct ThetaDataDxStreamOhlcvc {
    /// Contract this event refers to.
    pub contract: ThetaDataDxContract,
    /// Milliseconds since midnight Eastern Time when the event was recorded.
    pub ms_of_day: i32,
    /// Opening price of the bar.
    pub open: f64,
    /// Highest traded price within the bar.
    pub high: f64,
    /// Lowest traded price within the bar.
    pub low: f64,
    /// Closing price of the bar.
    pub close: f64,
    /// Total traded volume within the bar, in contracts/shares.
    pub volume: i64,
    /// Number of trades aggregated into the bar.
    pub count: i64,
    /// Trading date as `YYYYMMDD`.
    pub date: i32,
    /// Wall-clock nanoseconds since UNIX epoch, captured at frame decode time.
    pub received_at_ns: u64,
}

/// Streaming OpenInterest tick.
#[repr(C)]
pub struct ThetaDataDxStreamOpenInterest {
    /// Contract this event refers to.
    pub contract: ThetaDataDxContract,
    /// Milliseconds since midnight Eastern Time when the event was recorded.
    pub ms_of_day: i32,
    /// Number of outstanding open contracts.
    pub open_interest: i32,
    /// Trading date as `YYYYMMDD`.
    pub date: i32,
    /// Wall-clock nanoseconds since UNIX epoch, captured at frame decode time.
    pub received_at_ns: u64,
}

/// Streaming Quote tick.
#[repr(C)]
pub struct ThetaDataDxStreamQuote {
    /// Contract this event refers to.
    pub contract: ThetaDataDxContract,
    /// Milliseconds since midnight Eastern Time when the event was recorded.
    pub ms_of_day: i32,
    /// Number of contracts/shares resting at the bid.
    pub bid_size: i32,
    /// Exchange code posting the bid.
    pub bid_exchange: i32,
    /// Bid price.
    pub bid: f64,
    /// Quote condition code for the bid.
    pub bid_condition: i32,
    /// Number of contracts/shares resting at the ask.
    pub ask_size: i32,
    /// Exchange code posting the ask.
    pub ask_exchange: i32,
    /// Ask price.
    pub ask: f64,
    /// Quote condition code for the ask.
    pub ask_condition: i32,
    /// Trading date as `YYYYMMDD`.
    pub date: i32,
    /// Wall-clock nanoseconds since UNIX epoch, captured at frame decode time.
    pub received_at_ns: u64,
}

/// Streaming Trade tick.
#[repr(C)]
pub struct ThetaDataDxStreamTrade {
    /// Contract this event refers to.
    pub contract: ThetaDataDxContract,
    /// Milliseconds since midnight Eastern Time when the event was recorded.
    pub ms_of_day: i32,
    /// Exchange sequence number for ordering trades within the day.
    pub sequence: i32,
    /// Extended trade condition code 1.
    pub ext_condition1: i32,
    /// Extended trade condition code 2.
    pub ext_condition2: i32,
    /// Extended trade condition code 3.
    pub ext_condition3: i32,
    /// Extended trade condition code 4.
    pub ext_condition4: i32,
    /// Primary trade condition code.
    pub condition: i32,
    /// Trade size in contracts/shares.
    pub size: i32,
    /// Exchange code where the trade printed.
    pub exchange: i32,
    /// Trade price.
    pub price: f64,
    /// Bit flags qualifying the trade conditions.
    pub condition_flags: i32,
    /// Bit flags qualifying the trade price.
    pub price_flags: i32,
    /// Volume classification code for the trade.
    pub volume_type: i32,
    /// Number of records back this trade was reported (out-of-order correction offset).
    pub records_back: i32,
    /// Trading date as `YYYYMMDD`.
    pub date: i32,
    /// Wall-clock nanoseconds since UNIX epoch, captured at frame decode time.
    pub received_at_ns: u64,
}

/// Streaming server connection ack (wire code 4). Carries no payload.
#[repr(C)]
pub struct ThetaDataDxStreamConnected {
    /// Placeholder so the struct has size 1 on every C compiler.
    /// Empty `#[repr(C)]` structs are size 0 on Rust but size 1 on
    /// MSVC; the byte keeps the layout consistent across both.
    pub _padding: u8,
}

/// Streaming server assigned a contract id. The `contract` payload carries the full resolved contract (root, sec_type, expiration / strike / right for options).
#[repr(C)]
pub struct ThetaDataDxStreamContractAssigned {
    /// Wire-internal contract id the FPSS server assigns to this contract.
    pub id: i32,
    /// Contract this event refers to.
    pub contract: ThetaDataDxContract,
}

/// Streaming server disconnected the client (wire code 12). `reason` is the integer disconnect code; read the resolved reason-name field for the symbolic name.
#[repr(C)]
pub struct ThetaDataDxStreamDisconnected {
    /// Reason the server gave for dropping the connection.
    pub reason: i32,
}

/// Streaming login succeeded. `permissions` is the server's opaque bundle string — diagnostic metadata only; for feature gating use the Nexus REST subscription tiers.
#[repr(C)]
pub struct ThetaDataDxStreamLoginSuccess {
    /// Server "Bundle" string copied verbatim from the METADATA frame; opaque diagnostic metadata.
    pub permissions: *const c_char,
}

/// Streaming market-close signal (wire code 32). Carries no payload.
#[repr(C)]
pub struct ThetaDataDxStreamMarketClose {
    /// Placeholder so the struct has size 1 on every C compiler.
    /// Empty `#[repr(C)]` structs are size 0 on Rust but size 1 on
    /// MSVC; the byte keeps the layout consistent across both.
    pub _padding: u8,
}

/// Streaming market-open signal (wire code 30). Carries no payload.
#[repr(C)]
pub struct ThetaDataDxStreamMarketOpen {
    /// Placeholder so the struct has size 1 on every C compiler.
    /// Empty `#[repr(C)]` structs are size 0 on Rust but size 1 on
    /// MSVC; the byte keeps the layout consistent across both.
    pub _padding: u8,
}

/// Streaming protocol-level parse error. Named `ParseError` on every binding so it never collides with the language's own error types (Python's exception classes, the JS global `Error`).
#[repr(C)]
pub struct ThetaDataDxStreamParseError {
    /// Human-readable error text from the server.
    pub message: *const c_char,
}

/// Streaming server heartbeat (wire code 10). The server emits PING frames (observed 1-byte payload `[0]`) the client heartbeat logic does not have to answer; payload preserved for diagnostics.
#[repr(C)]
pub struct ThetaDataDxStreamPing {
    /// Raw frame payload bytes, preserved for diagnostics. Pointer to the first byte; null when empty.
    pub payload: *const u8,
    /// Length in bytes of the `payload` buffer.
    pub payload_len: usize,
}

/// Streaming auto-reconnect succeeded — connection is live again. Carries no payload.
#[repr(C)]
pub struct ThetaDataDxStreamReconnected {
    /// Placeholder so the struct has size 1 on every C compiler.
    /// Empty `#[repr(C)]` structs are size 0 on Rust but size 1 on
    /// MSVC; the byte keeps the layout consistent across both.
    pub _padding: u8,
}

/// Streaming server-side reconnect ack (wire code 13). Distinct from `Reconnected`, which the client emits from its auto-reconnect state machine once the new TLS session is authenticated.
#[repr(C)]
pub struct ThetaDataDxStreamReconnectedServer {
    /// Placeholder so the struct has size 1 on every C compiler.
    /// Empty `#[repr(C)]` structs are size 0 on Rust but size 1 on
    /// MSVC; the byte keeps the layout consistent across both.
    pub _padding: u8,
}

/// Streaming auto-reconnect is about to attempt reconnection. Emitted before sleeping for `delay_ms` milliseconds. `attempt` is 1-based and saturates at the maximum 32-bit signed value if the reconnect loop exceeds 2^31 attempts.
#[repr(C)]
pub struct ThetaDataDxStreamReconnecting {
    /// Reason the server gave for dropping the connection.
    pub reason: i32,
    /// 1-based index of this reconnect attempt.
    pub attempt: i32,
    /// Delay, in milliseconds, before the attempt fires.
    pub delay_ms: u64,
}

/// Streaming auto-reconnect stopped without a user-initiated shutdown — terminal for the session. Emitted when the reconnect budget (attempt count or wall-clock envelope) is exhausted, a permanent disconnect reason short-circuits recovery, a manual policy declines to reconnect, or a custom policy returns no delay. `reason` is the integer disconnect code of the final drop; read the resolved reason-name field for the symbolic name. `attempts` is the number of consecutive reconnect attempts consumed before giving up (0 when no reconnect was attempted).
#[repr(C)]
pub struct ThetaDataDxStreamReconnectsExhausted {
    /// Reason the server gave for dropping the connection.
    pub reason: i32,
    /// Number of consecutive reconnect attempts consumed before giving up.
    pub attempts: i32,
}

/// Streaming subscription response (wire code 40). `result` is an integer status code (0=Subscribed, 1=Error, 2=MaxStreamsReached, 3=InvalidPerms).
#[repr(C)]
pub struct ThetaDataDxStreamReqResponse {
    /// Identifier of the subscription request this response answers.
    pub req_id: i32,
    /// Outcome of the subscription request.
    pub result: i32,
}

/// Streaming server stream restart (wire code 31). The server restarts the stream without dropping the TCP connection; delta decode state should be cleared on receipt.
#[repr(C)]
pub struct ThetaDataDxStreamRestart {
    /// Placeholder so the struct has size 1 on every C compiler.
    /// Empty `#[repr(C)]` structs are size 0 on Rust but size 1 on
    /// MSVC; the byte keeps the layout consistent across both.
    pub _padding: u8,
}

/// Streaming server-error message (wire code 11).
#[repr(C)]
pub struct ThetaDataDxStreamServerError {
    /// Human-readable error text from the server.
    pub message: *const c_char,
}

/// Streaming control variant the SDK does not yet recognise. Surfaced when a newer protocol revision adds a control event this build predates — keep dispatch logic forward-compatible by handling this variant. Carries no payload.
#[repr(C)]
pub struct ThetaDataDxStreamUnknownControl {
    /// Placeholder so the struct has size 1 on every C compiler.
    /// Empty `#[repr(C)]` structs are size 0 on Rust but size 1 on
    /// MSVC; the byte keeps the layout consistent across both.
    pub _padding: u8,
}

/// Streaming server sent a frame with an unrecognised wire code. Raw bytes preserved for diagnostics / upstream bug reports.
#[repr(C)]
pub struct ThetaDataDxStreamUnknownFrame {
    /// Unrecognized frame code reported by the server.
    pub code: u8,
    /// Raw frame payload bytes, preserved for diagnostics. Pointer to the first byte; null when empty.
    pub payload: *const u8,
    /// Length in bytes of the `payload` buffer.
    pub payload_len: usize,
}

/// Tagged FPSS event for FFI. Check `kind` then read the corresponding
/// field. Only the field matching `kind` contains valid data — this is
/// a flat struct (not a C union) for simplicity and safety. The
/// per-variant control payloads (LoginSuccess, ContractAssigned, ...)
/// mirror the Rust `StreamControl::*` enum one-for-one; consumers
/// dispatch via `kind` and read the matching `event.<variant>` field.
#[repr(C)]
pub struct ThetaDataDxStreamEvent {
    /// Discriminant selecting which payload field below is valid.
    pub kind: ThetaDataDxStreamEventKind,
    /// `MarketValue` payload; valid when `kind` is `MarketValue`.
    pub market_value: ThetaDataDxStreamMarketValue,
    /// `Ohlcvc` payload; valid when `kind` is `Ohlcvc`.
    pub ohlcvc: ThetaDataDxStreamOhlcvc,
    /// `OpenInterest` payload; valid when `kind` is `OpenInterest`.
    pub open_interest: ThetaDataDxStreamOpenInterest,
    /// `Quote` payload; valid when `kind` is `Quote`.
    pub quote: ThetaDataDxStreamQuote,
    /// `Trade` payload; valid when `kind` is `Trade`.
    pub trade: ThetaDataDxStreamTrade,
    /// `Connected` payload; valid when `kind` is `Connected`.
    pub connected: ThetaDataDxStreamConnected,
    /// `ContractAssigned` payload; valid when `kind` is `ContractAssigned`.
    pub contract_assigned: ThetaDataDxStreamContractAssigned,
    /// `Disconnected` payload; valid when `kind` is `Disconnected`.
    pub disconnected: ThetaDataDxStreamDisconnected,
    /// `LoginSuccess` payload; valid when `kind` is `LoginSuccess`.
    pub login_success: ThetaDataDxStreamLoginSuccess,
    /// `MarketClose` payload; valid when `kind` is `MarketClose`.
    pub market_close: ThetaDataDxStreamMarketClose,
    /// `MarketOpen` payload; valid when `kind` is `MarketOpen`.
    pub market_open: ThetaDataDxStreamMarketOpen,
    /// `ParseError` payload; valid when `kind` is `ParseError`.
    pub parse_error: ThetaDataDxStreamParseError,
    /// `Ping` payload; valid when `kind` is `Ping`.
    pub ping: ThetaDataDxStreamPing,
    /// `Reconnected` payload; valid when `kind` is `Reconnected`.
    pub reconnected: ThetaDataDxStreamReconnected,
    /// `ReconnectedServer` payload; valid when `kind` is `ReconnectedServer`.
    pub reconnected_server: ThetaDataDxStreamReconnectedServer,
    /// `Reconnecting` payload; valid when `kind` is `Reconnecting`.
    pub reconnecting: ThetaDataDxStreamReconnecting,
    /// `ReconnectsExhausted` payload; valid when `kind` is `ReconnectsExhausted`.
    pub reconnects_exhausted: ThetaDataDxStreamReconnectsExhausted,
    /// `ReqResponse` payload; valid when `kind` is `ReqResponse`.
    pub req_response: ThetaDataDxStreamReqResponse,
    /// `Restart` payload; valid when `kind` is `Restart`.
    pub restart: ThetaDataDxStreamRestart,
    /// `ServerError` payload; valid when `kind` is `ServerError`.
    pub server_error: ThetaDataDxStreamServerError,
    /// `UnknownControl` payload; valid when `kind` is `UnknownControl`.
    pub unknown_control: ThetaDataDxStreamUnknownControl,
    /// `UnknownFrame` payload; valid when `kind` is `UnknownFrame`.
    pub unknown_frame: ThetaDataDxStreamUnknownFrame,
}

// Layout drift-guard: pin the `#[repr(C)]` size + alignment of every
// emitted struct on the Rust side that defines the ABI. A schema or
// field-width change that shifts a layout fails the build here, before
// the generated C header and its C++ asserts can drift out of sync.
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxContract>() == 40);
    assert!(core::mem::align_of::<ThetaDataDxContract>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamMarketValue>() == 88);
    assert!(core::mem::align_of::<ThetaDataDxStreamMarketValue>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamOhlcvc>() == 112);
    assert!(core::mem::align_of::<ThetaDataDxStreamOhlcvc>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamOpenInterest>() == 64);
    assert!(core::mem::align_of::<ThetaDataDxStreamOpenInterest>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamQuote>() == 104);
    assert!(core::mem::align_of::<ThetaDataDxStreamQuote>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamTrade>() == 120);
    assert!(core::mem::align_of::<ThetaDataDxStreamTrade>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamConnected>() == 1);
    assert!(core::mem::align_of::<ThetaDataDxStreamConnected>() == 1);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamContractAssigned>() == 48);
    assert!(core::mem::align_of::<ThetaDataDxStreamContractAssigned>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamDisconnected>() == 4);
    assert!(core::mem::align_of::<ThetaDataDxStreamDisconnected>() == 4);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamLoginSuccess>() == 8);
    assert!(core::mem::align_of::<ThetaDataDxStreamLoginSuccess>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamMarketClose>() == 1);
    assert!(core::mem::align_of::<ThetaDataDxStreamMarketClose>() == 1);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamMarketOpen>() == 1);
    assert!(core::mem::align_of::<ThetaDataDxStreamMarketOpen>() == 1);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamParseError>() == 8);
    assert!(core::mem::align_of::<ThetaDataDxStreamParseError>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamPing>() == 16);
    assert!(core::mem::align_of::<ThetaDataDxStreamPing>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamReconnected>() == 1);
    assert!(core::mem::align_of::<ThetaDataDxStreamReconnected>() == 1);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamReconnectedServer>() == 1);
    assert!(core::mem::align_of::<ThetaDataDxStreamReconnectedServer>() == 1);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamReconnecting>() == 16);
    assert!(core::mem::align_of::<ThetaDataDxStreamReconnecting>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamReconnectsExhausted>() == 8);
    assert!(core::mem::align_of::<ThetaDataDxStreamReconnectsExhausted>() == 4);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamReqResponse>() == 8);
    assert!(core::mem::align_of::<ThetaDataDxStreamReqResponse>() == 4);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamRestart>() == 1);
    assert!(core::mem::align_of::<ThetaDataDxStreamRestart>() == 1);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamServerError>() == 8);
    assert!(core::mem::align_of::<ThetaDataDxStreamServerError>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamUnknownControl>() == 1);
    assert!(core::mem::align_of::<ThetaDataDxStreamUnknownControl>() == 1);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamUnknownFrame>() == 24);
    assert!(core::mem::align_of::<ThetaDataDxStreamUnknownFrame>() == 8);
};
const _: () = {
    assert!(core::mem::size_of::<ThetaDataDxStreamEvent>() == 688);
    assert!(core::mem::align_of::<ThetaDataDxStreamEvent>() == 8);
};

// Zero-initialized defaults for inactive union-style fields.
pub(crate) const ZERO_MARKET_VALUE: ThetaDataDxStreamMarketValue = ThetaDataDxStreamMarketValue {
    contract: ZERO_CONTRACT_STRUCT,
    ms_of_day: 0,
    market_bid: 0.0,
    market_ask: 0.0,
    market_price: 0.0,
    date: 0,
    received_at_ns: 0,
};
pub(crate) const ZERO_OHLCVC: ThetaDataDxStreamOhlcvc = ThetaDataDxStreamOhlcvc {
    contract: ZERO_CONTRACT_STRUCT,
    ms_of_day: 0,
    open: 0.0,
    high: 0.0,
    low: 0.0,
    close: 0.0,
    volume: 0,
    count: 0,
    date: 0,
    received_at_ns: 0,
};
pub(crate) const ZERO_OI: ThetaDataDxStreamOpenInterest = ThetaDataDxStreamOpenInterest {
    contract: ZERO_CONTRACT_STRUCT,
    ms_of_day: 0,
    open_interest: 0,
    date: 0,
    received_at_ns: 0,
};
pub(crate) const ZERO_QUOTE: ThetaDataDxStreamQuote = ThetaDataDxStreamQuote {
    contract: ZERO_CONTRACT_STRUCT,
    ms_of_day: 0,
    bid_size: 0,
    bid_exchange: 0,
    bid: 0.0,
    bid_condition: 0,
    ask_size: 0,
    ask_exchange: 0,
    ask: 0.0,
    ask_condition: 0,
    date: 0,
    received_at_ns: 0,
};
pub(crate) const ZERO_TRADE: ThetaDataDxStreamTrade = ThetaDataDxStreamTrade {
    contract: ZERO_CONTRACT_STRUCT,
    ms_of_day: 0,
    sequence: 0,
    ext_condition1: 0,
    ext_condition2: 0,
    ext_condition3: 0,
    ext_condition4: 0,
    condition: 0,
    size: 0,
    exchange: 0,
    price: 0.0,
    condition_flags: 0,
    price_flags: 0,
    volume_type: 0,
    records_back: 0,
    date: 0,
    received_at_ns: 0,
};
pub(crate) const ZERO_CONNECTED: ThetaDataDxStreamConnected = ThetaDataDxStreamConnected {
    _padding: 0,
};
pub(crate) const ZERO_CONTRACT_ASSIGNED: ThetaDataDxStreamContractAssigned = ThetaDataDxStreamContractAssigned {
    id: 0,
    contract: ZERO_CONTRACT_STRUCT,
};
pub(crate) const ZERO_DISCONNECTED: ThetaDataDxStreamDisconnected = ThetaDataDxStreamDisconnected {
    reason: 0,
};
pub(crate) const ZERO_LOGIN_SUCCESS: ThetaDataDxStreamLoginSuccess = ThetaDataDxStreamLoginSuccess {
    permissions: ptr::null(),
};
pub(crate) const ZERO_MARKET_CLOSE: ThetaDataDxStreamMarketClose = ThetaDataDxStreamMarketClose {
    _padding: 0,
};
pub(crate) const ZERO_MARKET_OPEN: ThetaDataDxStreamMarketOpen = ThetaDataDxStreamMarketOpen {
    _padding: 0,
};
pub(crate) const ZERO_PARSE_ERROR: ThetaDataDxStreamParseError = ThetaDataDxStreamParseError {
    message: ptr::null(),
};
pub(crate) const ZERO_PING: ThetaDataDxStreamPing = ThetaDataDxStreamPing {
    payload: ptr::null(),
    payload_len: 0,
};
pub(crate) const ZERO_RECONNECTED: ThetaDataDxStreamReconnected = ThetaDataDxStreamReconnected {
    _padding: 0,
};
pub(crate) const ZERO_RECONNECTED_SERVER: ThetaDataDxStreamReconnectedServer = ThetaDataDxStreamReconnectedServer {
    _padding: 0,
};
pub(crate) const ZERO_RECONNECTING: ThetaDataDxStreamReconnecting = ThetaDataDxStreamReconnecting {
    reason: 0,
    attempt: 0,
    delay_ms: 0,
};
pub(crate) const ZERO_RECONNECTS_EXHAUSTED: ThetaDataDxStreamReconnectsExhausted = ThetaDataDxStreamReconnectsExhausted {
    reason: 0,
    attempts: 0,
};
pub(crate) const ZERO_REQ_RESPONSE: ThetaDataDxStreamReqResponse = ThetaDataDxStreamReqResponse {
    req_id: 0,
    result: 0,
};
pub(crate) const ZERO_RESTART: ThetaDataDxStreamRestart = ThetaDataDxStreamRestart {
    _padding: 0,
};
pub(crate) const ZERO_SERVER_ERROR: ThetaDataDxStreamServerError = ThetaDataDxStreamServerError {
    message: ptr::null(),
};
pub(crate) const ZERO_UNKNOWN_CONTROL: ThetaDataDxStreamUnknownControl = ThetaDataDxStreamUnknownControl {
    _padding: 0,
};
pub(crate) const ZERO_UNKNOWN_FRAME: ThetaDataDxStreamUnknownFrame = ThetaDataDxStreamUnknownFrame {
    code: 0,
    payload: ptr::null(),
    payload_len: 0,
};
pub(crate) const ZERO_STREAM_EVENT: ThetaDataDxStreamEvent = ThetaDataDxStreamEvent {
    kind: ThetaDataDxStreamEventKind::UnknownControl,
    market_value: ZERO_MARKET_VALUE,
    ohlcvc: ZERO_OHLCVC,
    open_interest: ZERO_OI,
    quote: ZERO_QUOTE,
    trade: ZERO_TRADE,
    connected: ZERO_CONNECTED,
    contract_assigned: ZERO_CONTRACT_ASSIGNED,
    disconnected: ZERO_DISCONNECTED,
    login_success: ZERO_LOGIN_SUCCESS,
    market_close: ZERO_MARKET_CLOSE,
    market_open: ZERO_MARKET_OPEN,
    parse_error: ZERO_PARSE_ERROR,
    ping: ZERO_PING,
    reconnected: ZERO_RECONNECTED,
    reconnected_server: ZERO_RECONNECTED_SERVER,
    reconnecting: ZERO_RECONNECTING,
    reconnects_exhausted: ZERO_RECONNECTS_EXHAUSTED,
    req_response: ZERO_REQ_RESPONSE,
    restart: ZERO_RESTART,
    server_error: ZERO_SERVER_ERROR,
    unknown_control: ZERO_UNKNOWN_CONTROL,
    unknown_frame: ZERO_UNKNOWN_FRAME,
};
