//! C++ SDK: FPSS declarations + definitions, utilities, lifecycle.

use super::common::{generated_header, push_cpp_doc_comment};
use super::spec::{MethodKind, MethodSpec};

/// Renders the C++ header declarations for the FPSS client methods.
pub(super) fn render_cpp_fpss_decls(methods: &[&MethodSpec]) -> String {
    let mut out = String::new();
    out.push_str(
        "    // @generated DO NOT EDIT — regenerated by build.rs from sdk_surface.toml\n\n",
    );
    for method in methods {
        out.push_str(&cpp_fpss_decl(method));
        if !out.ends_with('\n') {
            out.push('\n');
        }
    }
    out
}

/// Renders the C++ definitions for the FPSS client methods.
pub(super) fn render_cpp_fpss_defs(methods: &[&MethodSpec]) -> String {
    let mut out = String::new();
    out.push_str(generated_header());
    for method in methods {
        out.push_str(&cpp_fpss_def(method));
        out.push('\n');
    }
    out
}

/// Renders the C++ definitions for the credentials, config, and client lifecycle methods.
pub(super) fn render_cpp_lifecycle_defs(methods: &[&MethodSpec]) -> String {
    let mut out = String::new();
    out.push_str(generated_header());
    for method in methods {
        out.push_str(&cpp_lifecycle_def(method));
        out.push('\n');
    }
    out
}

fn cpp_fpss_decl(method: &MethodSpec) -> String {
    let mut out = String::new();
    push_cpp_doc_comment(&mut out, "    ", &method.doc);
    match method.kind {
        MethodKind::FpssConnect => {
            out.push_str("    StreamingClient(const Credentials& creds, const Config& config);\n");
        }
        MethodKind::FpssConnectFromFile => {
            out.push_str(
                "    static StreamingClient from_file(const std::string& path, const Config& config = Config::production());\n",
            );
        }
        MethodKind::IsAuthenticated => out.push_str("    bool is_authenticated() const;\n"),
        MethodKind::ActiveSubscriptions => {
            out.push_str("    std::vector<Subscription> active_subscriptions() const;\n");
        }
        MethodKind::Reconnect => out.push_str("    void reconnect();\n"),
        MethodKind::Shutdown => out.push_str("    void shutdown();\n"),
        other => panic!("unsupported C++ FPSS decl kind: {other:?}"),
    }
    out
}

fn cpp_fpss_def(method: &MethodSpec) -> String {
    match method.kind {
        MethodKind::FpssConnect => {
            include_str!("templates/cpp/fpss_connect_def.cpp.tmpl").to_string()
        }
        MethodKind::FpssConnectFromFile => {
            include_str!("templates/cpp/fpss_connect_from_file_def.cpp.tmpl").to_string()
        }
        MethodKind::IsAuthenticated => {
            "bool StreamingClient::is_authenticated() const { return thetadatadx_streaming_is_authenticated(handle_.get()) != 0; }\n"
                .to_string()
        }
        MethodKind::ActiveSubscriptions => {
            include_str!("templates/cpp/active_subscriptions_def.cpp.tmpl").to_string()
        }
        MethodKind::Reconnect => include_str!("templates/cpp/reconnect_def.cpp.tmpl").to_string(),
        MethodKind::Shutdown => {
            "void StreamingClient::shutdown() { thetadatadx_streaming_shutdown(handle_.get()); }\n".to_string()
        }
        other => panic!("unsupported C++ FPSS def kind: {other:?}"),
    }
}

fn cpp_lifecycle_def(method: &MethodSpec) -> String {
    match method.kind {
        MethodKind::CredentialsFromFile => {
            include_str!("templates/cpp/credentials_from_file_def.cpp.tmpl").to_string()
        }
        MethodKind::CredentialsFromEmail => {
            include_str!("templates/cpp/credentials_from_email_def.cpp.tmpl").to_string()
        }
        MethodKind::CredentialsFromApiKey => {
            include_str!("templates/cpp/credentials_from_api_key_def.cpp.tmpl").to_string()
        }
        MethodKind::CredentialsFromApiKeyWithEmail => {
            include_str!("templates/cpp/credentials_from_api_key_with_email_def.cpp.tmpl")
                .to_string()
        }
        MethodKind::CredentialsFromEnv => {
            include_str!("templates/cpp/credentials_from_env_def.cpp.tmpl").to_string()
        }
        MethodKind::CredentialsFromEnvOrFile => {
            include_str!("templates/cpp/credentials_from_env_or_file_def.cpp.tmpl").to_string()
        }
        MethodKind::CredentialsFromDotenv => {
            include_str!("templates/cpp/credentials_from_dotenv_def.cpp.tmpl").to_string()
        }
        MethodKind::ConfigConstructor => {
            let variant = method.config_variant.as_deref().unwrap();
            format!(
                "Config Config::{variant}() {{ return Config(thetadatadx_config_{variant}()); }}\n"
            )
        }
        MethodKind::ConfigFromDotenv => {
            include_str!("templates/cpp/config_from_dotenv_def.cpp.tmpl").to_string()
        }
        MethodKind::ClientConnect => {
            include_str!("templates/cpp/client_connect_def.cpp.tmpl").to_string()
        }
        MethodKind::ClientConnectFromFile => {
            include_str!("templates/cpp/client_connect_from_file_def.cpp.tmpl").to_string()
        }
        other => panic!("unsupported C++ lifecycle kind: {other:?}"),
    }
}
